// OVERLAY 0003 — "make it Greek, not just in Greek" (operator request, 2026-10-06).
//
//   * A new diet, `fasting` — the Orthodox fast as Greeks keep it: no meat, poultry, dairy or eggs;
//     fish with a backbone only on named feast days; invertebrate seafood (octopus, squid,
//     cuttlefish, shrimp, mussels) and fish roe (taramas) allowed; no oil or wine on strict days.
//     THE TAG on a recipe means "fits an ordinary fasting day WITH oil and wine" (the way most
//     households keep it); the diet text says strict days (xerofagia) drop both. Source: the
//     Greek Orthodox Archdiocese of America's page on the fasting rule.
//   * Thirty classic Greek dishes the base seed did not have. The base already carries
//     fasolada, fakes, revithada, gigantes, fava, gemista (vegan), briam, spanakorizo, lahanorizo,
//     imam, arakas, fasolakia, bamies, horiatiki, dakos, tzatziki, kolokithokeftedes, spanakopita,
//     octopus xydato and mydopilafo — those are NOT duplicated. Twenty-one new dishes are fasting.
//   * Two new ingredients the dishes need: `tarama` (salted fish roe) and `pearl-onions`.
//     Nutrition per 100 g from USDA FoodData Central reference values (tarama = "Fish, roe, mixed
//     species, raw"; pearl onions = "Onions, raw"); prices are a Greek supermarket range.
//   * `fasting` added to every EXISTING recipe that is mechanically fasting-compatible (no meat,
//     poultry, dairy, eggs, vertebrate fish, animal fats, gelatin, mayonnaise, stock cubes, egg
//     noodles, pesto, chocolate) — strict: the one dish on a shop pita (which may contain milk) is
//     left out. `src/content/seed/recipes.test.ts` enforces the same rule on every fasting tag, and
//     `./greek-kitchen.test.ts` proves FASTING_EXISTING_SLUGS is exactly the set the rule admits.
//
// Conventions are the base seed's (recipes/group1.ts header): equal step counts in both
// languages, Greek in the plural imperative, legumes/grains/pasta quantified DRY, every line in
// g/ml or the ingredient's own unit, diet tags only where the dish complies.

import type { IngredientSeed, RecipeSeed } from '../../types.ts'
import type { Overlay } from './types.ts'

const SOURCE_NOTE = 'Typical values, USDA FoodData Central reference ranges'
const PRICE_AS_OF = '2026-10-06'
const PER_KG = 'Typical Greek supermarket range, Oct 2026, per kg'

/** Plant-only dishes: every diet a vegan Greek dish complies with, plus the fast. */
const vegan = (...extra: string[]): string[] => [
  'vegan',
  'vegetarian',
  'flexitarian',
  'pescatarian',
  'mediterranean',
  'fasting',
  ...extra,
]
/** Invertebrate seafood / roe dishes: allowed on fasting days. */
const seafood = (...extra: string[]): string[] => [
  'pescatarian',
  'flexitarian',
  'mediterranean',
  'fasting',
  ...extra,
]

const INGREDIENTS: IngredientSeed[] = [
  {
    slug: 'tarama',
    name_el: 'Ταραμάς',
    name_en: 'Tarama (salted fish roe)',
    category: 'fish-seafood',
    unit: 'g',
    grams_per_unit: 1,
    kcal_100g: 143,
    protein_100g: 22.3,
    carbs_100g: 1.5,
    fat_100g: 6.4,
    source_note: SOURCE_NOTE,
    price_eur_min: 18,
    price_eur_max: 35,
    price_per: 'kg',
    price_as_of: PRICE_AS_OF,
    price_note: PER_KG,
    substitute_slugs: [],
    is_pantry_staple: false,
  },
  {
    slug: 'pearl-onions',
    name_el: 'Κρεμμυδάκια στιφάδου',
    name_en: 'Pearl onions',
    category: 'vegetables',
    unit: 'g',
    grams_per_unit: 1,
    kcal_100g: 40,
    protein_100g: 1.1,
    carbs_100g: 9.3,
    fat_100g: 0.1,
    source_note: SOURCE_NOTE,
    price_eur_min: 2.5,
    price_eur_max: 4.5,
    price_per: 'kg',
    price_as_of: PRICE_AS_OF,
    price_note: PER_KG,
    substitute_slugs: ['onion', 'red-onion'],
    is_pantry_staple: false,
  },
]

const RECIPES: RecipeSeed[] = [
  // --- Fasting (νηστίσιμα): plant dishes --------------------------------------------------------
  {
    slug: 'horta-vrasta-boiled-greens',
    title_el: 'Χόρτα βραστά με λεμόνι και ελαιόλαδο',
    title_en: 'Horta vrasta — boiled greens with lemon and olive oil',
    steps_el: [
      'Καθαρίστε τα χόρτα, κόψτε τις σκληρές ρίζες και πλύντε τα σε πολλά νερά.',
      'Βράστε άφθονο νερό με το αλάτι και ρίξτε τα χόρτα.',
      'Βράστε τα 10–15 λεπτά, μέχρι να μαλακώσουν τα κοτσάνια, και στραγγίστε τα.',
      'Σερβίρετε χλιαρά, περιχυμένα με το ελαιόλαδο και τον χυμό του λεμονιού.',
    ],
    steps_en: [
      'Clean the greens, trim the tough roots and wash them in several changes of water.',
      'Bring plenty of water to the boil with the salt and add the greens.',
      'Boil for 10–15 minutes until the stems are tender, then drain.',
      'Serve warm, dressed with the olive oil and the lemon juice.',
    ],
    portions: 4,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'horta',
        quantity: 1000,
        unit: 'g',
        note_el: 'ραδίκια, βλίτα ή σέσκουλα',
        note_en: 'dandelion, amaranth or chard',
      },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'dolmadakia-yalantzi-stuffed-vine-leaves',
    title_el: 'Ντολμαδάκια γιαλαντζί με ρύζι και μυρωδικά',
    title_en: 'Dolmadakia yalantzi — vine leaves stuffed with rice and herbs',
    steps_el: [
      'Ζεματίστε τα αμπελόφυλλα 2 λεπτά σε βραστό νερό και στραγγίστε τα.',
      'Τσιγαρίστε το ψιλοκομμένο κρεμμύδι και τα φρέσκα κρεμμυδάκια στο μισό λάδι για 5 λεπτά.',
      'Ρίξτε το ρύζι, τα κουκουνάρια, τον άνηθο, τον δυόσμο, αλάτι και πιπέρι και ανακατέψτε 2 λεπτά.',
      'Βάλτε ένα κουταλάκι γέμιση σε κάθε φύλλο, διπλώστε τα πλάγια και τυλίξτε σφιχτά.',
      'Στρώστε τα ντολμαδάκια πυκνά σε κατσαρόλα, περιχύστε με το υπόλοιπο λάδι, τον χυμό του ενός λεμονιού και το νερό και σκεπάστε με ένα πιάτο.',
      'Σιγοβράστε 45 λεπτά, αφήστε τα να κρυώσουν μέσα στην κατσαρόλα και σερβίρετε με φέτες από το δεύτερο λεμόνι.',
    ],
    steps_en: [
      'Blanch the vine leaves in boiling water for 2 minutes and drain.',
      'Soften the chopped onion and the spring onions in half the oil for 5 minutes.',
      'Add the rice, pine nuts, dill, mint, salt and pepper and stir for 2 minutes.',
      'Put a teaspoon of filling on each leaf, fold in the sides and roll up tightly.',
      'Pack the rolls snugly in a pan, pour over the rest of the oil, the juice of one lemon and the water, and weigh them down with a plate.',
      'Simmer for 45 minutes, let them cool in the pan and serve with wedges of the second lemon.',
    ],
    portions: 6,
    prep_min: 90,
    meal_types: ['lunch', 'snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'vine-leaves',
        quantity: 250,
        unit: 'g',
        note_el: 'σε άλμη, ξεπλυμένα',
        note_en: 'in brine, rinsed',
      },
      {
        ingredient_slug: 'rice',
        quantity: 250,
        unit: 'g',
        note_el: 'γλασέ, για γέμιση',
        note_en: 'short-grain, for stuffing',
      },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'pine-nuts', quantity: 30, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 8, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 500, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'melitzanosalata-smoky-aubergine-dip',
    title_el: 'Μελιτζανοσαλάτα',
    title_en: 'Melitzanosalata — smoky aubergine dip',
    steps_el: [
      'Τρυπήστε τις μελιτζάνες με πιρούνι και ψήστε τες ολόκληρες στη σχάρα ή στον φούρνο στους 220 °C για 40 λεπτά, μέχρι να καψαλιστεί η φλούδα και να μαλακώσουν.',
      'Ανοίξτε τες, βγάλτε τη σάρκα με κουτάλι και αφήστε τη να στραγγίξει σε σουρωτήρι 10 λεπτά.',
      'Ψιλοκόψτε τη σάρκα με μαχαίρι μαζί με το σκόρδο και το κρεμμύδι.',
      'Ανακατέψτε με το ξίδι, το λάδι, τον μαϊντανό, αλάτι και πιπέρι.',
      'Σερβίρετε δροσερή με ψωμί ή λαγάνα.',
    ],
    steps_en: [
      'Prick the aubergines with a fork and roast them whole on the grill or in the oven at 220 °C for 40 minutes, until the skin is charred and the flesh is soft.',
      'Split them, scoop out the flesh and leave it to drain in a colander for 10 minutes.',
      'Chop the flesh finely with a knife together with the garlic and the onion.',
      'Stir in the vinegar, oil, parsley, salt and pepper.',
      'Serve cool with bread or lagana.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'eggplant', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'skordalia-garlic-potato-dip',
    title_el: 'Σκορδαλιά με πατάτα',
    title_en: 'Skordalia — garlic and potato dip',
    steps_el: [
      'Βράστε τις πατάτες με τη φλούδα σε αλατισμένο νερό 25 λεπτά, μέχρι να μαλακώσουν.',
      'Κοπανίστε στο γουδί το σκόρδο με το αλάτι και τα αμύγδαλα μέχρι να γίνουν πάστα.',
      'Ξεφλουδίστε τις πατάτες ζεστές και λιώστε τες με το πρεσάκι — όχι στο μπλέντερ, γιατί κολλάνε.',
      'Ανακατέψτε με την πάστα σκόρδου και ρίξτε σιγά σιγά το λάδι, εναλλάξ με το ξίδι και τον χυμό του λεμονιού.',
      'Σερβίρετε σε θερμοκρασία δωματίου, δίπλα σε μπακαλιάρο, παντζάρια ή βραστά χόρτα.',
    ],
    steps_en: [
      'Boil the potatoes in their skins in salted water for 25 minutes until tender.',
      'Pound the garlic with the salt and the almonds in a mortar to a paste.',
      'Peel the potatoes while hot and mash them with a ricer — not in a blender, which makes them gluey.',
      'Mix in the garlic paste and add the oil slowly, alternating with the vinegar and the lemon juice.',
      'Serve at room temperature with salt cod, beetroot or boiled greens.',
    ],
    portions: 6,
    prep_min: 40,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 5, unit: 'clove' },
      {
        ingredient_slug: 'almonds',
        quantity: 40,
        unit: 'g',
        note_el: 'ξεφλουδισμένα',
        note_en: 'blanched',
      },
      { ingredient_slug: 'olive-oil', quantity: 8, unit: 'tbsp' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'revithokeftedes-chickpea-fritters',
    title_el: 'Ρεβιθοκεφτέδες',
    title_en: 'Revithokeftedes — chickpea fritters',
    steps_el: [
      'Στραγγίστε και ξεπλύνετε τα ρεβίθια και στεγνώστε τα σε πετσέτα.',
      'Χτυπήστε τα στο μπλέντερ με το κρεμμύδι, το σκόρδο, τον μαϊντανό, τον δυόσμο, το κύμινο, αλάτι και πιπέρι, ώστε να μείνουν λίγο χοντροκομμένα.',
      'Ανακατέψτε με το αλεύρι, πλάστε 16 μικρούς κεφτέδες και αφήστε τους 20 λεπτά στο ψυγείο.',
      'Τηγανίστε τους στο λάδι σε αντικολλητικό τηγάνι 3 λεπτά από κάθε πλευρά, μέχρι να ροδίσουν.',
      'Σερβίρετε με φέτες λεμονιού.',
    ],
    steps_en: [
      'Drain and rinse the chickpeas and dry them on a towel.',
      'Pulse them in a blender with the onion, garlic, parsley, mint, cumin, salt and pepper, leaving a little texture.',
      'Mix in the flour, shape 16 small patties and chill them for 20 minutes.',
      'Fry them in the oil in a non-stick pan for 3 minutes a side until golden.',
      'Serve with lemon wedges.',
    ],
    portions: 4,
    prep_min: 45,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'canned-chickpeas', quantity: 480, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'flour', quantity: 60, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan(),
  },
  {
    slug: 'domatokeftedes-santorini-tomato-fritters',
    title_el: 'Ντοματοκεφτέδες Σαντορίνης',
    title_en: 'Domatokeftedes — Santorini tomato fritters',
    steps_el: [
      'Κόψτε τα ντοματίνια στα τέσσερα, αλατίστε τα και αφήστε τα να στραγγίξουν σε σουρωτήρι 15 λεπτά.',
      'Ψιλοκόψτε το κρεμμύδι και τον δυόσμο και ανακατέψτε τα με τις ντομάτες, τη ρίγανη και το πιπέρι.',
      'Ρίξτε σταδιακά το αλεύρι με το μπέικιν πάουντερ, μέχρι να γίνει πηχτός, κολλώδης χυλός.',
      'Ρίχνετε κουταλιές από τον χυλό στο καυτό λάδι και τηγανίζετε 2–3 λεπτά από κάθε πλευρά.',
      'Στραγγίστε σε απορροφητικό χαρτί και σερβίρετε ζεστούς.',
    ],
    steps_en: [
      'Quarter the cherry tomatoes, salt them and leave them to drain in a colander for 15 minutes.',
      'Chop the onion and the mint finely and mix them with the tomatoes, oregano and pepper.',
      'Add the flour and baking powder gradually until you have a thick, sticky batter.',
      'Drop spoonfuls of the batter into the hot oil and fry for 2–3 minutes a side.',
      'Drain on kitchen paper and serve hot.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['snack', 'lunch'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'cherry-tomato',
        quantity: 500,
        unit: 'g',
        note_el: 'ή ντοματάκια Σαντορίνης',
        note_en: 'or Santorini tomatoes',
      },
      { ingredient_slug: 'red-onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'mint', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'flour', quantity: 150, unit: 'g' },
      { ingredient_slug: 'baking-powder', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan(),
  },
  {
    slug: 'prasorizo-leeks-with-rice',
    title_el: 'Πρασόρυζο',
    title_en: 'Prasorizo — leeks braised with rice',
    steps_el: [
      'Κόψτε τα πράσα σε ροδέλες 1 εκ. και πλύντε τα καλά να φύγει το χώμα.',
      'Σοτάρετε τα πράσα και τα κρεμμυδάκια στο λάδι 8–10 λεπτά να μαραθούν.',
      'Ρίξτε τον πελτέ και το ρύζι και ανακατέψτε 1 λεπτό.',
      'Προσθέστε το ζεστό νερό, αλάτι και πιπέρι και σιγοβράστε σκεπασμένο 18 λεπτά.',
      'Ρίξτε τον άνηθο, αφήστε 5 λεπτά εκτός φωτιάς και σερβίρετε με λεμόνι.',
    ],
    steps_en: [
      'Slice the leeks into 1 cm rounds and wash them well to remove any grit.',
      'Sauté the leeks and spring onions in the oil for 8–10 minutes until soft.',
      'Add the tomato paste and the rice and stir for 1 minute.',
      'Pour in the hot water, season and simmer, covered, for 18 minutes.',
      'Stir in the dill, rest off the heat for 5 minutes and serve with lemon.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'leek', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'tomato-paste', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'rice', quantity: 200, unit: 'g' },
      { ingredient_slug: 'water', quantity: 700, unit: 'ml' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'lagana-clean-monday-flatbread',
    title_el: 'Λαγάνα της Καθαράς Δευτέρας',
    title_en: 'Lagana — Clean Monday sesame flatbread',
    steps_el: [
      'Διαλύστε τη μαγιά και τη ζάχαρη στο χλιαρό νερό και αφήστε 10 λεπτά να αφρίσει.',
      'Ανακατέψτε το αλεύρι με το αλάτι, ρίξτε τη μαγιά και 2 κουταλιές λάδι και ζυμώστε 10 λεπτά, μέχρι να γίνει λεία ζύμη.',
      'Σκεπάστε και αφήστε σε ζεστό μέρος μία ώρα να διπλασιαστεί.',
      'Ανοίξτε τη ζύμη σε μακρόστενο φύλλο πάχους 1,5 εκ. σε λαδωμένο ταψί και αφήστε τη 20 λεπτά να φουσκώσει ξανά.',
      'Πατήστε τη με τα δάχτυλα για να κάνετε βαθουλώματα, αλείψτε με το υπόλοιπο λάδι και πασπαλίστε με το σουσάμι.',
      'Ψήστε στους 200 °C για 25 λεπτά, μέχρι να ροδίσει.',
    ],
    steps_en: [
      'Dissolve the yeast and sugar in the lukewarm water and leave for 10 minutes to foam.',
      'Mix the flour with the salt, add the yeast and 2 tablespoons of oil and knead for 10 minutes to a smooth dough.',
      'Cover and leave somewhere warm for an hour to double.',
      'Stretch the dough into a long oval 1.5 cm thick on an oiled tray and let it rise again for 20 minutes.',
      'Press dimples into it with your fingertips, brush with the remaining oil and scatter the sesame seeds over.',
      'Bake at 200 °C for 25 minutes until golden.',
    ],
    portions: 8,
    prep_min: 120,
    meal_types: ['snack', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'flour', quantity: 500, unit: 'g' },
      { ingredient_slug: 'dry-yeast', quantity: 2, unit: 'tsp' },
      {
        ingredient_slug: 'water',
        quantity: 300,
        unit: 'ml',
        note_el: 'χλιαρό',
        note_en: 'lukewarm',
      },
      { ingredient_slug: 'sugar', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'sesame-seeds', quantity: 3, unit: 'tbsp' },
    ],
    diet_slugs: vegan(),
  },
  {
    slug: 'halvas-simigdalenios-semolina-halva',
    title_el: 'Χαλβάς σιμιγδαλένιος',
    title_en: 'Semolina halva with almonds and raisins',
    steps_el: [
      'Βράστε το νερό με τη ζάχαρη, την κανέλα και τα γαρίφαλα 5 λεπτά και κρατήστε το σιρόπι ζεστό.',
      'Ζεστάνετε το λάδι σε κατσαρόλα και καβουρδίστε το σιμιγδάλι με τα αμύγδαλα ανακατεύοντας συνεχώς 10–12 λεπτά, μέχρι να πάρει χρώμα μπισκότου.',
      'Χαμηλώστε τη φωτιά και ρίξτε προσεκτικά το ζεστό σιρόπι — θα αφρίσει και θα βγάλει ατμό.',
      'Ρίξτε τις σταφίδες και ανακατεύετε σε χαμηλή φωτιά 2–3 λεπτά, μέχρι να ξεκολλάει από τα τοιχώματα.',
      'Βάλτε τον σε φόρμα, αφήστε τον να κρυώσει, ξεφορμάρετε και πασπαλίστε με κανέλα.',
    ],
    steps_en: [
      'Boil the water with the sugar, cinnamon and cloves for 5 minutes and keep the syrup hot.',
      'Heat the oil in a pan and toast the semolina with the almonds, stirring constantly, for 10–12 minutes until biscuit-coloured.',
      'Lower the heat and carefully pour in the hot syrup — it will bubble up and steam.',
      'Add the raisins and stir over low heat for 2–3 minutes until it comes away from the sides.',
      'Spoon it into a mould, let it cool, turn it out and dust with cinnamon.',
    ],
    portions: 10,
    prep_min: 30,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'semolina', quantity: 250, unit: 'g' },
      {
        ingredient_slug: 'sunflower-oil',
        quantity: 12,
        unit: 'tbsp',
        note_el: 'ή ελαιόλαδο',
        note_en: 'or olive oil',
      },
      { ingredient_slug: 'sugar', quantity: 300, unit: 'g' },
      { ingredient_slug: 'water', quantity: 800, unit: 'ml' },
      { ingredient_slug: 'almonds', quantity: 50, unit: 'g' },
      { ingredient_slug: 'raisins', quantity: 50, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cloves', quantity: 0.25, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'fasting'],
  },
  {
    slug: 'hortopita-lenten-wild-greens-pie',
    title_el: 'Χορτόπιτα νηστίσιμη',
    title_en: 'Hortopita — Lenten wild greens pie',
    steps_el: [
      'Πλύντε, στραγγίστε και ψιλοκόψτε τα χόρτα και το σπανάκι· τρίψτε τα με το αλάτι και στύψτε τα να βγάλουν τα νερά τους.',
      'Μαράνετε το πράσο και τα κρεμμυδάκια σε 2 κουταλιές λάδι για 5 λεπτά.',
      'Ανακατέψτε τα χόρτα με το πράσο, τον άνηθο, τον δυόσμο, το ρύζι, 2 κουταλιές λάδι και πιπέρι.',
      'Στρώστε τα μισά φύλλα σε λαδωμένο ταψί, λαδώνοντας το καθένα, απλώστε τη γέμιση και σκεπάστε με τα υπόλοιπα φύλλα, επίσης λαδωμένα.',
      'Χαράξτε σε κομμάτια, ραντίστε με λίγο νερό και ψήστε στους 180 °C για 50–60 λεπτά, μέχρι να ροδίσει.',
      'Αφήστε τη να σταθεί 15 λεπτά πριν την κόψετε.',
    ],
    steps_en: [
      'Wash, drain and chop the greens and the spinach; rub them with the salt and squeeze out their water.',
      'Soften the leek and spring onions in 2 tablespoons of oil for 5 minutes.',
      'Mix the greens with the leek, dill, mint, rice, 2 tablespoons of oil and pepper.',
      'Layer half the phyllo in an oiled tin, oiling each sheet, spread the filling and cover with the remaining sheets, oiled too.',
      'Score into portions, sprinkle with a little water and bake at 180 °C for 50–60 minutes until golden.',
      'Let it rest for 15 minutes before cutting.',
    ],
    portions: 8,
    prep_min: 90,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'phyllo',
        quantity: 450,
        unit: 'g',
        note_el: 'χωρίς βούτυρο',
        note_en: 'dairy-free',
      },
      { ingredient_slug: 'horta', quantity: 500, unit: 'g' },
      { ingredient_slug: 'spinach', quantity: 500, unit: 'g' },
      { ingredient_slug: 'leek', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 0.5, unit: 'bunch' },
      {
        ingredient_slug: 'rice',
        quantity: 50,
        unit: 'g',
        note_el: 'για να πιει τα υγρά',
        note_en: 'to absorb the juices',
      },
      { ingredient_slug: 'olive-oil', quantity: 8, unit: 'tbsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan(),
  },
  {
    slug: 'mavromatika-black-eyed-pea-salad',
    title_el: 'Σαλάτα με μαυρομάτικα φασόλια',
    title_en: 'Black-eyed pea salad with herbs and lemon',
    steps_el: [
      'Βράστε τα φασόλια σε άφθονο νερό 30–35 λεπτά, μέχρι να μαλακώσουν χωρίς να λιώσουν, και στραγγίστε τα.',
      'Ψιλοκόψτε το κρεμμύδι, τα κρεμμυδάκια, τον μαϊντανό και τον άνηθο· κόψτε τις ντομάτες σε κύβους.',
      'Χτυπήστε το λάδι με τον χυμό του λεμονιού, το ξίδι, αλάτι και πιπέρι.',
      'Ανακατέψτε τα χλιαρά φασόλια με τα λαχανικά και τη σάλτσα και αφήστε 15 λεπτά να πάρουν γεύση πριν σερβίρετε.',
    ],
    steps_en: [
      'Boil the peas in plenty of water for 30–35 minutes until tender but whole, then drain.',
      'Chop the onion, spring onions, parsley and dill finely; dice the tomatoes.',
      'Whisk the oil with the lemon juice, vinegar, salt and pepper.',
      'Toss the warm peas with the vegetables and the dressing and leave for 15 minutes to take the flavour before serving.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'black-eyed-peas', quantity: 300, unit: 'g' },
      { ingredient_slug: 'red-onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'patates-lemonates-lemon-oregano-potatoes',
    title_el: 'Πατάτες λεμονάτες στον φούρνο',
    title_en: 'Patates lemonates — oven potatoes with lemon and oregano',
    steps_el: [
      'Ξεφλουδίστε τις πατάτες και κόψτε τες κατά μήκος σε κυδωνάτα κομμάτια.',
      'Ανακατέψτε τες σε ταψί με το λάδι, τον χυμό των λεμονιών, το λιωμένο σκόρδο, τη ρίγανη, αλάτι, πιπέρι και το νερό.',
      'Ψήστε στους 200 °C για 50–60 λεπτά, γυρίζοντάς τες μία φορά, μέχρι να ροδίσουν και να πιουν τα υγρά.',
      'Αν στεγνώσουν νωρίς, προσθέστε λίγο ζεστό νερό· σερβίρετε ζεστές.',
    ],
    steps_en: [
      'Peel the potatoes and cut them lengthways into wedges.',
      'Toss them in a roasting tin with the oil, lemon juice, crushed garlic, oregano, salt, pepper and the water.',
      'Roast at 200 °C for 50–60 minutes, turning once, until golden and the liquid is absorbed.',
      'If they dry out early, add a splash of hot water; serve hot.',
    ],
    portions: 4,
    prep_min: 70,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 6, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'oregano', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'tahinosoupa-lenten-tahini-soup',
    title_el: 'Ταχινόσουπα',
    title_en: 'Tahinosoupa — Lenten tahini and lemon soup with rice',
    steps_el: [
      'Βράστε το νερό με το αλάτι, ρίξτε το ρύζι και σιγοβράστε 18 λεπτά.',
      'Σε ένα μπολ αραιώστε το ταχίνι με τον χυμό των λεμονιών και λίγο κρύο νερό, χτυπώντας μέχρι να γίνει λευκή κρέμα.',
      'Ρίξτε σταδιακά στο μπολ μερικές κουτάλες ζωμό, ανακατεύοντας συνεχώς, για να ζεσταθεί το μείγμα χωρίς να κόψει.',
      'Αδειάστε το μείγμα στην κατσαρόλα εκτός φωτιάς, ανακατέψτε, πιπερώστε και σερβίρετε αμέσως.',
    ],
    steps_en: [
      'Bring the water to the boil with the salt, add the rice and simmer for 18 minutes.',
      'In a bowl, thin the tahini with the lemon juice and a little cold water, whisking until it turns into a pale cream.',
      'Whisk a few ladles of the hot broth into the bowl, one at a time, so the mixture warms without splitting.',
      'Pour it back into the pan off the heat, stir, season with pepper and serve at once.',
    ],
    portions: 4,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'water', quantity: 1500, unit: 'ml' },
      { ingredient_slug: 'rice', quantity: 150, unit: 'g' },
      { ingredient_slug: 'tahini', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'pantzarosalata-beetroot-garlic-walnuts',
    title_el: 'Παντζαροσαλάτα με σκόρδο και καρύδια',
    title_en: 'Pantzarosalata — beetroot salad with garlic and walnuts',
    steps_el: [
      'Βράστε τα παντζάρια με τη φλούδα 40–50 λεπτά, μέχρι να τρυπιούνται εύκολα με μαχαίρι.',
      'Ξεφλουδίστε τα χλιαρά και κόψτε τα σε κύβους.',
      'Χτυπήστε το λάδι με το ξίδι, το λιωμένο σκόρδο και το αλάτι και περιχύστε τα παντζάρια.',
      'Πασπαλίστε με τα χοντροκομμένα καρύδια και τον μαϊντανό και σερβίρετε.',
    ],
    steps_en: [
      'Boil the beetroots in their skins for 40–50 minutes until a knife slides in easily.',
      'Peel them while warm and cut them into cubes.',
      'Whisk the oil with the vinegar, crushed garlic and salt and pour it over the beetroot.',
      'Scatter with the roughly chopped walnuts and parsley and serve.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beetroot', quantity: 6, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'walnuts', quantity: 40, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'fakorizo-lentils-with-rice',
    title_el: 'Φακόρυζο με καραμελωμένα κρεμμύδια',
    title_en: 'Fakorizo — lentils with rice and caramelised onions',
    steps_el: [
      'Ξεπλύνετε τις φακές και βράστε τες σε 1 λίτρο από το νερό με τη δάφνη για 15 λεπτά.',
      'Στο μεταξύ, κόψτε τα κρεμμύδια σε λεπτές φέτες και καραμελώστε τα στο λάδι σε χαμηλή φωτιά για 20 λεπτά.',
      'Ρίξτε στις φακές το ρύζι, το κύμινο, αλάτι, πιπέρι και το υπόλοιπο νερό και σιγοβράστε σκεπασμένο 15–18 λεπτά, μέχρι να απορροφηθούν τα υγρά.',
      'Ανακατέψτε μέσα τα μισά κρεμμύδια με το λάδι τους.',
      'Σερβίρετε με τα υπόλοιπα κρεμμύδια από πάνω.',
    ],
    steps_en: [
      'Rinse the lentils and boil them in 1 litre of the water with the bay leaves for 15 minutes.',
      'Meanwhile, slice the onions thinly and caramelise them in the oil over low heat for 20 minutes.',
      'Add the rice, cumin, salt, pepper and the rest of the water to the lentils and simmer, covered, for 15–18 minutes until the liquid is absorbed.',
      'Stir in half the onions with their oil.',
      'Serve topped with the remaining onions.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'lentils', quantity: 250, unit: 'g' },
      { ingredient_slug: 'rice', quantity: 150, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 1200, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },
  {
    slug: 'aginares-a-la-polita-artichoke-stew',
    title_el: 'Αγκινάρες α λα πολίτα',
    title_en: 'Aginares a la polita — Constantinople-style artichoke stew',
    steps_el: [
      'Καθαρίστε τις αγκινάρες από τα σκληρά φύλλα και το χνούδι και βάλτε τες σε νερό με τον χυμό του ενός λεμονιού, για να μη μαυρίσουν.',
      'Σοτάρετε το κρεμμύδι και τα κρεμμυδάκια στο λάδι 5 λεπτά.',
      'Ρίξτε τα καρότα σε ροδέλες και τις πατάτες σε κομμάτια και ανακατέψτε 2 λεπτά.',
      'Τοποθετήστε από πάνω τις αγκινάρες, προσθέστε το νερό, αλάτι και πιπέρι και σιγοβράστε σκεπασμένο 35–40 λεπτά.',
      'Ρίξτε τον άνηθο και τον χυμό του δεύτερου λεμονιού και κουνήστε την κατσαρόλα να απλωθούν.',
      'Αφήστε το φαγητό 10 λεπτά να ξεκουραστεί και σερβίρετε.',
    ],
    steps_en: [
      'Trim the artichokes of their tough leaves and choke and keep them in water with the juice of one lemon so they do not darken.',
      'Sauté the onion and the spring onions in the oil for 5 minutes.',
      'Add the sliced carrots and the potato chunks and stir for 2 minutes.',
      'Lay the artichokes on top, add the water, salt and pepper and simmer, covered, for 35–40 minutes.',
      'Add the dill and the juice of the second lemon and shake the pan to spread them.',
      'Let the dish rest for 10 minutes and serve.',
    ],
    portions: 4,
    prep_min: 70,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'artichoke', quantity: 8, unit: 'piece' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'carrot', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 500, unit: 'ml' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: vegan('gluten-free'),
  },

  // --- Fasting (νηστίσιμα): seafood without a backbone, and roe --------------------------------
  {
    slug: 'htapodi-kritharaki-octopus-orzo',
    title_el: 'Χταπόδι με κριθαράκι',
    title_en: 'Octopus with orzo in tomato sauce',
    steps_el: [
      'Βάλτε το χταπόδι σε κατσαρόλα χωρίς νερό, σκεπάστε και αφήστε το να βγάλει τα υγρά του σε μέτρια φωτιά για 20 λεπτά.',
      'Βγάλτε το, κόψτε το σε μπουκιές και κρατήστε τον ζωμό του.',
      'Τσιγαρίστε στο λάδι το κρεμμύδι και το σκόρδο, ρίξτε το χταπόδι και σβήστε με το κρασί.',
      'Προσθέστε τις ντομάτες, τον πελτέ, τη δάφνη, το μπαχάρι και τον ζωμό και σιγοβράστε 40 λεπτά, μέχρι να μαλακώσει το χταπόδι.',
      'Ρίξτε το νερό ζεστό και το κριθαράκι και μαγειρέψτε 12–15 λεπτά ανακατεύοντας, μέχρι να μαλακώσει και να μείνει ζουμερό.',
      'Πιπερώστε, αφήστε 5 λεπτά σκεπασμένο και σερβίρετε.',
    ],
    steps_en: [
      'Put the octopus in a pan with no water, cover and let it release its juices over medium heat for 20 minutes.',
      'Lift it out, cut it into bite-sized pieces and keep the cooking liquid.',
      'Soften the onion and garlic in the oil, add the octopus and deglaze with the wine.',
      'Add the tomatoes, tomato paste, bay leaves, allspice and the reserved liquid and simmer for 40 minutes until the octopus is tender.',
      'Add the hot water and the orzo and cook for 12–15 minutes, stirring, until tender but still saucy.',
      'Season with pepper, rest covered for 5 minutes and serve.',
    ],
    portions: 4,
    prep_min: 100,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'octopus',
        quantity: 1000,
        unit: 'g',
        note_el: 'φρέσκο ή κατεψυγμένο, καθαρισμένο',
        note_en: 'fresh or frozen, cleaned',
      },
      { ingredient_slug: 'orzo', quantity: 300, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-wine', quantity: 150, unit: 'ml' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'tomato-paste', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'allspice', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 800, unit: 'ml' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: seafood(),
  },
  {
    slug: 'kalamarakia-stifado-squid-pearl-onions',
    title_el: 'Καλαμάρια στιφάδο',
    title_en: 'Squid stifado — squid stewed with pearl onions',
    steps_el: [
      'Καθαρίστε τα καλαμάρια και κόψτε τα σε κρίκους, αφήνοντας τα πλοκάμια ολόκληρα.',
      'Ζεματίστε τα κρεμμυδάκια 2 λεπτά, ξεφλουδίστε τα και αφήστε τα ολόκληρα.',
      'Σοτάρετε τα κρεμμυδάκια στο λάδι 8 λεπτά να ροδίσουν, ρίξτε το σκόρδο και μετά τα καλαμάρια για 5 λεπτά.',
      'Σβήστε με το κρασί και το ξίδι και αφήστε να εξατμιστεί το αλκοόλ.',
      'Προσθέστε τον πελτέ, τις ντομάτες, τη δάφνη, το μπαχάρι, την κανέλα, αλάτι και πιπέρι και σιγοβράστε σκεπασμένο 45–50 λεπτά.',
      'Αφήστε τη σάλτσα να δέσει χωρίς καπάκι για 5 λεπτά και σερβίρετε.',
    ],
    steps_en: [
      'Clean the squid and cut the bodies into rings, leaving the tentacles whole.',
      'Blanch the pearl onions for 2 minutes, peel them and leave them whole.',
      'Brown the onions in the oil for 8 minutes, add the garlic and then the squid for 5 minutes.',
      'Deglaze with the wine and the vinegar and let the alcohol cook off.',
      'Add the tomato paste, tomatoes, bay leaves, allspice, cinnamon, salt and pepper and simmer, covered, for 45–50 minutes.',
      'Reduce the sauce uncovered for 5 minutes and serve.',
    ],
    portions: 4,
    prep_min: 80,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'squid', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'pearl-onions', quantity: 600, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'red-wine', quantity: 150, unit: 'ml' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'allspice', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: seafood('gluten-free'),
  },
  {
    slug: 'soupies-me-spanaki-cuttlefish-spinach',
    title_el: 'Σουπιές με σπανάκι',
    title_en: 'Cuttlefish with spinach and dill',
    steps_el: [
      'Καθαρίστε τις σουπιές, αφαιρέστε τη σακούλα με το μελάνι και το κόκαλο και κόψτε τες σε λωρίδες.',
      'Σοτάρετε το κρεμμύδι και τα κρεμμυδάκια στο λάδι 5 λεπτά.',
      'Ρίξτε τις σουπιές, ανακατέψτε 5 λεπτά και σβήστε με το κρασί.',
      'Προσθέστε το νερό και σιγοβράστε σκεπασμένο 40 λεπτά, μέχρι να μαλακώσουν.',
      'Ρίξτε το σπανάκι και τον άνηθο χοντροκομμένα, αλάτι και πιπέρι και μαγειρέψτε 10 λεπτά ακόμα.',
      'Σβήστε τη φωτιά, περιχύστε με τον χυμό του λεμονιού και σερβίρετε.',
    ],
    steps_en: [
      'Clean the cuttlefish, remove the ink sac and the cuttlebone and cut them into strips.',
      'Sauté the onion and the spring onions in the oil for 5 minutes.',
      'Add the cuttlefish, stir for 5 minutes and deglaze with the wine.',
      'Add the water and simmer, covered, for 40 minutes until tender.',
      'Add the roughly chopped spinach and dill, salt and pepper and cook for 10 minutes more.',
      'Take off the heat, pour over the lemon juice and serve.',
    ],
    portions: 4,
    prep_min: 75,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'cuttlefish', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'spinach', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'white-wine', quantity: 150, unit: 'ml' },
      { ingredient_slug: 'water', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: seafood('gluten-free'),
  },
  {
    slug: 'mydia-achnista-steamed-mussels',
    title_el: 'Μύδια αχνιστά με κρασί και σκόρδο',
    title_en: 'Mydia achnista — mussels steamed with wine and garlic',
    steps_el: [
      'Τρίψτε τα μύδια με συρματάκι, τραβήξτε τα «γένια» και πετάξτε όσα είναι ανοιχτά ή σπασμένα.',
      'Ζεστάνετε το λάδι σε φαρδιά κατσαρόλα και σοτάρετε το σκόρδο με το μπούκοβο 1 λεπτό.',
      'Ρίξτε τα μύδια, ανακατέψτε και σβήστε με το κρασί.',
      'Σκεπάστε και αχνίστε 4–5 λεπτά σε δυνατή φωτιά, κουνώντας την κατσαρόλα, μέχρι να ανοίξουν· πετάξτε όσα μείνουν κλειστά.',
      'Πασπαλίστε με τον μαϊντανό και το πιπέρι, στύψτε το λεμόνι και σερβίρετε με τον ζωμό τους.',
    ],
    steps_en: [
      'Scrub the mussels, pull off the beards and discard any that are open or broken.',
      'Heat the oil in a wide pan and sauté the garlic with the chilli flakes for 1 minute.',
      'Add the mussels, stir and deglaze with the wine.',
      'Cover and steam over high heat for 4–5 minutes, shaking the pan, until they open; discard any that stay shut.',
      'Scatter with the parsley and pepper, squeeze over the lemon and serve with the cooking juices.',
    ],
    portions: 2,
    prep_min: 25,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'mussels',
        quantity: 500,
        unit: 'g',
        note_el: 'ψίχα· περίπου 1,5 κιλό με το όστρακο',
        note_en: 'meat; about 1.5 kg in the shell',
      },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'white-wine', quantity: 200, unit: 'ml' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: seafood('gluten-free'),
  },
  {
    slug: 'taramosalata-fish-roe-dip',
    title_el: 'Ταραμοσαλάτα',
    title_en: 'Taramosalata — fish roe dip',
    steps_el: [
      'Μουλιάστε το ψωμί στο νερό για 5 λεπτά και στύψτε το καλά.',
      'Χτυπήστε στο μπλέντερ τον ταραμά με το τριμμένο κρεμμύδι μέχρι να γίνει πολτός.',
      'Προσθέστε το ψωμί και χτυπήστε ξανά.',
      'Με το μοτέρ σε λειτουργία, ρίχνετε το λάδι σε λεπτή ροή εναλλάξ με τον χυμό των λεμονιών, μέχρι να γίνει αφράτη κρέμα.',
      'Δοκιμάστε, διορθώστε με λεμόνι και αφήστε τη μία ώρα στο ψυγείο πριν τη σερβίρετε.',
    ],
    steps_en: [
      'Soak the bread in the water for 5 minutes and squeeze it dry.',
      'Blend the tarama with the grated onion to a paste.',
      'Add the bread and blend again.',
      'With the motor running, pour in the oil in a thin stream, alternating with the lemon juice, until light and creamy.',
      'Taste, adjust with lemon and chill for an hour before serving.',
    ],
    portions: 6,
    prep_min: 20,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'tarama',
        quantity: 100,
        unit: 'g',
        note_el: 'λευκός',
        note_en: 'white',
      },
      {
        ingredient_slug: 'bread',
        quantity: 6,
        unit: 'slice',
        note_el: 'μπαγιάτικο, χωρίς κόρα',
        note_en: 'stale, crusts removed',
      },
      { ingredient_slug: 'water', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 8, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
    ],
    diet_slugs: seafood(),
  },

  // --- Classics outside the fast -----------------------------------------------------------------
  {
    slug: 'kakavia-fishermans-soup',
    title_el: 'Κακαβιά, η ψαρόσουπα των ψαράδων',
    title_en: 'Kakavia — Greek fisherman’s soup',
    steps_el: [
      'Καθαρίστε τα ψάρια, κόψτε τα μεγάλα σε κομμάτια και αλατίστε τα ελαφρά.',
      'Βάλτε σε φαρδιά κατσαρόλα τα κρεμμύδια σε φέτες, το σέλινο, τα καρότα, τις πατάτες σε χοντρά κομμάτια και τις ντομάτες στα τέσσερα.',
      'Προσθέστε το νερό, το λάδι, τη δάφνη και πιπέρι και βράστε 20 λεπτά.',
      'Ακουμπήστε τα ψάρια πάνω στα λαχανικά και σιγοβράστε 15 λεπτά χωρίς να ανακατέψετε, για να μη διαλυθούν.',
      'Βγάλτε προσεκτικά τα ψάρια και τα λαχανικά σε πιατέλα και σουρώστε τον ζωμό.',
      'Σερβίρετε τον ζωμό με λεμόνι και δίπλα τα ψάρια με τα λαχανικά.',
    ],
    steps_en: [
      'Clean the fish, cut the large ones into pieces and salt them lightly.',
      'Put the sliced onions, celery, carrots, potato chunks and quartered tomatoes in a wide pan.',
      'Add the water, oil, bay leaf and pepper and boil for 20 minutes.',
      'Lay the fish on top of the vegetables and simmer for 15 minutes without stirring, so it does not break up.',
      'Lift the fish and vegetables carefully onto a platter and strain the broth.',
      'Serve the broth with lemon, with the fish and vegetables alongside.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'grouper', quantity: 500, unit: 'g' },
      { ingredient_slug: 'red-mullet', quantity: 400, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'celery', quantity: 100, unit: 'g' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 2000, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'bay-leaf', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'gluten-free'],
  },
  {
    slug: 'bakaliaros-tiganitos-fried-salt-cod',
    title_el: 'Μπακαλιάρος τηγανητός',
    title_en: 'Bakaliaros — fried salt cod in batter',
    steps_el: [
      'Ξαρμυρίστε τον μπακαλιάρο σε κρύο νερό για 24–36 ώρες, αλλάζοντας το νερό 4–5 φορές.',
      'Βγάλτε πέτσα και κόκαλα, κόψτε τον σε μερίδες και στεγνώστε τον καλά.',
      'Χτυπήστε το αλεύρι με το ανθρακούχο νερό σε πηχτό κουρκούτι.',
      'Βουτήξτε τα κομμάτια στο κουρκούτι και τηγανίστε τα σε καυτό λάδι 3–4 λεπτά από κάθε πλευρά, μέχρι να ροδίσουν.',
      'Σερβίρετε με λεμόνι και σκορδαλιά — το πιάτο του Ευαγγελισμού και της Κυριακής των Βαΐων, όταν η νηστεία επιτρέπει ψάρι.',
    ],
    steps_en: [
      'Desalt the cod in cold water for 24–36 hours, changing the water 4–5 times.',
      'Remove skin and bones, cut it into portions and pat it very dry.',
      'Whisk the flour with the sparkling water into a thick batter.',
      'Dip the pieces in the batter and fry them in hot oil for 3–4 minutes a side until golden.',
      'Serve with lemon and skordalia — the dish of the Annunciation and Palm Sunday, when the fast allows fish.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'salted-cod',
        quantity: 500,
        unit: 'g',
        note_el: 'βάρος πριν το ξαρμύρισμα',
        note_en: 'weight before desalting',
      },
      { ingredient_slug: 'flour', quantity: 120, unit: 'g' },
      { ingredient_slug: 'sparkling-water', quantity: 200, unit: 'ml' },
      {
        ingredient_slug: 'sunflower-oil',
        quantity: 6,
        unit: 'tbsp',
        note_el: 'όσο απορροφάται στο τηγάνισμα',
        note_en: 'the amount absorbed in frying',
      },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'kotosoupa-avgolemono',
    title_el: 'Κοτόσουπα αυγολέμονο',
    title_en: 'Kotosoupa avgolemono — chicken soup with egg and lemon',
    steps_el: [
      'Βάλτε το κοτόπουλο σε μεγάλη κατσαρόλα με το νερό, βράστε το και ξαφρίστε.',
      'Ρίξτε το κρεμμύδι, τα καρότα, το σέλινο, αλάτι και πιπέρι και σιγοβράστε 1 ώρα, μέχρι να ξεκολλάει το κρέας.',
      'Βγάλτε το κοτόπουλο, σουρώστε τον ζωμό και βράστε μέσα του το ρύζι 18 λεπτά.',
      'Χτυπήστε τα αυγά με τον χυμό των λεμονιών σε μπολ μέχρι να αφρίσουν.',
      'Ρίξτε σιγά σιγά στο αυγολέμονο 2–3 κουτάλες ζεστό ζωμό, χτυπώντας συνεχώς, και αδειάστε το στην κατσαρόλα εκτός φωτιάς.',
      'Κουνήστε την κατσαρόλα να ενωθεί η σούπα και σερβίρετε με το κοτόπουλο ξεψαχνισμένο μέσα ή δίπλα.',
    ],
    steps_en: [
      'Put the chicken in a large pan with the water, bring to the boil and skim.',
      'Add the onion, carrots, celery, salt and pepper and simmer for 1 hour until the meat falls off the bone.',
      'Lift out the chicken, strain the broth and cook the rice in it for 18 minutes.',
      'Whisk the eggs with the lemon juice in a bowl until frothy.',
      'Whisk 2–3 ladles of hot broth into the egg-lemon, one at a time, then pour it into the pan off the heat.',
      'Swirl the pan so the soup comes together and serve with the chicken shredded into it or alongside.',
    ],
    portions: 6,
    prep_min: 100,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'whole-chicken', quantity: 1200, unit: 'g' },
      { ingredient_slug: 'water', quantity: 2500, unit: 'ml' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'celery', quantity: 100, unit: 'g' },
      { ingredient_slug: 'rice', quantity: 150, unit: 'g' },
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian', 'mediterranean', 'gluten-free'],
  },
  {
    slug: 'giouvarlakia-avgolemono-meatball-soup',
    title_el: 'Γιουβαρλάκια αυγολέμονο',
    title_en: 'Giouvarlakia — meatball and rice soup with egg and lemon',
    steps_el: [
      'Ζυμώστε τον κιμά με το ρύζι, το τριμμένο κρεμμύδι, τον μαϊντανό, τον άνηθο, 1 αυγό, αλάτι και πιπέρι.',
      'Πλάστε μικρά στρογγυλά γιουβαρλάκια, στο μέγεθος καρυδιού.',
      'Βράστε το νερό με το λάδι, ρίξτε ένα ένα τα γιουβαρλάκια και σιγοβράστε σκεπασμένα 40 λεπτά.',
      'Χτυπήστε τα 2 αυγά που έμειναν με τον χυμό των λεμονιών μέχρι να αφρίσουν.',
      'Ρίξτε σιγά σιγά στο αυγολέμονο 2–3 κουτάλες ζωμό, χτυπώντας, και αδειάστε το στην κατσαρόλα εκτός φωτιάς.',
      'Κουνήστε την κατσαρόλα να δέσει η σούπα και σερβίρετε αμέσως.',
    ],
    steps_en: [
      'Knead the mince with the rice, grated onion, parsley, dill, 1 egg, salt and pepper.',
      'Roll into small walnut-sized balls.',
      'Bring the water to the boil with the oil, drop in the meatballs one by one and simmer, covered, for 40 minutes.',
      'Whisk the remaining 2 eggs with the lemon juice until frothy.',
      'Whisk 2–3 ladles of broth into the egg-lemon, one at a time, then pour it into the pan off the heat.',
      'Swirl the pan so the soup thickens and serve at once.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beef-mince', quantity: 600, unit: 'g' },
      { ingredient_slug: 'rice', quantity: 100, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'egg', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 1500, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian', 'gluten-free'],
  },
  {
    slug: 'moussakas-aubergine-mince-bechamel',
    title_el: 'Μουσακάς',
    title_en: 'Moussaka — aubergine, mince and béchamel bake',
    steps_el: [
      'Κόψτε τις μελιτζάνες σε φέτες 1 εκ., αλατίστε τες και αφήστε τες 30 λεπτά· ξεπλύνετε και στεγνώστε τες.',
      'Αλείψτε τις μελιτζάνες και τις πατάτες σε φέτες με το μισό λάδι και ψήστε τες σε λαμαρίνες στους 200 °C για 25 λεπτά.',
      'Τσιγαρίστε τον κιμά με το κρεμμύδι και το σκόρδο στο υπόλοιπο λάδι, σβήστε με το κρασί και ρίξτε τις ντομάτες, την κανέλα, αλάτι και πιπέρι· σιγοβράστε 25 λεπτά να δέσει.',
      'Για την μπεσαμέλ λιώστε το βούτυρο, ρίξτε το αλεύρι και ανακατέψτε 2 λεπτά· προσθέστε σιγά σιγά το ζεστό γάλα, χτυπώντας μέχρι να πήξει.',
      'Εκτός φωτιάς ρίξτε το μοσχοκάρυδο, τα αυγά και το μισό κεφαλοτύρι και χτυπήστε γρήγορα.',
      'Στρώστε σε ταψί τις πατάτες, τις μισές μελιτζάνες, τον κιμά και τις υπόλοιπες μελιτζάνες· καλύψτε με την μπεσαμέλ και το υπόλοιπο κεφαλοτύρι.',
      'Ψήστε στους 180 °C για 45 λεπτά, μέχρι να πάρει χρυσαφί κρούστα.',
      'Αφήστε τον να σταθεί 30 λεπτά πριν τον κόψετε, για να κρατήσει το σχήμα του.',
    ],
    steps_en: [
      'Slice the aubergines 1 cm thick, salt them and leave for 30 minutes; rinse and pat dry.',
      'Brush the aubergine and the sliced potatoes with half the oil and roast them on trays at 200 °C for 25 minutes.',
      'Brown the mince with the onion and garlic in the rest of the oil, deglaze with the wine and add the tomatoes, cinnamon, salt and pepper; simmer for 25 minutes until thick.',
      'For the béchamel, melt the butter, stir in the flour for 2 minutes, then add the hot milk gradually, whisking until it thickens.',
      'Off the heat, whisk in the nutmeg, the eggs and half the kefalotyri quickly.',
      'Layer the potatoes, half the aubergine, the mince and the remaining aubergine in a tin; cover with the béchamel and the rest of the cheese.',
      'Bake at 180 °C for 45 minutes until golden on top.',
      'Rest for 30 minutes before cutting so it holds its shape.',
    ],
    portions: 8,
    prep_min: 150,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'eggplant', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'beef-mince', quantity: 700, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'butter', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'flour', quantity: 80, unit: 'g' },
      { ingredient_slug: 'milk', quantity: 750, unit: 'ml' },
      { ingredient_slug: 'nutmeg', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'kefalotyri', quantity: 80, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian'],
  },
  {
    slug: 'pastitsio-baked-pasta-mince-bechamel',
    title_el: 'Παστίτσιο',
    title_en: 'Pastitsio — baked pasta with mince and béchamel',
    steps_el: [
      'Τσιγαρίστε τον κιμά με το κρεμμύδι και το σκόρδο στο λάδι, σβήστε με το κρασί, ρίξτε τις ντομάτες, την κανέλα, το μπαχάρι, αλάτι και πιπέρι και σιγοβράστε 25 λεπτά.',
      'Βράστε τα μακαρόνια 2 λεπτά λιγότερο από τις οδηγίες, στραγγίστε και ανακατέψτε τα με 1 αυγό και το ένα τρίτο του κεφαλοτυριού.',
      'Για την μπεσαμέλ λιώστε το βούτυρο, ρίξτε το αλεύρι και ανακατέψτε 2 λεπτά· προσθέστε σιγά σιγά το ζεστό γάλα, χτυπώντας μέχρι να πήξει.',
      'Εκτός φωτιάς ρίξτε το μοσχοκάρυδο, τα 2 αυγά που έμειναν και το μισό από το υπόλοιπο κεφαλοτύρι.',
      'Στρώστε σε βουτυρωμένο ταψί τα μισά μακαρόνια, όλο τον κιμά και τα υπόλοιπα μακαρόνια· καλύψτε με την μπεσαμέλ και το τυρί που έμεινε.',
      'Ψήστε στους 180 °C για 50 λεπτά, μέχρι να ροδίσει.',
      'Αφήστε το 30 λεπτά να σταθεί πριν το κόψετε.',
    ],
    steps_en: [
      'Brown the mince with the onion and garlic in the oil, deglaze with the wine, add the tomatoes, cinnamon, allspice, salt and pepper and simmer for 25 minutes.',
      'Boil the pasta 2 minutes short of the packet time, drain and toss it with 1 egg and a third of the kefalotyri.',
      'For the béchamel, melt the butter, stir in the flour for 2 minutes, then add the hot milk gradually, whisking until it thickens.',
      'Off the heat, whisk in the nutmeg, the remaining 2 eggs and half of the remaining cheese.',
      'Layer half the pasta, all the mince and the rest of the pasta in a buttered tin; cover with the béchamel and the last of the cheese.',
      'Bake at 180 °C for 50 minutes until golden.',
      'Rest for 30 minutes before cutting.',
    ],
    portions: 10,
    prep_min: 120,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beef-mince', quantity: 600, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'red-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'allspice', quantity: 0.5, unit: 'tsp' },
      {
        ingredient_slug: 'pasta',
        quantity: 500,
        unit: 'g',
        note_el: 'χοντρά μακαρόνια για παστίτσιο',
        note_en: 'thick tubular pastitsio pasta',
      },
      { ingredient_slug: 'egg', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'kefalotyri', quantity: 120, unit: 'g' },
      { ingredient_slug: 'butter', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'flour', quantity: 100, unit: 'g' },
      { ingredient_slug: 'milk', quantity: 1000, unit: 'ml' },
      { ingredient_slug: 'nutmeg', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian'],
  },
  {
    slug: 'soutzoukakia-smyrneika',
    title_el: 'Σουτζουκάκια σμυρνέικα',
    title_en: 'Soutzoukakia — Smyrna-style meatballs in tomato sauce',
    steps_el: [
      'Μουλιάστε το ψωμί στο κρασί και στύψτε το.',
      'Ζυμώστε τον κιμά με το ψωμί, το μισό σκόρδο λιωμένο, το κύμινο, το αυγό, αλάτι και πιπέρι και αφήστε 30 λεπτά στο ψυγείο.',
      'Πλάστε μακρόστενα σουτζουκάκια και ροδίστε τα σε τηγάνι με το μισό λάδι.',
      'Σε κατσαρόλα σοτάρετε το υπόλοιπο σκόρδο στο υπόλοιπο λάδι, ρίξτε τις ντομάτες, τη ζάχαρη, τη δάφνη και την κανέλα και βράστε 10 λεπτά.',
      'Βάλτε τα σουτζουκάκια στη σάλτσα και σιγοβράστε 25 λεπτά.',
      'Σερβίρετε με ρύζι ή πουρέ.',
    ],
    steps_en: [
      'Soak the bread in the wine and squeeze it out.',
      'Knead the mince with the bread, half the garlic crushed, the cumin, the egg, salt and pepper and chill for 30 minutes.',
      'Shape into long ovals and brown them in a frying pan in half the oil.',
      'In a pan, soften the rest of the garlic in the rest of the oil, add the tomatoes, sugar, bay leaf and cinnamon and boil for 10 minutes.',
      'Add the meatballs to the sauce and simmer for 25 minutes.',
      'Serve with rice or mashed potatoes.',
    ],
    portions: 4,
    prep_min: 75,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beef-mince', quantity: 700, unit: 'g' },
      { ingredient_slug: 'bread', quantity: 3, unit: 'slice' },
      { ingredient_slug: 'red-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'garlic', quantity: 4, unit: 'clove' },
      { ingredient_slug: 'cumin', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'egg', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 800, unit: 'g' },
      { ingredient_slug: 'sugar', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'bay-leaf', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian'],
  },
  {
    slug: 'giouvetsi-beef-orzo',
    title_el: 'Γιουβέτσι με μοσχάρι',
    title_en: 'Giouvetsi — oven-baked beef with orzo',
    steps_el: [
      'Κόψτε το μοσχάρι σε μερίδες και ροδίστε το στο λάδι από όλες τις πλευρές.',
      'Ρίξτε το κρεμμύδι και το σκόρδο, σοτάρετε 3 λεπτά και σβήστε με το κρασί.',
      'Προσθέστε τον πελτέ, τις ντομάτες, την κανέλα, το μπαχάρι, τη δάφνη, αλάτι, πιπέρι και ένα ποτήρι από το νερό και σιγοβράστε σκεπασμένο 1 ώρα και 15 λεπτά.',
      'Μεταφέρετε κρέας και σάλτσα σε γάστρα ή πήλινο, προσθέστε το κριθαράκι και το υπόλοιπο νερό ζεστό και ανακατέψτε.',
      'Ψήστε στους 180 °C για 30–35 λεπτά, ανακατεύοντας μία φορά, μέχρι να μαλακώσει το κριθαράκι.',
      'Σερβίρετε με τριμμένο κεφαλοτύρι από πάνω.',
    ],
    steps_en: [
      'Cut the beef into portions and brown it in the oil on all sides.',
      'Add the onion and garlic, sauté for 3 minutes and deglaze with the wine.',
      'Add the tomato paste, tomatoes, cinnamon, allspice, bay leaves, salt, pepper and a glass of the water and simmer, covered, for 1 hour 15 minutes.',
      'Move the meat and sauce to a clay or roasting dish, add the orzo and the rest of the water, hot, and stir.',
      'Bake at 180 °C for 30–35 minutes, stirring once, until the orzo is tender.',
      'Serve with grated kefalotyri on top.',
    ],
    portions: 6,
    prep_min: 140,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beef-stew', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-wine', quantity: 150, unit: 'ml' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'allspice', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 1200, unit: 'ml' },
      { ingredient_slug: 'orzo', quantity: 400, unit: 'g' },
      { ingredient_slug: 'kefalotyri', quantity: 60, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian'],
  },
  {
    slug: 'moschari-stifado-beef-pearl-onions',
    title_el: 'Μοσχάρι στιφάδο',
    title_en: 'Beef stifado with pearl onions',
    steps_el: [
      'Ζεματίστε τα κρεμμυδάκια 2 λεπτά, ξεφλουδίστε τα και κρατήστε τα ολόκληρα.',
      'Ροδίστε το μοσχάρι στο λάδι σε φαρδιά κατσαρόλα και βγάλτε το.',
      'Στο ίδιο λάδι σοτάρετε τα κρεμμυδάκια 10 λεπτά να καραμελώσουν και ρίξτε το σκόρδο.',
      'Επιστρέψτε το κρέας, σβήστε με το κρασί και το ξίδι και ρίξτε τον πελτέ, τις ντομάτες, τα μπαχαρικά, αλάτι, πιπέρι και το νερό.',
      'Σιγοβράστε σκεπασμένο 1,5–2 ώρες χωρίς να ανακατεύετε με κουτάλι — κουνήστε την κατσαρόλα — μέχρι να μαλακώσει το κρέας και να δέσει η σάλτσα.',
      'Αφήστε το 10 λεπτά να ξεκουραστεί και σερβίρετε.',
    ],
    steps_en: [
      'Blanch the pearl onions for 2 minutes, peel them and keep them whole.',
      'Brown the beef in the oil in a wide pan and lift it out.',
      'In the same oil, cook the onions for 10 minutes until caramelised and add the garlic.',
      'Return the meat, deglaze with the wine and vinegar and add the tomato paste, tomatoes, spices, salt, pepper and the water.',
      'Simmer, covered, for 1.5–2 hours without stirring with a spoon — shake the pan instead — until the meat is tender and the sauce thick.',
      'Rest for 10 minutes and serve.',
    ],
    portions: 5,
    prep_min: 150,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beef-stew', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'pearl-onions', quantity: 1000, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'garlic', quantity: 4, unit: 'clove' },
      { ingredient_slug: 'red-wine', quantity: 200, unit: 'ml' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'bay-leaf', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'allspice', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cloves', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 300, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['flexitarian', 'gluten-free'],
  },
]

/**
 * Existing recipes that already fit an ordinary fasting day (see the header: strict, mechanical,
 * the shop-pita dish left out). `./greek-kitchen.test.ts` proves this list is exactly the base
 * recipes the fasting rule admits, so it can be neither padded nor short.
 */
export const FASTING_EXISTING_SLUGS: readonly string[] = [
  'oat-porridge-banana-walnuts',
  'overnight-oats-apple-cinnamon',
  'avocado-toast-whole-wheat',
  'green-smoothie-spinach-banana',
  'tahini-petimezi-toast',
  'tofu-scramble-turmeric-peppers',
  'seasonal-fruit-salad-walnuts',
  'fasolada-white-bean-soup',
  'fakes-lentil-soup',
  'revithada-sifnos-baked-chickpeas',
  'gigantes-plaki-baked-giant-beans',
  'fava-santorini-yellow-split-pea-puree',
  'hummus-homemade',
  'pumpkin-red-lentil-soup',
  'gemista-stuffed-tomatoes-peppers',
  'briam-baked-summer-vegetables',
  'spanakorizo-spinach-rice',
  'lahanorizo-cabbage-rice',
  'imam-bayildi-stuffed-eggplant',
  'arakas-latheros-pea-stew',
  'fasolakia-ladera-green-bean-stew',
  'bamies-okra-tomato-stew',
  'chickpea-salad-lemon-parsley',
  'lentil-salad-roasted-beetroot-walnuts',
  'quinoa-tabbouleh',
  'roasted-cauliflower-tahini-pomegranate',
  'spaghetti-tomato-garlic-basil',
  'lentil-bolognese-whole-wheat-pasta',
  'octopus-xydato-vinegar-oregano',
  'mydopilafo-mussel-rice',
  'roasted-chickpeas-paprika-cumin',
  'date-oat-energy-balls',
  'paleo-chia-coconut-pudding',
  'paleo-berry-coconut-smoothie',
  'keto-chocolate-almond-fat-bombs',
  'chia-pudding-coconut-strawberry',
  'overnight-oats-peanut-banana',
  'quinoa-porridge-orange-walnuts',
  'almond-milk-rice-pudding',
  'buckwheat-chia-seeded-bread',
  'fruit-salad-coconut-walnuts',
  'socca-roasted-peppers-rocket',
  'carrot-ginger-rice-soup',
  'rice-noodle-tofu-peanut-salad',
  'quinoa-black-bean-sweet-potato-bowl',
  'date-walnut-cocoa-energy-balls',
  'apple-almond-butter-cinnamon',
  'rice-cakes-peanut-butter-banana',
]

export const OVERLAY: Overlay = {
  id: '0003-greek-kitchen',
  summary:
    'Orthodox fasting diet, 30 classic Greek recipes, 2 ingredients, fasting tag on 48 existing recipes',
  additions: {
    ingredients: INGREDIENTS,
    diets: [
      {
        slug: 'fasting',
        name_el: 'Νηστεία (Ορθόδοξη)',
        name_en: 'Orthodox fasting (Lent)',
        summary_el:
          'Η νηστεία της Ορθόδοξης Εκκλησίας, όπως την τηρούν πολλοί Έλληνες. Τις ημέρες νηστείας δεν τρώγονται κρέας, πουλερικά, γαλακτοκομικά και αυγά· το ψάρι με ραχοκοκαλιά επιτρέπεται μόνο σε ορισμένες γιορτές (Ευαγγελισμός, Κυριακή των Βαΐων), ενώ χταπόδι, καλαμάρι, σουπιά, γαρίδες, μύδια και ταραμάς επιτρέπονται. Στις αυστηρές ημέρες (ξηροφαγία) παραλείπονται και το λάδι και το κρασί. Οι μεγάλες περίοδοι είναι η Μεγάλη Σαρακοστή πριν από το Πάσχα, η νηστεία των Χριστουγέννων (15 Νοεμβρίου–24 Δεκεμβρίου), του Δεκαπενταύγουστου (1–14 Αυγούστου) και των Αγίων Αποστόλων, καθώς και κάθε Τετάρτη και Παρασκευή. Στην πράξη είναι φυτική διατροφή με όσπρια, λαδερά, χόρτα και θαλασσινά. Η ετικέτα «Νηστεία» σε μια συνταγή σημαίνει ότι ταιριάζει σε συνηθισμένη ημέρα νηστείας με λάδι και κρασί.',
        summary_en:
          'The fast of the Orthodox Church as many Greeks keep it. On fasting days there is no meat, poultry, dairy or eggs; fish with a backbone is allowed only on certain feasts (the Annunciation, Palm Sunday), while octopus, squid, cuttlefish, shrimp, mussels and fish roe (taramas) are allowed. On strict days (xerofagia) oil and wine are dropped too. The main periods are Great Lent before Easter, the Nativity fast (15 November–24 December), the Dormition fast (1–14 August) and the Apostles’ fast, plus every Wednesday and Friday. In practice it is a plant-based diet of legumes, vegetables cooked in olive oil, greens and seafood. The "Fasting" tag on a recipe means it fits an ordinary fasting day with oil and wine.',
        allowed_el: [
          'Όσπρια: φακές, φασόλια, ρεβίθια, φάβα, γίγαντες',
          'Λαδερά: φασολάκια, μπάμιες, αρακάς, μπριάμ, γεμιστά',
          'Χόρτα, λαχανικά και φρούτα εποχής',
          'Ψωμί, λαγάνα, ρύζι, ζυμαρικά χωρίς αυγό, πλιγούρι',
          'Χταπόδι, καλαμάρι, σουπιά, γαρίδες, μύδια και ταραμάς',
          'Ταχίνι, χαλβάς, ξηροί καρποί και ελιές',
          'Ελαιόλαδο και κρασί, εκτός από τις ημέρες ξηροφαγίας',
          'Φυτικά ροφήματα (βρώμης, αμυγδάλου, σόγιας) και τόφου',
        ],
        allowed_en: [
          'Legumes: lentils, beans, chickpeas, fava, giant beans',
          'Vegetables cooked in olive oil (ladera): green beans, okra, peas, briam, gemista',
          'Greens, vegetables and seasonal fruit',
          'Bread, lagana, rice, egg-free pasta, bulgur',
          'Octopus, squid, cuttlefish, shrimp, mussels and fish roe (taramas)',
          'Tahini, halva, nuts and olives',
          'Olive oil and wine, except on strict (xerofagia) days',
          'Plant milks (oat, almond, soy) and tofu',
        ],
        avoided_el: [
          'Κρέας και αλλαντικά',
          'Πουλερικά',
          'Γάλα, γιαούρτι, τυρί και βούτυρο',
          'Αυγά, και ζυμαρικά με αυγό όπως οι χυλοπίτες',
          'Ψάρι με ραχοκοκαλιά, εκτός από τις ημέρες που επιτρέπεται',
          'Ζωικά λίπη (λαρδί, λίπος μοσχαριού) και ζελατίνη',
          'Λάδι και κρασί στις ημέρες ξηροφαγίας: κατά την αυστηρή τήρηση, οι καθημερινές της Μεγάλης Σαρακοστής και η Μεγάλη Παρασκευή',
        ],
        avoided_en: [
          'Meat and cold cuts',
          'Poultry',
          'Milk, yoghurt, cheese and butter',
          'Eggs, and egg pasta such as hilopites',
          'Fish with a backbone, except on the days it is allowed',
          'Animal fats (lard, tallow) and gelatin',
          'Oil and wine on strict days: in the strict rule, the weekdays of Great Lent and Good Friday',
        ],
        pros_el: [
          'Φέρνει στο τραπέζι πολλά όσπρια, λαχανικά και φυτικές ίνες — τον πυρήνα της παραδοσιακής μεσογειακής διατροφής',
          'Μελέτη σε Κρητικούς που νήστευαν (Sarri και συν., British Journal of Nutrition, 2004) έδειξε χαμηλότερη ολική και LDL χοληστερόλη στις περιόδους νηστείας',
          'Η ελληνική κουζίνα έχει πλούσια νηστίσιμη παράδοση: λαδερά, όσπρια, πίτες, θαλασσινά',
          'Οικονομική, αφού βασίζεται σε όσπρια και λαχανικά εποχής',
        ],
        pros_en: [
          'Puts plenty of legumes, vegetables and fibre on the table — the core of the traditional Mediterranean diet',
          'A study of fasting Cretans (Sarri et al., British Journal of Nutrition, 2004) found lower total and LDL cholesterol during fasting periods',
          'Greek cooking has a rich fasting tradition: ladera, legumes, pies, seafood',
          'Inexpensive, since it rests on legumes and seasonal vegetables',
        ],
        cons_el: [
          'Χωρίς σχεδιασμό, οι μεγάλες περίοδοι μπορεί να δώσουν λιγότερη πρωτεΐνη, ασβέστιο, σίδηρο και βιταμίνη B12',
          'Τα «νηστίσιμα» έτοιμα γλυκά και αρτοσκευάσματα έχουν συχνά πολλή ζάχαρη και λίπος',
          'Το πολύ λάδι στα λαδερά ανεβάζει γρήγορα τις θερμίδες',
          'Οι κανόνες διαφέρουν ανά περίοδο, ημέρα και τοπική παράδοση',
        ],
        cons_en: [
          'Without planning, long periods can mean less protein, calcium, iron and vitamin B12',
          'Shop-bought "fasting" sweets and baked goods are often high in sugar and fat',
          'Generous olive oil in ladera adds calories quickly',
          'The rules vary by period, day and local tradition',
        ],
        avoid_if_el: [
          'Αν είστε έγκυος ή θηλάζετε, έχετε διαβήτη (ιδίως με ινσουλίνη ή φάρμακα που ρίχνουν το σάκχαρο), νεφρική νόσο ή άλλη διαγνωσμένη πάθηση, ρωτήστε πρώτα γιατρό ή διαιτολόγο.',
          'Η Εκκλησία απαλλάσσει από την αυστηρή νηστεία τα παιδιά, τους ηλικιωμένους, τους ασθενείς και τις εγκύους· η απόφαση παίρνεται με τον πνευματικό και τον γιατρό.',
          'Αν έχετε ιστορικό διατροφικής διαταραχής, μιλήστε πρώτα με επαγγελματία υγείας.',
          'Στις μεγάλες περιόδους, φροντίστε για αρκετή πρωτεΐνη από όσπρια και θαλασσινά και ρωτήστε για συμπλήρωμα βιταμίνης B12.',
        ],
        avoid_if_en: [
          'If you are pregnant or breastfeeding, have diabetes (especially on insulin or glucose-lowering medication), kidney disease or another diagnosed condition, ask a doctor or dietitian first.',
          'The Church excuses children, the elderly, the sick and pregnant women from the strict fast; decide with your spiritual father and your doctor.',
          'If you have a history of an eating disorder, talk to a health professional first.',
          'In the long periods, get enough protein from legumes and seafood and ask about a vitamin B12 supplement.',
        ],
        source_url: 'https://www.goarch.org/-/fasting',
      },
    ],
    recipes: RECIPES,
    recipe_diets: FASTING_EXISTING_SLUGS.map((recipe_slug) => ({
      recipe_slug,
      diet_slug: 'fasting',
    })),
  },
}
