// SEED CONTENT — diets (P1.10). Sixteen well-defined eating patterns, EL + EN on the same row
// (PLAN.md §1.2). Informational, not prescriptive; evidence quality stated honestly in pros/cons.
// `source_url` is a real, stable, authoritative page or null — never a guess (PLAN.md §0). Greek
// loanwords (keto, paleo, Atkins, Whole30, DASH, FODMAP) stay Latin-script inside Greek text.
// The seed generator (P1.12) turns this array into the seed migration; the app keys diets by slug.

import type { DietSeed } from '../types.ts'

/** The caution every diet carries, in both languages (PLAN.md P1.10). */
export const ASK_DOCTOR_EL =
  'Αν είστε έγκυος ή θηλάζετε, βρίσκεστε υπό ιατρική αγωγή ή έχετε διαγνωσμένη πάθηση, ρωτήστε πρώτα γιατρό ή διαιτολόγο.'
export const ASK_DOCTOR_EN =
  'If you are pregnant or breastfeeding, under medical treatment, or have a diagnosed condition, ask a doctor or dietitian first.'

export const DIETS: readonly DietSeed[] = [
  {
    slug: 'mediterranean',
    name_el: 'Μεσογειακή διατροφή',
    name_en: 'Mediterranean diet',
    summary_el:
      'Το παραδοσιακό διατροφικό πρότυπο της Κρήτης, της νότιας Ιταλίας και άλλων μεσογειακών περιοχών, όπως καταγράφηκε στη Μελέτη των Επτά Χωρών τη δεκαετία του 1950. Βασίζεται σε λαχανικά, όσπρια, φρούτα, δημητριακά ολικής άλεσης, ελαιόλαδο και ψάρι, με λίγο κόκκινο κρέας και ελάχιστα επεξεργασμένα τρόφιμα. Δεν μετράει θερμίδες ούτε αποκλείει ομάδες τροφίμων· δίνει έμφαση στην ποιότητα και στο κοινό γεύμα.',
    summary_en:
      'The traditional eating pattern of Crete, southern Italy and other Mediterranean regions, as documented in the Seven Countries Study of the 1950s. It is built on vegetables, legumes, fruit, whole grains, olive oil and fish, with little red meat and few processed foods. It counts no calories and excludes no food group; the emphasis is on quality and on eating together.',
    allowed_el: [
      'Ελαιόλαδο ως κύριο λίπος',
      'Λαχανικά και χόρτα κάθε μέρα',
      'Όσπρια (φακές, ρεβίθια, φασόλια)',
      'Δημητριακά ολικής άλεσης, ψωμί, ζυμαρικά',
      'Φρούτα εποχής',
      'Ψάρι και θαλασσινά 2–3 φορές την εβδομάδα',
      'Ξηροί καρποί και σπόροι',
      'Γιαούρτι και τυρί σε μέτριες ποσότητες',
      'Βότανα και μπαχαρικά αντί για αλάτι',
    ],
    allowed_en: [
      'Olive oil as the main fat',
      'Vegetables and greens every day',
      'Legumes (lentils, chickpeas, beans)',
      'Whole grains, bread, pasta',
      'Seasonal fruit',
      'Fish and seafood two to three times a week',
      'Nuts and seeds',
      'Yoghurt and cheese in moderate amounts',
      'Herbs and spices instead of salt',
    ],
    avoided_el: [
      'Επεξεργασμένα κρέατα (αλλαντικά)',
      'Κόκκινο κρέας πάνω από λίγες φορές τον μήνα',
      'Ζαχαρούχα αναψυκτικά',
      'Γλυκά και αρτοσκευάσματα με πρόσθετη ζάχαρη',
      'Βούτυρο και μαργαρίνη ως κύριο λίπος',
      'Έτοιμα, πολύ επεξεργασμένα τρόφιμα',
    ],
    avoided_en: [
      'Processed meats (cold cuts, sausages)',
      'Red meat more than a few times a month',
      'Sugary soft drinks',
      'Sweets and pastries with added sugar',
      'Butter and margarine as the main fat',
      'Ready-made, ultra-processed foods',
    ],
    pros_el: [
      'Από τα καλύτερα μελετημένα διατροφικά πρότυπα· τυχαιοποιημένες μελέτες (π.χ. PREDIMED) δείχνουν λιγότερα καρδιαγγειακά συμβάντα',
      'Ευέλικτο, χωρίς αποκλεισμούς· εύκολο να το ακολουθήσει κανείς μακροχρόνια',
      'Ταιριάζει φυσικά με τα ελληνικά προϊόντα και την εποχικότητα',
      'Πλούσιο σε φυτικές ίνες, ακόρεστα λιπαρά και αντιοξειδωτικά',
    ],
    pros_en: [
      'One of the best-studied eating patterns; randomised trials (e.g. PREDIMED) show fewer cardiovascular events',
      'Flexible, with no exclusions; easy to keep up long-term',
      'Fits Greek produce and seasonality naturally',
      'Rich in fibre, unsaturated fats and antioxidants',
    ],
    cons_el: [
      'Δεν δίνει αυτόματα απώλεια βάρους· οι ποσότητες ελαιολάδου, ψωμιού και ξηρών καρπών μετράνε',
      'Ψάρι, ελαιόλαδο και φρέσκα προϊόντα μπορεί να κοστίζουν περισσότερο',
      'Ο ορισμός διαφέρει από μελέτη σε μελέτη, οπότε η «μεσογειακή» ετικέτα χρησιμοποιείται χαλαρά',
    ],
    cons_en: [
      'Does not produce weight loss by itself; portions of olive oil, bread and nuts still count',
      'Fish, olive oil and fresh produce can cost more',
      'The definition varies between studies, so the "Mediterranean" label is used loosely',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε αλλεργία στα ψάρια, τα θαλασσινά ή τους ξηρούς καρπούς, προσαρμόστε τις πηγές πρωτεΐνης και λίπους με έναν διαιτολόγο.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you are allergic to fish, shellfish or nuts, adapt the protein and fat sources with a dietitian.',
    ],
    source_url:
      'https://nutritionsource.hsph.harvard.edu/healthy-weight/diet-reviews/mediterranean-diet/',
  },
  {
    slug: 'dash',
    name_el: 'Δίαιτα DASH',
    name_en: 'DASH diet',
    summary_el:
      'Το DASH (Dietary Approaches to Stop Hypertension) αναπτύχθηκε από το αμερικανικό NHLBI τη δεκαετία του 1990 ως διατροφικό σχήμα για τη μείωση της αρτηριακής πίεσης. Δίνει έμφαση σε λαχανικά, φρούτα, γαλακτοκομικά χαμηλών λιπαρών, δημητριακά ολικής άλεσης, όσπρια και ξηρούς καρπούς, περιορίζοντας το νάτριο, τα κορεσμένα λιπαρά και τη ζάχαρη. Ορίζεται με μερίδες ανά ομάδα τροφίμων για δεδομένο επίπεδο θερμίδων.',
    summary_en:
      'DASH (Dietary Approaches to Stop Hypertension) was developed by the US NHLBI in the 1990s as an eating plan to lower blood pressure. It emphasises vegetables, fruit, low-fat dairy, whole grains, legumes and nuts while limiting sodium, saturated fat and sugar. It is defined as servings per food group for a given calorie level.',
    allowed_el: [
      'Λαχανικά 4–5 μερίδες την ημέρα',
      'Φρούτα 4–5 μερίδες την ημέρα',
      'Δημητριακά ολικής άλεσης',
      'Γαλακτοκομικά χαμηλών λιπαρών',
      'Άπαχο πουλερικό και ψάρι',
      'Όσπρια, ξηροί καρποί, σπόροι λίγες φορές την εβδομάδα',
      'Φυτικά έλαια σε μικρές ποσότητες',
    ],
    allowed_en: [
      'Vegetables, four to five servings a day',
      'Fruit, four to five servings a day',
      'Whole grains',
      'Low-fat dairy',
      'Lean poultry and fish',
      'Legumes, nuts and seeds a few times a week',
      'Vegetable oils in small amounts',
    ],
    avoided_el: [
      'Αλάτι πάνω από 2.300 mg νατρίου την ημέρα (ή 1.500 mg στην αυστηρή εκδοχή)',
      'Αλμυρά σνακ και κονσέρβες με πολύ νάτριο',
      'Αλλαντικά και επεξεργασμένα κρέατα',
      'Πλήρη γαλακτοκομικά και βούτυρο',
      'Ζαχαρούχα ποτά και γλυκά',
      'Λιπαρά κόκκινα κρέατα',
    ],
    avoided_en: [
      'Salt above 2,300 mg sodium a day (or 1,500 mg in the stricter version)',
      'Salty snacks and high-sodium tinned foods',
      'Cold cuts and processed meats',
      'Full-fat dairy and butter',
      'Sugary drinks and sweets',
      'Fatty red meats',
    ],
    pros_el: [
      'Τεκμηριωμένο σε τυχαιοποιημένες δοκιμές ότι μειώνει την αρτηριακή πίεση μέσα σε λίγες εβδομάδες',
      'Ισορροπημένο και πλήρες· δεν αποκλείει ομάδες τροφίμων',
      'Σαφείς οδηγίες μερίδων, εύκολο να προσαρμοστεί σε διαφορετικές θερμίδες',
      'Συστήνεται από πολλούς επίσημους οργανισμούς υγείας',
    ],
    pros_en: [
      'Shown in randomised trials to lower blood pressure within weeks',
      'Balanced and complete; excludes no food group',
      'Clear serving guidance, easy to scale to different calorie levels',
      'Recommended by many official health bodies',
    ],
    cons_el: [
      'Η καταμέτρηση μερίδων απαιτεί προσοχή, ειδικά στην αρχή',
      'Ο αυστηρός περιορισμός αλατιού δυσκολεύει το φαγητό έξω και τα τυποποιημένα τρόφιμα',
      'Σχεδιάστηκε για την πίεση, όχι για απώλεια βάρους· οι θερμίδες πρέπει να ρυθμιστούν χωριστά',
    ],
    cons_en: [
      'Counting servings takes attention, especially at first',
      'The strict salt limit makes eating out and packaged foods harder',
      'Designed for blood pressure, not weight loss; calories must be set separately',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν παίρνετε φάρμακα για την πίεση ή διουρητικά, η αλλαγή στο αλάτι και στο κάλιο πρέπει να συντονιστεί με τον γιατρό σας.',
      'Αν έχετε χρόνια νεφρική νόσο, η πρόσληψη καλίου από φρούτα και λαχανικά χρειάζεται ιατρική καθοδήγηση.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you take blood-pressure medication or diuretics, the change in salt and potassium should be coordinated with your doctor.',
      'If you have chronic kidney disease, the potassium intake from fruit and vegetables needs medical guidance.',
    ],
    source_url: 'https://www.nhlbi.nih.gov/education/dash-eating-plan',
  },
  {
    slug: 'flexitarian',
    name_el: 'Flexitarian (ευέλικτη χορτοφαγία)',
    name_en: 'Flexitarian diet',
    summary_el:
      'Ένα κυρίως φυτικό διατροφικό πρότυπο που επιτρέπει κρέας και ψάρι περιστασιακά και σε μικρές ποσότητες. Ο όρος διαδόθηκε από τη διαιτολόγο Dawn Jackson Blatner (2009), αλλά η ιδέα ταυτίζεται με το πώς έτρωγαν παραδοσιακά πολλές αγροτικές κοινωνίες, και στην Ελλάδα. Δεν υπάρχει αυστηρός κανόνας· ο στόχος είναι τα όσπρια, τα λαχανικά και τα δημητριακά να γίνουν η βάση του πιάτου.',
    summary_en:
      'A mostly plant-based eating pattern that allows meat and fish occasionally and in small amounts. The term was popularised by dietitian Dawn Jackson Blatner (2009), but the idea matches how many farming communities, Greece included, traditionally ate. There is no strict rule; the aim is for legumes, vegetables and grains to become the base of the plate.',
    allowed_el: [
      'Όσπρια, τόφου και άλλες φυτικές πρωτεΐνες ως βάση',
      'Λαχανικά, φρούτα, δημητριακά ολικής άλεσης',
      'Αυγά και γαλακτοκομικά',
      'Ξηροί καρποί, σπόροι, ελαιόλαδο',
      'Ψάρι περιστασιακά',
      'Κρέας σπάνια και σε μικρή μερίδα, κατά προτίμηση πουλερικό',
    ],
    allowed_en: [
      'Legumes, tofu and other plant proteins as the base',
      'Vegetables, fruit, whole grains',
      'Eggs and dairy',
      'Nuts, seeds, olive oil',
      'Fish occasionally',
      'Meat rarely and in a small portion, preferably poultry',
    ],
    avoided_el: [
      'Κρέας σε κάθε γεύμα',
      'Επεξεργασμένα κρέατα και αλλαντικά',
      'Πολύ επεξεργασμένα «φυτικά» υποκατάστατα με πολύ αλάτι',
      'Ζαχαρούχα ποτά και γλυκά',
      'Τηγανητά και έτοιμα φαγητά',
      'Εξευγενισμένα δημητριακά ως κύρια πηγή υδατανθράκων',
    ],
    avoided_en: [
      'Meat at every meal',
      'Processed meats and cold cuts',
      'Ultra-processed "plant-based" substitutes high in salt',
      'Sugary drinks and sweets',
      'Fried and ready-made foods',
      'Refined grains as the main carbohydrate source',
    ],
    pros_el: [
      'Παρατηρησιακές μελέτες συνδέουν τα κυρίως φυτικά πρότυπα με χαμηλότερο κίνδυνο καρδιοπάθειας και διαβήτη τύπου 2',
      'Χωρίς αυστηρές απαγορεύσεις· εύκολο σε οικογενειακά και κοινωνικά γεύματα',
      'Χαμηλότερο κόστος και περιβαλλοντικό αποτύπωμα από την κρεατοφαγία',
      'Ομαλό πρώτο βήμα προς τη χορτοφαγία για όποιον το θέλει',
    ],
    pros_en: [
      'Observational studies link mostly plant-based patterns to lower risk of heart disease and type 2 diabetes',
      'No strict bans; easy at family and social meals',
      'Lower cost and environmental footprint than a meat-centred diet',
      'A gentle first step towards vegetarianism for those who want it',
    ],
    cons_el: [
      'Ασαφής ορισμός· το «περιστασιακά» σημαίνει διαφορετικά πράγματα για τον καθένα',
      'Λιγότερες άμεσες μελέτες από ό,τι η μεσογειακή ή η χορτοφαγική διατροφή',
      'Χρειάζεται προσοχή στον σίδηρο και τη βιταμίνη B12 όσο μειώνεται το κρέας',
    ],
    cons_en: [
      'Loosely defined; "occasionally" means different things to different people',
      'Fewer direct studies than the Mediterranean or vegetarian diets',
      'Iron and vitamin B12 need attention as meat is reduced',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε ιστορικό σιδηροπενικής αναιμίας, παρακολουθήστε τον σίδηρο καθώς μειώνετε το κρέας.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have a history of iron-deficiency anaemia, monitor your iron as you cut back on meat.',
    ],
    source_url: null,
  },
  {
    slug: 'pescatarian',
    name_el: 'Pescatarian (ψαροφαγική χορτοφαγία)',
    name_en: 'Pescatarian diet',
    summary_el:
      'Χορτοφαγική διατροφή που περιλαμβάνει ψάρι και θαλασσινά αλλά όχι κρέας ή πουλερικά· συνήθως περιλαμβάνει και αυγά και γαλακτοκομικά. Η λέξη συνδυάζει το ιταλικό pesce (ψάρι) με το vegetarian και εμφανίστηκε τη δεκαετία του 1990. Στην πράξη μοιάζει πολύ με τη μεσογειακή διατροφή των νησιών, όπου το ψάρι ήταν η κύρια ζωική πρωτεΐνη.',
    summary_en:
      'A vegetarian diet that includes fish and seafood but no meat or poultry; it usually includes eggs and dairy too. The word combines the Italian pesce (fish) with vegetarian and appeared in the 1990s. In practice it closely resembles the island Mediterranean diet, where fish was the main animal protein.',
    allowed_el: [
      'Ψάρια, ιδίως λιπαρά (σαρδέλα, γαύρος, σκουμπρί, σολομός)',
      'Θαλασσινά (γαρίδες, μύδια, καλαμάρι)',
      'Αυγά και γαλακτοκομικά',
      'Όσπρια και τόφου',
      'Λαχανικά, φρούτα, δημητριακά ολικής άλεσης',
      'Ξηροί καρποί, σπόροι, ελαιόλαδο',
    ],
    allowed_en: [
      'Fish, especially oily fish (sardines, anchovies, mackerel, salmon)',
      'Seafood (prawns, mussels, squid)',
      'Eggs and dairy',
      'Legumes and tofu',
      'Vegetables, fruit, whole grains',
      'Nuts, seeds, olive oil',
    ],
    avoided_el: [
      'Κόκκινο κρέας (μοσχάρι, χοιρινό, αρνί)',
      'Πουλερικά',
      'Αλλαντικά και επεξεργασμένα κρέατα',
      'Ζωμοί και σάλτσες με βάση το κρέας',
      'Ζελατίνη ζωικής προέλευσης (για τους αυστηρότερους)',
      'Μεγάλα αρπακτικά ψάρια με πολύ υδράργυρο σε συχνή κατανάλωση (ξιφίας, καρχαρίας)',
    ],
    avoided_en: [
      'Red meat (beef, pork, lamb)',
      'Poultry',
      'Cold cuts and processed meats',
      'Meat-based stocks and sauces',
      'Animal gelatine (for stricter followers)',
      'Large predatory fish high in mercury eaten often (swordfish, shark)',
    ],
    pros_el: [
      'Παρέχει ωμέγα-3 λιπαρά, βιταμίνη B12 και πλήρη πρωτεΐνη που λείπουν συχνά από την αυστηρή χορτοφαγία',
      'Μεγάλες μελέτες κοόρτης δείχνουν ευνοϊκή καρδιαγγειακή εικόνα',
      'Μεγάλη ποικιλία πιάτων· εύκολο στην ελληνική κουζίνα',
    ],
    pros_en: [
      'Provides omega-3 fats, vitamin B12 and complete protein that strict vegetarian diets often lack',
      'Large cohort studies show a favourable cardiovascular profile',
      'Wide variety of dishes; easy within Greek cooking',
    ],
    cons_el: [
      'Το φρέσκο ψάρι κοστίζει· οι κονσέρβες και τα κατεψυγμένα βοηθούν',
      'Ο υδράργυρος στα μεγάλα ψάρια απαιτεί προσοχή, ειδικά στην εγκυμοσύνη',
      'Η βιωσιμότητα εξαρτάται από το είδος και τη μέθοδο αλιείας',
    ],
    cons_en: [
      'Fresh fish is expensive; tinned and frozen options help',
      'Mercury in large fish needs attention, especially in pregnancy',
      'Sustainability depends on the species and fishing method',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε αλλεργία σε ψάρια ή οστρακοειδή, το πρότυπο αυτό δεν είναι κατάλληλο.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you are allergic to fish or shellfish, this pattern is not suitable.',
    ],
    source_url: null,
  },
  {
    slug: 'vegetarian',
    name_el: 'Χορτοφαγική διατροφή',
    name_en: 'Vegetarian diet',
    summary_el:
      'Διατροφή χωρίς κρέας, πουλερικά και ψάρι. Η πιο διαδεδομένη μορφή (λακτο-ωο-χορτοφαγία) περιλαμβάνει αυγά και γαλακτοκομικά. Έχει μακρά ιστορία για θρησκευτικούς, ηθικούς και υγειονομικούς λόγους, από την Ινδία και την αρχαία Ελλάδα (Πυθαγόρας) ως τη νηστεία της Ορθόδοξης παράδοσης. Οι σημερινές οδηγίες υγείας τη θεωρούν πλήρη, εφόσον σχεδιαστεί σωστά.',
    summary_en:
      'A diet without meat, poultry or fish. The most common form (lacto-ovo vegetarian) includes eggs and dairy. It has a long history for religious, ethical and health reasons, from India and ancient Greece (Pythagoras) to Orthodox fasting traditions. Current health guidance considers it nutritionally complete when well planned.',
    allowed_el: [
      'Όσπρια (φακές, ρεβίθια, φασόλια, φάβα)',
      'Αυγά',
      'Γαλακτοκομικά (γιαούρτι, τυρί, γάλα)',
      'Τόφου, τέμπε και άλλα προϊόντα σόγιας',
      'Δημητριακά ολικής άλεσης και ζυμαρικά',
      'Λαχανικά και φρούτα',
      'Ξηροί καρποί και σπόροι',
      'Ελαιόλαδο και άλλα φυτικά έλαια',
    ],
    allowed_en: [
      'Legumes (lentils, chickpeas, beans, split peas)',
      'Eggs',
      'Dairy (yoghurt, cheese, milk)',
      'Tofu, tempeh and other soy products',
      'Whole grains and pasta',
      'Vegetables and fruit',
      'Nuts and seeds',
      'Olive oil and other vegetable oils',
    ],
    avoided_el: [
      'Κόκκινο κρέας',
      'Πουλερικά',
      'Ψάρι και θαλασσινά',
      'Ζωμοί κρέατος και ζωικό λίπος',
      'Ζελατίνη',
      'Τυριά με ζωική πυτιά (για τους αυστηρότερους)',
    ],
    avoided_en: [
      'Red meat',
      'Poultry',
      'Fish and seafood',
      'Meat stock and animal fat',
      'Gelatine',
      'Cheeses made with animal rennet (for stricter followers)',
    ],
    pros_el: [
      'Μεγάλες μελέτες (π.χ. Adventist Health, EPIC-Oxford) δείχνουν χαμηλότερο κίνδυνο ισχαιμικής καρδιοπάθειας και διαβήτη τύπου 2',
      'Συνήθως πλούσια σε φυτικές ίνες και χαμηλή σε κορεσμένα λιπαρά',
      'Οικονομική, όταν βασίζεται σε όσπρια και εποχικά λαχανικά',
      'Ταιριάζει με τα νηστίσιμα της ελληνικής κουζίνας',
    ],
    pros_en: [
      'Large studies (e.g. Adventist Health, EPIC-Oxford) show lower risk of ischaemic heart disease and type 2 diabetes',
      'Usually high in fibre and low in saturated fat',
      'Inexpensive when based on legumes and seasonal vegetables',
      'Fits the fasting dishes of Greek cuisine',
    ],
    cons_el: [
      'Σίδηρος, ψευδάργυρος και ωμέγα-3 απορροφώνται λιγότερο από φυτικές πηγές· χρειάζεται σχεδιασμός',
      'Η B12 καλύπτεται μόνο από αυγά και γαλακτοκομικά· σε μικρή κατανάλωση μπορεί να υστερεί',
      'Μια «χορτοφαγία» με πατατάκια και γλυκά παραμένει κακή διατροφή — η ετικέτα δεν αρκεί',
    ],
    cons_en: [
      'Iron, zinc and omega-3 are absorbed less well from plant sources; planning is needed',
      'B12 comes only from eggs and dairy; with low intake it can fall short',
      'A "vegetarian" diet of crisps and sweets is still a poor diet — the label is not enough',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Παιδιά, έφηβοι και έγκυες που ακολουθούν χορτοφαγία χρειάζονται παρακολούθηση σιδήρου και B12 από επαγγελματία.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'Children, teenagers and pregnant women following a vegetarian diet need iron and B12 monitoring by a professional.',
    ],
    source_url:
      'https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/the-vegetarian-diet/',
  },
  {
    slug: 'vegan',
    name_el: 'Vegan (αυστηρή χορτοφαγία)',
    name_en: 'Vegan diet',
    summary_el:
      'Αποκλείει κάθε τρόφιμο ζωικής προέλευσης: κρέας, ψάρι, αυγά, γαλακτοκομικά και συνήθως μέλι. Ο όρος δημιουργήθηκε το 1944 από την Vegan Society στη Βρετανία. Για πολλούς είναι ηθική ή περιβαλλοντική επιλογή πέρα από διατροφή. Μπορεί να είναι θρεπτικά επαρκής με σχεδιασμό, αλλά απαιτεί υποχρεωτικά συμπλήρωμα βιταμίνης B12.',
    summary_en:
      'Excludes every food of animal origin: meat, fish, eggs, dairy and usually honey. The term was coined in 1944 by the Vegan Society in Britain. For many it is an ethical or environmental choice beyond nutrition. It can be nutritionally adequate with planning, but a vitamin B12 supplement is mandatory.',
    allowed_el: [
      'Όσπρια κάθε μέρα',
      'Τόφου, τέμπε, σεϊτάν',
      'Δημητριακά ολικής άλεσης',
      'Λαχανικά και φρούτα',
      'Ξηροί καρποί, σπόροι, ταχίνι',
      'Φυτικά ροφήματα εμπλουτισμένα με ασβέστιο και B12',
      'Ελαιόλαδο και αβοκάντο',
      'Συμπλήρωμα βιταμίνης B12',
    ],
    allowed_en: [
      'Legumes every day',
      'Tofu, tempeh, seitan',
      'Whole grains',
      'Vegetables and fruit',
      'Nuts, seeds, tahini',
      'Plant drinks fortified with calcium and B12',
      'Olive oil and avocado',
      'A vitamin B12 supplement',
    ],
    avoided_el: [
      'Κρέας και πουλερικά',
      'Ψάρι και θαλασσινά',
      'Αυγά',
      'Γάλα, τυρί, γιαούρτι, βούτυρο',
      'Μέλι',
      'Ζελατίνη και άλλα ζωικά πρόσθετα',
    ],
    avoided_en: [
      'Meat and poultry',
      'Fish and seafood',
      'Eggs',
      'Milk, cheese, yoghurt, butter',
      'Honey',
      'Gelatine and other animal-derived additives',
    ],
    pros_el: [
      'Μελέτες κοόρτης δείχνουν χαμηλότερο σωματικό βάρος, LDL χοληστερόλη και κίνδυνο διαβήτη τύπου 2',
      'Το χαμηλότερο περιβαλλοντικό αποτύπωμα από όλα τα διατροφικά πρότυπα',
      'Πολύ πλούσια σε φυτικές ίνες, κάλιο και αντιοξειδωτικά',
    ],
    pros_en: [
      'Cohort studies show lower body weight, LDL cholesterol and type 2 diabetes risk',
      'The lowest environmental footprint of any eating pattern',
      'Very high in fibre, potassium and antioxidants',
    ],
    cons_el: [
      'Χωρίς συμπλήρωμα B12 η ανεπάρκεια είναι βέβαιη σε βάθος χρόνου και μπορεί να βλάψει τα νεύρα',
      'Ασβέστιο, βιταμίνη D, σίδηρος, ιώδιο και ωμέγα-3 χρειάζονται ενεργή φροντίδα',
      'Σε μελέτες παρατηρήθηκε κάπως υψηλότερος κίνδυνος καταγμάτων, πιθανώς λόγω ασβεστίου και πρωτεΐνης',
      'Το φαγητό έξω και τα κοινωνικά γεύματα είναι πιο περίπλοκα',
    ],
    cons_en: [
      'Without a B12 supplement deficiency is certain over time and can damage the nerves',
      'Calcium, vitamin D, iron, iodine and omega-3 need active attention',
      'Studies observed a somewhat higher fracture risk, possibly related to calcium and protein',
      'Eating out and social meals are more complicated',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Βρέφη, μικρά παιδιά και έγκυες σε vegan διατροφή χρειάζονται οπωσδήποτε παρακολούθηση από παιδίατρο ή διαιτολόγο.',
      'Αν έχετε ιστορικό διατροφικής διαταραχής, ο αυστηρός αποκλεισμός τροφίμων μπορεί να επιβαρύνει.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'Infants, young children and pregnant women on a vegan diet definitely need monitoring by a paediatrician or dietitian.',
      'If you have a history of an eating disorder, strict food exclusion can be a burden.',
    ],
    source_url: 'https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/the-vegan-diet/',
  },
  {
    slug: 'paleo',
    name_el: 'Δίαιτα paleo',
    name_en: 'Paleo diet',
    summary_el:
      'Η paleo (παλαιολιθική) δίαιτα προτείνει να τρώμε ό,τι υποτίθεται ότι έτρωγαν οι κυνηγοί-τροφοσυλλέκτες πριν από τη γεωργία: κρέας, ψάρι, αυγά, λαχανικά, φρούτα, ξηρούς καρπούς. Αποκλείει δημητριακά, όσπρια, γαλακτοκομικά, ζάχαρη και επεξεργασμένα τρόφιμα. Διαδόθηκε από τον Loren Cordain τη δεκαετία του 2000. Η ιστορική της βάση αμφισβητείται, αλλά στην πράξη οδηγεί σε λιγότερα επεξεργασμένα τρόφιμα.',
    summary_en:
      'The paleo (Palaeolithic) diet proposes eating what hunter-gatherers supposedly ate before agriculture: meat, fish, eggs, vegetables, fruit, nuts. It excludes grains, legumes, dairy, sugar and processed foods. It was popularised by Loren Cordain in the 2000s. Its historical premise is disputed, but in practice it leads to fewer processed foods.',
    allowed_el: [
      'Κρέας, κατά προτίμηση από ζώα ελεύθερης βοσκής',
      'Ψάρι και θαλασσινά',
      'Αυγά',
      'Λαχανικά όλων των ειδών',
      'Φρούτα',
      'Ξηροί καρποί και σπόροι (όχι φιστίκια αράπικα)',
      'Ελαιόλαδο, αβοκάντο, λάδι καρύδας',
      'Γλυκοπατάτα (στις περισσότερες εκδοχές)',
    ],
    allowed_en: [
      'Meat, preferably grass-fed',
      'Fish and seafood',
      'Eggs',
      'Vegetables of every kind',
      'Fruit',
      'Nuts and seeds (not peanuts)',
      'Olive oil, avocado, coconut oil',
      'Sweet potato (in most versions)',
    ],
    avoided_el: [
      'Δημητριακά (σιτάρι, ρύζι, βρώμη, καλαμπόκι)',
      'Όσπρια, συμπεριλαμβανομένων των φιστικιών και της σόγιας',
      'Γαλακτοκομικά',
      'Επεξεργασμένη ζάχαρη και σιρόπια',
      'Επεξεργασμένα φυτικά έλαια (ηλιέλαιο, σογιέλαιο)',
      'Αλάτι σε μεγάλες ποσότητες',
      'Επεξεργασμένα τρόφιμα γενικά',
    ],
    avoided_en: [
      'Grains (wheat, rice, oats, maize)',
      'Legumes, including peanuts and soy',
      'Dairy',
      'Refined sugar and syrups',
      'Refined seed oils (sunflower, soybean)',
      'Salt in large amounts',
      'Processed foods in general',
    ],
    pros_el: [
      'Αποκλείει τη ζάχαρη και τα πολύ επεξεργασμένα τρόφιμα, κάτι που συμφωνεί με κάθε διατροφική οδηγία',
      'Μικρές, βραχυχρόνιες μελέτες δείχνουν βελτίωση βάρους, πίεσης και τριγλυκεριδίων',
      'Υψηλή πρωτεΐνη και φυτικές ίνες από λαχανικά· κορεστικό',
    ],
    pros_en: [
      'Cuts out sugar and ultra-processed foods, which agrees with every dietary guideline',
      'Small, short-term trials show improvements in weight, blood pressure and triglycerides',
      'High in protein and vegetable fibre; filling',
    ],
    cons_el: [
      'Αποκλείει όσπρια και δημητριακά ολικής άλεσης, που έχουν ισχυρή τεκμηρίωση για την υγεία',
      'Χωρίς γαλακτοκομικά το ασβέστιο χρειάζεται φροντίδα',
      'Ακριβή, αν βασίζεται σε πολύ κρέας και ψάρι',
      'Λίγες και μικρές μελέτες· καμία μακροχρόνια απόδειξη',
      'Η επιστημονική της αφήγηση (τι έτρωγαν πραγματικά οι παλαιολιθικοί άνθρωποι) δεν στέκει',
    ],
    cons_en: [
      'Excludes legumes and whole grains, which have strong evidence for health',
      'Without dairy, calcium needs attention',
      'Expensive when based on a lot of meat and fish',
      'Few and small studies; no long-term evidence',
      'Its scientific story (what Palaeolithic people actually ate) does not hold up',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε νεφρική νόσο, η υψηλή πρόσληψη πρωτεΐνης χρειάζεται ιατρική έγκριση.',
      'Αν έχετε οστεοπόρωση ή χαμηλή πρόσληψη ασβεστίου, ο αποκλεισμός των γαλακτοκομικών θέλει αντιστάθμιση.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have kidney disease, the high protein intake needs medical approval.',
      'If you have osteoporosis or a low calcium intake, excluding dairy needs to be compensated.',
    ],
    source_url: 'https://nutritionsource.hsph.harvard.edu/healthy-weight/diet-reviews/paleo-diet/',
  },
  {
    slug: 'low-carb',
    name_el: 'Διατροφή χαμηλών υδατανθράκων',
    name_en: 'Low-carb diet',
    summary_el:
      'Γενικός όρος για διατροφές που περιορίζουν τους υδατάνθρακες, συνήθως κάτω από 130 g την ημέρα (ή κάτω από το 26% των θερμίδων), χωρίς να φτάνουν στην αυστηρότητα της keto. Η πρωτεΐνη και το λίπος αναπληρώνουν τις θερμίδες. Δεν έχει έναν ιδρυτή· η ιδέα υπάρχει από τον William Banting (1863) και επανέρχεται τακτικά. Χρησιμοποιείται κυρίως για απώλεια βάρους και για τον έλεγχο του σακχάρου.',
    summary_en:
      'A general term for diets that restrict carbohydrates, usually below 130 g a day (or under 26% of calories), without reaching the strictness of keto. Protein and fat make up the calories. It has no single founder; the idea dates back to William Banting (1863) and returns regularly. It is used mainly for weight loss and blood-sugar control.',
    allowed_el: [
      'Κρέας, πουλερικά, ψάρι, αυγά',
      'Μη αμυλούχα λαχανικά (πράσινα φυλλώδη, κολοκυθάκια, μπρόκολο, ντομάτα)',
      'Τυρί, γιαούρτι, κρέμα',
      'Ξηροί καρποί και σπόροι',
      'Ελαιόλαδο, βούτυρο, αβοκάντο',
      'Μούρα και φρούτα με λίγη ζάχαρη σε μέτρια ποσότητα',
      'Μικρές μερίδες οσπρίων ή δημητριακών ολικής, ανάλογα με το όριο',
    ],
    allowed_en: [
      'Meat, poultry, fish, eggs',
      'Non-starchy vegetables (leafy greens, courgette, broccoli, tomato)',
      'Cheese, yoghurt, cream',
      'Nuts and seeds',
      'Olive oil, butter, avocado',
      'Berries and low-sugar fruit in moderation',
      'Small portions of legumes or whole grains, depending on the limit',
    ],
    avoided_el: [
      'Ψωμί, ζυμαρικά, ρύζι, πατάτες σε κανονικές μερίδες',
      'Ζάχαρη, μέλι, σιρόπια',
      'Γλυκά, μπισκότα, αρτοσκευάσματα',
      'Αναψυκτικά και χυμοί',
      'Μπίρα',
      'Φρούτα με πολλή ζάχαρη σε μεγάλες ποσότητες (σταφύλι, μπανάνα, αποξηραμένα)',
    ],
    avoided_en: [
      'Bread, pasta, rice, potatoes in normal portions',
      'Sugar, honey, syrups',
      'Sweets, biscuits, pastries',
      'Soft drinks and fruit juice',
      'Beer',
      'High-sugar fruit in large amounts (grapes, banana, dried fruit)',
    ],
    pros_el: [
      'Τυχαιοποιημένες μελέτες δείχνουν ταχύτερη απώλεια βάρους τους πρώτους 6 μήνες σε σχέση με χαμηλά λιπαρά· στα 1–2 χρόνια η διαφορά σβήνει',
      'Βελτιώνει το σάκχαρο και τα τριγλυκερίδια σε άτομα με αντίσταση στην ινσουλίνη',
      'Κορεστικό· λιγότερη πείνα για πολλούς ανθρώπους',
      'Πιο ευέλικτο από την keto, επιτρέπει φρούτα και κάποια όσπρια',
    ],
    pros_en: [
      'Randomised trials show faster weight loss in the first six months than low-fat diets; by one to two years the difference fades',
      'Improves blood sugar and triglycerides in people with insulin resistance',
      'Filling; less hunger for many people',
      'More flexible than keto, allowing fruit and some legumes',
    ],
    cons_el: [
      'Η ποιότητα μετράει: ένα low-carb με πολύ κόκκινο κρέας και βούτυρο συνδέεται με χειρότερη μακροχρόνια έκβαση από ένα φυτικό low-carb',
      'Χαμηλές φυτικές ίνες και δυσκοιλιότητα αν λείπουν τα λαχανικά',
      'Η LDL χοληστερόλη ανεβαίνει σε μερικούς ανθρώπους',
      'Ασαφής ορισμός· το «χαμηλό» ποικίλλει πολύ',
    ],
    cons_en: [
      'Quality matters: a low-carb diet heavy in red meat and butter is linked to worse long-term outcomes than a plant-based low-carb one',
      'Low fibre and constipation if vegetables are lacking',
      'LDL cholesterol rises in some people',
      'Loosely defined; "low" varies a great deal',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν παίρνετε ινσουλίνη ή φάρμακα για τον διαβήτη, η μείωση των υδατανθράκων μπορεί να προκαλέσει υπογλυκαιμία· προσαρμόστε τη δόση με τον γιατρό σας.',
      'Αν έχετε νεφρική νόσο, η αυξημένη πρωτεΐνη χρειάζεται ιατρική καθοδήγηση.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you take insulin or diabetes medication, cutting carbohydrates can cause hypoglycaemia; adjust the dose with your doctor.',
      'If you have kidney disease, the higher protein intake needs medical guidance.',
    ],
    source_url:
      'https://www.mayoclinic.org/healthy-lifestyle/weight-loss/in-depth/low-carb-diet/art-20045831',
  },
  {
    slug: 'keto',
    name_el: 'Κετογονική διατροφή (keto)',
    name_en: 'Ketogenic diet (keto)',
    summary_el:
      'Διατροφή πολύ χαμηλή σε υδατάνθρακες (συνήθως κάτω από 50 g την ημέρα) και πολύ υψηλή σε λίπος, ώστε ο οργανισμός να παράγει κετόνες και να τις χρησιμοποιεί ως καύσιμο αντί για γλυκόζη. Αναπτύχθηκε τη δεκαετία του 1920 ως θεραπεία της επιληψίας στα παιδιά, όπου εξακολουθεί να χρησιμοποιείται ιατρικά. Η σημερινή δημοφιλής εκδοχή στοχεύει στην απώλεια βάρους και στον έλεγχο του σακχάρου.',
    summary_en:
      'A diet very low in carbohydrates (usually under 50 g a day) and very high in fat, so that the body produces ketones and uses them for fuel instead of glucose. It was developed in the 1920s as a treatment for childhood epilepsy, where it is still used medically. The popular version today aims at weight loss and blood-sugar control.',
    allowed_el: [
      'Κρέας, πουλερικά, ψάρι, αυγά',
      'Ελαιόλαδο, βούτυρο, λάδι καρύδας, κρέμα γάλακτος',
      'Τυριά',
      'Αβοκάντο',
      'Ξηροί καρποί και σπόροι (με μέτρο)',
      'Μη αμυλούχα λαχανικά (σπανάκι, κουνουπίδι, κολοκυθάκια)',
      'Ελιές',
      'Λίγα μούρα',
    ],
    allowed_en: [
      'Meat, poultry, fish, eggs',
      'Olive oil, butter, coconut oil, cream',
      'Cheeses',
      'Avocado',
      'Nuts and seeds (in moderation)',
      'Non-starchy vegetables (spinach, cauliflower, courgette)',
      'Olives',
      'A few berries',
    ],
    avoided_el: [
      'Ψωμί, ζυμαρικά, ρύζι, πατάτες',
      'Ζάχαρη, μέλι, γλυκά',
      'Τα περισσότερα φρούτα',
      'Όσπρια',
      'Αμυλούχα λαχανικά (καρότο, παντζάρι, καλαμπόκι)',
      'Γάλα σε μεγάλη ποσότητα',
      'Αναψυκτικά, χυμοί, μπίρα',
    ],
    avoided_en: [
      'Bread, pasta, rice, potatoes',
      'Sugar, honey, sweets',
      'Most fruit',
      'Legumes',
      'Starchy vegetables (carrot, beetroot, maize)',
      'Milk in large amounts',
      'Soft drinks, juice, beer',
    ],
    pros_el: [
      'Ταχεία αρχική απώλεια βάρους (εν μέρει νερό) και έντονη μείωση της όρεξης',
      'Μελέτες δείχνουν σημαντική βελτίωση του σακχάρου και της HbA1c στον διαβήτη τύπου 2, συχνά με μείωση φαρμάκων',
      'Ιατρικά τεκμηριωμένη για την ανθεκτική επιληψία στα παιδιά',
    ],
    pros_en: [
      'Rapid initial weight loss (partly water) and a marked drop in appetite',
      'Trials show significant improvement in blood sugar and HbA1c in type 2 diabetes, often with less medication',
      'Medically established for drug-resistant epilepsy in children',
    ],
    cons_el: [
      'Πολύ περιοριστική· δύσκολη να τηρηθεί πέρα από λίγους μήνες, και το βάρος συνήθως επανέρχεται',
      'Η «κετο-γρίπη» (κόπωση, πονοκέφαλος, ζάλη) τις πρώτες εβδομάδες',
      'Η LDL χοληστερόλη ανεβαίνει σημαντικά σε ένα μέρος των ανθρώπων',
      'Χαμηλές φυτικές ίνες, δυσκοιλιότητα, κίνδυνος πέτρας στα νεφρά',
      'Καμία αξιόπιστη μακροχρόνια μελέτη ασφάλειας στον γενικό πληθυσμό',
    ],
    cons_en: [
      'Very restrictive; hard to maintain beyond a few months, and weight usually returns',
      'The "keto flu" (fatigue, headache, dizziness) in the first weeks',
      'LDL cholesterol rises substantially in a share of people',
      'Low fibre, constipation, risk of kidney stones',
      'No reliable long-term safety studies in the general population',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε διαβήτη τύπου 1 ή παίρνετε αναστολείς SGLT2 (π.χ. εμπαγλιφλοζίνη, δαπαγλιφλοζίνη), υπάρχει κίνδυνος κετοξέωσης· μην ξεκινήσετε χωρίς τον γιατρό σας.',
      'Αν παίρνετε ινσουλίνη ή σουλφονυλουρίες, υπάρχει κίνδυνος σοβαρής υπογλυκαιμίας.',
      'Αν έχετε παγκρεατίτιδα, ηπατική ανεπάρκεια, διαταραχές του μεταβολισμού των λιπών ή αφαιρεμένη χοληδόχο κύστη, η keto μπορεί να μην είναι ασφαλής.',
      'Αν έχετε ιστορικό διατροφικής διαταραχής, αποφύγετε τις πολύ περιοριστικές δίαιτες.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have type 1 diabetes or take SGLT2 inhibitors (e.g. empagliflozin, dapagliflozin), there is a risk of ketoacidosis; do not start without your doctor.',
      'If you take insulin or sulfonylureas, there is a risk of severe hypoglycaemia.',
      'If you have pancreatitis, liver failure, a fat-metabolism disorder or no gallbladder, keto may not be safe.',
      'If you have a history of an eating disorder, avoid highly restrictive diets.',
    ],
    source_url:
      'https://nutritionsource.hsph.harvard.edu/healthy-weight/diet-reviews/ketogenic-diet/',
  },
  {
    slug: 'atkins',
    name_el: 'Δίαιτα Atkins',
    name_en: 'Atkins diet',
    summary_el:
      'Η πρώτη εμπορικά επιτυχημένη δίαιτα χαμηλών υδατανθράκων, από τον καρδιολόγο Robert Atkins (1972). Ξεκινά με μια πολύ αυστηρή φάση «εισαγωγής» (περίπου 20 g υδατανθράκων την ημέρα) και προσθέτει σταδιακά υδατάνθρακες σε τέσσερις φάσεις μέχρι τη «διατήρηση». Πρωτεΐνη και λίπος τρώγονται ελεύθερα· δεν μετρώνται θερμίδες. Οι νεότερες εκδοχές (Atkins 20, Atkins 40) είναι ηπιότερες.',
    summary_en:
      'The first commercially successful low-carb diet, from cardiologist Robert Atkins (1972). It starts with a very strict "induction" phase (about 20 g carbohydrate a day) and gradually adds carbohydrates through four phases up to "maintenance". Protein and fat are eaten freely; calories are not counted. Newer versions (Atkins 20, Atkins 40) are milder.',
    allowed_el: [
      'Κρέας, πουλερικά, ψάρι, αυγά χωρίς περιορισμό ποσότητας',
      'Τυριά και κρέμα',
      'Βούτυρο, ελαιόλαδο, μαγιονέζα',
      'Πράσινα φυλλώδη λαχανικά και σαλατικά',
      'Αργότερα: ξηροί καρποί, μούρα, γιαούρτι',
      'Στις τελευταίες φάσεις: όσπρια, φρούτα, δημητριακά ολικής σε μικρές μερίδες',
    ],
    allowed_en: [
      'Meat, poultry, fish, eggs without a quantity limit',
      'Cheeses and cream',
      'Butter, olive oil, mayonnaise',
      'Leafy greens and salad vegetables',
      'Later: nuts, berries, yoghurt',
      'In the final phases: legumes, fruit, whole grains in small portions',
    ],
    avoided_el: [
      'Ζάχαρη και κάθε γλυκό',
      'Ψωμί, ζυμαρικά, ρύζι, πατάτες (ειδικά στην εισαγωγή)',
      'Φρούτα στην πρώτη φάση',
      'Γάλα',
      'Αμυλούχα λαχανικά',
      'Αναψυκτικά, χυμοί, μπίρα',
      'Trans λιπαρά και επεξεργασμένα τρόφιμα',
    ],
    avoided_en: [
      'Sugar and all sweets',
      'Bread, pasta, rice, potatoes (especially in induction)',
      'Fruit in the first phase',
      'Milk',
      'Starchy vegetables',
      'Soft drinks, juice, beer',
      'Trans fats and processed foods',
    ],
    pros_el: [
      'Σε τυχαιοποιημένες συγκρίσεις (π.χ. A TO Z, 2007) έδωσε ίση ή καλύτερη απώλεια βάρους στον έναν χρόνο από άλλες δημοφιλείς δίαιτες',
      'Το σταδιακό σχήμα διδάσκει ποια ποσότητα υδατανθράκων ανέχεται ο καθένας',
      'Κορεστική· δεν απαιτεί ζύγισμα και μέτρημα θερμίδων',
    ],
    pros_en: [
      'In randomised comparisons (e.g. A TO Z, 2007) it gave equal or better weight loss at one year than other popular diets',
      'The phased structure teaches how much carbohydrate each person tolerates',
      'Filling; requires no weighing or calorie counting',
    ],
    cons_el: [
      'Η κλασική εκδοχή ενθαρρύνει πολύ κορεσμένο λίπος και επεξεργασμένο κρέας, που αντιβαίνει στις οδηγίες για την καρδιά',
      'Η φάση εισαγωγής προκαλεί συχνά κόπωση, πονοκέφαλο, δυσκοιλιότητα και κακοσμία στόματος',
      'Χαμηλές φυτικές ίνες και λίγα φρούτα στην αρχή',
      'Εμπορικό προϊόν· ένα μέρος του οικοσυστήματος είναι η πώληση μπαρών και σνακ',
    ],
    cons_en: [
      'The classic version encourages a lot of saturated fat and processed meat, against heart guidelines',
      'The induction phase often causes fatigue, headache, constipation and bad breath',
      'Low fibre and little fruit at the start',
      'A commercial product; part of the ecosystem is selling bars and snacks',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε νεφρική νόσο, η απεριόριστη πρωτεΐνη δεν είναι κατάλληλη.',
      'Αν παίρνετε ινσουλίνη, σουλφονυλουρίες ή αναστολείς SGLT2, η φάση εισαγωγής απαιτεί ιατρική προσαρμογή της αγωγής.',
      'Αν έχετε υψηλή χοληστερόλη ή καρδιοπάθεια, παρακολουθήστε τα λιπίδια στενά.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have kidney disease, unlimited protein is not appropriate.',
      'If you take insulin, sulfonylureas or SGLT2 inhibitors, the induction phase requires medical adjustment of your treatment.',
      'If you have high cholesterol or heart disease, monitor your lipids closely.',
    ],
    source_url: null,
  },
  {
    slug: 'carnivore',
    name_el: 'Carnivore (αποκλειστικά ζωική διατροφή)',
    name_en: 'Carnivore diet',
    summary_el:
      'Διατροφή μόνο με ζωικά τρόφιμα: κρέας, ψάρι, αυγά και, σε ορισμένες εκδοχές, γαλακτοκομικά. Αποκλείει πλήρως τα φυτικά τρόφιμα, άρα δεν έχει σχεδόν καθόλου υδατάνθρακες ή φυτικές ίνες. Διαδόθηκε μέσω του διαδικτύου από τα τέλη της δεκαετίας του 2010 (Shawn Baker). Είναι η πιο ακραία μορφή δίαιτας χαμηλών υδατανθράκων και δεν υποστηρίζεται από κανέναν οργανισμό υγείας.',
    summary_en:
      'A diet of animal foods only: meat, fish, eggs and, in some versions, dairy. It excludes all plant foods entirely, so it has almost no carbohydrate or fibre. It spread online from the late 2010s (Shawn Baker). It is the most extreme form of low-carb diet and is not endorsed by any health organisation.',
    allowed_el: [
      'Μοσχάρι, αρνί, χοιρινό, κυνήγι',
      'Πουλερικά',
      'Ψάρι και θαλασσινά',
      'Αυγά',
      'Εντόσθια (συκώτι, καρδιά)',
      'Ζωικό λίπος, βούτυρο, ζωμός από κόκαλα',
      'Σκληρά τυριά (σε ορισμένες εκδοχές)',
      'Αλάτι και νερό',
    ],
    allowed_en: [
      'Beef, lamb, pork, game',
      'Poultry',
      'Fish and seafood',
      'Eggs',
      'Offal (liver, heart)',
      'Animal fat, butter, bone broth',
      'Hard cheeses (in some versions)',
      'Salt and water',
    ],
    avoided_el: [
      'Όλα τα λαχανικά',
      'Όλα τα φρούτα',
      'Δημητριακά και ψωμί',
      'Όσπρια',
      'Ξηροί καρποί και σπόροι',
      'Φυτικά έλαια, συμπεριλαμβανομένου του ελαιολάδου',
      'Ζάχαρη και κάθε επεξεργασμένο τρόφιμο',
      'Καφές, τσάι, μπαχαρικά (στις αυστηρές εκδοχές)',
    ],
    avoided_en: [
      'All vegetables',
      'All fruit',
      'Grains and bread',
      'Legumes',
      'Nuts and seeds',
      'Vegetable oils, including olive oil',
      'Sugar and every processed food',
      'Coffee, tea, spices (in strict versions)',
    ],
    pros_el: [
      'Εξαιρετικά απλή· καμία επιλογή, κανένα μέτρημα',
      'Αποκλείει αυτομάτως τη ζάχαρη και τα επεξεργασμένα τρόφιμα',
      'Υψηλή πρωτεΐνη και κορεσμός· κάποιοι αναφέρουν απώλεια βάρους',
    ],
    pros_en: [
      'Extremely simple; no choices, no counting',
      'Automatically excludes sugar and processed foods',
      'High protein and satiety; some people report weight loss',
    ],
    cons_el: [
      'Δεν υπάρχει καμία ελεγχόμενη μελέτη· τα στοιχεία είναι προσωπικές μαρτυρίες και ένα ερωτηματολόγιο αυτοαναφοράς',
      'Μηδενικές φυτικές ίνες, ελάχιστη βιταμίνη C, φυλλικό οξύ, κάλιο και μαγνήσιο',
      'Πολύ κορεσμένο λίπος· η LDL συχνά ανεβαίνει έντονα',
      'Αντίκειται στις διατροφικές οδηγίες κάθε χώρας και στα δεδομένα για το κόκκινο κρέας και τον καρκίνο του εντέρου',
      'Ακριβή, κοινωνικά απομονωτική, δύσκολη μακροχρόνια',
    ],
    cons_en: [
      'There is no controlled study at all; the evidence is personal testimony and one self-report survey',
      'Zero fibre, minimal vitamin C, folate, potassium and magnesium',
      'Very high saturated fat; LDL often rises sharply',
      'Contradicts every national dietary guideline and the evidence on red meat and bowel cancer',
      'Expensive, socially isolating, hard to sustain long-term',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε νεφρική νόσο, ουρική αρθρίτιδα, υψηλή χοληστερόλη ή καρδιοπάθεια, η δίαιτα αυτή είναι ακατάλληλη.',
      'Αν έχετε ιστορικό διατροφικής διαταραχής, ο ολικός αποκλεισμός ομάδων τροφίμων είναι επικίνδυνος.',
      'Παιδιά, έφηβοι και ηλικιωμένοι δεν θα πρέπει να την ακολουθούν.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have kidney disease, gout, high cholesterol or heart disease, this diet is unsuitable.',
      'If you have a history of an eating disorder, excluding whole food groups is dangerous.',
      'Children, teenagers and older adults should not follow it.',
    ],
    source_url: null,
  },
  {
    slug: 'intermittent-fasting',
    name_el: 'Διαλειμματική νηστεία (16:8)',
    name_en: 'Intermittent fasting (16:8)',
    summary_el:
      'Όχι δίαιτα με την έννοια του «τι» αλλά του «πότε»: το φαγητό περιορίζεται σε ένα παράθυρο 8 ωρών (π.χ. 12:00–20:00) και τις υπόλοιπες 16 ώρες καταναλώνονται μόνο νερό, καφές ή τσάι χωρίς θερμίδες. Άλλες εκδοχές είναι το 5:2 (δύο ημέρες πολύ χαμηλών θερμίδων) και η εναλλάξ νηστεία. Η νηστεία έχει βαθιές ρίζες σε θρησκείες και πολιτισμούς· η σύγχρονη ερευνητική εκδοχή είναι της δεκαετίας του 2010.',
    summary_en:
      'Not a diet about "what" but about "when": eating is limited to an 8-hour window (e.g. 12:00–20:00) and for the remaining 16 hours only water, coffee or tea without calories are consumed. Other versions are 5:2 (two very-low-calorie days) and alternate-day fasting. Fasting has deep roots in religions and cultures; the modern research version dates from the 2010s.',
    allowed_el: [
      'Οποιοδήποτε φαγητό μέσα στο παράθυρο, κατά προτίμηση ισορροπημένο',
      'Νερό, ανθρακούχο νερό',
      'Σκέτος καφές και τσάι εκτός παραθύρου',
      'Λαχανικά, όσπρια, πρωτεΐνη και δημητριακά ολικής στα γεύματα',
      'Φρούτα και ξηροί καρποί ως σνακ μέσα στο παράθυρο',
      'Αφεψήματα βοτάνων χωρίς ζάχαρη',
    ],
    allowed_en: [
      'Any food within the window, preferably balanced',
      'Water, sparkling water',
      'Black coffee and tea outside the window',
      'Vegetables, legumes, protein and whole grains at meals',
      'Fruit and nuts as snacks within the window',
      'Unsweetened herbal infusions',
    ],
    avoided_el: [
      'Κάθε θερμίδα εκτός παραθύρου (γάλα στον καφέ, χυμοί, σνακ)',
      'Υπερφαγία «για αναπλήρωση» μέσα στο παράθυρο',
      'Αναψυκτικά και γλυκά ως κύρια πηγή θερμίδων',
      'Αλκοόλ κατά τη νηστεία',
      'Παράλειψη πρωτεΐνης και λαχανικών επειδή «μετράει μόνο ο χρόνος»',
      'Έντονη άσκηση με άδειο στομάχι στην αρχή',
    ],
    avoided_en: [
      'Any calories outside the window (milk in coffee, juice, snacks)',
      'Overeating "to make up" within the window',
      'Soft drinks and sweets as the main calorie source',
      'Alcohol while fasting',
      'Skipping protein and vegetables because "only timing counts"',
      'Hard exercise on an empty stomach at first',
    ],
    pros_el: [
      'Απλός κανόνας χωρίς μέτρημα θερμίδων· πολλοί το βρίσκουν πιο εύκολο από τον συνεχή περιορισμό',
      'Τυχαιοποιημένες μελέτες δείχνουν απώλεια βάρους 3–8% σε 8–12 εβδομάδες — παρόμοια με τον κλασικό θερμιδικό περιορισμό',
      'Μικρές βελτιώσεις στην ινσουλίνη και στην πίεση σε ορισμένες μελέτες',
      'Συμβατό με οποιοδήποτε διατροφικό πρότυπο',
    ],
    pros_en: [
      'A simple rule with no calorie counting; many find it easier than continuous restriction',
      'Randomised trials show 3–8% weight loss over 8–12 weeks — similar to classic calorie restriction',
      'Small improvements in insulin and blood pressure in some studies',
      'Compatible with any eating pattern',
    ],
    cons_el: [
      'Μεγάλες δοκιμές (π.χ. TREAT 2020, Liu 2022) δείχνουν ότι δεν υπερτερεί του απλού θερμιδικού περιορισμού· το όφελος είναι ότι τρώμε λιγότερο',
      'Πείνα, ευερεθιστότητα, πονοκέφαλος και δυσκολία συγκέντρωσης τις πρώτες εβδομάδες',
      'Κίνδυνος απώλειας μυϊκής μάζας αν η πρωτεΐνη είναι χαμηλή',
      'Δύσκολο σε οικογενειακά και κοινωνικά γεύματα, ιδίως τα πρωινά',
      'Τα δεδομένα για «κυτταρική ανανέωση» (αυτοφαγία) προέρχονται από ζώα, όχι από ανθρώπους',
    ],
    cons_en: [
      'Large trials (e.g. TREAT 2020, Liu 2022) show it is not superior to plain calorie restriction; the benefit is eating less',
      'Hunger, irritability, headache and poor concentration in the first weeks',
      'Risk of muscle loss if protein is low',
      'Hard at family and social meals, especially breakfast',
      'The "cellular renewal" (autophagy) evidence comes from animals, not humans',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε ιστορικό διατροφικής διαταραχής, η νηστεία μπορεί να πυροδοτήσει υποτροπή· δεν συνιστάται.',
      'Αν παίρνετε ινσουλίνη ή φάρμακα που ρίχνουν το σάκχαρο, η νηστεία μπορεί να προκαλέσει υπογλυκαιμία.',
      'Παιδιά, έφηβοι, ηλικιωμένοι με ευπάθεια και άτομα με χαμηλό βάρος δεν θα πρέπει να νηστεύουν.',
      'Αν παίρνετε φάρμακα που πρέπει να λαμβάνονται με φαγητό, προσαρμόστε το πρόγραμμα με τον γιατρό σας.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have a history of an eating disorder, fasting can trigger a relapse; it is not recommended.',
      'If you take insulin or glucose-lowering medication, fasting can cause hypoglycaemia.',
      'Children, teenagers, frail older adults and underweight people should not fast.',
      'If you take medication that must be taken with food, adjust the schedule with your doctor.',
    ],
    source_url:
      'https://nutritionsource.hsph.harvard.edu/healthy-weight/diet-reviews/intermittent-fasting/',
  },
  {
    slug: 'whole30',
    name_el: 'Whole30',
    name_en: 'Whole30',
    summary_el:
      'Πρόγραμμα 30 ημερών «επανεκκίνησης» που δημιούργησαν οι Melissa και Dallas Hartwig το 2009. Για έναν μήνα αποκλείονται πλήρως ζάχαρη και γλυκαντικά, αλκοόλ, δημητριακά, όσπρια, γαλακτοκομικά και πρόσθετα· μετά, τα τρόφιμα επανεισάγονται ένα-ένα για να παρατηρηθεί πώς αντιδρά ο οργανισμός. Δεν μετρώνται θερμίδες και απαγορεύεται το ζύγισμα κατά τη διάρκεια. Είναι βραχυπρόθεσμο πρόγραμμα, όχι μόνιμη διατροφή.',
    summary_en:
      'A 30-day "reset" programme created by Melissa and Dallas Hartwig in 2009. For one month sugar and sweeteners, alcohol, grains, legumes, dairy and additives are fully excluded; afterwards, foods are reintroduced one at a time to observe how the body reacts. Calories are not counted and weighing yourself is forbidden during the month. It is a short-term programme, not a permanent diet.',
    allowed_el: [
      'Κρέας, πουλερικά, ψάρι, αυγά',
      'Λαχανικά όλων των ειδών, μαζί με πατάτες',
      'Φρούτα',
      'Ξηροί καρποί και σπόροι (όχι φιστίκια αράπικα)',
      'Ελαιόλαδο, λάδι καρύδας, αβοκάντο, ghee',
      'Βότανα, μπαχαρικά, ξίδι (εκτός από βυνόξιδο)',
      'Καφές και τσάι χωρίς γάλα και ζάχαρη',
    ],
    allowed_en: [
      'Meat, poultry, fish, eggs',
      'Vegetables of every kind, including potatoes',
      'Fruit',
      'Nuts and seeds (not peanuts)',
      'Olive oil, coconut oil, avocado, ghee',
      'Herbs, spices, vinegar (except malt vinegar)',
      'Coffee and tea without milk or sugar',
    ],
    avoided_el: [
      'Ζάχαρη, μέλι, σιρόπια και κάθε γλυκαντικό, φυσικό ή τεχνητό',
      'Αλκοόλ, ακόμη και στο μαγείρεμα',
      'Δημητριακά (σιτάρι, ρύζι, βρώμη, καλαμπόκι, κινόα)',
      'Όσπρια, σόγια και φιστίκια αράπικα',
      'Γαλακτοκομικά (εκτός από ghee)',
      'Καραγενάνη, MSG, θειώδη',
      '«Υγιεινές» μιμήσεις γλυκών και ψωμιού με επιτρεπόμενα υλικά',
    ],
    avoided_en: [
      'Sugar, honey, syrups and every sweetener, natural or artificial',
      'Alcohol, even in cooking',
      'Grains (wheat, rice, oats, maize, quinoa)',
      'Legumes, soy and peanuts',
      'Dairy (except ghee)',
      'Carrageenan, MSG, sulphites',
      '"Healthy" imitations of sweets and bread made with allowed ingredients',
    ],
    pros_el: [
      'Σαφείς κανόνες και συγκεκριμένο τέλος· η δομή της επανεισαγωγής βοηθά να εντοπιστούν τρόφιμα που ενοχλούν',
      'Αποκοπή από ζάχαρη, αλκοόλ και επεξεργασμένα τρόφιμα για έναν μήνα',
      'Στρέφει την προσοχή σε μαγείρεμα από το μηδέν και σε ετικέτες τροφίμων',
    ],
    pros_en: [
      'Clear rules and a fixed end; the reintroduction structure helps identify foods that cause trouble',
      'A month away from sugar, alcohol and processed foods',
      'Shifts attention to cooking from scratch and to reading food labels',
    ],
    cons_el: [
      'Δεν έχει μελετηθεί σε κλινικές δοκιμές· τα οφέλη είναι ανεκδοτολογικά',
      'Αποκλείει όσπρια και δημητριακά ολικής, που είναι καλά τεκμηριωμένα για την υγεία, χωρίς ιατρικό λόγο',
      'Η γλώσσα «όλα ή τίποτα» (μία παρασπονδία = ξεκίνα από την αρχή) μπορεί να καλλιεργήσει ενοχή γύρω από το φαγητό',
      'Χρονοβόρο και ακριβό· απαιτεί πολύ μαγείρεμα',
    ],
    cons_en: [
      'Not studied in clinical trials; the benefits are anecdotal',
      'Excludes legumes and whole grains, which are well established for health, without a medical reason',
      'The all-or-nothing language (one slip = start over) can foster guilt around food',
      'Time-consuming and expensive; requires a lot of cooking',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε ιστορικό διατροφικής διαταραχής, οι αυστηροί κανόνες και η επανεκκίνηση μετά από παρασπονδία μπορεί να είναι επιβλαβείς.',
      'Αν έχετε διαβήτη υπό φαρμακευτική αγωγή, η απότομη αλλαγή στους υδατάνθρακες θέλει ιατρική προσαρμογή.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have a history of an eating disorder, the strict rules and the restart after a slip can be harmful.',
      'If you have diabetes on medication, the sudden change in carbohydrates needs medical adjustment.',
    ],
    source_url: null,
  },
  {
    slug: 'gluten-free',
    name_el: 'Διατροφή χωρίς γλουτένη',
    name_en: 'Gluten-free diet',
    summary_el:
      'Αποκλείει τη γλουτένη, την πρωτεΐνη του σιταριού, του κριθαριού και της σίκαλης. Είναι η μόνη θεραπεία για την κοιλιοκάκη (αυτοάνοσο νόσημα που προσβάλλει περίπου 1% του πληθυσμού) και απαραίτητη για την αλλεργία στο σιτάρι· χρησιμοποιείται και σε ευαισθησία στη γλουτένη χωρίς κοιλιοκάκη. Για όσους δεν έχουν κάποια από αυτές τις καταστάσεις, δεν υπάρχουν στοιχεία ότι ωφελεί. Η διάγνωση πρέπει να γίνει πριν την αποκοπή της γλουτένης, αλλιώς οι εξετάσεις βγαίνουν ψευδώς αρνητικές.',
    summary_en:
      'Excludes gluten, the protein in wheat, barley and rye. It is the only treatment for coeliac disease (an autoimmune condition affecting about 1% of the population) and is essential for wheat allergy; it is also used for non-coeliac gluten sensitivity. For people without one of these conditions there is no evidence of benefit. Diagnosis must happen before cutting gluten, otherwise the tests come back falsely negative.',
    allowed_el: [
      'Ρύζι, καλαμπόκι, πατάτες',
      'Κινόα, φαγόπυρο, κεχρί',
      'Βρώμη με πιστοποίηση «χωρίς γλουτένη»',
      'Όσπρια',
      'Κρέας, ψάρι, αυγά, γαλακτοκομικά χωρίς πρόσθετα',
      'Λαχανικά και φρούτα',
      'Ξηροί καρποί και σπόροι',
      'Προϊόντα με το σήμα του διαγραμμένου σταχιού',
    ],
    allowed_en: [
      'Rice, maize, potatoes',
      'Quinoa, buckwheat, millet',
      'Oats certified gluten-free',
      'Legumes',
      'Meat, fish, eggs, dairy without additives',
      'Vegetables and fruit',
      'Nuts and seeds',
      'Products carrying the crossed-grain symbol',
    ],
    avoided_el: [
      'Σιτάρι, κριθάρι, σίκαλη και τα παράγωγά τους (σιμιγδάλι, πλιγούρι, σπέλτα)',
      'Κανονικό ψωμί, ζυμαρικά, παξιμάδι, φύλλο',
      'Μπίρα από κριθάρι',
      'Σάλτσες και σούπες δεμένες με αλεύρι',
      'Σάλτσα σόγιας (η κοινή περιέχει σιτάρι)',
      'Παναρισμένα και τηγανητά σε κοινό λάδι',
      'Μη πιστοποιημένη βρώμη (επιμόλυνση)',
    ],
    avoided_en: [
      'Wheat, barley, rye and their products (semolina, bulgur, spelt)',
      'Ordinary bread, pasta, rusks, filo pastry',
      'Barley-based beer',
      'Sauces and soups thickened with flour',
      'Soy sauce (the common kind contains wheat)',
      'Breaded and fried foods cooked in shared oil',
      'Uncertified oats (cross-contamination)',
    ],
    pros_el: [
      'Για την κοιλιοκάκη είναι θεραπεία με αδιαμφισβήτητη τεκμηρίωση: το έντερο επουλώνεται και τα συμπτώματα υποχωρούν',
      'Απαραίτητη και αποτελεσματική στην αλλεργία στο σιτάρι',
      'Μπορεί να ανακουφίσει συμπτώματα σε διαγνωσμένη ευαισθησία στη γλουτένη',
    ],
    pros_en: [
      'For coeliac disease it is a treatment with indisputable evidence: the gut heals and symptoms subside',
      'Essential and effective in wheat allergy',
      'Can relieve symptoms in diagnosed gluten sensitivity',
    ],
    cons_el: [
      'Χωρίς διάγνωση δεν προσφέρει τίποτα· οι μελέτες σε υγιείς δεν δείχνουν όφελος για βάρος ή υγεία',
      'Τα τυποποιημένα προϊόντα «χωρίς γλουτένη» είναι συχνά πιο ακριβά, με περισσότερη ζάχαρη και λίπος και λιγότερες ίνες',
      'Κίνδυνος χαμηλής πρόσληψης φυτικών ινών, σιδήρου και βιταμινών Β αν δεν αντικατασταθούν τα δημητριακά σωστά',
      'Το φαγητό έξω απαιτεί συνεχή επαγρύπνηση για επιμόλυνση',
    ],
    cons_en: [
      'Without a diagnosis it offers nothing; studies in healthy people show no benefit for weight or health',
      'Packaged "gluten-free" products are often pricier, with more sugar and fat and less fibre',
      'Risk of low fibre, iron and B-vitamin intake if grains are not replaced properly',
      'Eating out requires constant vigilance about cross-contamination',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν υποψιάζεστε κοιλιοκάκη, ΜΗΝ κόψετε τη γλουτένη πριν από τις εξετάσεις — οι αντισωματικές εξετάσεις και η βιοψία χρειάζονται τη γλουτένη στη διατροφή για να είναι αξιόπιστες.',
      'Αν δεν έχετε κοιλιοκάκη, αλλεργία στο σιτάρι ή διαγνωσμένη ευαισθησία, δεν υπάρχει λόγος υγείας να την ακολουθήσετε.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you suspect coeliac disease, do NOT cut gluten before testing — the antibody tests and biopsy need gluten in the diet to be reliable.',
      'If you do not have coeliac disease, wheat allergy or a diagnosed sensitivity, there is no health reason to follow it.',
    ],
    source_url: 'https://nutritionsource.hsph.harvard.edu/gluten/',
  },
  {
    slug: 'high-protein',
    name_el: 'Διατροφή υψηλής πρωτεΐνης',
    name_en: 'High-protein diet',
    summary_el:
      'Διατροφή όπου η πρωτεΐνη καλύπτει το 25–35% των θερμίδων (περίπου 1,6–2,2 g ανά κιλό σωματικού βάρους), έναντι 10–15% στη συνήθη διατροφή. Δεν αποκλείει ομάδες τροφίμων· ανακατανέμει τις θερμίδες προς πηγές πρωτεΐνης, συχνά μαζί με προπόνηση αντιστάσεων. Χρησιμοποιείται για διατήρηση μυϊκής μάζας κατά την απώλεια βάρους, για αθλητές και για ηλικιωμένους που χάνουν μυς.',
    summary_en:
      'A diet in which protein supplies 25–35% of calories (roughly 1.6–2.2 g per kilogram of body weight), versus 10–15% in a typical diet. It excludes no food group; it shifts calories towards protein sources, often alongside resistance training. It is used to preserve muscle during weight loss, by athletes, and by older adults losing muscle.',
    allowed_el: [
      'Κοτόπουλο, γαλοπούλα, άπαχο κρέας',
      'Ψάρι και θαλασσινά',
      'Αυγά',
      'Γιαούρτι στραγγιστό, cottage, τυρί',
      'Όσπρια, τόφου, τέμπε',
      'Πρωτεΐνη σε σκόνη (ορού γάλακτος ή φυτική) ως συμπλήρωμα',
      'Λαχανικά και φρούτα για ίνες',
      'Δημητριακά ολικής σε μετρημένες μερίδες',
    ],
    allowed_en: [
      'Chicken, turkey, lean meat',
      'Fish and seafood',
      'Eggs',
      'Strained yoghurt, cottage cheese, cheese',
      'Legumes, tofu, tempeh',
      'Protein powder (whey or plant-based) as a supplement',
      'Vegetables and fruit for fibre',
      'Whole grains in measured portions',
    ],
    avoided_el: [
      'Εξευγενισμένοι υδατάνθρακες και ζάχαρη ως κύρια πηγή θερμίδων',
      'Λιπαρά επεξεργασμένα κρέατα (λουκάνικα, μπέικον)',
      'Τηγανητά',
      'Αναψυκτικά και αλκοόλ',
      'Γεύματα χωρίς καθόλου πρωτεΐνη',
      'Υπερβολικές δόσεις συμπληρωμάτων αντί για φαγητό',
    ],
    avoided_en: [
      'Refined carbohydrates and sugar as the main calorie source',
      'Fatty processed meats (sausages, bacon)',
      'Fried foods',
      'Soft drinks and alcohol',
      'Meals with no protein at all',
      'Excessive supplement doses in place of food',
    ],
    pros_el: [
      'Καλά τεκμηριωμένο ότι βοηθά στη διατήρηση μυϊκής μάζας κατά τον θερμιδικό περιορισμό και στην αποκατάσταση μετά από προπόνηση',
      'Η πρωτεΐνη είναι το πιο κορεστικό μακροθρεπτικό· βοηθά στον έλεγχο της πείνας',
      'Ελαφρώς υψηλότερη θερμογένεση σε σχέση με υδατάνθρακες και λίπος',
      'Σημαντική για ηλικιωμένους έναντι της σαρκοπενίας',
    ],
    pros_en: [
      'Well established to help preserve muscle during calorie restriction and to aid recovery after training',
      'Protein is the most satiating macronutrient; it helps control hunger',
      'Slightly higher thermogenesis than carbohydrate and fat',
      'Important for older adults against sarcopenia',
    ],
    cons_el: [
      'Πάνω από περίπου 2 g/kg δεν υπάρχει πρόσθετο όφελος για τους περισσότερους',
      'Πολλή πρωτεΐνη από κόκκινο και επεξεργασμένο κρέας σχετίζεται με χειρότερη μακροχρόνια υγεία· η πηγή μετράει',
      'Αυξημένο φορτίο για τα νεφρά σε άτομα με ήδη μειωμένη νεφρική λειτουργία',
      'Κόστος· τα προϊόντα «high protein» είναι συχνά απλώς ακριβότερα',
    ],
    cons_en: [
      'Above roughly 2 g/kg there is no extra benefit for most people',
      'A lot of protein from red and processed meat is linked to worse long-term health; the source matters',
      'Increased load on the kidneys in people with already reduced kidney function',
      'Cost; "high protein" products are often simply more expensive',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Αν έχετε χρόνια νεφρική νόσο ή μειωμένη νεφρική λειτουργία, η υψηλή πρωτεΐνη μπορεί να επιταχύνει την επιδείνωση· απαιτείται ιατρική παρακολούθηση.',
      'Αν έχετε ουρική αρθρίτιδα, η πολλή ζωική πρωτεΐνη μπορεί να προκαλέσει κρίσεις.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'If you have chronic kidney disease or reduced kidney function, high protein can speed up decline; medical monitoring is required.',
      'If you have gout, a lot of animal protein can trigger flares.',
    ],
    source_url: null,
  },
  {
    slug: 'low-fodmap',
    name_el: 'Δίαιτα χαμηλών FODMAP',
    name_en: 'Low-FODMAP diet',
    summary_el:
      'Ιατρική δίαιτα τριών φάσεων για το σύνδρομο ευερέθιστου εντέρου (IBS), που αναπτύχθηκε στο Πανεπιστήμιο Monash της Αυστραλίας. Τα FODMAP είναι ζυμώσιμοι υδατάνθρακες (φρουκτάνες, λακτόζη, φρουκτόζη, πολυόλες) που σε ευαίσθητα άτομα προκαλούν φούσκωμα και πόνο. Για 2–6 εβδομάδες περιορίζονται αυστηρά, μετά επανεισάγονται ομάδα-ομάδα, και τέλος διαμορφώνεται μια εξατομικευμένη διατροφή. Πρέπει να γίνεται με καθοδήγηση διαιτολόγου και δεν προορίζεται για μόνιμη χρήση.',
    summary_en:
      'A three-phase medical diet for irritable bowel syndrome (IBS), developed at Monash University in Australia. FODMAPs are fermentable carbohydrates (fructans, lactose, fructose, polyols) that cause bloating and pain in sensitive people. They are strictly limited for two to six weeks, then reintroduced group by group, and finally a personalised diet is shaped. It should be done with a dietitian and is not meant for permanent use.',
    allowed_el: [
      'Ρύζι, βρώμη, κινόα, ψωμί από προζύμι σπέλτα',
      'Καρότο, αγγούρι, ντομάτα, κολοκυθάκι, σπανάκι',
      'Μπανάνα (άγουρη), πορτοκάλι, φράουλες, σταφύλι',
      'Κρέας, ψάρι, αυγά, τόφου σκληρό',
      'Γαλακτοκομικά χωρίς λακτόζη, σκληρά τυριά, φέτα',
      'Καρύδια, φιστίκια αράπικα, κολοκυθόσποροι',
      'Ελαιόλαδο, λάδι με άρωμα σκόρδου',
      'Πράσινο μέρος του φρέσκου κρεμμυδιού, τζίντζερ',
    ],
    allowed_en: [
      'Rice, oats, quinoa, spelt sourdough bread',
      'Carrot, cucumber, tomato, courgette, spinach',
      'Banana (firm), orange, strawberries, grapes',
      'Meat, fish, eggs, firm tofu',
      'Lactose-free dairy, hard cheeses, feta',
      'Walnuts, peanuts, pumpkin seeds',
      'Olive oil, garlic-infused oil',
      'Green part of spring onion, ginger',
    ],
    avoided_el: [
      'Σκόρδο και κρεμμύδι',
      'Σιτάρι και σίκαλη σε μεγάλες μερίδες (ψωμί, ζυμαρικά)',
      'Όσπρια (φακές, ρεβίθια, φασόλια) πάνω από μικρές μερίδες',
      'Γάλα, γιαούρτι, μαλακά τυριά με λακτόζη',
      'Μήλο, αχλάδι, καρπούζι, μάνγκο, αποξηραμένα φρούτα',
      'Μέλι, σιρόπι αγαύης, σιρόπι καλαμποκιού υψηλής φρουκτόζης',
      'Γλυκαντικά που λήγουν σε -όλη (σορβιτόλη, μαννιτόλη, ξυλιτόλη)',
      'Κουνουπίδι, μανιτάρια, αγκινάρες, σπαράγγια',
    ],
    avoided_en: [
      'Garlic and onion',
      'Wheat and rye in large portions (bread, pasta)',
      'Legumes (lentils, chickpeas, beans) beyond small portions',
      'Milk, yoghurt, soft cheeses with lactose',
      'Apple, pear, watermelon, mango, dried fruit',
      'Honey, agave syrup, high-fructose corn syrup',
      'Sweeteners ending in -ol (sorbitol, mannitol, xylitol)',
      'Cauliflower, mushrooms, artichokes, asparagus',
    ],
    pros_el: [
      'Τυχαιοποιημένες μελέτες δείχνουν ανακούφιση συμπτωμάτων στο 50–75% των ατόμων με IBS· είναι από τις καλύτερα τεκμηριωμένες διατροφικές θεραπείες',
      'Συστήνεται σε κατευθυντήριες οδηγίες γαστρεντερολογικών εταιρειών ως δεύτερης γραμμής θεραπεία για το IBS',
      'Η φάση επανεισαγωγής εντοπίζει με ακρίβεια ποιες ομάδες ενοχλούν, ώστε ο περιορισμός να είναι ο ελάχιστος δυνατός',
    ],
    pros_en: [
      'Randomised trials show symptom relief in 50–75% of people with IBS; it is one of the best-evidenced dietary therapies',
      'Recommended in gastroenterology society guidelines as a second-line treatment for IBS',
      'The reintroduction phase pinpoints which groups cause trouble so the restriction can be as small as possible',
    ],
    cons_el: [
      'Περίπλοκη· τα όρια μερίδων διαφέρουν ανά τρόφιμο και χρειάζεται η εφαρμογή του Monash ή ένας διαιτολόγος',
      'Η αυστηρή φάση μειώνει τα ωφέλιμα βακτήρια του εντέρου· δεν πρέπει να παραταθεί',
      'Αποκλείει πολλά υγιεινά τρόφιμα (όσπρια, σκόρδο, κρεμμύδι) που είναι βάση της ελληνικής κουζίνας',
      'Δεν είναι δίαιτα απώλειας βάρους ούτε «γενικής υγείας»· χωρίς IBS δεν έχει νόημα',
    ],
    cons_en: [
      'Complex; portion thresholds differ per food and the Monash app or a dietitian is needed',
      'The strict phase reduces beneficial gut bacteria; it should not be prolonged',
      'Excludes many healthy foods (legumes, garlic, onion) that are the base of Greek cooking',
      'Not a weight-loss or "general health" diet; without IBS it has no purpose',
    ],
    avoid_if_el: [
      ASK_DOCTOR_EL,
      'Μην την ξεκινήσετε χωρίς διάγνωση IBS από γιατρό — συμπτώματα όπως αιμορραγία, απώλεια βάρους ή αναιμία χρειάζονται διερεύνηση για κοιλιοκάκη, φλεγμονώδη νόσο ή καρκίνο πρώτα.',
      'Αν έχετε ιστορικό διατροφικής διαταραχής, η περιοριστική φάση μπορεί να είναι επικίνδυνη.',
      'Προορίζεται για βραχυπρόθεσμη χρήση με καθοδήγηση διαιτολόγου· η αυστηρή φάση δεν πρέπει να ξεπερνά τις 6 εβδομάδες.',
    ],
    avoid_if_en: [
      ASK_DOCTOR_EN,
      'Do not start it without an IBS diagnosis from a doctor — symptoms such as bleeding, weight loss or anaemia need investigation for coeliac disease, inflammatory bowel disease or cancer first.',
      'If you have a history of an eating disorder, the restrictive phase can be dangerous.',
      'It is meant for short-term use under dietitian guidance; the strict phase should not exceed six weeks.',
    ],
    source_url: 'https://www.monashfodmap.com/',
  },
]
