// SEED: exercises (PLAN.md P4.7). Bilingual coaching library every workout template (P4.8) draws
// from — 7 workout types × 3 levels, each cell with warm-up-suitable, main-block and cool-down /
// stretch movements. Standard, mainstream exercises only (content drafting rule, PLAN.md §0); Greek
// uses everyday gym vocabulary and keeps established loanwords as Greeks write them.
//
// Erasable syntax only: `scripts/gen-seed-sql.mjs` imports this module under node's type stripping.

import type { Level, WorkoutType } from '../enums.ts'
import type { ExerciseSeed } from '../types.ts'

/** The fixed muscle-group vocabulary; every `muscle_groups` entry must come from here. */
export const MUSCLE_GROUPS = [
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'chest',
  'back',
  'shoulders',
  'biceps',
  'triceps',
  'forearms',
  'core',
  'hip-flexors',
  'adductors',
  'full-body',
  'cardio',
] as const
export type MuscleGroup = (typeof MUSCLE_GROUPS)[number]

type Equipment = readonly [en: string, el: string]

/** Builds one row; `equipment` omitted = bodyweight (both columns null). */
function ex(
  slug: string,
  workout_type: WorkoutType,
  level: Level,
  muscle_groups: MuscleGroup[],
  name_en: string,
  name_el: string,
  cue_en: string,
  cue_el: string,
  equipment?: Equipment,
): ExerciseSeed {
  return {
    slug,
    workout_type,
    level,
    muscle_groups,
    name_en,
    name_el,
    cue_en,
    cue_el,
    equipment_en: equipment ? equipment[0] : null,
    equipment_el: equipment ? equipment[1] : null,
  }
}

const DUMBBELLS: Equipment = ['Dumbbells', 'Αλτήρες']
const BARBELL: Equipment = ['Barbell', 'Μπάρα']
const KETTLEBELL: Equipment = ['Kettlebell', 'Kettlebell']
const BAND: Equipment = ['Resistance band', 'Λάστιχο αντίστασης']
const PULLUP_BAR: Equipment = ['Pull-up bar', 'Μονόζυγο']
const DIP_BARS: Equipment = ['Dip bars', 'Δίζυγο']
const BENCH: Equipment = ['Bench', 'Πάγκος']
const CABLE: Equipment = ['Cable machine', 'Τροχαλία']
const MACHINE: Equipment = ['Machine', 'Μηχάνημα']
const BIKE: Equipment = ['Bicycle', 'Ποδήλατο']
const KICKBOARD: Equipment = ['Kickboard', 'Σανίδα κολύμβησης']
const PULL_BUOY: Equipment = ['Pull buoy', 'Pull buoy']
const FINS: Equipment = ['Fins', 'Βατραχοπέδιλα']
const MAT: Equipment = ['Mat', 'Στρώμα']
const FOAM_ROLLER: Equipment = ['Foam roller', 'Αφρώδης κύλινδρος']
const CHAIR: Equipment = ['Chair', 'Καρέκλα']
const JUMP_ROPE: Equipment = ['Jump rope', 'Σχοινάκι']

// --- home ----------------------------------------------------------------------------------------

const HOME: ExerciseSeed[] = [
  ex(
    'arm-circles',
    'home',
    'beginner',
    ['shoulders'],
    'Arm circles',
    'Κύκλοι χεριών',
    'Stand tall and draw slow circles with straight arms, small to large, then reverse. Breathe easily and keep the shoulders away from the ears.',
    'Σταθείτε όρθιοι και κάντε αργούς κύκλους με τεντωμένα χέρια, από μικρούς σε μεγάλους, μετά αντίστροφα. Αναπνέετε άνετα και κρατήστε τους ώμους μακριά από τα αυτιά.',
  ),
  ex(
    'march-in-place',
    'home',
    'beginner',
    ['cardio', 'hip-flexors'],
    'March in place',
    'Βάδισμα επί τόπου',
    'Lift the knees to hip height and swing the arms naturally. Keep a steady rhythm and breathe through the nose.',
    'Σηκώνετε τα γόνατα στο ύψος του ισχίου και κουνάτε τα χέρια φυσικά. Κρατήστε σταθερό ρυθμό και αναπνέετε από τη μύτη.',
  ),
  ex(
    'bodyweight-squat',
    'home',
    'beginner',
    ['quads', 'glutes'],
    'Bodyweight squat',
    'Καθίσματα χωρίς βάρος',
    'Feet shoulder-width, sit the hips back and down with the chest up and knees tracking over the toes. Inhale on the way down, exhale as you stand.',
    'Πόδια στο άνοιγμα των ώμων, καθίστε με τους γοφούς πίσω και κάτω, στήθος ψηλά και γόνατα στην κατεύθυνση των δακτύλων. Εισπνοή στην κάθοδο, εκπνοή καθώς σηκώνεστε.',
  ),
  ex(
    'wall-push-up',
    'home',
    'beginner',
    ['chest', 'triceps', 'shoulders'],
    'Wall push-up',
    'Κάμψεις στον τοίχο',
    'Hands on the wall at chest height, body in a straight line. Bend the elbows to bring the chest toward the wall, exhale as you push away.',
    'Χέρια στον τοίχο στο ύψος του στήθους, σώμα σε ευθεία γραμμή. Λυγίστε τους αγκώνες φέρνοντας το στήθος προς τον τοίχο, εκπνεύστε καθώς σπρώχνετε.',
  ),
  ex(
    'glute-bridge',
    'home',
    'beginner',
    ['glutes', 'hamstrings', 'core'],
    'Glute bridge',
    'Γέφυρα γλουτών',
    'Lie on your back with knees bent, press through the heels and lift the hips until the body forms a line from knees to shoulders. Squeeze the glutes at the top and exhale.',
    'Ξαπλώστε ανάσκελα με λυγισμένα γόνατα, πιέστε με τις φτέρνες και σηκώστε τους γοφούς ώστε το σώμα να σχηματίζει ευθεία από γόνατα έως ώμους. Σφίξτε τους γλουτούς στην κορυφή και εκπνεύστε.',
  ),
  ex(
    'knee-plank',
    'home',
    'beginner',
    ['core', 'shoulders'],
    'Knee plank',
    'Σανίδα στα γόνατα',
    'Forearms under the shoulders, knees on the floor, straight line from head to knees. Brace the belly as if expecting a tap and breathe steadily.',
    'Πήχεις κάτω από τους ώμους, γόνατα στο πάτωμα, ευθεία γραμμή από το κεφάλι ως τα γόνατα. Σφίξτε την κοιλιά και αναπνέετε σταθερά.',
  ),
  ex(
    'standing-quad-stretch',
    'home',
    'beginner',
    ['quads', 'hip-flexors'],
    'Standing quad stretch',
    'Διάταση τετρακεφάλου όρθια',
    'Hold a wall if needed, bring one heel toward the glutes and keep the knees together. Tuck the pelvis slightly and breathe slowly for 20–30 seconds each side.',
    'Κρατηθείτε από τοίχο αν χρειάζεται, φέρτε τη μία φτέρνα προς τους γλουτούς και κρατήστε τα γόνατα ενωμένα. Γείρετε ελαφρά τη λεκάνη και αναπνέετε αργά για 20–30 δευτερόλεπτα σε κάθε πλευρά.',
  ),
  ex(
    'jumping-jacks',
    'home',
    'intermediate',
    ['cardio', 'full-body'],
    'Jumping jacks',
    'Jumping jacks',
    'Jump the feet wide while the arms rise overhead, then back together. Land softly on the balls of the feet and keep the breath rhythmic.',
    'Ανοίξτε τα πόδια με άλμα ενώ τα χέρια ανεβαίνουν πάνω από το κεφάλι, και κλείστε ξανά. Προσγειωθείτε απαλά στις μύτες και κρατήστε ρυθμική αναπνοή.',
  ),
  ex(
    'push-up',
    'home',
    'intermediate',
    ['chest', 'triceps', 'shoulders', 'core'],
    'Push-up',
    'Κάμψεις',
    'Hands slightly wider than the shoulders, body rigid from head to heels. Lower the chest toward the floor with elbows at about 45 degrees and exhale on the push.',
    'Χέρια λίγο πιο ανοιχτά από τους ώμους, σώμα σφιχτό από το κεφάλι ως τις φτέρνες. Κατεβάστε το στήθος προς το πάτωμα με αγκώνες στις 45 μοίρες και εκπνεύστε στο σπρώξιμο.',
  ),
  ex(
    'reverse-lunge',
    'home',
    'intermediate',
    ['quads', 'glutes', 'hamstrings'],
    'Reverse lunge',
    'Προβολές προς τα πίσω',
    'Step one foot back and lower until both knees are near 90 degrees, torso upright. Drive through the front heel to return and alternate legs.',
    'Κάντε βήμα πίσω με το ένα πόδι και κατεβείτε μέχρι τα δύο γόνατα να είναι κοντά στις 90 μοίρες, κορμός όρθιος. Σπρώξτε με τη μπροστινή φτέρνα για να επιστρέψετε και εναλλάξτε πόδια.',
  ),
  ex(
    'plank',
    'home',
    'intermediate',
    ['core', 'shoulders'],
    'Plank',
    'Σανίδα',
    'Forearms on the floor, toes tucked, body a straight line. Squeeze the glutes, pull the ribs down and breathe without letting the hips sag.',
    'Πήχεις στο πάτωμα, μύτες ποδιών στο έδαφος, σώμα σε ευθεία γραμμή. Σφίξτε τους γλουτούς, κατεβάστε τα πλευρά και αναπνέετε χωρίς να πέφτουν οι γοφοί.',
  ),
  ex(
    'dumbbell-row-home',
    'home',
    'intermediate',
    ['back', 'biceps'],
    'Dumbbell row',
    'Κωπηλατική με αλτήρα',
    'Hinge at the hips with a flat back, one hand on a chair. Pull the dumbbell to the hip with the elbow close to the body, exhaling on the pull.',
    'Κάμψη από τους γοφούς με ίσια πλάτη, το ένα χέρι σε καρέκλα. Τραβήξτε τον αλτήρα προς τον γοφό με τον αγκώνα κοντά στο σώμα, εκπνέοντας στο τράβηγμα.',
    DUMBBELLS,
  ),
  ex(
    'mountain-climbers',
    'home',
    'intermediate',
    ['core', 'cardio', 'hip-flexors'],
    'Mountain climbers',
    'Ορειβάτες',
    'From a high plank, drive one knee toward the chest and switch quickly while the hips stay level. Keep the shoulders over the wrists and breathe fast but steady.',
    'Από ψηλή σανίδα, φέρτε το ένα γόνατο προς το στήθος και εναλλάξτε γρήγορα, κρατώντας τους γοφούς σταθερούς. Ώμοι πάνω από τους καρπούς και γρήγορη αλλά σταθερή αναπνοή.',
  ),
  ex(
    'seated-hamstring-stretch',
    'home',
    'intermediate',
    ['hamstrings', 'back'],
    'Seated hamstring stretch',
    'Διάταση οπίσθιων μηριαίων καθιστά',
    'Sit with one leg straight, reach toward the toes with a long spine instead of a rounded back. Exhale into the stretch and hold 30 seconds per side.',
    'Καθίστε με το ένα πόδι τεντωμένο, τεντωθείτε προς τα δάχτυλα με μακριά σπονδυλική στήλη αντί για καμπουριασμένη πλάτη. Εκπνεύστε στη διάταση και κρατήστε 30 δευτερόλεπτα ανά πλευρά.',
  ),
  ex(
    'burpees',
    'home',
    'advanced',
    ['full-body', 'cardio'],
    'Burpees',
    'Burpees',
    'Squat down, jump the feet back to a plank, do a push-up, jump the feet in and leap up with arms overhead. Land softly and keep the breathing rhythmic.',
    'Καθίστε, πετάξτε τα πόδια πίσω σε σανίδα, κάντε μία κάμψη, φέρτε τα πόδια μπροστά και αναπηδήστε με τα χέρια ψηλά. Προσγειωθείτε απαλά και κρατήστε ρυθμική αναπνοή.',
  ),
  ex(
    'jump-squat',
    'home',
    'advanced',
    ['quads', 'glutes', 'calves', 'cardio'],
    'Jump squat',
    'Καθίσματα με άλμα',
    'Squat down, then explode upward and land quietly back into the squat with knees tracking over the toes. Exhale on the jump.',
    'Καθίστε και εκραγείτε προς τα πάνω, προσγειωθείτε αθόρυβα πίσω στο κάθισμα με τα γόνατα στην κατεύθυνση των δακτύλων. Εκπνεύστε στο άλμα.',
  ),
  ex(
    'bulgarian-split-squat',
    'home',
    'advanced',
    ['quads', 'glutes', 'hamstrings'],
    'Bulgarian split squat',
    'Βουλγαρικά καθίσματα',
    'Rear foot on a chair, lower straight down until the front thigh is parallel, torso tall. Drive through the front heel and exhale as you stand.',
    'Πίσω πόδι σε καρέκλα, κατεβείτε κάθετα μέχρι ο μπροστινός μηρός να είναι παράλληλος, κορμός ψηλά. Σπρώξτε με τη μπροστινή φτέρνα και εκπνεύστε καθώς σηκώνεστε.',
    CHAIR,
  ),
  ex(
    'single-leg-glute-bridge',
    'home',
    'advanced',
    ['glutes', 'hamstrings', 'core'],
    'Single-leg glute bridge',
    'Γέφυρα γλουτών με ένα πόδι',
    'Lying on your back, extend one leg and drive through the other heel to lift the hips, keeping the pelvis level. Exhale at the top and lower with control.',
    'Ξαπλωμένοι ανάσκελα, τεντώστε το ένα πόδι και σπρώξτε με την άλλη φτέρνα για να σηκώσετε τους γοφούς, κρατώντας τη λεκάνη ίσια. Εκπνεύστε στην κορυφή και κατεβείτε ελεγχόμενα.',
  ),
  ex(
    'skipping-rope',
    'home',
    'advanced',
    ['cardio', 'calves'],
    'Jump rope',
    'Σχοινάκι',
    'Bounce lightly on the balls of the feet with the elbows close to the body and the wrists turning the rope. Keep the jumps small and breathe steadily.',
    'Αναπηδάτε ελαφρά στις μύτες των ποδιών με τους αγκώνες κοντά στο σώμα και τους καρπούς να γυρίζουν το σχοινί. Κρατήστε τα άλματα χαμηλά και την αναπνοή σταθερή.',
    JUMP_ROPE,
  ),
  ex(
    'pigeon-stretch',
    'home',
    'advanced',
    ['glutes', 'hip-flexors'],
    'Pigeon stretch',
    'Διάταση περιστεριού',
    'From all fours bring one shin forward across the body and extend the other leg back, hips square. Fold forward only as far as the breath stays slow; hold 30–45 seconds each side.',
    'Από τα τέσσερα φέρτε την κνήμη μπροστά διαγώνια και τεντώστε το άλλο πόδι πίσω, γοφοί ευθυγραμμισμένοι. Σκύψτε μόνο όσο η αναπνοή μένει αργή· κρατήστε 30–45 δευτερόλεπτα σε κάθε πλευρά.',
  ),
]

// --- gym -----------------------------------------------------------------------------------------

const GYM: ExerciseSeed[] = [
  ex(
    'treadmill-walk-5min',
    'gym',
    'beginner',
    ['cardio'],
    'Treadmill walk, 5 min',
    'Περπάτημα σε διάδρομο, 5 λεπτά',
    'Walk briskly at a pace where you can still talk, arms swinging freely. Breathe through the nose and let the body warm up gradually.',
    'Περπατήστε γρήγορα σε ρυθμό που μπορείτε ακόμα να μιλάτε, με τα χέρια να κινούνται ελεύθερα. Αναπνέετε από τη μύτη και αφήστε το σώμα να ζεσταθεί σταδιακά.',
    MACHINE,
  ),
  ex(
    'leg-press',
    'gym',
    'beginner',
    ['quads', 'glutes', 'hamstrings'],
    'Leg press',
    'Πιέσεις ποδιών',
    'Feet shoulder-width on the platform, lower the sled until the knees reach about 90 degrees without the lower back lifting off the pad. Exhale as you press, never lock the knees.',
    'Πόδια στο άνοιγμα των ώμων πάνω στην πλατφόρμα, κατεβάστε μέχρι τα γόνατα να φτάσουν περίπου στις 90 μοίρες χωρίς να σηκωθεί η μέση. Εκπνεύστε καθώς σπρώχνετε, μην κλειδώνετε τα γόνατα.',
    MACHINE,
  ),
  ex(
    'lat-pulldown',
    'gym',
    'beginner',
    ['back', 'biceps'],
    'Lat pulldown',
    'Έλξεις τροχαλίας',
    'Grip slightly wider than the shoulders, lean back a little and pull the bar to the upper chest while the elbows drive down. Exhale on the pull and control the return.',
    'Λαβή λίγο πιο ανοιχτή από τους ώμους, γείρετε ελαφρά πίσω και τραβήξτε τη μπάρα στο πάνω στήθος με τους αγκώνες να κατεβαίνουν. Εκπνεύστε στο τράβηγμα και ελέγξτε την επιστροφή.',
    CABLE,
  ),
  ex(
    'chest-press-machine',
    'gym',
    'beginner',
    ['chest', 'triceps', 'shoulders'],
    'Chest press machine',
    'Πιέσεις στήθους σε μηχάνημα',
    'Set the handles at mid-chest height, press forward until the arms are almost straight and return slowly. Exhale on the press and keep the shoulder blades back.',
    'Ρυθμίστε τις λαβές στο ύψος του στήθους, σπρώξτε μέχρι τα χέρια να είναι σχεδόν τεντωμένα και επιστρέψτε αργά. Εκπνεύστε στο σπρώξιμο και κρατήστε τις ωμοπλάτες πίσω.',
    MACHINE,
  ),
  ex(
    'seated-cable-row',
    'gym',
    'beginner',
    ['back', 'biceps'],
    'Seated cable row',
    'Κωπηλατική τροχαλίας καθιστά',
    'Sit tall with a slight knee bend, pull the handle to the belly squeezing the shoulder blades together. Exhale on the pull and let the arms extend fully on the return.',
    'Καθίστε όρθιοι με ελαφρά λυγισμένα γόνατα, τραβήξτε τη λαβή στην κοιλιά σφίγγοντας τις ωμοπλάτες. Εκπνεύστε στο τράβηγμα και αφήστε τα χέρια να τεντώσουν στην επιστροφή.',
    CABLE,
  ),
  ex(
    'dumbbell-shoulder-press',
    'gym',
    'beginner',
    ['shoulders', 'triceps'],
    'Dumbbell shoulder press',
    'Πιέσεις ώμων με αλτήρες',
    'Seated or standing, start with the dumbbells at ear level and press overhead until the arms are straight without arching the lower back. Exhale on the press.',
    'Καθιστοί ή όρθιοι, ξεκινήστε με τους αλτήρες στο ύψος των αυτιών και πιέστε πάνω από το κεφάλι μέχρι τα χέρια να τεντώσουν, χωρίς να καμπουριάζει η μέση. Εκπνεύστε στην πίεση.',
    DUMBBELLS,
  ),
  ex(
    'stationary-bike-cooldown',
    'gym',
    'beginner',
    ['cardio'],
    'Stationary bike cool-down',
    'Αποθεραπεία σε στατικό ποδήλατο',
    'Pedal easily with light resistance for a few minutes, letting the heart rate come down. Breathe slowly and relax the shoulders.',
    'Κάντε πετάλι χαλαρά με ελαφριά αντίσταση για λίγα λεπτά, αφήνοντας τον καρδιακό ρυθμό να πέσει. Αναπνέετε αργά και χαλαρώστε τους ώμους.',
    MACHINE,
  ),
  ex(
    'goblet-squat',
    'gym',
    'intermediate',
    ['quads', 'glutes', 'core'],
    'Goblet squat',
    'Goblet squat',
    'Hold a dumbbell or kettlebell at the chest, squat between the knees with the elbows inside the thighs and the chest tall. Inhale down, exhale up.',
    'Κρατήστε αλτήρα ή kettlebell στο στήθος, καθίστε ανάμεσα στα γόνατα με τους αγκώνες μέσα από τους μηρούς και το στήθος ψηλά. Εισπνοή στην κάθοδο, εκπνοή στην άνοδο.',
    DUMBBELLS,
  ),
  ex(
    'romanian-deadlift',
    'gym',
    'intermediate',
    ['hamstrings', 'glutes', 'back'],
    'Romanian deadlift',
    'Ρουμανικές άρσεις θανάτου',
    'Soft knees, push the hips back and lower the bar along the thighs with a flat back until you feel the hamstrings stretch. Exhale as the hips drive forward to stand.',
    'Ελαφρά λυγισμένα γόνατα, σπρώξτε τους γοφούς πίσω και κατεβάστε τη μπάρα κατά μήκος των μηρών με ίσια πλάτη μέχρι να νιώσετε τους οπίσθιους μηριαίους να τεντώνουν. Εκπνεύστε καθώς οι γοφοί σπρώχνουν μπροστά.',
    BARBELL,
  ),
  ex(
    'dumbbell-bench-press',
    'gym',
    'intermediate',
    ['chest', 'triceps', 'shoulders'],
    'Dumbbell bench press',
    'Πιέσεις πάγκου με αλτήρες',
    'Lie on the bench with feet flat, lower the dumbbells to the sides of the chest with elbows at about 45 degrees and press up to lockout. Exhale on the press.',
    'Ξαπλώστε στον πάγκο με τα πέλματα στο πάτωμα, κατεβάστε τους αλτήρες στα πλάγια του στήθους με αγκώνες στις 45 μοίρες και πιέστε προς τα πάνω. Εκπνεύστε στην πίεση.',
    DUMBBELLS,
  ),
  ex(
    'barbell-row',
    'gym',
    'intermediate',
    ['back', 'biceps'],
    'Barbell row',
    'Κωπηλατική με μπάρα',
    'Hinge to about 45 degrees with a flat back, pull the bar to the lower chest with the elbows close and squeeze the shoulder blades. Exhale on the pull, lower under control.',
    'Κάμψη περίπου στις 45 μοίρες με ίσια πλάτη, τραβήξτε τη μπάρα στο κάτω στήθος με τους αγκώνες κοντά και σφίξτε τις ωμοπλάτες. Εκπνεύστε στο τράβηγμα, κατεβάστε ελεγχόμενα.',
    BARBELL,
  ),
  ex(
    'walking-lunge-dumbbells',
    'gym',
    'intermediate',
    ['quads', 'glutes', 'hamstrings'],
    'Walking lunge with dumbbells',
    'Προβολές βάδην με αλτήρες',
    'Step forward into a lunge with both knees near 90 degrees, torso upright, then drive through the front heel into the next step. Breathe out as you rise.',
    'Κάντε βήμα μπροστά σε προβολή με τα δύο γόνατα κοντά στις 90 μοίρες, κορμός όρθιος, και σπρώξτε με τη μπροστινή φτέρνα στο επόμενο βήμα. Εκπνεύστε καθώς σηκώνεστε.',
    DUMBBELLS,
  ),
  ex(
    'cable-face-pull',
    'gym',
    'intermediate',
    ['shoulders', 'back'],
    'Cable face pull',
    'Face pull σε τροχαλία',
    'Set the rope at face height, pull toward the forehead with the elbows high and wide, squeezing the rear shoulders. Exhale on the pull and return slowly.',
    'Ρυθμίστε το σχοινί στο ύψος του προσώπου, τραβήξτε προς το μέτωπο με τους αγκώνες ψηλά και ανοιχτά, σφίγγοντας τους πίσω ώμους. Εκπνεύστε στο τράβηγμα και επιστρέψτε αργά.',
    CABLE,
  ),
  ex(
    'rowing-machine-easy',
    'gym',
    'intermediate',
    ['cardio', 'back', 'full-body'],
    'Rowing machine, easy pace',
    'Κωπηλατοεργόμετρο, χαλαρός ρυθμός',
    'Push with the legs first, then swing the torso and finish with the arms; reverse the order on the return. Keep the stroke rate low and breathe out on the drive.',
    'Σπρώξτε πρώτα με τα πόδια, μετά γείρετε τον κορμό και τελειώστε με τα χέρια· αντίστροφη σειρά στην επιστροφή. Κρατήστε χαμηλό ρυθμό κωπηλασίας και εκπνεύστε στην ώθηση.',
    MACHINE,
  ),
  ex(
    'barbell-back-squat',
    'gym',
    'advanced',
    ['quads', 'glutes', 'hamstrings', 'core'],
    'Barbell back squat',
    'Καθίσματα με μπάρα',
    'Bar on the upper back, brace the core with a big breath, squat until the hips are below the knees with the chest up and knees out. Exhale through the sticking point on the way up.',
    'Μπάρα στην πάνω πλάτη, σφίξτε τον κορμό με βαθιά εισπνοή, καθίστε μέχρι οι γοφοί να περάσουν κάτω από τα γόνατα με στήθος ψηλά και γόνατα ανοιχτά. Εκπνεύστε στο δύσκολο σημείο της ανόδου.',
    BARBELL,
  ),
  ex(
    'deadlift',
    'gym',
    'advanced',
    ['hamstrings', 'glutes', 'back', 'core'],
    'Deadlift',
    'Άρσεις θανάτου',
    'Bar over mid-foot, hips higher than knees, flat back and shoulders over the bar. Brace, push the floor away and stand tall; exhale at the top and lower along the legs.',
    'Μπάρα πάνω από το μέσο του πέλματος, γοφοί ψηλότερα από τα γόνατα, ίσια πλάτη και ώμοι πάνω από τη μπάρα. Σφίξτε, σπρώξτε το πάτωμα και σηκωθείτε όρθιοι· εκπνεύστε στην κορυφή και κατεβάστε κατά μήκος των ποδιών.',
    BARBELL,
  ),
  ex(
    'barbell-bench-press',
    'gym',
    'advanced',
    ['chest', 'triceps', 'shoulders'],
    'Barbell bench press',
    'Πιέσεις πάγκου με μπάρα',
    'Shoulder blades pinched, feet planted, lower the bar to the lower chest with control and press back over the shoulders. Inhale down, exhale on the press; always use a spotter or safeties.',
    'Ωμοπλάτες σφιγμένες, πέλματα σταθερά, κατεβάστε τη μπάρα ελεγχόμενα στο κάτω στήθος και πιέστε πίσω πάνω από τους ώμους. Εισπνοή στην κάθοδο, εκπνοή στην πίεση· πάντα με βοηθό ή ασφάλειες.',
    BARBELL,
  ),
  ex(
    'overhead-press',
    'gym',
    'advanced',
    ['shoulders', 'triceps', 'core'],
    'Barbell overhead press',
    'Πιέσεις ώμων με μπάρα',
    'Bar at the collarbones, squeeze the glutes and brace, press straight up and move the head through once the bar passes. Exhale on the press, lower with control.',
    'Μπάρα στις κλείδες, σφίξτε γλουτούς και κορμό, πιέστε κάθετα και περάστε το κεφάλι μπροστά μόλις περάσει η μπάρα. Εκπνεύστε στην πίεση, κατεβάστε ελεγχόμενα.',
    BARBELL,
  ),
  ex(
    'weighted-pull-up',
    'gym',
    'advanced',
    ['back', 'biceps', 'core'],
    'Weighted pull-up',
    'Έλξεις με βάρος',
    'Hang with added weight on a belt, pull until the chin clears the bar with the elbows driving down, lower fully. Exhale on the pull and avoid swinging.',
    'Κρεμαστείτε με πρόσθετο βάρος σε ζώνη, τραβήξτε μέχρι το πηγούνι να περάσει τη μπάρα με τους αγκώνες να κατεβαίνουν, κατεβείτε πλήρως. Εκπνεύστε στο τράβηγμα και αποφύγετε την αιώρηση.',
    PULLUP_BAR,
  ),
  ex(
    'kettlebell-swing',
    'gym',
    'advanced',
    ['glutes', 'hamstrings', 'core', 'cardio'],
    'Kettlebell swing',
    'Αιωρήσεις με kettlebell',
    'Hinge at the hips, hike the bell back and snap the hips forward so it floats to chest height with straight arms. Exhale sharply at the top; the arms only guide.',
    'Κάμψη από τους γοφούς, στείλτε το kettlebell πίσω και σπρώξτε απότομα τους γοφούς μπροστά ώστε να ανέβει στο ύψος του στήθους με τεντωμένα χέρια. Εκπνεύστε απότομα στην κορυφή· τα χέρια μόνο καθοδηγούν.',
    KETTLEBELL,
  ),
  ex(
    'foam-roll-quads',
    'gym',
    'advanced',
    ['quads', 'hip-flexors'],
    'Foam roll quads',
    'Κύλινδρος στους τετρακέφαλους',
    'Lie face down with the roller under the thighs and roll slowly from hip to knee, pausing on tender spots. Breathe slowly and keep the core braced.',
    'Ξαπλώστε μπρούμυτα με τον κύλινδρο κάτω από τους μηρούς και κυλήστε αργά από τον γοφό ως το γόνατο, σταματώντας στα ευαίσθητα σημεία. Αναπνέετε αργά και κρατήστε τον κορμό σφιχτό.',
    FOAM_ROLLER,
  ),
]

// --- calisthenics --------------------------------------------------------------------------------

const CALISTHENICS: ExerciseSeed[] = [
  ex(
    'wrist-circles',
    'calisthenics',
    'beginner',
    ['forearms'],
    'Wrist circles',
    'Κύκλοι καρπών',
    'Interlace the fingers and roll the wrists slowly in both directions, then press the palms to the floor on all fours for a gentle stretch. Breathe easily.',
    'Πλέξτε τα δάχτυλα και γυρίστε τους καρπούς αργά προς τις δύο κατευθύνσεις, μετά πιέστε τις παλάμες στο πάτωμα στα τέσσερα για ήπια διάταση. Αναπνέετε άνετα.',
  ),
  ex(
    'incline-push-up',
    'calisthenics',
    'beginner',
    ['chest', 'triceps', 'shoulders'],
    'Incline push-up',
    'Κάμψεις με κλίση',
    'Hands on a bench or step, body straight from head to heels, lower the chest to the edge and press away. Exhale on the push; a lower surface makes it harder.',
    'Χέρια σε πάγκο ή σκαλί, σώμα ευθεία από το κεφάλι ως τις φτέρνες, κατεβάστε το στήθος στην άκρη και σπρώξτε. Εκπνεύστε στο σπρώξιμο· όσο χαμηλότερη η επιφάνεια, τόσο δυσκολότερο.',
  ),
  ex(
    'australian-row',
    'calisthenics',
    'beginner',
    ['back', 'biceps', 'core'],
    'Australian row (inverted row)',
    'Αυστραλέζικες έλξεις (οριζόντιες)',
    'Hang under a low bar with heels on the floor and body straight, pull the chest to the bar squeezing the shoulder blades. Exhale on the pull, lower slowly.',
    'Κρεμαστείτε κάτω από χαμηλή μπάρα με τις φτέρνες στο πάτωμα και σώμα ευθεία, τραβήξτε το στήθος στη μπάρα σφίγγοντας τις ωμοπλάτες. Εκπνεύστε στο τράβηγμα, κατεβείτε αργά.',
    PULLUP_BAR,
  ),
  ex(
    'assisted-squat',
    'calisthenics',
    'beginner',
    ['quads', 'glutes'],
    'Assisted squat',
    'Υποβοηθούμενα καθίσματα',
    'Hold a pole or door frame lightly, sit back as deep as comfortable with heels down and chest up. Use the hands only as much as needed and exhale as you stand.',
    'Κρατηθείτε ελαφρά από κολόνα ή κάσα πόρτας, καθίστε όσο βαθιά είναι άνετο με τις φτέρνες κάτω και το στήθος ψηλά. Χρησιμοποιήστε τα χέρια μόνο όσο χρειάζεται και εκπνεύστε καθώς σηκώνεστε.',
  ),
  ex(
    'dead-hang',
    'calisthenics',
    'beginner',
    ['forearms', 'back', 'shoulders'],
    'Dead hang',
    'Παθητικό κρέμασμα',
    'Grip the bar shoulder-width and hang with straight arms, shoulders relaxed, feet off the floor. Breathe slowly and hold for time to build grip.',
    'Πιάστε τη μπάρα στο άνοιγμα των ώμων και κρεμαστείτε με τεντωμένα χέρια, ώμοι χαλαροί, πόδια στον αέρα. Αναπνέετε αργά και κρατήστε με χρόνο για να δυναμώσει η λαβή.',
    PULLUP_BAR,
  ),
  ex(
    'hollow-hold-tuck',
    'calisthenics',
    'beginner',
    ['core', 'hip-flexors'],
    'Tuck hollow hold',
    'Hollow hold με μαζεμένα γόνατα',
    'Lie on your back, press the lower back into the floor and lift the shoulders and bent knees off the ground. Breathe steadily without letting the back arch.',
    'Ξαπλώστε ανάσκελα, πιέστε τη μέση στο πάτωμα και σηκώστε ώμους και λυγισμένα γόνατα από το έδαφος. Αναπνέετε σταθερά χωρίς να σηκώνεται η μέση.',
  ),
  ex(
    'chest-doorway-stretch',
    'calisthenics',
    'beginner',
    ['chest', 'shoulders'],
    'Doorway chest stretch',
    'Διάταση στήθους σε πόρτα',
    'Forearms on the door frame with elbows at shoulder height, step one foot through until the chest opens. Breathe slowly and hold 30 seconds.',
    'Πήχεις στην κάσα της πόρτας με τους αγκώνες στο ύψος των ώμων, κάντε ένα βήμα μπροστά μέχρι να ανοίξει το στήθος. Αναπνέετε αργά και κρατήστε 30 δευτερόλεπτα.',
  ),
  ex(
    'scapular-pull-up',
    'calisthenics',
    'intermediate',
    ['back', 'shoulders'],
    'Scapular pull-up',
    'Έλξεις ωμοπλατών',
    'From a dead hang, pull the shoulder blades down and together so the body rises a few centimetres with straight arms, then release. Exhale on the squeeze.',
    'Από παθητικό κρέμασμα, τραβήξτε τις ωμοπλάτες κάτω και μαζί ώστε το σώμα να ανέβει λίγα εκατοστά με τεντωμένα χέρια, μετά χαλαρώστε. Εκπνεύστε στο σφίξιμο.',
    PULLUP_BAR,
  ),
  ex(
    'pull-up',
    'calisthenics',
    'intermediate',
    ['back', 'biceps', 'core'],
    'Pull-up',
    'Έλξεις στο μονόζυγο',
    'Overhand grip, start from a full hang and pull until the chin passes the bar with the elbows driving down. Exhale on the pull and lower all the way.',
    'Λαβή με παλάμες μπροστά, ξεκινήστε από πλήρες κρέμασμα και τραβήξτε μέχρι το πηγούνι να περάσει τη μπάρα με τους αγκώνες να κατεβαίνουν. Εκπνεύστε στο τράβηγμα και κατεβείτε πλήρως.',
    PULLUP_BAR,
  ),
  ex(
    'bench-dip',
    'calisthenics',
    'intermediate',
    ['triceps', 'chest', 'shoulders'],
    'Bench dip',
    'Βυθίσεις σε πάγκο',
    'Hands on the bench edge behind you, lower the hips until the elbows reach 90 degrees, keeping the shoulders down. Exhale as you press back up.',
    'Χέρια στην άκρη του πάγκου πίσω σας, κατεβάστε τους γοφούς μέχρι οι αγκώνες να φτάσουν στις 90 μοίρες, κρατώντας τους ώμους κάτω. Εκπνεύστε καθώς σπρώχνετε πάνω.',
    BENCH,
  ),
  ex(
    'diamond-push-up',
    'calisthenics',
    'intermediate',
    ['triceps', 'chest', 'core'],
    'Diamond push-up',
    'Κάμψεις διαμάντι',
    'Hands together under the chest with thumbs and index fingers touching, elbows brushing the ribs as you lower. Exhale on the push and keep the body rigid.',
    'Χέρια ενωμένα κάτω από το στήθος με αντίχειρες και δείκτες να ακουμπούν, αγκώνες κοντά στα πλευρά καθώς κατεβαίνετε. Εκπνεύστε στο σπρώξιμο και κρατήστε το σώμα σφιχτό.',
  ),
  ex(
    'hanging-knee-raise',
    'calisthenics',
    'intermediate',
    ['core', 'hip-flexors', 'forearms'],
    'Hanging knee raise',
    'Άρσεις γονάτων σε κρέμασμα',
    'Hang from the bar and lift the knees toward the chest by curling the pelvis, then lower slowly without swinging. Exhale as the knees rise.',
    'Κρεμαστείτε από τη μπάρα και σηκώστε τα γόνατα προς το στήθος γυρίζοντας τη λεκάνη, μετά κατεβάστε αργά χωρίς αιώρηση. Εκπνεύστε καθώς ανεβαίνουν τα γόνατα.',
    PULLUP_BAR,
  ),
  ex(
    'hollow-hold',
    'calisthenics',
    'intermediate',
    ['core', 'hip-flexors'],
    'Hollow body hold',
    'Hollow hold',
    'Lower back pressed into the floor, arms overhead and legs straight a few centimetres off the ground, body shaped like a shallow banana. Breathe steadily throughout.',
    'Μέση πιεσμένη στο πάτωμα, χέρια πάνω από το κεφάλι και πόδια τεντωμένα λίγα εκατοστά από το έδαφος, σώμα σε σχήμα ρηχής μπανάνας. Αναπνέετε σταθερά σε όλη τη διάρκεια.',
  ),
  ex(
    'lat-stretch-bar',
    'calisthenics',
    'intermediate',
    ['back', 'shoulders'],
    'Lat stretch on the bar',
    'Διάταση πλάτης στο μονόζυγο',
    'Hold the bar with one hand and sit the hips back and away to lengthen the side of the back. Breathe slowly and hold 30 seconds each side.',
    'Κρατήστε τη μπάρα με το ένα χέρι και στείλτε τους γοφούς πίσω και μακριά για να επιμηκυνθεί η πλευρά της πλάτης. Αναπνέετε αργά και κρατήστε 30 δευτερόλεπτα σε κάθε πλευρά.',
    PULLUP_BAR,
  ),
  ex(
    'archer-push-up',
    'calisthenics',
    'advanced',
    ['chest', 'triceps', 'shoulders', 'core'],
    'Archer push-up',
    'Κάμψεις τοξότη',
    'Hands wide, lower toward one hand while the other arm straightens to the side, then push back to centre and alternate. Exhale on the push and keep the hips level.',
    'Χέρια ανοιχτά, κατεβείτε προς το ένα χέρι ενώ το άλλο τεντώνει στο πλάι, σπρώξτε πίσω στο κέντρο και εναλλάξτε. Εκπνεύστε στο σπρώξιμο και κρατήστε τους γοφούς σταθερούς.',
  ),
  ex(
    'pistol-squat',
    'calisthenics',
    'advanced',
    ['quads', 'glutes', 'core'],
    'Pistol squat',
    'Καθίσματα σε ένα πόδι (pistol)',
    'Stand on one leg with the other extended forward, sit down slowly keeping the heel on the floor and the arms reaching forward for balance. Exhale as you stand; hold a support if needed.',
    'Σταθείτε σε ένα πόδι με το άλλο τεντωμένο μπροστά, καθίστε αργά κρατώντας τη φτέρνα στο πάτωμα και τα χέρια μπροστά για ισορροπία. Εκπνεύστε καθώς σηκώνεστε· κρατηθείτε αν χρειάζεται.',
  ),
  ex(
    'parallel-bar-dip',
    'calisthenics',
    'advanced',
    ['chest', 'triceps', 'shoulders'],
    'Parallel bar dip',
    'Βυθίσεις στο δίζυγο',
    'Support on the bars with straight arms, lean slightly forward and lower until the shoulders dip just below the elbows. Exhale as you press up; stop short of any shoulder pinch.',
    'Στηριχθείτε στις μπάρες με τεντωμένα χέρια, γείρετε ελαφρά μπροστά και κατεβείτε μέχρι οι ώμοι να περάσουν λίγο κάτω από τους αγκώνες. Εκπνεύστε καθώς σπρώχνετε· σταματήστε πριν τσιμπήσει ο ώμος.',
    DIP_BARS,
  ),
  ex(
    'chest-to-bar-pull-up',
    'calisthenics',
    'advanced',
    ['back', 'biceps', 'core'],
    'Chest-to-bar pull-up',
    'Έλξεις μέχρι το στήθος',
    'Pull explosively until the chest touches the bar, leaning back slightly at the top, then lower under control. Exhale on the pull; this is the muscle-up prerequisite.',
    'Τραβήξτε εκρηκτικά μέχρι το στήθος να ακουμπήσει τη μπάρα, γέρνοντας ελαφρά πίσω στην κορυφή, και κατεβείτε ελεγχόμενα. Εκπνεύστε στο τράβηγμα· είναι η προϋπόθεση για το muscle-up.',
    PULLUP_BAR,
  ),
  ex(
    'hanging-leg-raise',
    'calisthenics',
    'advanced',
    ['core', 'hip-flexors', 'forearms'],
    'Hanging leg raise',
    'Άρσεις ποδιών σε κρέμασμα',
    'Hang with straight arms and lift straight legs to hip height or higher by curling the pelvis up. Exhale on the lift and lower slowly without swinging.',
    'Κρεμαστείτε με τεντωμένα χέρια και σηκώστε τεντωμένα πόδια στο ύψος των γοφών ή ψηλότερα γυρίζοντας τη λεκάνη. Εκπνεύστε στην άρση και κατεβάστε αργά χωρίς αιώρηση.',
    PULLUP_BAR,
  ),
  ex(
    'l-sit',
    'calisthenics',
    'advanced',
    ['core', 'hip-flexors', 'triceps'],
    'L-sit',
    'L-sit',
    'Support on dip bars or the floor with straight arms, lift straight legs to horizontal and hold with the shoulders pushed down. Breathe short and steady; bend the knees to regress.',
    'Στηριχθείτε σε δίζυγο ή στο πάτωμα με τεντωμένα χέρια, σηκώστε τα τεντωμένα πόδια σε οριζόντια θέση και κρατήστε με τους ώμους πιεσμένους κάτω. Αναπνέετε κοντά και σταθερά· λυγίστε τα γόνατα για ευκολότερη εκδοχή.',
    DIP_BARS,
  ),
  ex(
    'german-hang-stretch',
    'calisthenics',
    'advanced',
    ['shoulders', 'chest', 'biceps'],
    'Shoulder extension stretch on the bar',
    'Διάταση ώμων σε έκταση στο μονόζυγο',
    'Hold a low bar behind you and gently lower the hips to open the front of the shoulders. Breathe slowly, keep the elbows straight and never force the range.',
    'Κρατήστε χαμηλή μπάρα πίσω σας και κατεβάστε απαλά τους γοφούς για να ανοίξει το μπροστινό μέρος των ώμων. Αναπνέετε αργά, κρατήστε τους αγκώνες τεντωμένους και μην πιέζετε ποτέ το εύρος.',
    PULLUP_BAR,
  ),
]

// --- running -------------------------------------------------------------------------------------

const RUNNING: ExerciseSeed[] = [
  ex(
    'brisk-walk-5min',
    'running',
    'beginner',
    ['cardio'],
    'Brisk walk, 5 min',
    'Γρήγορο περπάτημα, 5 λεπτά',
    'Walk at a pace that warms you without leaving you breathless, arms swinging freely. Breathe through the nose and loosen the shoulders.',
    'Περπατήστε σε ρυθμό που σας ζεσταίνει χωρίς να σας κόβει την ανάσα, με τα χέρια να κινούνται ελεύθερα. Αναπνέετε από τη μύτη και χαλαρώστε τους ώμους.',
  ),
  ex(
    'leg-swings',
    'running',
    'beginner',
    ['hip-flexors', 'hamstrings', 'adductors'],
    'Leg swings',
    'Αιωρήσεις ποδιών',
    'Hold a wall and swing one leg forward and back, then side to side, growing the range gradually. Keep the torso tall and breathe easily; 10–15 each direction.',
    'Κρατηθείτε από τοίχο και αιωρήστε το ένα πόδι μπρος-πίσω, μετά πλάγια, αυξάνοντας το εύρος σταδιακά. Κορμός ψηλά και άνετη αναπνοή· 10–15 ανά κατεύθυνση.',
  ),
  ex(
    'walk-jog-intervals',
    'running',
    'beginner',
    ['cardio', 'quads', 'calves'],
    'Walk–jog intervals (1 min jog / 2 min walk)',
    'Διαλείμματα περπάτημα–τζόκινγκ (1 λεπτό τζόκινγκ / 2 λεπτά περπάτημα)',
    'Jog slowly for one minute at a pace where you could speak in full sentences, then walk for two to recover. Land lightly under the hips and breathe rhythmically.',
    'Τρέξτε αργά για ένα λεπτό σε ρυθμό που μπορείτε να μιλάτε με ολόκληρες προτάσεις, μετά περπατήστε δύο λεπτά για αποκατάσταση. Προσγειωθείτε ελαφρά κάτω από τους γοφούς και αναπνέετε ρυθμικά.',
  ),
  ex(
    'easy-jog',
    'running',
    'beginner',
    ['cardio', 'quads', 'calves'],
    'Easy jog',
    'Χαλαρό τζόκινγκ',
    'Run at a conversational pace with short, quick steps and relaxed arms. If you cannot speak comfortably, slow down; breathe in a steady rhythm.',
    'Τρέξτε σε ρυθμό συζήτησης με κοντά, γρήγορα βήματα και χαλαρά χέρια. Αν δεν μπορείτε να μιλήσετε άνετα, επιβραδύνετε· αναπνέετε σε σταθερό ρυθμό.',
  ),
  ex(
    'high-knees',
    'running',
    'beginner',
    ['hip-flexors', 'cardio', 'calves'],
    'High knees',
    'Ψηλά γόνατα',
    'Jog in place driving the knees to hip height with a quick ground contact and tall posture. Keep the arms pumping and the breath quick but relaxed.',
    'Τρέξτε επί τόπου φέρνοντας τα γόνατα στο ύψος των γοφών με γρήγορη επαφή στο έδαφος και όρθια στάση. Κουνάτε τα χέρια και κρατήστε την αναπνοή γρήγορη αλλά χαλαρή.',
  ),
  ex(
    'calf-stretch-wall',
    'running',
    'beginner',
    ['calves'],
    'Wall calf stretch',
    'Διάταση γαστροκνημίων στον τοίχο',
    'Hands on the wall, step one foot back with the heel down and the knee straight until the calf stretches. Breathe slowly, hold 30 seconds, then bend the back knee slightly for the lower calf.',
    'Χέρια στον τοίχο, κάντε βήμα πίσω με τη φτέρνα κάτω και το γόνατο τεντωμένο μέχρι να τεντώσει η γάμπα. Αναπνέετε αργά, κρατήστε 30 δευτερόλεπτα, μετά λυγίστε ελαφρά το πίσω γόνατο για την κάτω γάμπα.',
  ),
  ex(
    'butt-kicks',
    'running',
    'intermediate',
    ['hamstrings', 'cardio'],
    'Butt kicks',
    'Φτέρνες στους γλουτούς',
    'Jog in place flicking the heels toward the glutes with quick, light steps and a tall torso. Keep the knees pointing down and breathe rhythmically.',
    'Τρέξτε επί τόπου φέρνοντας τις φτέρνες προς τους γλουτούς με γρήγορα, ελαφριά βήματα και όρθιο κορμό. Κρατήστε τα γόνατα να δείχνουν κάτω και αναπνέετε ρυθμικά.',
  ),
  ex(
    'strides-100m',
    'running',
    'intermediate',
    ['cardio', 'quads', 'hamstrings', 'calves'],
    'Strides, 100 m',
    'Strides 100 μέτρων',
    'Accelerate smoothly over 100 m to about 85% effort, run tall and relaxed, then walk back to recover. Breathe freely; these are fast but not all-out.',
    'Επιταχύνετε ομαλά για 100 μέτρα μέχρι περίπου το 85% της προσπάθειας, τρέξτε όρθιοι και χαλαροί, μετά περπατήστε πίσω για αποκατάσταση. Αναπνέετε ελεύθερα· είναι γρήγορα αλλά όχι στο μέγιστο.',
  ),
  ex(
    'tempo-run-20min',
    'running',
    'intermediate',
    ['cardio', 'quads', 'hamstrings', 'calves'],
    'Tempo run, 20 min',
    'Tempo run 20 λεπτών',
    'Run at a comfortably hard pace you could hold for about an hour — a few words at a time, not sentences. Keep the cadence quick and the breathing deep and even.',
    'Τρέξτε σε άνετα σκληρό ρυθμό που θα μπορούσατε να κρατήσετε για περίπου μία ώρα — λίγες λέξεις τη φορά, όχι προτάσεις. Κρατήστε γρήγορη συχνότητα βημάτων και βαθιά, ομοιόμορφη αναπνοή.',
  ),
  ex(
    'fartlek-30-30',
    'running',
    'intermediate',
    ['cardio', 'quads', 'calves'],
    'Fartlek 30/30',
    'Fartlek 30/30',
    'Alternate 30 seconds of faster running with 30 seconds of easy jogging, by feel rather than by pace. Stay relaxed in the shoulders and breathe through the hard halves.',
    'Εναλλάξτε 30 δευτερόλεπτα γρηγορότερου τρεξίματος με 30 δευτερόλεπτα χαλαρού τζόκινγκ, με το αίσθημα και όχι με το ρολόι. Μείνετε χαλαροί στους ώμους και αναπνέετε στα δύσκολα μισά.',
  ),
  ex(
    'hill-walk-recovery',
    'running',
    'intermediate',
    ['cardio', 'glutes', 'calves'],
    'Hill walk recovery',
    'Ανηφορικό περπάτημα αποκατάστασης',
    'Walk up a gentle hill with short steps and a slight forward lean, then jog or walk down easy. Use the climb to bring the breathing back under control.',
    'Περπατήστε ήπια ανηφόρα με κοντά βήματα και ελαφριά κλίση μπροστά, μετά κατεβείτε χαλαρά. Χρησιμοποιήστε την ανηφόρα για να ελέγξετε ξανά την αναπνοή.',
  ),
  ex(
    'standing-hamstring-stretch',
    'running',
    'intermediate',
    ['hamstrings', 'calves'],
    'Standing hamstring stretch',
    'Διάταση οπίσθιων μηριαίων όρθια',
    'Place one heel on a low step with the leg straight, hinge forward from the hips with a flat back until the hamstring stretches. Breathe slowly and hold 30 seconds each side.',
    'Ακουμπήστε τη μία φτέρνα σε χαμηλό σκαλί με το πόδι τεντωμένο, σκύψτε από τους γοφούς με ίσια πλάτη μέχρι να τεντώσει ο οπίσθιος μηριαίος. Αναπνέετε αργά και κρατήστε 30 δευτερόλεπτα ανά πλευρά.',
  ),
  ex(
    'a-skips',
    'running',
    'advanced',
    ['hip-flexors', 'calves', 'cardio'],
    'A-skips',
    'A-skips',
    'Skip forward driving one knee up with the opposite arm, snapping the foot back down under the hips. Stay tall and bouncy; exhale with each drive.',
    'Κάντε skip προς τα εμπρός ανεβάζοντας το ένα γόνατο με το αντίθετο χέρι και φέρνοντας το πέλμα γρήγορα κάτω από τους γοφούς. Μείνετε όρθιοι και ελαστικοί· εκπνεύστε σε κάθε ώθηση.',
  ),
  ex(
    'intervals-400m',
    'running',
    'advanced',
    ['cardio', 'quads', 'hamstrings', 'calves'],
    'Intervals, 400 m',
    'Διαλείμματα 400 μέτρων',
    'Run 400 m at roughly your 5 km race pace, then jog or walk for equal time to recover; repeat. Keep the form tall when it hurts and breathe deeply, not in gasps.',
    'Τρέξτε 400 μέτρα περίπου στον ρυθμό αγώνα 5 χιλιομέτρων, μετά τζόκινγκ ή περπάτημα για ίσο χρόνο· επαναλάβετε. Κρατήστε όρθια τεχνική όταν δυσκολεύει και αναπνέετε βαθιά, όχι με λαχάνιασμα.',
  ),
  ex(
    'hill-sprints',
    'running',
    'advanced',
    ['glutes', 'quads', 'calves', 'cardio'],
    'Hill sprints, 10–12 s',
    'Σπριντ σε ανηφόρα, 10–12 δευτερόλεπτα',
    'Sprint hard up a moderate hill for 10–12 seconds, driving the knees and arms, then walk down for full recovery. Exhale forcefully with each push-off.',
    'Σπριντάρετε δυνατά σε μέτρια ανηφόρα για 10–12 δευτερόλεπτα, σπρώχνοντας γόνατα και χέρια, μετά κατεβείτε περπατώντας για πλήρη αποκατάσταση. Εκπνεύστε δυνατά σε κάθε ώθηση.',
  ),
  ex(
    'threshold-run-2x15min',
    'running',
    'advanced',
    ['cardio', 'quads', 'hamstrings', 'calves'],
    'Threshold run, 2 × 15 min',
    'Threshold run 2 × 15 λεπτά',
    'Two 15-minute blocks at a controlled hard pace with 3 minutes of easy jogging between. Breathe deeply and rhythmically; the second block should feel the same as the first.',
    'Δύο μπλοκ 15 λεπτών σε ελεγχόμενα σκληρό ρυθμό με 3 λεπτά χαλαρού τζόκινγκ ανάμεσα. Αναπνέετε βαθιά και ρυθμικά· το δεύτερο μπλοκ πρέπει να μοιάζει με το πρώτο.',
  ),
  ex(
    'long-run-easy',
    'running',
    'advanced',
    ['cardio', 'quads', 'hamstrings', 'calves'],
    'Long easy run',
    'Μεγάλη χαλαρή διαδρομή',
    'Run at an easy, conversational pace for longer than your usual run, keeping the steps short and light. Drink as needed and keep the breathing relaxed throughout.',
    'Τρέξτε σε χαλαρό ρυθμό συζήτησης για περισσότερο από το συνηθισμένο, με κοντά και ελαφριά βήματα. Πιείτε νερό όσο χρειάζεται και κρατήστε χαλαρή αναπνοή σε όλη τη διάρκεια.',
  ),
  ex(
    'hip-flexor-stretch-kneeling',
    'running',
    'advanced',
    ['hip-flexors', 'quads'],
    'Kneeling hip flexor stretch',
    'Διάταση καμπτήρων ισχίου σε γονάτισμα',
    'Half-kneel, tuck the pelvis and shift forward gently until the front of the back hip stretches, torso tall. Breathe slowly and hold 30–45 seconds each side.',
    'Γονατίστε στο ένα πόδι, γείρετε τη λεκάνη και μετακινηθείτε απαλά μπροστά μέχρι να τεντώσει το μπροστινό μέρος του πίσω ισχίου, κορμός όρθιος. Αναπνέετε αργά και κρατήστε 30–45 δευτερόλεπτα ανά πλευρά.',
    MAT,
  ),
]

// --- swimming ------------------------------------------------------------------------------------

const SWIMMING: ExerciseSeed[] = [
  ex(
    'easy-swim-100m',
    'swimming',
    'beginner',
    ['cardio', 'full-body'],
    'Easy swim, 100 m',
    'Χαλαρό κολύμπι, 100 μέτρα',
    'Swim any stroke at a relaxed pace, long and smooth, to warm the shoulders and settle the breathing. Exhale into the water, inhale quickly when the face turns.',
    'Κολυμπήστε όποιο στυλ θέλετε σε χαλαρό ρυθμό, με μακριές και ομαλές κινήσεις, για να ζεσταθούν οι ώμοι και να ηρεμήσει η αναπνοή. Εκπνεύστε μέσα στο νερό, εισπνεύστε γρήγορα όταν γυρίζει το πρόσωπο.',
  ),
  ex(
    'bobbing-breath-practice',
    'swimming',
    'beginner',
    ['cardio'],
    'Bobbing breath practice',
    'Άσκηση αναπνοής με βυθίσεις',
    'In chest-deep water, sink under and blow bubbles steadily out of the nose and mouth, surface for a quick breath and repeat. Make the exhale slow and complete.',
    'Σε νερό μέχρι το στήθος, βυθιστείτε και φυσήξτε σταθερά φυσαλίδες από μύτη και στόμα, βγείτε για μια γρήγορη εισπνοή και επαναλάβετε. Κάντε την εκπνοή αργή και πλήρη.',
  ),
  ex(
    'drill-kick-board',
    'swimming',
    'beginner',
    ['quads', 'glutes', 'core'],
    'Kickboard flutter kick',
    'Ποδιά με σανίδα',
    'Hold the board at arm’s length, kick from the hips with soft knees and pointed toes, making a small splash. Keep the head low and breathe freely.',
    'Κρατήστε τη σανίδα με τεντωμένα χέρια, κλωτσήστε από τους γοφούς με χαλαρά γόνατα και τεντωμένα δάχτυλα, κάνοντας μικρό πιτσίλισμα. Κεφάλι χαμηλά και ελεύθερη αναπνοή.',
    KICKBOARD,
  ),
  ex(
    'freestyle-25m-repeats',
    'swimming',
    'beginner',
    ['cardio', 'back', 'shoulders'],
    'Freestyle, 25 m repeats',
    'Ελεύθερο, επαναλήψεις 25 μέτρων',
    'Swim one length of freestyle with long strokes, rest 20–30 seconds at the wall, repeat. Breathe every second or third stroke and exhale fully underwater.',
    'Κολυμπήστε ένα μήκος ελεύθερο με μακριές χεριές, ξεκουραστείτε 20–30 δευτερόλεπτα στον τοίχο, επαναλάβετε. Αναπνέετε κάθε δεύτερη ή τρίτη χεριά και εκπνεύστε πλήρως κάτω από το νερό.',
  ),
  ex(
    'backstroke-easy',
    'swimming',
    'beginner',
    ['back', 'shoulders', 'core'],
    'Easy backstroke',
    'Χαλαρό ύπτιο',
    'Float on your back with the hips high and ears in the water, alternate straight-arm pulls with a steady kick. Breathe freely and look straight up.',
    'Επιπλεύστε ανάσκελα με τους γοφούς ψηλά και τα αυτιά στο νερό, εναλλάξτε χεριές με τεντωμένα χέρια και σταθερή ποδιά. Αναπνέετε ελεύθερα και κοιτάτε ευθεία πάνω.',
  ),
  ex(
    'pool-wall-shoulder-stretch',
    'swimming',
    'beginner',
    ['shoulders', 'chest'],
    'Shoulder stretch at the pool wall',
    'Διάταση ώμων στον τοίχο της πισίνας',
    'Hold the gutter with one hand, turn the body away until the front of the shoulder stretches, then switch. Breathe slowly and hold 20–30 seconds each side.',
    'Κρατηθείτε από το χείλος με το ένα χέρι, γυρίστε το σώμα αντίθετα μέχρι να τεντώσει το μπροστινό μέρος του ώμου, μετά αλλάξτε. Αναπνέετε αργά και κρατήστε 20–30 δευτερόλεπτα ανά πλευρά.',
  ),
  ex(
    'drill-catch-up-freestyle',
    'swimming',
    'intermediate',
    ['shoulders', 'back', 'core'],
    'Catch-up freestyle drill',
    'Άσκηση catch-up στο ελεύθερο',
    'Keep one arm extended in front until the other arm finishes its stroke and touches it, then switch. Focus on a long body line and a steady kick; breathe to the side without lifting the head.',
    'Κρατήστε το ένα χέρι τεντωμένο μπροστά μέχρι το άλλο να ολοκληρώσει τη χεριά και να το ακουμπήσει, μετά αλλάξτε. Εστιάστε σε μακριά γραμμή σώματος και σταθερή ποδιά· αναπνεύστε στο πλάι χωρίς να σηκώνετε το κεφάλι.',
  ),
  ex(
    'pull-buoy-freestyle',
    'swimming',
    'intermediate',
    ['back', 'shoulders', 'triceps'],
    'Pull buoy freestyle',
    'Ελεύθερο με pull buoy',
    'Hold the buoy between the thighs and swim freestyle with the arms only, reaching long and pulling through to the hip. Exhale continuously underwater and keep the hips high.',
    'Κρατήστε το pull buoy ανάμεσα στους μηρούς και κολυμπήστε ελεύθερο μόνο με τα χέρια, τεντώνοντας μακριά και τραβώντας μέχρι τον γοφό. Εκπνεύστε συνεχόμενα κάτω από το νερό και κρατήστε τους γοφούς ψηλά.',
    PULL_BUOY,
  ),
  ex(
    'freestyle-50m-repeats',
    'swimming',
    'intermediate',
    ['cardio', 'back', 'shoulders'],
    'Freestyle, 50 m repeats',
    'Ελεύθερο, επαναλήψεις 50 μέτρων',
    'Swim 50 m at a steady effort you could repeat eight times, resting 20 seconds between. Hold your stroke count per length and breathe bilaterally if you can.',
    'Κολυμπήστε 50 μέτρα σε σταθερή προσπάθεια που μπορείτε να επαναλάβετε οκτώ φορές, με 20 δευτερόλεπτα ανάπαυση. Κρατήστε σταθερό αριθμό χεριών ανά μήκος και αναπνέετε αμφίπλευρα αν μπορείτε.',
  ),
  ex(
    'breaststroke-100m',
    'swimming',
    'intermediate',
    ['chest', 'adductors', 'cardio'],
    'Breaststroke, 100 m',
    'Πρόσθιο, 100 μέτρα',
    'Pull, breathe, kick, glide: sweep the hands out and in, lift to breathe, whip the legs together and hold a long streamline before the next stroke. Exhale during the glide.',
    'Χεριά, αναπνοή, ποδιά, γλίστρημα: ανοίξτε και κλείστε τα χέρια, σηκωθείτε για αναπνοή, κλείστε τα πόδια δυνατά και κρατήστε μακρύ streamline πριν την επόμενη χεριά. Εκπνεύστε στο γλίστρημα.',
  ),
  ex(
    'fins-kick-set',
    'swimming',
    'intermediate',
    ['quads', 'glutes', 'core', 'cardio'],
    'Kick set with fins',
    'Σετ ποδιάς με βατραχοπέδιλα',
    'Kick on your front or side with fins, driving from the hips with a loose ankle and a tight core. Keep the kicks narrow and breathe calmly.',
    'Κλωτσήστε μπρούμυτα ή στο πλάι με βατραχοπέδιλα, κινώντας από τους γοφούς με χαλαρό αστράγαλο και σφιχτό κορμό. Κρατήστε στενή ποδιά και ήρεμη αναπνοή.',
    FINS,
  ),
  ex(
    'easy-swim-cooldown-200m',
    'swimming',
    'intermediate',
    ['cardio', 'full-body'],
    'Easy swim cool-down, 200 m',
    'Χαλαρό κολύμπι αποθεραπείας, 200 μέτρα',
    'Swim slowly mixing strokes, stretching each stroke out and letting the heart rate drop. Exhale long and slow into the water.',
    'Κολυμπήστε αργά εναλλάσσοντας στυλ, επιμηκύνοντας κάθε χεριά και αφήνοντας τον καρδιακό ρυθμό να πέσει. Εκπνεύστε μακριά και αργά μέσα στο νερό.',
  ),
  ex(
    'drill-sculling',
    'swimming',
    'advanced',
    ['forearms', 'shoulders', 'core'],
    'Sculling drill',
    'Άσκηση sculling',
    'Float face down with the arms extended and move the hands in small figure-eights to feel pressure on the forearms, propelling slowly forward. Breathe with a snorkel or lift briefly.',
    'Επιπλεύστε μπρούμυτα με τα χέρια τεντωμένα και κινήστε τις παλάμες σε μικρά οκτάρια για να νιώσετε πίεση στους πήχεις, προωθούμενοι αργά. Αναπνεύστε με αναπνευστήρα ή σηκωθείτε σύντομα.',
  ),
  ex(
    'freestyle-100m-intervals',
    'swimming',
    'advanced',
    ['cardio', 'back', 'shoulders', 'core'],
    'Freestyle, 100 m intervals',
    'Ελεύθερο, διαλείμματα 100 μέτρων',
    'Swim 100 m at a hard but repeatable pace, leaving on a fixed interval that gives 15–20 seconds of rest. Keep the stroke long under fatigue and exhale fully every stroke.',
    'Κολυμπήστε 100 μέτρα σε σκληρό αλλά επαναλήψιμο ρυθμό, ξεκινώντας σε σταθερό διάστημα που αφήνει 15–20 δευτερόλεπτα ανάπαυση. Κρατήστε μακριά χεριά στην κούραση και εκπνεύστε πλήρως σε κάθε χεριά.',
  ),
  ex(
    'butterfly-25m',
    'swimming',
    'advanced',
    ['chest', 'back', 'shoulders', 'core'],
    'Butterfly, 25 m',
    'Πεταλούδα, 25 μέτρα',
    'Two kicks per arm cycle: press the chest down as the hands enter, kick again as they exit, and breathe low and forward every second stroke. Keep the stroke rhythmic, not forced.',
    'Δύο ποδιές ανά κύκλο χεριών: πιέστε το στήθος κάτω όταν μπαίνουν τα χέρια, κλωτσήστε ξανά όταν βγαίνουν, και αναπνεύστε χαμηλά και μπροστά κάθε δεύτερη χεριά. Κρατήστε τον ρυθμό, μην πιέζετε.',
  ),
  ex(
    'individual-medley-100m',
    'swimming',
    'advanced',
    ['full-body', 'cardio'],
    'Individual medley, 100 m',
    'Μικτή ατομική, 100 μέτρα',
    'Swim 25 m each of butterfly, backstroke, breaststroke and freestyle with legal turns between. Pace the first half and breathe deliberately in every stroke.',
    'Κολυμπήστε 25 μέτρα από πεταλούδα, ύπτιο, πρόσθιο και ελεύθερο με κανονικές στροφές ανάμεσα. Μοιράστε την προσπάθεια στο πρώτο μισό και αναπνέετε συνειδητά σε κάθε στυλ.',
  ),
  ex(
    'hypoxic-breathing-set',
    'swimming',
    'advanced',
    ['cardio', 'core'],
    'Breathing-pattern set (3-5-7)',
    'Σετ μοτίβου αναπνοής (3-5-7)',
    'Swim 25 m breathing every 3rd stroke, then every 5th, then every 7th, with rest between. Stop and breathe normally the moment you feel light-headed; never swim alone for this.',
    'Κολυμπήστε 25 μέτρα αναπνέοντας κάθε 3η χεριά, μετά κάθε 5η, μετά κάθε 7η, με ανάπαυση ανάμεσα. Σταματήστε και αναπνεύστε κανονικά μόλις νιώσετε ζάλη· ποτέ μόνοι σας σε αυτό.',
  ),
  ex(
    'streamline-glide-stretch',
    'swimming',
    'advanced',
    ['shoulders', 'back', 'core'],
    'Streamline glide stretch',
    'Διάταση streamline',
    'Push off the wall in a tight streamline, hands stacked and arms squeezing the ears, and glide until you slow. Exhale slowly through the glide and repeat as a relaxing finisher.',
    'Σπρώξτε από τον τοίχο σε σφιχτό streamline, παλάμες η μία πάνω στην άλλη και χέρια να πιέζουν τα αυτιά, και γλιστρήστε μέχρι να επιβραδύνετε. Εκπνεύστε αργά στο γλίστρημα και επαναλάβετε ως χαλαρωτικό κλείσιμο.',
  ),
]

// --- cycling -------------------------------------------------------------------------------------

const CYCLING: ExerciseSeed[] = [
  ex(
    'easy-spin',
    'cycling',
    'beginner',
    ['cardio', 'quads'],
    'Easy spin',
    'Χαλαρό πετάλι',
    'Pedal in a light gear at a relaxed cadence, hands soft on the bars and shoulders down. Breathe through the nose and let the legs warm up.',
    'Κάντε πετάλι σε ελαφριά σχέση και χαλαρό ρυθμό, με απαλή λαβή στο τιμόνι και ώμους κάτω. Αναπνέετε από τη μύτη και αφήστε τα πόδια να ζεσταθούν.',
    BIKE,
  ),
  ex(
    'steady-ride-20min',
    'cycling',
    'beginner',
    ['cardio', 'quads', 'glutes'],
    'Steady ride, 20 min',
    'Σταθερή διαδρομή, 20 λεπτά',
    'Ride at a pace where you can hold a conversation, keeping the cadence smooth and the upper body still. Breathe evenly and drink regularly.',
    'Οδηγήστε σε ρυθμό που μπορείτε να συζητάτε, με ομαλό πετάλι και ακίνητο πάνω μέρος του σώματος. Αναπνέετε ομοιόμορφα και πίνετε τακτικά νερό.',
    BIKE,
  ),
  ex(
    'cadence-drill-90rpm',
    'cycling',
    'beginner',
    ['quads', 'hamstrings', 'cardio'],
    'Cadence drill, 90 rpm',
    'Άσκηση ρυθμού, 90 στροφές/λεπτό',
    'Choose an easy gear and hold about 90 pedal revolutions per minute for 3 minutes without bouncing in the saddle. Relax the feet and breathe steadily.',
    'Επιλέξτε ελαφριά σχέση και κρατήστε περίπου 90 στροφές το λεπτό για 3 λεπτά χωρίς να αναπηδάτε στη σέλα. Χαλαρώστε τα πέλματα και αναπνέετε σταθερά.',
    BIKE,
  ),
  ex(
    'single-leg-pedalling',
    'cycling',
    'beginner',
    ['quads', 'hamstrings', 'hip-flexors'],
    'Single-leg pedalling',
    'Πετάλι με ένα πόδι',
    'On a trainer, unclip one foot and pedal smooth circles with the other for 30 seconds, pulling through the bottom and over the top. Switch legs and breathe evenly.',
    'Σε προπονητήριο, βγάλτε το ένα πόδι και κάντε ομαλούς κύκλους με το άλλο για 30 δευτερόλεπτα, τραβώντας στο κάτω μέρος και περνώντας από το πάνω. Αλλάξτε πόδι και αναπνέετε ομοιόμορφα.',
    BIKE,
  ),
  ex(
    'spin-down-5min',
    'cycling',
    'beginner',
    ['cardio'],
    'Spin-down, 5 min',
    'Ξεκούραστο πετάλι αποθεραπείας, 5 λεπτά',
    'Shift to the easiest gear and pedal lightly for 5 minutes, letting the heart rate fall. Breathe slowly and shake out the arms one at a time.',
    'Βάλτε την πιο ελαφριά σχέση και κάντε ελαφρύ πετάλι για 5 λεπτά, αφήνοντας τον καρδιακό ρυθμό να πέσει. Αναπνέετε αργά και χαλαρώστε τα χέρια ένα-ένα.',
    BIKE,
  ),
  ex(
    'post-ride-quad-stretch',
    'cycling',
    'beginner',
    ['quads', 'hip-flexors'],
    'Post-ride quad stretch',
    'Διάταση τετρακεφάλων μετά τη διαδρομή',
    'Off the bike, hold the frame or a wall and draw one heel to the glutes with the knees together and the pelvis tucked. Breathe slowly, 30 seconds each side.',
    'Κατεβείτε από το ποδήλατο, κρατηθείτε από το σκελετό ή τοίχο και φέρτε τη μία φτέρνα στους γλουτούς με τα γόνατα ενωμένα και τη λεκάνη μαζεμένη. Αναπνέετε αργά, 30 δευτερόλεπτα ανά πλευρά.',
  ),
  ex(
    'cadence-drill-100rpm',
    'cycling',
    'intermediate',
    ['quads', 'hamstrings', 'cardio'],
    'Cadence drill, 100 rpm',
    'Άσκηση ρυθμού, 100 στροφές/λεπτό',
    'In a light gear, spin at about 100 rpm for 2–3 minutes keeping the hips still and the pedal stroke round. Recover at an easy cadence and breathe deeply.',
    'Σε ελαφριά σχέση, γυρίστε περίπου 100 στροφές το λεπτό για 2–3 λεπτά κρατώντας τους γοφούς ακίνητους και το πετάλι κυκλικό. Αποκατάσταση σε χαλαρό ρυθμό και βαθιά αναπνοή.',
    BIKE,
  ),
  ex(
    'tempo-ride-20min',
    'cycling',
    'intermediate',
    ['cardio', 'quads', 'glutes'],
    'Tempo ride, 20 min',
    'Tempo διαδρομή, 20 λεπτά',
    'Ride at a comfortably hard, steady effort — short phrases only — holding a cadence of 85–95 rpm. Keep the upper body relaxed and breathe deep and even.',
    'Οδηγήστε σε άνετα σκληρή, σταθερή προσπάθεια — μόνο σύντομες φράσεις — με ρυθμό 85–95 στροφών. Κρατήστε χαλαρό το πάνω σώμα και βαθιά, ομοιόμορφη αναπνοή.',
    BIKE,
  ),
  ex(
    'seated-climb-intervals',
    'cycling',
    'intermediate',
    ['quads', 'glutes', 'hamstrings', 'cardio'],
    'Seated climb intervals, 5 min',
    'Διαλείμματα καθιστής ανάβασης, 5 λεπτά',
    'Shift to a heavier gear at 70–80 rpm and hold a strong seated effort for 5 minutes, hands on the tops. Keep the torso quiet and breathe rhythmically; spin easy between efforts.',
    'Βάλτε βαρύτερη σχέση στις 70–80 στροφές και κρατήστε δυνατή καθιστή προσπάθεια για 5 λεπτά, με τα χέρια πάνω στο τιμόνι. Ήρεμος κορμός και ρυθμική αναπνοή· χαλαρό πετάλι ανάμεσα.',
    BIKE,
  ),
  ex(
    'standing-climb-drill',
    'cycling',
    'intermediate',
    ['quads', 'glutes', 'calves', 'core'],
    'Standing climb drill',
    'Άσκηση όρθιας ανάβασης',
    'Shift up two gears, stand on the pedals and rock the bike gently beneath you for 30–60 seconds, hips over the cranks. Exhale on each downstroke.',
    'Ανεβείτε δύο σχέσεις, σηκωθείτε στα πετάλια και κουνήστε απαλά το ποδήλατο κάτω σας για 30–60 δευτερόλεπτα, με τους γοφούς πάνω από τα πετάλια. Εκπνεύστε σε κάθε πάτημα.',
    BIKE,
  ),
  ex(
    'over-under-intervals',
    'cycling',
    'intermediate',
    ['cardio', 'quads', 'glutes'],
    'Over-under intervals',
    'Διαλείμματα over-under',
    'Alternate 2 minutes just below your hard sustainable pace with 1 minute just above it, for 9–12 minutes. Keep the cadence steady and breathe through the harder minute.',
    'Εναλλάξτε 2 λεπτά λίγο κάτω από τον σκληρό βιώσιμο ρυθμό σας με 1 λεπτό λίγο πάνω, για 9–12 λεπτά. Κρατήστε σταθερό ρυθμό πεταλιάς και αναπνέετε στο δύσκολο λεπτό.',
    BIKE,
  ),
  ex(
    'post-ride-hip-stretch',
    'cycling',
    'intermediate',
    ['glutes', 'hip-flexors'],
    'Figure-four hip stretch',
    'Διάταση ισχίου σε θέση τέσσερα',
    'Sit or lie down, cross one ankle over the opposite knee and draw the legs toward the chest until the outer hip stretches. Breathe slowly, 30 seconds per side.',
    'Καθίστε ή ξαπλώστε, σταυρώστε τον έναν αστράγαλο πάνω από το αντίθετο γόνατο και τραβήξτε τα πόδια προς το στήθος μέχρι να τεντώσει ο έξω γοφός. Αναπνέετε αργά, 30 δευτερόλεπτα ανά πλευρά.',
    MAT,
  ),
  ex(
    'vo2-intervals-3min',
    'cycling',
    'advanced',
    ['cardio', 'quads', 'glutes'],
    'VO2 intervals, 3 min',
    'Διαλείμματα VO2, 3 λεπτά',
    'Ride 3 minutes very hard at 95–105 rpm — the last minute should be a real fight — then spin easy for 3 minutes; repeat 4–5 times. Breathe deep and fast, shoulders relaxed.',
    'Οδηγήστε 3 λεπτά πολύ σκληρά στις 95–105 στροφές — το τελευταίο λεπτό πρέπει να είναι πραγματική μάχη — μετά χαλαρό πετάλι 3 λεπτά· επαναλάβετε 4–5 φορές. Βαθιά και γρήγορη αναπνοή, χαλαροί ώμοι.',
    BIKE,
  ),
  ex(
    'sprint-intervals-30s',
    'cycling',
    'advanced',
    ['quads', 'glutes', 'calves', 'cardio'],
    'Sprint intervals, 30 s',
    'Διαλείμματα σπριντ, 30 δευτερόλεπτα',
    'From a rolling start, sprint all-out for 30 seconds out of the saddle then seated, with 4–5 minutes of easy spinning between. Exhale hard; keep the bike straight.',
    'Από κίνηση, σπριντάρετε στο μέγιστο για 30 δευτερόλεπτα όρθιοι και μετά καθιστοί, με 4–5 λεπτά χαλαρό πετάλι ανάμεσα. Εκπνεύστε δυνατά· κρατήστε το ποδήλατο ίσιο.',
    BIKE,
  ),
  ex(
    'threshold-ride-2x20min',
    'cycling',
    'advanced',
    ['cardio', 'quads', 'glutes', 'hamstrings'],
    'Threshold ride, 2 × 20 min',
    'Threshold διαδρομή, 2 × 20 λεπτά',
    'Two 20-minute efforts at the hardest pace you could hold for an hour, with 5 minutes easy between. Keep the cadence at 85–95 rpm and the breathing deep and controlled.',
    'Δύο προσπάθειες 20 λεπτών στον σκληρότερο ρυθμό που θα κρατούσατε για μία ώρα, με 5 λεπτά χαλαρά ανάμεσα. Ρυθμός 85–95 στροφών και βαθιά, ελεγχόμενη αναπνοή.',
    BIKE,
  ),
  ex(
    'low-cadence-strength',
    'cycling',
    'advanced',
    ['quads', 'glutes', 'hamstrings'],
    'Low-cadence strength efforts',
    'Προσπάθειες δύναμης με χαμηλό ρυθμό',
    'Seated in a heavy gear at 50–60 rpm, push a strong, smooth effort for 5 minutes with the core braced and the knees tracking straight. Breathe slowly; stop if the knees complain.',
    'Καθιστοί σε βαριά σχέση στις 50–60 στροφές, σπρώξτε δυνατή και ομαλή προσπάθεια για 5 λεπτά με σφιχτό κορμό και γόνατα σε ευθεία. Αναπνέετε αργά· σταματήστε αν πονέσουν τα γόνατα.',
    BIKE,
  ),
  ex(
    'long-endurance-ride',
    'cycling',
    'advanced',
    ['cardio', 'quads', 'glutes'],
    'Long endurance ride',
    'Μεγάλη διαδρομή αντοχής',
    'Ride for two hours or more at a steady conversational pace, eating and drinking every 20–30 minutes. Change hand position often and keep the breathing relaxed.',
    'Οδηγήστε δύο ώρες ή περισσότερο σε σταθερό ρυθμό συζήτησης, τρώγοντας και πίνοντας κάθε 20–30 λεπτά. Αλλάζετε συχνά θέση χεριών και κρατήστε χαλαρή αναπνοή.',
    BIKE,
  ),
  ex(
    'post-ride-foam-roll',
    'cycling',
    'advanced',
    ['quads', 'glutes', 'calves'],
    'Post-ride foam rolling',
    'Κύλινδρος μετά τη διαδρομή',
    'Roll the quads, glutes and calves slowly for about a minute each, pausing on tight spots. Breathe slowly and keep the pressure tolerable.',
    'Κυλήστε τετρακέφαλους, γλουτούς και γάμπες αργά για περίπου ένα λεπτό το καθένα, σταματώντας στα σφιγμένα σημεία. Αναπνέετε αργά και κρατήστε την πίεση ανεκτή.',
    FOAM_ROLLER,
  ),
]

// --- mobility ------------------------------------------------------------------------------------

const MOBILITY: ExerciseSeed[] = [
  ex(
    'neck-rolls',
    'mobility',
    'beginner',
    ['shoulders'],
    'Neck rolls',
    'Κύκλοι αυχένα',
    'Drop the chin to the chest and roll the head slowly from shoulder to shoulder in a half circle, never forcing backward. Breathe slowly with each pass.',
    'Κατεβάστε το πηγούνι στο στήθος και γυρίστε το κεφάλι αργά από ώμο σε ώμο σε ημικύκλιο, χωρίς να πιέζετε προς τα πίσω. Αναπνέετε αργά σε κάθε πέρασμα.',
  ),
  ex(
    'cat-cow',
    'mobility',
    'beginner',
    ['back', 'core'],
    'Cat–cow',
    'Γάτα–αγελάδα',
    'On all fours, inhale as you drop the belly and lift the gaze, exhale as you round the spine and tuck the chin. Move slowly, one breath per position.',
    'Στα τέσσερα, εισπνεύστε καθώς χαμηλώνετε την κοιλιά και σηκώνετε το βλέμμα, εκπνεύστε καθώς στρογγυλεύετε τη σπονδυλική στήλη και μαζεύετε το πηγούνι. Κινηθείτε αργά, μία αναπνοή ανά θέση.',
    MAT,
  ),
  ex(
    'childs-pose',
    'mobility',
    'beginner',
    ['back', 'shoulders', 'glutes'],
    "Child's pose",
    'Στάση του παιδιού',
    'Kneel, sit the hips back onto the heels and stretch the arms forward with the forehead resting down. Breathe slowly into the back for 30–60 seconds.',
    'Γονατίστε, καθίστε με τους γοφούς στις φτέρνες και τεντώστε τα χέρια μπροστά με το μέτωπο να ακουμπά κάτω. Αναπνέετε αργά προς την πλάτη για 30–60 δευτερόλεπτα.',
    MAT,
  ),
  ex(
    'hip-circles',
    'mobility',
    'beginner',
    ['hip-flexors', 'glutes'],
    'Hip circles',
    'Κύκλοι ισχίων',
    'Hands on the hips, draw slow wide circles with the pelvis in both directions as if tracing a hula hoop. Keep the knees soft and breathe easily.',
    'Χέρια στους γοφούς, κάντε αργούς πλατιούς κύκλους με τη λεκάνη προς τις δύο κατευθύνσεις σαν να γυρίζετε χούλα χουπ. Γόνατα χαλαρά και άνετη αναπνοή.',
  ),
  ex(
    'ankle-circles',
    'mobility',
    'beginner',
    ['calves'],
    'Ankle circles',
    'Κύκλοι αστραγάλων',
    'Lift one foot and circle the ankle slowly 10 times each way, then switch. Keep the movement smooth and breathe normally.',
    'Σηκώστε το ένα πόδι και γυρίστε τον αστράγαλο αργά 10 φορές προς κάθε κατεύθυνση, μετά αλλάξτε. Ομαλή κίνηση και κανονική αναπνοή.',
  ),
  ex(
    'shoulder-rolls',
    'mobility',
    'beginner',
    ['shoulders', 'back'],
    'Shoulder rolls',
    'Κύκλοι ώμων',
    'Lift the shoulders toward the ears, roll them back and down in slow circles, then reverse. Exhale as the shoulders drop.',
    'Σηκώστε τους ώμους προς τα αυτιά, γυρίστε τους πίσω και κάτω σε αργούς κύκλους, μετά αντίστροφα. Εκπνεύστε καθώς πέφτουν οι ώμοι.',
  ),
  ex(
    'supine-knee-hug',
    'mobility',
    'beginner',
    ['back', 'glutes'],
    'Knees-to-chest hug',
    'Αγκάλιασμα γονάτων στο στήθος',
    'Lie on your back, hug both knees toward the chest and rock gently side to side. Breathe slowly and let the lower back release.',
    'Ξαπλώστε ανάσκελα, αγκαλιάστε τα δύο γόνατα προς το στήθος και κουνηθείτε απαλά δεξιά-αριστερά. Αναπνέετε αργά και αφήστε τη μέση να χαλαρώσει.',
    MAT,
  ),
  ex(
    'worlds-greatest-stretch',
    'mobility',
    'intermediate',
    ['hip-flexors', 'hamstrings', 'back', 'shoulders'],
    "World's greatest stretch",
    'Η μεγαλύτερη διάταση του κόσμου',
    'Step into a long lunge, place the opposite hand down, rotate the other arm toward the ceiling, then drop the elbow inside the front foot. Exhale on each rotation; alternate sides.',
    'Κάντε μακριά προβολή, ακουμπήστε το αντίθετο χέρι κάτω, γυρίστε το άλλο χέρι προς το ταβάνι και μετά κατεβάστε τον αγκώνα μέσα από το μπροστινό πόδι. Εκπνεύστε σε κάθε περιστροφή· εναλλάξ πλευρές.',
  ),
  ex(
    'thoracic-rotation',
    'mobility',
    'intermediate',
    ['back', 'core', 'shoulders'],
    'Thoracic rotation (open book)',
    'Περιστροφή θωρακικής μοίρας (ανοιχτό βιβλίο)',
    'Lie on your side with knees bent at 90 degrees, arms stacked in front, and open the top arm across to the other side following it with the eyes. Exhale as you open; keep the knees down.',
    'Ξαπλώστε στο πλάι με γόνατα λυγισμένα στις 90 μοίρες, χέρια ενωμένα μπροστά, και ανοίξτε το πάνω χέρι προς την άλλη πλευρά ακολουθώντας το με το βλέμμα. Εκπνεύστε καθώς ανοίγετε· γόνατα κάτω.',
    MAT,
  ),
  ex(
    'ninety-ninety-hip-switch',
    'mobility',
    'intermediate',
    ['hip-flexors', 'glutes', 'adductors'],
    '90/90 hip switch',
    'Εναλλαγή ισχίων 90/90',
    'Sit with both knees bent at 90 degrees, one in front and one to the side, then rotate the knees to the other side without using the hands. Sit tall and exhale on the switch.',
    'Καθίστε με τα δύο γόνατα λυγισμένα στις 90 μοίρες, το ένα μπροστά και το άλλο στο πλάι, και γυρίστε τα γόνατα προς την άλλη πλευρά χωρίς τα χέρια. Καθίστε όρθιοι και εκπνεύστε στην αλλαγή.',
    MAT,
  ),
  ex(
    'deep-squat-hold',
    'mobility',
    'intermediate',
    ['hip-flexors', 'adductors', 'calves', 'quads'],
    'Deep squat hold',
    'Κράτημα βαθέος καθίσματος',
    'Sink into the deepest squat you can with heels down, elbows pressing the knees gently outward and the chest tall. Breathe slowly for 30–60 seconds; hold a support if needed.',
    'Βυθιστείτε στο βαθύτερο κάθισμα που μπορείτε με τις φτέρνες κάτω, οι αγκώνες σπρώχνουν απαλά τα γόνατα προς τα έξω και το στήθος ψηλά. Αναπνέετε αργά για 30–60 δευτερόλεπτα· κρατηθείτε αν χρειάζεται.',
  ),
  ex(
    'downward-dog',
    'mobility',
    'intermediate',
    ['hamstrings', 'calves', 'shoulders', 'back'],
    'Downward dog',
    'Σκύλος που κοιτά κάτω',
    'From all fours lift the hips up and back into an inverted V, pedalling the heels toward the floor one at a time. Press the floor away through the hands and breathe slowly.',
    'Από τα τέσσερα σηκώστε τους γοφούς πάνω και πίσω σε ανάποδο V, φέρνοντας εναλλάξ τις φτέρνες προς το πάτωμα. Σπρώξτε το πάτωμα με τις παλάμες και αναπνέετε αργά.',
    MAT,
  ),
  ex(
    'half-kneeling-adductor-rock',
    'mobility',
    'intermediate',
    ['adductors', 'hip-flexors'],
    'Half-kneeling adductor rock',
    'Διάταση προσαγωγών σε γονάτισμα',
    'Kneel on one knee with the other leg extended straight to the side, foot flat, and rock the hips back toward the kneeling heel. Exhale as you rock back; keep the back flat.',
    'Γονατίστε στο ένα γόνατο με το άλλο πόδι τεντωμένο στο πλάι και το πέλμα στο πάτωμα, και κουνήστε τους γοφούς πίσω προς τη φτέρνα. Εκπνεύστε καθώς πηγαίνετε πίσω· πλάτη ίσια.',
    MAT,
  ),
  ex(
    'band-shoulder-dislocates',
    'mobility',
    'intermediate',
    ['shoulders', 'chest'],
    'Band shoulder pass-throughs',
    'Περάσματα ώμων με λάστιχο',
    'Hold a band wide with straight arms and lift it slowly overhead and behind you, then back to the front. Widen the grip if it pinches and breathe steadily.',
    'Κρατήστε λάστιχο με ανοιχτή λαβή και τεντωμένα χέρια, σηκώστε το αργά πάνω από το κεφάλι και πίσω, μετά ξανά μπροστά. Ανοίξτε τη λαβή αν τσιμπάει και αναπνέετε σταθερά.',
    BAND,
  ),
  ex(
    'cossack-squat',
    'mobility',
    'advanced',
    ['adductors', 'glutes', 'quads', 'hamstrings'],
    'Cossack squat',
    'Κοζάκικα καθίσματα',
    'Stand wide, shift all your weight onto one leg and sit deep over it while the other leg stays straight with toes up. Exhale as you shift, keep the heel down.',
    'Σταθείτε με ανοιχτά πόδια, μεταφέρετε όλο το βάρος στο ένα πόδι και καθίστε βαθιά πάνω του ενώ το άλλο μένει τεντωμένο με τα δάχτυλα πάνω. Εκπνεύστε στη μεταφορά, φτέρνα κάτω.',
  ),
  ex(
    'jefferson-curl',
    'mobility',
    'advanced',
    ['hamstrings', 'back'],
    'Jefferson curl (light)',
    'Jefferson curl (ελαφρύ)',
    'Standing on a step with a very light weight, tuck the chin and roll down one vertebra at a time until the weight passes the toes, then stack back up. Exhale on the way down; never add load quickly.',
    'Όρθιοι σε σκαλί με πολύ ελαφρύ βάρος, μαζέψτε το πηγούνι και κυλήστε κάτω σπόνδυλο-σπόνδυλο μέχρι το βάρος να περάσει τα δάχτυλα, μετά ξαναχτίστε προς τα πάνω. Εκπνεύστε στην κάθοδο· μην αυξάνετε ποτέ γρήγορα το βάρος.',
    DUMBBELLS,
  ),
  ex(
    'wall-shoulder-flexion-slides',
    'mobility',
    'advanced',
    ['shoulders', 'back'],
    'Wall shoulder flexion slides',
    'Ολισθήσεις ώμων στον τοίχο',
    'Back and head against the wall, slide the backs of the forearms up the wall keeping the ribs down and the wrists in contact. Exhale as the arms rise; stop where contact breaks.',
    'Πλάτη και κεφάλι στον τοίχο, σύρετε το πίσω μέρος των πήχεων πάνω στον τοίχο κρατώντας τα πλευρά κάτω και τους καρπούς σε επαφή. Εκπνεύστε καθώς ανεβαίνουν τα χέρια· σταματήστε όπου χάνεται η επαφή.',
  ),
  ex(
    'couch-stretch',
    'mobility',
    'advanced',
    ['quads', 'hip-flexors'],
    'Couch stretch',
    'Διάταση couch',
    'Kneel with one shin up against a wall or couch and the other foot forward, squeeze the glute of the back leg and lift the torso tall. Breathe slowly for 60 seconds per side; back off if the knee hurts.',
    'Γονατίστε με τη μία κνήμη όρθια στον τοίχο ή στον καναπέ και το άλλο πόδι μπροστά, σφίξτε τον γλουτό του πίσω ποδιού και σηκώστε τον κορμό. Αναπνέετε αργά για 60 δευτερόλεπτα ανά πλευρά· υποχωρήστε αν πονάει το γόνατο.',
    MAT,
  ),
  ex(
    'bridge-pose',
    'mobility',
    'advanced',
    ['hip-flexors', 'back', 'shoulders', 'glutes'],
    'Bridge pose',
    'Στάση γέφυρας',
    'Lying on your back with feet close to the hips, press the hips high and interlace the hands beneath you, opening the chest. Breathe slowly for 20–30 seconds and lower one vertebra at a time.',
    'Ξαπλωμένοι ανάσκελα με τα πέλματα κοντά στους γοφούς, σηκώστε τους γοφούς ψηλά και πλέξτε τα χέρια από κάτω, ανοίγοντας το στήθος. Αναπνέετε αργά για 20–30 δευτερόλεπτα και κατεβείτε σπόνδυλο-σπόνδυλο.',
    MAT,
  ),
  ex(
    'legs-up-the-wall',
    'mobility',
    'advanced',
    ['hamstrings', 'back'],
    'Legs up the wall',
    'Πόδια στον τοίχο',
    'Lie on your back with the hips near a wall and the legs resting straight up it, arms relaxed at the sides. Breathe slowly and deeply for 2–5 minutes as a full-body cool-down.',
    'Ξαπλώστε ανάσκελα με τους γοφούς κοντά σε τοίχο και τα πόδια τεντωμένα πάνω του, χέρια χαλαρά στα πλάγια. Αναπνέετε αργά και βαθιά για 2–5 λεπτά ως αποθεραπεία όλου του σώματος.',
    MAT,
  ),
]

/** Every seeded exercise, in catalogue order (home → gym → calisthenics → running → swimming → cycling → mobility). */
export const EXERCISES: readonly ExerciseSeed[] = [
  ...HOME,
  ...GYM,
  ...CALISTHENICS,
  ...RUNNING,
  ...SWIMMING,
  ...CYCLING,
  ...MOBILITY,
]
