// RECIPES SEED — GROUP 3: special patterns (P1.11). Gluten-free baking and bowls, low-FODMAP
// bowls and soups, Whole30 sheet-pan dinners and egg bakes, and large balanced "break-the-fast"
// meals for intermittent fasting. EL + EN on the same row (PLAN.md §1.2); ingredient lines use only
// P1.9 slugs with raw/dry quantities; `diet_slugs` use only P1.10 slugs and follow "suitable for"
// semantics: every diet the dish complies with is tagged, so a diet filter shows everything a
// follower can eat.
//
// Compliance notes the tags rely on (checked mechanically in ../recipes.test.ts):
//   - `gluten-free`: no wheat/barley/rye product; `oats` is NOT tagged GF (the seed's oats are not
//     certified — the diet's own avoided list says so) and `tortilla` is a wheat tortilla.
//   - `low-fodmap`: no onion/garlic/wheat/legumes/high-lactose dairy/high-FODMAP fruit; spring onion
//     is always "green parts only"; hard cheeses, feta and mozzarella in Monash-sized portions.
//   - `whole30`: no grains, legumes, dairy (eggs and ghee excepted), added sugar or alcohol.
//   - `intermittent-fasting`: protein-rich, generous meals that suit a two-meal eating window.
//
// Greek loanwords stay Latin-script in `title_el` only when a Greek speaker writes them that way
// (Whole30); everything else is in Greek script.

import type { RecipeSeed } from '../../types.ts'

export const RECIPES_GROUP3: readonly RecipeSeed[] = [
  // --- Breakfast ---------------------------------------------------------------------------------
  {
    slug: 'buckwheat-banana-pancakes',
    title_el: 'Τηγανίτες φαγόπυρου με μπανάνα',
    title_en: 'Buckwheat pancakes with banana',
    steps_el: [
      'Αλέστε το φαγόπυρο σε μπλέντερ μέχρι να γίνει αλεύρι και ανακατέψτε το με το μπέικιν πάουντερ, την κανέλα και το αλάτι.',
      'Χτυπήστε τα αυγά με το γάλα αμυγδάλου και προσθέστε τα στα στερεά· ανακατέψτε μέχρι να έχετε ένα ομοιογενές χυλό.',
      'Ζεστάνετε λίγο λάδι σε αντικολλητικό τηγάνι και ψήστε τις τηγανίτες 2 λεπτά από κάθε πλευρά, μέχρι να ροδίσουν.',
      'Σερβίρετε με φέτες μπανάνας και λίγο σιρόπι σφενδάμου.',
    ],
    steps_en: [
      'Blitz the buckwheat in a blender until it becomes flour, then mix it with the baking powder, cinnamon and salt.',
      'Whisk the eggs with the almond milk and add to the dry ingredients; stir until you have a smooth batter.',
      'Heat a little oil in a non-stick pan and cook the pancakes for 2 minutes per side until golden.',
      'Serve topped with banana slices and a little maple syrup.',
    ],
    portions: 2,
    prep_min: 20,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'buckwheat',
        quantity: 150,
        unit: 'g',
        note_el: 'αλεσμένο σε αλεύρι',
        note_en: 'ground to flour',
      },
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'almond-milk', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'baking-powder', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'maple-syrup', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: ['gluten-free', 'low-fodmap', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'almond-buckwheat-banana-bread',
    title_el: 'Κέικ μπανάνας με αλεύρι αμυγδάλου και φαγόπυρο',
    title_en: 'Banana bread with almond and buckwheat flour',
    steps_el: [
      'Προθερμάνετε τον φούρνο στους 175°C και στρώστε μια φόρμα κέικ με λαδόκολλα.',
      'Λιώστε τις μπανάνες με πιρούνι και χτυπήστε τες με τα αυγά, το λιωμένο λάδι καρύδας και το σιρόπι σφενδάμου.',
      'Αλέστε το φαγόπυρο σε αλεύρι και ανακατέψτε το με το αλεύρι αμυγδάλου, τη σόδα, την κανέλα και το αλάτι· ενώστε με το μείγμα της μπανάνας και προσθέστε τα καρύδια.',
      'Αδειάστε στη φόρμα και ψήστε 50–55 λεπτά, μέχρι η οδοντογλυφίδα να βγαίνει καθαρή.',
      'Αφήστε να κρυώσει 15 λεπτά πριν το κόψετε σε φέτες.',
    ],
    steps_en: [
      'Preheat the oven to 175°C and line a loaf tin with baking paper.',
      'Mash the bananas with a fork and whisk them with the eggs, melted coconut oil and maple syrup.',
      'Grind the buckwheat to flour and mix it with the almond flour, baking soda, cinnamon and salt; fold into the banana mixture and add the walnuts.',
      'Pour into the tin and bake for 50–55 minutes, until a skewer comes out clean.',
      'Let it cool for 15 minutes before slicing.',
    ],
    portions: 8,
    prep_min: 70,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'banana', quantity: 3, unit: 'piece', note_el: 'ώριμες', note_en: 'ripe' },
      { ingredient_slug: 'egg', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'coconut-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'maple-syrup', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'almond-flour', quantity: 150, unit: 'g' },
      {
        ingredient_slug: 'buckwheat',
        quantity: 100,
        unit: 'g',
        note_el: 'αλεσμένο σε αλεύρι',
        note_en: 'ground to flour',
      },
      { ingredient_slug: 'baking-soda', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'walnuts', quantity: 50, unit: 'g' },
    ],
    diet_slugs: ['gluten-free', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'chia-pudding-coconut-strawberry',
    title_el: 'Πουτίγκα τσία με καρύδα και φράουλες',
    title_en: 'Chia pudding with coconut and strawberries',
    steps_el: [
      'Ανακατέψτε σε βάζο τους σπόρους τσία με το γάλα αμυγδάλου, το γάλα καρύδας, το σιρόπι σφενδάμου και τη βανίλια.',
      'Ανακατέψτε ξανά μετά από 10 λεπτά για να μη σβολιάσει και αφήστε στο ψυγείο τουλάχιστον 4 ώρες ή όλη νύχτα.',
      'Σερβίρετε με κομμένες φράουλες και ακτινίδιο.',
    ],
    steps_en: [
      'In a jar, stir the chia seeds with the almond milk, coconut milk, maple syrup and vanilla.',
      'Stir again after 10 minutes so it does not clump, then chill for at least 4 hours or overnight.',
      'Serve topped with sliced strawberries and kiwi.',
    ],
    portions: 2,
    prep_min: 10,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chia-seeds', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'almond-milk', quantity: 300, unit: 'ml' },
      { ingredient_slug: 'coconut-milk', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'maple-syrup', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'vanilla-extract', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'strawberry', quantity: 150, unit: 'g' },
      { ingredient_slug: 'kiwi', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: [
      'gluten-free',
      'low-fodmap',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'paleo',
    ],
  },
  {
    slug: 'overnight-oats-peanut-banana',
    title_el: 'Βρώμη ολονυκτίας με φυστικοβούτυρο και μπανάνα',
    title_en: 'Overnight oats with peanut butter and banana',
    steps_el: [
      'Ανακατέψτε σε βάζο τη βρώμη, τους σπόρους τσία, την κανέλα, το γάλα αμυγδάλου και το σιρόπι σφενδάμου.',
      'Κλείστε και αφήστε στο ψυγείο όλη νύχτα.',
      'Το πρωί προσθέστε το φυστικοβούτυρο και σερβίρετε με φέτες μπανάνας.',
    ],
    steps_en: [
      'In a jar, combine the oats, chia seeds, cinnamon, almond milk and maple syrup.',
      'Seal and leave in the fridge overnight.',
      'In the morning stir in the peanut butter and top with banana slices.',
    ],
    portions: 2,
    prep_min: 10,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'oats', quantity: 80, unit: 'g' },
      { ingredient_slug: 'chia-seeds', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'almond-milk', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'maple-syrup', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'peanut-butter', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece', note_el: 'σφιχτή', note_en: 'firm' },
    ],
    diet_slugs: ['low-fodmap', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian', 'dash'],
  },
  {
    slug: 'sweet-potato-hash-eggs',
    title_el: 'Γλυκοπατάτα τηγανιού με αυγά και σπανάκι',
    title_en: 'Sweet potato hash with eggs and spinach',
    steps_el: [
      'Κόψτε τη γλυκοπατάτα και την πιπεριά σε μικρούς κύβους.',
      'Σοτάρετε τη γλυκοπατάτα στο ελαιόλαδο σε μέτρια φωτιά για 10 λεπτά, προσθέστε την πιπεριά, την πάπρικα, το αλάτι και το πιπέρι και μαγειρέψτε 5 λεπτά ακόμη.',
      'Προσθέστε το σπανάκι και το πράσινο μέρος του φρέσκου κρεμμυδιού και ανακατέψτε μέχρι να μαραθεί.',
      'Ανοίξτε τέσσερις λακκούβες, σπάστε μέσα τα αυγά, σκεπάστε και μαγειρέψτε 4–5 λεπτά μέχρι να πήξουν τα ασπράδια.',
    ],
    steps_en: [
      'Dice the sweet potato and the pepper into small cubes.',
      'Sauté the sweet potato in the olive oil over medium heat for 10 minutes, add the pepper, paprika, salt and pepper and cook 5 minutes more.',
      'Add the spinach and the green part of the spring onion and stir until wilted.',
      'Make four wells, crack in the eggs, cover and cook 4–5 minutes until the whites are set.',
    ],
    portions: 2,
    prep_min: 30,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'sweet-potato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'bell-pepper', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'spinach', quantity: 100, unit: 'g' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'egg', quantity: 4, unit: 'piece' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'intermittent-fasting',
    ],
  },
  {
    slug: 'baked-egg-casserole-zucchini-spinach',
    title_el: 'Αυγά φούρνου με κολοκυθάκι, ντοματίνια και σπανάκι',
    title_en: 'Baked egg casserole with zucchini, cherry tomatoes and spinach',
    steps_el: [
      'Προθερμάνετε τον φούρνο στους 180°C και λαδώστε ένα πυρίμαχο σκεύος.',
      'Τρίψτε το κολοκυθάκι, στύψτε το καλά και απλώστε το στο σκεύος μαζί με το σπανάκι, τα ντοματίνια κομμένα στη μέση και το πράσινο μέρος του φρέσκου κρεμμυδιού.',
      'Χτυπήστε τα αυγά με το ελαιόλαδο, τη ρίγανη, το αλάτι και το πιπέρι και περιχύστε τα λαχανικά.',
      'Ψήστε 25–30 λεπτά μέχρι να πήξει και να ροδίσει η επιφάνεια· κόψτε σε τετράγωνα.',
    ],
    steps_en: [
      'Preheat the oven to 180°C and oil a baking dish.',
      'Grate the zucchini, squeeze it well and spread it in the dish with the spinach, the halved cherry tomatoes and the green part of the spring onion.',
      'Whisk the eggs with the olive oil, oregano, salt and pepper and pour over the vegetables.',
      'Bake 25–30 minutes until set and golden on top; cut into squares.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spinach', quantity: 150, unit: 'g' },
      { ingredient_slug: 'cherry-tomato', quantity: 150, unit: 'g' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'egg', quantity: 8, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'low-fodmap',
      'low-carb',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
    ],
  },
  {
    slug: 'quinoa-porridge-orange-walnuts',
    title_el: 'Χυλός κινόα με πορτοκάλι, κανέλα και καρύδια',
    title_en: 'Quinoa porridge with orange, cinnamon and walnuts',
    steps_el: [
      'Ξεπλύνετε καλά την κινόα και βάλτε τη σε κατσαρόλα με το γάλα αμυγδάλου, την κανέλα και τη βανίλια.',
      'Σιγοβράστε 15–18 λεπτά ανακατεύοντας πού και πού, μέχρι να απορροφηθεί το υγρό και να ανοίξουν οι σπόροι.',
      'Γλυκάνετε με το σιρόπι σφενδάμου και σερβίρετε με φέτες πορτοκαλιού και χοντροκομμένα καρύδια.',
    ],
    steps_en: [
      'Rinse the quinoa well and put it in a saucepan with the almond milk, cinnamon and vanilla.',
      'Simmer 15–18 minutes, stirring now and then, until the liquid is absorbed and the grains have opened.',
      'Sweeten with the maple syrup and serve with orange segments and roughly chopped walnuts.',
    ],
    portions: 2,
    prep_min: 25,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'quinoa', quantity: 150, unit: 'g' },
      { ingredient_slug: 'almond-milk', quantity: 400, unit: 'ml' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'vanilla-extract', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'maple-syrup', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'orange', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'walnuts', quantity: 40, unit: 'g' },
    ],
    diet_slugs: [
      'gluten-free',
      'low-fodmap',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'dash',
    ],
  },
  {
    slug: 'rice-cakes-smoked-salmon-egg',
    title_el: 'Ρυζογκοφρέτες με καπνιστό σολομό, αυγό και ρόκα',
    title_en: 'Rice cakes with smoked salmon, egg and rocket',
    steps_el: [
      'Βράστε τα αυγά 8 λεπτά, κρυώστε τα σε κρύο νερό και κόψτε τα σε φέτες.',
      'Ανακατέψτε τη ρόκα με το ελαιόλαδο, τον χυμό λεμονιού και το πιπέρι.',
      'Μοιράστε τη ρόκα στις ρυζογκοφρέτες, στρώστε τον σολομό και το αυγό και τελειώστε με ψιλοκομμένο άνηθο.',
    ],
    steps_en: [
      'Boil the eggs for 8 minutes, cool them in cold water and slice.',
      'Toss the rocket with the olive oil, lemon juice and pepper.',
      'Divide the rocket over the rice cakes, layer on the salmon and egg and finish with chopped dill.',
    ],
    portions: 2,
    prep_min: 15,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'rocket', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'lemon-juice', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'rice-cakes', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'smoked-salmon', quantity: 100, unit: 'g' },
      { ingredient_slug: 'dill', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: [
      'gluten-free',
      'low-fodmap',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'dash',
    ],
  },
  {
    slug: 'skyr-bowl-kiwi-strawberry',
    title_el: 'Μπολ σκυρ με ακτινίδιο, φράουλες και κολοκυθόσπορους',
    title_en: 'Skyr bowl with kiwi, strawberries and pumpkin seeds',
    steps_el: [
      'Μοιράστε το σκυρ σε δύο μπολ.',
      'Κόψτε το ακτινίδιο και τις φράουλες και απλώστε τα από πάνω.',
      'Πασπαλίστε με κολοκυθόσπορους και σπόρους τσία και περιχύστε με το μέλι.',
    ],
    steps_en: [
      'Divide the skyr between two bowls.',
      'Slice the kiwi and strawberries and arrange them on top.',
      'Sprinkle with pumpkin seeds and chia seeds and drizzle with the honey.',
    ],
    portions: 2,
    prep_min: 5,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'skyr', quantity: 300, unit: 'g' },
      { ingredient_slug: 'kiwi', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'strawberry', quantity: 150, unit: 'g' },
      { ingredient_slug: 'pumpkin-seeds', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'chia-seeds', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'honey', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['gluten-free', 'high-protein', 'vegetarian', 'pescatarian', 'flexitarian', 'dash'],
  },
  {
    slug: 'turkey-spinach-breakfast-patties',
    title_el: 'Μπιφτεκάκια γαλοπούλας με σπανάκι και φασκόμηλο',
    title_en: 'Turkey and spinach breakfast patties',
    steps_el: [
      'Ψιλοκόψτε το σπανάκι και το πράσινο μέρος του φρέσκου κρεμμυδιού και ζυμώστε τα με τον κιμά, το αυγό, το φασκόμηλο, το αλάτι και το πιπέρι.',
      'Πλάστε οκτώ μικρά, επίπεδα μπιφτεκάκια.',
      'Ψήστε τα στο ελαιόλαδο σε μέτρια φωτιά 4–5 λεπτά από κάθε πλευρά, μέχρι να ψηθούν καλά στο κέντρο.',
      'Σερβίρετε με φέτες ντομάτας.',
    ],
    steps_en: [
      'Finely chop the spinach and the green part of the spring onion and knead them into the mince with the egg, sage, salt and pepper.',
      'Shape eight small, flat patties.',
      'Cook them in the olive oil over medium heat 4–5 minutes per side, until cooked through.',
      'Serve with tomato slices.',
    ],
    portions: 4,
    prep_min: 25,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'turkey-mince', quantity: 400, unit: 'g' },
      { ingredient_slug: 'spinach', quantity: 100, unit: 'g' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 0.5,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'egg', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'sage', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'low-fodmap',
      'low-carb',
      'high-protein',
      'flexitarian',
    ],
  },
  {
    slug: 'almond-milk-rice-pudding',
    title_el: 'Ρυζόγαλο με γάλα αμυγδάλου',
    title_en: 'Rice pudding with almond milk',
    steps_el: [
      'Βάλτε το ρύζι με 600 ml από το γάλα αμυγδάλου σε κατσαρόλα και σιγοβράστε 20 λεπτά ανακατεύοντας συχνά.',
      'Διαλύστε το κορν φλάουρ στο υπόλοιπο γάλα, προσθέστε το με τη ζάχαρη και τη βανίλια και μαγειρέψτε 3–4 λεπτά μέχρι να δέσει.',
      'Μοιράστε σε μπολ, πασπαλίστε με κανέλα και αφήστε να κρυώσει.',
    ],
    steps_en: [
      'Put the rice with 600 ml of the almond milk in a saucepan and simmer 20 minutes, stirring often.',
      'Dissolve the cornstarch in the remaining milk, add it with the sugar and vanilla and cook 3–4 minutes until thickened.',
      'Divide into bowls, dust with cinnamon and let cool.',
    ],
    portions: 3,
    prep_min: 35,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'rice', quantity: 120, unit: 'g' },
      { ingredient_slug: 'almond-milk', quantity: 750, unit: 'ml' },
      { ingredient_slug: 'cornstarch', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'sugar', quantity: 6, unit: 'tsp' },
      { ingredient_slug: 'vanilla-extract', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cinnamon', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['gluten-free', 'low-fodmap', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'break-the-fast-egg-avocado-feta-plate',
    title_el: 'Πιάτο «πρώτου γεύματος» με αυγά, αβοκάντο, φέτα και ρυζογκοφρέτες',
    title_en: 'Break-the-fast plate with eggs, avocado, feta and rice cakes',
    steps_el: [
      'Βράστε τα αυγά 8 λεπτά, κρυώστε τα και κόψτε τα στη μέση.',
      'Κόψτε το αβοκάντο και την ντομάτα σε φέτες και βάλτε τα στο πιάτο με τη φέτα, τις ελιές και τις ρυζογκοφρέτες.',
      'Περιχύστε με ελαιόλαδο και πασπαλίστε με ρίγανη.',
    ],
    steps_en: [
      'Boil the eggs for 8 minutes, cool and halve them.',
      'Slice the avocado and tomato and arrange on the plate with the feta, olives and rice cakes.',
      'Drizzle with olive oil and sprinkle with oregano.',
    ],
    portions: 1,
    prep_min: 15,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'egg', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'avocado', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'tomato', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'feta', quantity: 50, unit: 'g' },
      { ingredient_slug: 'kalamata-olives', quantity: 6, unit: 'piece' },
      { ingredient_slug: 'rice-cakes', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'intermittent-fasting',
      'gluten-free',
      'high-protein',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
    ],
  },
  {
    slug: 'buckwheat-chia-seeded-bread',
    title_el: 'Ψωμί φαγόπυρου με τσία και ηλιόσπορους (χωρίς γλουτένη)',
    title_en: 'Buckwheat and chia seeded bread (gluten-free)',
    steps_el: [
      'Αλέστε το φαγόπυρο σε αλεύρι και ανακατέψτε το με το ψύλλιο, τους σπόρους τσία, τους ηλιόσπορους, το μπέικιν πάουντερ και το αλάτι.',
      'Προσθέστε το νερό, το ελαιόλαδο και το ξίδι, ανακατέψτε καλά και αφήστε 10 λεπτά να φουσκώσει το ψύλλιο.',
      'Αδειάστε σε λαδωμένη φόρμα και ψήστε στους 190°C για 55–60 λεπτά.',
      'Αφήστε να κρυώσει εντελώς πριν το κόψετε, αλλιώς θρυμματίζεται.',
    ],
    steps_en: [
      'Grind the buckwheat to flour and mix it with the psyllium, chia seeds, sunflower seeds, baking powder and salt.',
      'Add the water, olive oil and vinegar, mix well and leave 10 minutes for the psyllium to swell.',
      'Pour into an oiled loaf tin and bake at 190°C for 55–60 minutes.',
      'Cool completely before slicing or it will crumble.',
    ],
    portions: 10,
    prep_min: 80,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'buckwheat',
        quantity: 300,
        unit: 'g',
        note_el: 'αλεσμένο σε αλεύρι',
        note_en: 'ground to flour',
      },
      { ingredient_slug: 'psyllium-husk', quantity: 15, unit: 'g' },
      { ingredient_slug: 'chia-seeds', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'sunflower-seeds', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'baking-powder', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 400, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'apple-cider-vinegar', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['gluten-free', 'low-fodmap', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'fruit-salad-coconut-walnuts',
    title_el: 'Φρουτοσαλάτα με καρύδα, καρύδια και δυόσμο',
    title_en: 'Fruit salad with coconut, walnuts and mint',
    steps_el: [
      'Καθαρίστε τα πορτοκάλια και τα ακτινίδια και κόψτε τα σε κομμάτια μαζί με τις φράουλες και την μπανάνα.',
      'Περιχύστε με τον χυμό του λάιμ και ανακατέψτε απαλά.',
      'Πασπαλίστε με την καρύδα, τα καρύδια και ψιλοκομμένο δυόσμο.',
    ],
    steps_en: [
      'Peel the oranges and kiwis and cut them into pieces with the strawberries and banana.',
      'Squeeze over the lime juice and toss gently.',
      'Sprinkle with the coconut, walnuts and chopped mint.',
    ],
    portions: 3,
    prep_min: 15,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'orange', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'kiwi', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'strawberry', quantity: 200, unit: 'g' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece', note_el: 'σφιχτή', note_en: 'firm' },
      { ingredient_slug: 'lime', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'desiccated-coconut', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'walnuts', quantity: 30, unit: 'g' },
      { ingredient_slug: 'mint', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'low-fodmap',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'dash',
    ],
  },

  // --- Lunch -------------------------------------------------------------------------------------
  {
    slug: 'quinoa-tabbouleh',
    title_el: 'Ταμπουλέ με κινόα',
    title_en: 'Quinoa tabbouleh',
    steps_el: [
      'Ξεπλύνετε την κινόα, βράστε τη σε διπλάσιο νερό 15 λεπτά και αφήστε τη να κρυώσει.',
      'Ψιλοκόψτε τον μαϊντανό, τον δυόσμο και το πράσινο μέρος του φρέσκου κρεμμυδιού· κόψτε την ντομάτα και το αγγούρι σε μικρούς κύβους.',
      'Ανακατέψτε όλα τα υλικά με τον χυμό λεμονιού, το ελαιόλαδο, το αλάτι και το πιπέρι και αφήστε 15 λεπτά να δέσουν οι γεύσεις.',
    ],
    steps_en: [
      'Rinse the quinoa, cook it in twice its volume of water for 15 minutes and let it cool.',
      'Finely chop the parsley, mint and the green part of the spring onion; dice the tomato and cucumber.',
      'Toss everything with the lemon juice, olive oil, salt and pepper and leave 15 minutes for the flavours to meld.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'quinoa', quantity: 200, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 2, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 1, unit: 'bunch' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'tomato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'cucumber', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'lemon-juice', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'gluten-free',
      'low-fodmap',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'dash',
    ],
  },
  {
    slug: 'polenta-mushroom-ragout',
    title_el: 'Κρεμώδης πολέντα με ραγού μανιταριών',
    title_en: 'Creamy polenta with mushroom ragout',
    steps_el: [
      'Σοτάρετε το κρεμμύδι και το σκόρδο στο ελαιόλαδο, προσθέστε τα μανιτάρια κομμένα σε φέτες και μαγειρέψτε σε δυνατή φωτιά μέχρι να ροδίσουν.',
      'Ρίξτε τις ντομάτες κονσέρβας, το θυμάρι, το μισό αλάτι και το πιπέρι και σιγοβράστε 15 λεπτά να δέσει η σάλτσα.',
      'Βράστε το νερό με το υπόλοιπο αλάτι, ρίξτε το καλαμποκάλευρο σιγά σιγά ανακατεύοντας και μαγειρέψτε 25–30 λεπτά σε χαμηλή φωτιά.',
      'Αποσύρετε, ανακατέψτε την παρμεζάνα και το βούτυρο μέσα στην πολέντα και σερβίρετε με το ραγού από πάνω.',
    ],
    steps_en: [
      'Sauté the onion and garlic in the olive oil, add the sliced mushrooms and cook over high heat until browned.',
      'Add the canned tomatoes, thyme, half the salt and the pepper and simmer 15 minutes until the sauce thickens.',
      'Bring the water to the boil with the remaining salt, pour in the cornmeal slowly while stirring and cook 25–30 minutes over low heat.',
      'Off the heat, stir the parmesan and butter into the polenta and serve with the ragout on top.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'mushrooms', quantity: 400, unit: 'g' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'thyme', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 800, unit: 'ml' },
      { ingredient_slug: 'cornmeal', quantity: 200, unit: 'g' },
      { ingredient_slug: 'parmesan', quantity: 50, unit: 'g' },
      { ingredient_slug: 'butter', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['gluten-free', 'vegetarian', 'pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'pumpkin-sage-risotto',
    title_el: 'Ριζότο κολοκύθας με φασκόμηλο',
    title_en: 'Pumpkin and sage risotto',
    steps_el: [
      'Κόψτε την κολοκύθα σε μικρούς κύβους και σοτάρετέ τη με το κρεμμύδι στο ελαιόλαδο για 8 λεπτά.',
      'Προσθέστε το ρύζι, ανακατέψτε 1 λεπτό να γυαλίσει και σβήστε με το κρασί.',
      'Ρίχνετε το ζεστό αλατισμένο νερό μία κουτάλα τη φορά, ανακατεύοντας, μέχρι να απορροφηθεί — περίπου 18 λεπτά.',
      'Αποσύρετε και ανακατέψτε το βούτυρο, την παρμεζάνα, το φασκόμηλο και το πιπέρι· αφήστε 2 λεπτά σκεπασμένο πριν σερβίρετε.',
    ],
    steps_en: [
      'Cut the pumpkin into small cubes and sauté it with the onion in the olive oil for 8 minutes.',
      'Add the rice, stir 1 minute until glossy and deglaze with the wine.',
      'Add the hot salted water a ladle at a time, stirring, until absorbed — about 18 minutes.',
      'Off the heat, stir in the butter, parmesan, sage and pepper; rest covered 2 minutes before serving.',
    ],
    portions: 4,
    prep_min: 45,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'pumpkin', quantity: 500, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'arborio-rice', quantity: 300, unit: 'g' },
      { ingredient_slug: 'white-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml', note_el: 'ζεστό', note_en: 'hot' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'butter', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'parmesan', quantity: 60, unit: 'g' },
      { ingredient_slug: 'sage', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'gluten-free',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'intermittent-fasting',
    ],
  },
  {
    slug: 'lemon-chicken-rice-bowl',
    title_el: 'Μπολ με λεμονάτο κοτόπουλο, ρύζι μπασμάτι και καρότο',
    title_en: 'Lemon chicken and basmati rice bowl with carrot',
    steps_el: [
      'Μαρινάρετε το κοτόπουλο κομμένο σε κομμάτια με τον χυμό και το ξύσμα του λεμονιού, το τριμμένο τζίντζερ, τη ρίγανη, το αλάτι και το πιπέρι για 15 λεπτά.',
      'Βράστε το ρύζι μπασμάτι σύμφωνα με τις οδηγίες και κρατήστε το ζεστό.',
      'Ψήστε το κοτόπουλο στο ελαιόλαδο σε δυνατή φωτιά 6–8 λεπτά μέχρι να ροδίσει και να ψηθεί.',
      'Μοιράστε το ρύζι σε μπολ, προσθέστε το κοτόπουλο, το τριμμένο καρότο, το αγγούρι σε φέτες και το πράσινο μέρος του φρέσκου κρεμμυδιού.',
    ],
    steps_en: [
      'Marinate the chicken, cut into chunks, with the lemon juice and zest, grated ginger, oregano, salt and pepper for 15 minutes.',
      'Cook the basmati rice according to the packet and keep warm.',
      'Sear the chicken in the olive oil over high heat 6–8 minutes until golden and cooked through.',
      'Divide the rice between bowls, add the chicken, grated carrot, sliced cucumber and the green part of the spring onion.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chicken-breast', quantity: 400, unit: 'g' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'ginger', quantity: 10, unit: 'g' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'basmati-rice', quantity: 250, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'cucumber', quantity: 0.5, unit: 'piece' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
      'dash',
    ],
  },
  {
    slug: 'quinoa-roasted-vegetable-feta-bowl',
    title_el: 'Μπολ κινόα με ψητά λαχανικά, φέτα και κολοκυθόσπορους',
    title_en: 'Quinoa bowl with roasted vegetables, feta and pumpkin seeds',
    steps_el: [
      'Κόψτε τα καρότα, το κολοκυθάκι και την πιπεριά σε κομμάτια, ανακατέψτε με 2 κουταλιές ελαιόλαδο, τη ρίγανη, το αλάτι και το πιπέρι και ψήστε στους 200°C για 25 λεπτά.',
      'Στο μεταξύ ξεπλύνετε και βράστε την κινόα 15 λεπτά σε διπλάσιο νερό.',
      'Μοιράστε την κινόα σε μπολ, προσθέστε τα ψητά λαχανικά, θρυμματίστε τη φέτα από πάνω και πασπαλίστε με κολοκυθόσπορους και το πράσινο μέρος του φρέσκου κρεμμυδιού.',
      'Περιχύστε με το υπόλοιπο ελαιόλαδο και τον χυμό λεμονιού.',
    ],
    steps_en: [
      'Cut the carrots, zucchini and pepper into chunks, toss with 2 tablespoons of olive oil, the oregano, salt and pepper and roast at 200°C for 25 minutes.',
      'Meanwhile rinse and cook the quinoa 15 minutes in twice its volume of water.',
      'Divide the quinoa between bowls, add the roasted vegetables, crumble the feta on top and sprinkle with pumpkin seeds and the green part of the spring onion.',
      'Drizzle with the remaining olive oil and the lemon juice.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'carrot', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      {
        ingredient_slug: 'bell-pepper',
        quantity: 1,
        unit: 'piece',
        note_el: 'κόκκινη',
        note_en: 'red',
      },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'quinoa', quantity: 200, unit: 'g' },
      { ingredient_slug: 'feta', quantity: 100, unit: 'g' },
      { ingredient_slug: 'pumpkin-seeds', quantity: 3, unit: 'tbsp' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'lemon-juice', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
    ],
  },
  {
    slug: 'tuna-potato-green-bean-salad',
    title_el: 'Σαλάτα με τόνο, πατάτες, φασολάκια και αυγό',
    title_en: 'Tuna, potato and green bean salad with egg',
    steps_el: [
      'Βράστε τις πατάτες με τη φλούδα 20 λεπτά· τα τελευταία 6 λεπτά προσθέστε τα φασολάκια και, σε ξεχωριστή κατσαρόλα, βράστε τα αυγά 8 λεπτά.',
      'Κόψτε τις πατάτες σε κομμάτια, τα ντοματίνια στη μέση, το κρεμμύδι σε λεπτές φέτες και τα αυγά στα τέσσερα.',
      'Χτυπήστε το ελαιόλαδο με το ξίδι, τη μουστάρδα και το πιπέρι.',
      'Ανακατέψτε πατάτες, φασολάκια, ντοματίνια, κρεμμύδι, ελιές και στραγγισμένο τόνο με τη σάλτσα· βάλτε τα αυγά από πάνω και πασπαλίστε με μαϊντανό.',
    ],
    steps_en: [
      'Boil the potatoes in their skins for 20 minutes; add the green beans for the last 6 minutes and, in a separate pan, boil the eggs for 8 minutes.',
      'Cut the potatoes into chunks, halve the cherry tomatoes, thinly slice the onion and quarter the eggs.',
      'Whisk the olive oil with the vinegar, mustard and pepper.',
      'Toss the potatoes, beans, tomatoes, onion, olives and drained tuna with the dressing; top with the eggs and sprinkle with parsley.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'green-beans', quantity: 200, unit: 'g' },
      { ingredient_slug: 'egg', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'cherry-tomato', quantity: 200, unit: 'g' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'mustard', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'kalamata-olives', quantity: 16, unit: 'piece' },
      {
        ingredient_slug: 'canned-tuna',
        quantity: 300,
        unit: 'g',
        note_el: 'σε νερό, στραγγισμένος',
        note_en: 'in water, drained',
      },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: [
      'whole30',
      'gluten-free',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'high-protein',
      'intermittent-fasting',
    ],
  },
  {
    slug: 'chicken-avocado-orange-salad',
    title_el: 'Σαλάτα με κοτόπουλο, αβοκάντο, πορτοκάλι και καρύδια',
    title_en: 'Chicken, avocado and orange salad with walnuts',
    steps_el: [
      'Αλατοπιπερώστε το κοτόπουλο και ψήστε το σε αντικολλητικό τηγάνι με 1 κουταλιά ελαιόλαδο 6–7 λεπτά από κάθε πλευρά· αφήστε το 5 λεπτά και κόψτε το σε φέτες.',
      'Χτυπήστε το υπόλοιπο ελαιόλαδο με τον χυμό λεμονιού και τη μουστάρδα.',
      'Στρώστε το μαρούλι σε πιατέλα με τις φέτες πορτοκαλιού, το αβοκάντο, το κρεμμύδι και το κοτόπουλο· περιχύστε με τη σάλτσα και πασπαλίστε με καρύδια.',
    ],
    steps_en: [
      'Season the chicken and cook it in a non-stick pan with 1 tablespoon of olive oil 6–7 minutes per side; rest 5 minutes and slice.',
      'Whisk the remaining olive oil with the lemon juice and mustard.',
      'Lay the lettuce on a platter with the orange segments, avocado, onion and chicken; drizzle with the dressing and scatter the walnuts over.',
    ],
    portions: 4,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chicken-breast', quantity: 400, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'lemon-juice', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'mustard', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'lettuce', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'orange', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'avocado', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'walnuts', quantity: 40, unit: 'g' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'low-carb',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
      'mediterranean',
      'dash',
    ],
  },
  {
    slug: 'socca-roasted-peppers-rocket',
    title_el: 'Σόκα (τηγανίτα ρεβιθάλευρου) με ψητές πιπεριές και ρόκα',
    title_en: 'Socca (chickpea flour flatbread) with roasted peppers and rocket',
    steps_el: [
      'Χτυπήστε το ρεβιθάλευρο με το νερό, 1 κουταλιά ελαιόλαδο, το δεντρολίβανο και το αλάτι και αφήστε τον χυλό 30 λεπτά.',
      'Ζεστάνετε 1 κουταλιά ελαιόλαδο σε τηγάνι που μπαίνει στον φούρνο, ρίξτε τον χυλό και ψήστε στους 230°C για 12–15 λεπτά μέχρι να ροδίσουν οι άκρες.',
      'Κόψτε σε κομμάτια και σερβίρετε με τις ψητές πιπεριές, τη ρόκα, τις ελιές, το υπόλοιπο ελαιόλαδο και τον χυμό λεμονιού.',
    ],
    steps_en: [
      'Whisk the chickpea flour with the water, 1 tablespoon of olive oil, the rosemary and salt and rest the batter 30 minutes.',
      'Heat 1 tablespoon of olive oil in an ovenproof pan, pour in the batter and bake at 230°C for 12–15 minutes until the edges are golden.',
      'Cut into wedges and serve with the roasted peppers, rocket, olives, the remaining olive oil and the lemon juice.',
    ],
    portions: 3,
    prep_min: 55,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chickpea-flour', quantity: 200, unit: 'g' },
      { ingredient_slug: 'water', quantity: 300, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'rosemary', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'roasted-red-peppers', quantity: 150, unit: 'g' },
      { ingredient_slug: 'rocket', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'kalamata-olives', quantity: 12, unit: 'piece' },
      { ingredient_slug: 'lemon-juice', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: [
      'gluten-free',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
    ],
  },
  {
    slug: 'buckwheat-beetroot-walnut-salad',
    title_el: 'Σαλάτα φαγόπυρου με ψητό παντζάρι, καρύδια και φέτα',
    title_en: 'Buckwheat salad with roasted beetroot, walnuts and feta',
    steps_el: [
      'Τυλίξτε τα παντζάρια σε αλουμινόχαρτο και ψήστε στους 200°C για 45 λεπτά· ξεφλουδίστε και κόψτε σε κύβους.',
      'Βράστε το φαγόπυρο σε αλατισμένο νερό 10–12 λεπτά, στραγγίστε και αφήστε να κρυώσει.',
      'Ανακατέψτε το φαγόπυρο με το παντζάρι, το κρεμμύδι σε λεπτές φέτες, τη ρόκα και τα καρύδια.',
      'Περιχύστε με ελαιόλαδο και βαλσάμικο, πιπερώστε και θρυμματίστε τη φέτα από πάνω.',
    ],
    steps_en: [
      'Wrap the beetroots in foil and roast at 200°C for 45 minutes; peel and dice.',
      'Cook the buckwheat in salted water 10–12 minutes, drain and let cool.',
      'Toss the buckwheat with the beetroot, thinly sliced onion, rocket and walnuts.',
      'Dress with olive oil and balsamic, season with pepper and crumble the feta over.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beetroot', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'buckwheat', quantity: 200, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'rocket', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'walnuts', quantity: 50, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'balsamic-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'feta', quantity: 100, unit: 'g' },
    ],
    diet_slugs: ['gluten-free', 'vegetarian', 'pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'carrot-ginger-rice-soup',
    title_el: 'Σούπα καρότου με τζίντζερ, ρύζι και γάλα καρύδας',
    title_en: 'Carrot, ginger and rice soup with coconut milk',
    steps_el: [
      'Σοτάρετε το πράσινο μέρος του φρέσκου κρεμμυδιού και το τριμμένο τζίντζερ στο ελαιόλαδο για 2 λεπτά.',
      'Προσθέστε τα καρότα σε ροδέλες, το ρύζι, τον κουρκουμά, το αλάτι και το νερό και σιγοβράστε 25 λεπτά μέχρι να μαλακώσουν.',
      'Πολτοποιήστε με ραβδομπλέντερ, προσθέστε το γάλα καρύδας και τον χυμό λεμονιού και ζεστάνετε ξανά.',
      'Σερβίρετε με πιπέρι και ψιλοκομμένο κόλιανδρο.',
    ],
    steps_en: [
      'Sauté the green part of the spring onion and the grated ginger in the olive oil for 2 minutes.',
      'Add the sliced carrots, rice, turmeric, salt and water and simmer 25 minutes until soft.',
      'Blend with a stick blender, add the coconut milk and lemon juice and reheat.',
      'Serve with pepper and chopped coriander.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'ginger', quantity: 20, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'carrot', quantity: 6, unit: 'piece' },
      { ingredient_slug: 'rice', quantity: 80, unit: 'g' },
      { ingredient_slug: 'turmeric', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 1200, unit: 'ml' },
      { ingredient_slug: 'coconut-milk', quantity: 150, unit: 'ml' },
      { ingredient_slug: 'lemon-juice', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'coriander', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'dash',
    ],
  },
  {
    slug: 'rice-noodle-tofu-peanut-salad',
    title_el: 'Σαλάτα με ρυζομακάρονα, τόφου, αγγούρι και φιστίκια',
    title_en: 'Rice noodle salad with tofu, cucumber and peanuts',
    steps_el: [
      'Κόψτε το τόφου σε κύβους, στεγνώστε το καλά και ψήστε το στο ελαιόλαδο μέχρι να ροδίσει από όλες τις πλευρές.',
      'Βράστε τα ρυζομακάρονα σύμφωνα με τις οδηγίες, ξεπλύνετε με κρύο νερό και στραγγίστε.',
      'Χτυπήστε τον χυμό του λάιμ με το σησαμέλαιο, το σιρόπι σφενδάμου, το τριμμένο τζίντζερ και το αλάτι.',
      'Ανακατέψτε τα ρυζομακάρονα με το αγγούρι και το καρότο σε λεπτές λωρίδες, το πράσινο μέρος του φρέσκου κρεμμυδιού και τη σάλτσα· προσθέστε το τόφου, τα φιστίκια και τον κόλιανδρο.',
    ],
    steps_en: [
      'Cube the tofu, pat it very dry and fry in the olive oil until golden on all sides.',
      'Cook the rice noodles according to the packet, rinse under cold water and drain.',
      'Whisk the lime juice with the sesame oil, maple syrup, grated ginger and salt.',
      'Toss the noodles with the cucumber and carrot cut into thin strips, the green part of the spring onion and the dressing; add the tofu, peanuts and coriander.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'tofu', quantity: 300, unit: 'g', note_el: 'σκληρό', note_en: 'firm' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'rice-noodles', quantity: 200, unit: 'g' },
      { ingredient_slug: 'lime', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'sesame-oil', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'maple-syrup', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'ginger', quantity: 10, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'cucumber', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
      { ingredient_slug: 'peanuts', quantity: 50, unit: 'g' },
    ],
    diet_slugs: ['low-fodmap', 'gluten-free', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'quinoa-black-bean-sweet-potato-bowl',
    title_el: 'Μπολ κινόα με μαύρα φασόλια, ψητή γλυκοπατάτα και αβοκάντο',
    title_en: 'Quinoa, black bean and roasted sweet potato bowl with avocado',
    steps_el: [
      'Μουλιάστε τα μαύρα φασόλια από το προηγούμενο βράδυ και βράστε τα 60–75 λεπτά μέχρι να μαλακώσουν· στραγγίστε.',
      'Κόψτε τη γλυκοπατάτα σε κύβους, ανακατέψτε με 1 κουταλιά ελαιόλαδο, το κύμινο, την πάπρικα και το αλάτι και ψήστε στους 200°C για 25 λεπτά.',
      'Ξεπλύνετε και βράστε την κινόα 15 λεπτά σε διπλάσιο νερό.',
      'Μοιράστε την κινόα σε μπολ με τα φασόλια, τη γλυκοπατάτα, τα ντοματίνια, το κρεμμύδι και το αβοκάντο· περιχύστε με το υπόλοιπο ελαιόλαδο και τον χυμό του λάιμ και πασπαλίστε με κόλιανδρο.',
    ],
    steps_en: [
      'Soak the black beans overnight and boil 60–75 minutes until tender; drain.',
      'Dice the sweet potato, toss with 1 tablespoon of olive oil, the cumin, paprika and salt and roast at 200°C for 25 minutes.',
      'Rinse and cook the quinoa 15 minutes in twice its volume of water.',
      'Divide the quinoa between bowls with the beans, sweet potato, cherry tomatoes, onion and avocado; drizzle with the remaining olive oil and lime juice and scatter with coriander.',
    ],
    portions: 4,
    prep_min: 90,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'black-beans', quantity: 150, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'sweet-potato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'quinoa', quantity: 200, unit: 'g' },
      { ingredient_slug: 'cherry-tomato', quantity: 200, unit: 'g' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'avocado', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'lime', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'coriander', quantity: 1, unit: 'bunch' },
    ],
    diet_slugs: [
      'gluten-free',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'intermittent-fasting',
      'dash',
    ],
  },
  {
    slug: 'lentil-pasta-tomato-spinach-feta',
    title_el: 'Ζυμαρικά φακής με σάλτσα ντομάτας, σπανάκι και φέτα',
    title_en: 'Lentil pasta with tomato sauce, spinach and feta',
    steps_el: [
      'Σοτάρετε το κρεμμύδι και το σκόρδο στο ελαιόλαδο, προσθέστε τις ντομάτες, τη ρίγανη, τις νιφάδες τσίλι, το αλάτι και το πιπέρι και σιγοβράστε 15 λεπτά.',
      'Βράστε τα ζυμαρικά φακής 1 λεπτό λιγότερο από τις οδηγίες και στραγγίστε.',
      'Ρίξτε το σπανάκι στη σάλτσα να μαραθεί, προσθέστε τα ζυμαρικά και ανακατέψτε.',
      'Σερβίρετε με θρυμματισμένη φέτα και φύλλα βασιλικού.',
    ],
    steps_en: [
      'Sauté the onion and garlic in the olive oil, add the tomatoes, oregano, chilli flakes, salt and pepper and simmer 15 minutes.',
      'Cook the lentil pasta 1 minute short of the packet time and drain.',
      'Wilt the spinach into the sauce, add the pasta and toss.',
      'Serve with crumbled feta and basil leaves.',
    ],
    portions: 4,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'lentil-pasta', quantity: 300, unit: 'g' },
      { ingredient_slug: 'spinach', quantity: 150, unit: 'g' },
      { ingredient_slug: 'feta', quantity: 100, unit: 'g' },
      { ingredient_slug: 'basil', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: [
      'gluten-free',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'high-protein',
      'intermittent-fasting',
    ],
  },

  // --- Dinner ------------------------------------------------------------------------------------
  {
    slug: 'sheet-pan-chicken-sweet-potato-broccoli',
    title_el: 'Κοτόπουλο ταψιού με γλυκοπατάτα, μπρόκολο και λεμόνι',
    title_en: 'Sheet-pan chicken with sweet potato, broccoli and lemon',
    steps_el: [
      'Προθερμάνετε τον φούρνο στους 210°C. Ανακατέψτε τα μπούτια με 2 κουταλιές ελαιόλαδο, την πάπρικα, τη ρίγανη, το λιωμένο σκόρδο, το αλάτι και το πιπέρι.',
      'Κόψτε τη γλυκοπατάτα σε κύβους και το κρεμμύδι σε φέτες, ανακατέψτε με το υπόλοιπο ελαιόλαδο και απλώστε τα σε ταψί μαζί με το κοτόπουλο· ψήστε 25 λεπτά.',
      'Προσθέστε το μπρόκολο σε μπουκετάκια και τις φέτες λεμονιού, ανακατέψτε και ψήστε 15–20 λεπτά ακόμη μέχρι το κοτόπουλο να ροδίσει και η γλυκοπατάτα να μαλακώσει.',
    ],
    steps_en: [
      'Preheat the oven to 210°C. Toss the thighs with 2 tablespoons of olive oil, the paprika, oregano, crushed garlic, salt and pepper.',
      'Dice the sweet potato and slice the onion, toss with the remaining olive oil and spread on a tray with the chicken; roast 25 minutes.',
      'Add the broccoli florets and lemon slices, toss and roast 15–20 minutes more until the chicken is golden and the sweet potato tender.',
    ],
    portions: 4,
    prep_min: 55,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'chicken-thigh',
        quantity: 800,
        unit: 'g',
        note_el: 'με κόκαλο',
        note_en: 'bone-in',
      },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'sweet-potato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'broccoli', quantity: 400, unit: 'g' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
    ],
  },
  {
    slug: 'sheet-pan-salmon-asparagus-potatoes',
    title_el: 'Σολομός ταψιού με σπαράγγια, πατάτες και άνηθο',
    title_en: 'Sheet-pan salmon with asparagus, potatoes and dill',
    steps_el: [
      'Κόψτε τις πατάτες σε κομμάτια, ανακατέψτε με 2 κουταλιές ελαιόλαδο, το μισό αλάτι και πιπέρι και ψήστε στους 210°C για 25 λεπτά.',
      'Προσθέστε στο ταψί τον σολομό και τα σπαράγγια, περιχύστε με το υπόλοιπο ελαιόλαδο, το λιωμένο σκόρδο, το υπόλοιπο αλάτι και πιπέρι και φέτες λεμονιού.',
      'Ψήστε 12–14 λεπτά ακόμη, μέχρι ο σολομός να ξεφλουδίζει με το πιρούνι, και πασπαλίστε με ψιλοκομμένο άνηθο.',
    ],
    steps_en: [
      'Cut the potatoes into chunks, toss with 2 tablespoons of olive oil and half the salt and pepper and roast at 210°C for 25 minutes.',
      'Add the salmon and asparagus to the tray, drizzle with the remaining olive oil, crushed garlic, the rest of the salt and pepper and lemon slices.',
      'Roast 12–14 minutes more, until the salmon flakes with a fork, and scatter with chopped dill.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salmon', quantity: 600, unit: 'g', note_el: 'φιλέτο', note_en: 'fillet' },
      { ingredient_slug: 'asparagus', quantity: 400, unit: 'g' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
    ],
    diet_slugs: [
      'whole30',
      'gluten-free',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'high-protein',
      'intermittent-fasting',
    ],
  },
  {
    slug: 'pork-tenderloin-roasted-carrots-potatoes',
    title_el: 'Ψαρονέφρι με ψητά καρότα, πατάτες και δεντρολίβανο',
    title_en: 'Pork tenderloin with roasted carrots, potatoes and rosemary',
    steps_el: [
      'Κόψτε τα καρότα και τις πατάτες σε κομμάτια, ανακατέψτε με 2 κουταλιές ελαιόλαδο, το δεντρολίβανο, το μισό αλάτι και πιπέρι και ψήστε στους 200°C για 20 λεπτά.',
      'Αλείψτε το ψαρονέφρι με τη μουστάρδα, το υπόλοιπο αλάτι και πιπέρι και θωρακίστε το στο υπόλοιπο ελαιόλαδο 2 λεπτά από κάθε πλευρά.',
      'Βάλτε το ψαρονέφρι πάνω στα λαχανικά και ψήστε 18–20 λεπτά· αφήστε το 5 λεπτά πριν το κόψετε.',
      'Σερβίρετε με χυμό λεμονιού και το πράσινο μέρος του φρέσκου κρεμμυδιού ψιλοκομμένο.',
    ],
    steps_en: [
      'Cut the carrots and potatoes into chunks, toss with 2 tablespoons of olive oil, the rosemary and half the salt and pepper and roast at 200°C for 20 minutes.',
      'Rub the tenderloin with the mustard and the rest of the salt and pepper and sear it in the remaining olive oil 2 minutes per side.',
      'Set the tenderloin on top of the vegetables and roast 18–20 minutes; rest 5 minutes before slicing.',
      'Serve with a squeeze of lemon and the chopped green part of the spring onion.',
    ],
    portions: 4,
    prep_min: 55,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'carrot', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'rosemary', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'pork-tenderloin', quantity: 600, unit: 'g' },
      { ingredient_slug: 'mustard', quantity: 3, unit: 'tsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 0.5,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
    ],
    diet_slugs: [
      'whole30',
      'low-fodmap',
      'gluten-free',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
    ],
  },
  {
    slug: 'beef-zucchini-ginger-stir-fry-rice',
    title_el: 'Μοσχάρι σοτέ με κολοκυθάκι, τζίντζερ και ρύζι',
    title_en: 'Beef and zucchini stir-fry with ginger and rice',
    steps_el: [
      'Βράστε το ρύζι σύμφωνα με τις οδηγίες.',
      'Κόψτε το μοσχάρι σε λεπτές λωρίδες και αλατοπιπερώστε· ζεστάνετε το ελαιόλαδο σε βαθύ τηγάνι σε πολύ δυνατή φωτιά και σοτάρετε το κρέας 2–3 λεπτά σε δόσεις· βγάλτε το.',
      'Στο ίδιο τηγάνι σοτάρετε το κολοκυθάκι, την πιπεριά, το καρότο σε λεπτές φέτες και το τριμμένο τζίντζερ 4 λεπτά.',
      'Επιστρέψτε το κρέας, προσθέστε το σησαμέλαιο, τις νιφάδες τσίλι και το πράσινο μέρος του φρέσκου κρεμμυδιού, ανακατέψτε 1 λεπτό και σερβίρετε πάνω στο ρύζι.',
    ],
    steps_en: [
      'Cook the rice according to the packet.',
      'Slice the beef into thin strips and season; heat the olive oil in a deep pan over very high heat and sear the beef 2–3 minutes in batches; remove.',
      'In the same pan stir-fry the zucchini, pepper, thinly sliced carrot and grated ginger for 4 minutes.',
      'Return the beef, add the sesame oil, chilli flakes and the green part of the spring onion, toss 1 minute and serve over the rice.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'rice', quantity: 250, unit: 'g' },
      { ingredient_slug: 'beef-steak', quantity: 500, unit: 'g' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      {
        ingredient_slug: 'bell-pepper',
        quantity: 1,
        unit: 'piece',
        note_el: 'κόκκινη',
        note_en: 'red',
      },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'ginger', quantity: 20, unit: 'g' },
      { ingredient_slug: 'sesame-oil', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.5, unit: 'tsp' },
      {
        ingredient_slug: 'spring-onion',
        quantity: 1,
        unit: 'bunch',
        note_el: 'μόνο το πράσινο μέρος',
        note_en: 'green parts only',
      },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
    ],
  },
  {
    slug: 'shrimp-lemon-risotto',
    title_el: 'Ριζότο με γαρίδες, λεμόνι και μαϊντανό',
    title_en: 'Shrimp risotto with lemon and parsley',
    steps_el: [
      'Σοτάρετε το κρεμμύδι και το σκόρδο σε 2 κουταλιές ελαιόλαδο μέχρι να μαλακώσουν, προσθέστε το ρύζι και ανακατέψτε 1 λεπτό.',
      'Σβήστε με το κρασί και ρίχνετε το ζεστό αλατισμένο νερό μία κουτάλα τη φορά, ανακατεύοντας, για περίπου 16 λεπτά.',
      'Σοτάρετε τις γαρίδες στο υπόλοιπο ελαιόλαδο 2 λεπτά από κάθε πλευρά με το πιπέρι.',
      'Ανακατέψτε στο ριζότο το βούτυρο, τον χυμό και το ξύσμα του λεμονιού και τον μαϊντανό· σερβίρετε με τις γαρίδες από πάνω.',
    ],
    steps_en: [
      'Sauté the onion and garlic in 2 tablespoons of olive oil until soft, add the rice and stir 1 minute.',
      'Deglaze with the wine and add the hot salted water a ladle at a time, stirring, for about 16 minutes.',
      'Sear the shrimp in the remaining olive oil 2 minutes per side with the pepper.',
      'Stir the butter, lemon juice and zest and parsley into the risotto; serve with the shrimp on top.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'arborio-rice', quantity: 300, unit: 'g' },
      { ingredient_slug: 'white-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml', note_el: 'ζεστό', note_en: 'hot' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      {
        ingredient_slug: 'shrimp',
        quantity: 400,
        unit: 'g',
        note_el: 'καθαρισμένες',
        note_en: 'peeled',
      },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'butter', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
    ],
    diet_slugs: [
      'gluten-free',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'high-protein',
      'intermittent-fasting',
    ],
  },
  {
    slug: 'chicken-coconut-curry-rice',
    title_el: 'Κάρι κοτόπουλου με γάλα καρύδας, σπανάκι και ρύζι μπασμάτι',
    title_en: 'Chicken coconut curry with spinach and basmati rice',
    steps_el: [
      'Σοτάρετε το κρεμμύδι, το σκόρδο και το τζίντζερ στο ελαιόλαδο 5 λεπτά, προσθέστε το κάρι σε σκόνη και ανακατέψτε 1 λεπτό.',
      'Προσθέστε το κοτόπουλο κομμένο σε κομμάτια και σοτάρετε μέχρι να αλλάξει χρώμα.',
      'Ρίξτε τις ντομάτες, το γάλα καρύδας και το αλάτι και σιγοβράστε 20 λεπτά· στο μεταξύ βράστε το ρύζι.',
      'Ρίξτε το σπανάκι να μαραθεί, σερβίρετε πάνω στο ρύζι και πασπαλίστε με κόλιανδρο.',
    ],
    steps_en: [
      'Sauté the onion, garlic and ginger in the olive oil for 5 minutes, add the curry powder and stir 1 minute.',
      'Add the chicken cut into chunks and sauté until it changes colour.',
      'Add the tomatoes, coconut milk and salt and simmer 20 minutes; meanwhile cook the rice.',
      'Wilt in the spinach, serve over the rice and scatter with coriander.',
    ],
    portions: 4,
    prep_min: 45,
    meal_types: ['dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'ginger', quantity: 20, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'curry-powder', quantity: 4, unit: 'tsp' },
      {
        ingredient_slug: 'chicken-thigh',
        quantity: 600,
        unit: 'g',
        note_el: 'φιλέτο',
        note_en: 'boneless',
      },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'coconut-milk', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'basmati-rice', quantity: 200, unit: 'g' },
      { ingredient_slug: 'spinach', quantity: 150, unit: 'g' },
      { ingredient_slug: 'coriander', quantity: 1, unit: 'bunch' },
    ],
    diet_slugs: ['gluten-free', 'high-protein', 'intermittent-fasting', 'flexitarian'],
  },
  {
    slug: 'beef-vegetable-chili-no-beans',
    title_el: 'Τσίλι μοσχαριού με λαχανικά (χωρίς φασόλια)',
    title_en: 'Beef and vegetable chili (no beans)',
    steps_el: [
      'Σοτάρετε το κρεμμύδι, το σκόρδο και τις πιπεριές στο ελαιόλαδο 5 λεπτά.',
      'Προσθέστε τον κιμά και τσιγαρίστε τον μέχρι να ροδίσει, σπάζοντας τους σβόλους.',
      'Ρίξτε το κύμινο, την πάπρικα, τις νιφάδες τσίλι, τον πελτέ, τις ντομάτες, το κολοκυθάκι σε κύβους και το αλάτι.',
      'Σιγοβράστε 35–40 λεπτά με μισάνοιχτο καπάκι μέχρι να δέσει.',
    ],
    steps_en: [
      'Sauté the onion, garlic and peppers in the olive oil for 5 minutes.',
      'Add the mince and brown it, breaking up the lumps.',
      'Add the cumin, paprika, chilli flakes, tomato paste, tomatoes, diced zucchini and salt.',
      'Simmer 35–40 minutes with the lid ajar until thick.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'bell-pepper', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'beef-mince', quantity: 500, unit: 'g' },
      { ingredient_slug: 'cumin', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'paprika', quantity: 2, unit: 'tsp' },
      { ingredient_slug: 'chilli-flakes', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 800, unit: 'g' },
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'low-carb',
      'high-protein',
      'intermittent-fasting',
      'flexitarian',
    ],
  },
  {
    slug: 'baked-polenta-tomato-mozzarella',
    title_el: 'Πολέντα φούρνου με σάλτσα ντομάτας, βασιλικό και μοτσαρέλα',
    title_en: 'Baked polenta with tomato sauce, basil and mozzarella',
    steps_el: [
      'Βράστε το νερό με το αλάτι, ρίξτε το καλαμποκάλευρο σιγά σιγά ανακατεύοντας και μαγειρέψτε 25 λεπτά σε χαμηλή φωτιά· απλώστε σε λαδωμένο ταψί και αφήστε να σφίξει.',
      'Ζεστάνετε 2 κουταλιές ελαιόλαδο, προσθέστε την πασάτα, τη ρίγανη, το πιπέρι και τον μισό βασιλικό και σιγοβράστε 10 λεπτά.',
      'Κόψτε την πολέντα σε κομμάτια, καλύψτε με τη σάλτσα, την παρμεζάνα και τη μοτσαρέλα σε φέτες και περιχύστε με το υπόλοιπο ελαιόλαδο.',
      'Ψήστε στους 200°C για 20 λεπτά μέχρι να λιώσει το τυρί· σερβίρετε με τον υπόλοιπο βασιλικό.',
    ],
    steps_en: [
      'Bring the water to the boil with the salt, pour in the cornmeal slowly while stirring and cook 25 minutes over low heat; spread in an oiled tray and let it set.',
      'Heat 2 tablespoons of olive oil, add the passata, oregano, pepper and half the basil and simmer 10 minutes.',
      'Cut the polenta into pieces, top with the sauce, parmesan and sliced mozzarella and drizzle with the remaining olive oil.',
      'Bake at 200°C for 20 minutes until the cheese melts; serve with the rest of the basil.',
    ],
    portions: 4,
    prep_min: 70,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml' },
      { ingredient_slug: 'salt', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cornmeal', quantity: 250, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'passata', quantity: 500, unit: 'ml' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'basil', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'parmesan', quantity: 80, unit: 'g' },
      { ingredient_slug: 'mozzarella', quantity: 150, unit: 'g' },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
    ],
  },
  {
    slug: 'fish-taco-bowls-cabbage-slaw',
    title_el: 'Μπολ «fish taco» με ρύζι, λάχανο και λάιμ',
    title_en: 'Fish taco bowls with rice, cabbage slaw and lime',
    steps_el: [
      'Βράστε το ρύζι σύμφωνα με τις οδηγίες.',
      'Ψιλοκόψτε το λάχανο και τρίψτε το καρότο· ανακατέψτε τα με τη μαγιονέζα, τον χυμό του ενός λάιμ και τον μισό κόλιανδρο.',
      'Αλείψτε τον μπακαλιάρο με 1 κουταλιά ελαιόλαδο, το κύμινο, την πάπρικα, τις νιφάδες τσίλι και το αλάτι και ψήστε τον στο υπόλοιπο ελαιόλαδο 3–4 λεπτά από κάθε πλευρά.',
      'Μοιράστε το ρύζι σε μπολ, βάλτε από πάνω τη σαλάτα λάχανου και το ψάρι σε κομμάτια και σερβίρετε με το δεύτερο λάιμ και τον υπόλοιπο κόλιανδρο.',
    ],
    steps_en: [
      'Cook the rice according to the packet.',
      'Finely shred the cabbage and grate the carrot; toss with the mayonnaise, the juice of one lime and half the coriander.',
      'Rub the cod with 1 tablespoon of olive oil, the cumin, paprika, chilli flakes and salt and cook it in the remaining olive oil 3–4 minutes per side.',
      'Divide the rice between bowls, top with the slaw and the flaked fish and serve with the second lime and the rest of the coriander.',
    ],
    portions: 4,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'rice', quantity: 250, unit: 'g' },
      { ingredient_slug: 'cabbage', quantity: 300, unit: 'g' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'mayonnaise', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lime', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'coriander', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'cod', quantity: 600, unit: 'g', note_el: 'φιλέτο', note_en: 'fillet' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'low-fodmap',
      'gluten-free',
      'pescatarian',
      'flexitarian',
      'high-protein',
      'intermittent-fasting',
    ],
  },

  // --- Snacks ------------------------------------------------------------------------------------
  {
    slug: 'date-walnut-cocoa-energy-balls',
    title_el: 'Μπαλίτσες ενέργειας με χουρμάδες, καρύδια και κακάο',
    title_en: 'Date, walnut and cocoa energy balls',
    steps_el: [
      'Αφαιρέστε τα κουκούτσια από τους χουρμάδες και χτυπήστε τους στο μπλέντερ με τα καρύδια, το κακάο, την κανέλα και το αλάτι μέχρι να γίνουν μια κολλώδης μάζα.',
      'Πλάστε οκτώ μπαλίτσες με βρεγμένα χέρια.',
      'Κυλήστε τες στην καρύδα και κρατήστε τες στο ψυγείο σε κλειστό δοχείο.',
    ],
    steps_en: [
      'Pit the dates and blitz them in a food processor with the walnuts, cocoa, cinnamon and salt until the mixture becomes a sticky mass.',
      'Roll into eight balls with damp hands.',
      'Roll in the coconut and keep in the fridge in a sealed container.',
    ],
    portions: 8,
    prep_min: 15,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'dates', quantity: 20, unit: 'piece' },
      { ingredient_slug: 'walnuts', quantity: 100, unit: 'g' },
      { ingredient_slug: 'cocoa-powder', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'desiccated-coconut', quantity: 3, unit: 'tbsp' },
    ],
    diet_slugs: ['gluten-free', 'paleo', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
  {
    slug: 'roasted-chickpeas-paprika-cumin',
    title_el: 'Ψητά ρεβίθια με πάπρικα και κύμινο',
    title_en: 'Roasted chickpeas with paprika and cumin',
    steps_el: [
      'Στραγγίστε και ξεπλύνετε τα ρεβίθια και στεγνώστε τα πολύ καλά με πετσέτα.',
      'Ανακατέψτε τα με το ελαιόλαδο, την πάπρικα, το κύμινο και το αλάτι και απλώστε τα σε ταψί σε μία στρώση.',
      'Ψήστε στους 200°C για 30–35 λεπτά, ανακινώντας το ταψί δύο φορές, μέχρι να γίνουν τραγανά· αφήστε να κρυώσουν.',
    ],
    steps_en: [
      'Drain and rinse the chickpeas and dry them very thoroughly with a towel.',
      'Toss with the olive oil, paprika, cumin and salt and spread on a tray in one layer.',
      'Roast at 200°C for 30–35 minutes, shaking the tray twice, until crunchy; let cool.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'canned-chickpeas', quantity: 400, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'gluten-free',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
      'mediterranean',
      'dash',
    ],
  },
  {
    slug: 'apple-almond-butter-cinnamon',
    title_el: 'Φέτες μήλου με αμυγδαλοβούτυρο και κανέλα',
    title_en: 'Apple slices with almond butter and cinnamon',
    steps_el: [
      'Πλύντε τα μήλα και κόψτε τα σε φέτες, αφαιρώντας τα κουκούτσια.',
      'Απλώστε λίγο αμυγδαλοβούτυρο σε κάθε φέτα.',
      'Πασπαλίστε με κανέλα και σερβίρετε αμέσως.',
    ],
    steps_en: [
      'Wash the apples and cut into slices, removing the core.',
      'Spread a little almond butter on each slice.',
      'Dust with cinnamon and serve straight away.',
    ],
    portions: 2,
    prep_min: 5,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'apple', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'almond-butter', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: [
      'whole30',
      'paleo',
      'gluten-free',
      'vegan',
      'vegetarian',
      'pescatarian',
      'flexitarian',
    ],
  },
  {
    slug: 'rice-cakes-peanut-butter-banana',
    title_el: 'Ρυζογκοφρέτες με φυστικοβούτυρο και μπανάνα',
    title_en: 'Rice cakes with peanut butter and banana',
    steps_el: [
      'Αλείψτε τις ρυζογκοφρέτες με το φυστικοβούτυρο.',
      'Κόψτε την μπανάνα σε ροδέλες και απλώστε τες από πάνω.',
      'Σερβίρετε αμέσως για να μείνουν τραγανές.',
    ],
    steps_en: [
      'Spread the rice cakes with the peanut butter.',
      'Slice the banana into rounds and arrange on top.',
      'Serve immediately so they stay crisp.',
    ],
    portions: 1,
    prep_min: 5,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'rice-cakes', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'peanut-butter', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece', note_el: 'σφιχτή', note_en: 'firm' },
    ],
    diet_slugs: ['low-fodmap', 'gluten-free', 'vegan', 'vegetarian', 'pescatarian', 'flexitarian'],
  },
]
