// RECIPES SEED — GROUP 1: Mediterranean & plant-forward (PLAN.md §P1.11). Dishes native to the
// `mediterranean`, `dash`, `flexitarian`, `pescatarian`, `vegetarian` and `vegan` patterns: the Greek
// ladera and legume classics, grain and seafood dishes, breakfasts and snacks people actually cook.
//
// Conventions (PLAN.md §0 content drafting rule, §2 `recipes` / `recipe_ingredients` / `recipe_diets`):
//   - Bilingual on the same row: `title_el`/`title_en`, `steps_el`/`steps_en` with EQUAL step counts
//     (3–8), Greek in the plural imperative as Greek cookbooks write it.
//   - Every `ingredient_slug` is a P1.9 slug; `unit` is the ingredient's own unit or `g`/`ml`; the
//     ingredient nutrition is for the raw/dry state, so legumes, grains and pasta are quantified DRY.
//   - `diet_slugs` are only diets the dish actually complies with: `vegan` has no animal product and
//     no honey; `dash` has no added salt, no feta/olives/capers/cured or tinned fish and only low-fat
//     dairy; `pescatarian` has no meat or poultry; `flexitarian` is tagged on every plant/fish dish.
//   - Portions 1–6; quantities sized so a portion lands roughly 150–900 kcal via `computeNutrition`.
//
// Plain data on purpose: scripts/gen-seed-sql.mjs (P1.12) imports it under node's type stripping.

import type { RecipeSeed } from '../../types.ts'

export const RECIPES_GROUP1: readonly RecipeSeed[] = [
  // --- Breakfasts — πρωινά (14) --------------------------------------------------------------------
  {
    slug: 'oat-porridge-banana-walnuts',
    title_el: 'Χυλός βρώμης με μπανάνα και καρύδια',
    title_en: 'Oat porridge with banana and walnuts',
    steps_el: [
      'Βάλτε τη βρώμη και το γάλα βρώμης σε κατσαρολάκι σε μέτρια φωτιά.',
      'Ανακατεύετε 4–5 λεπτά μέχρι να πήξει ο χυλός.',
      'Κόψτε την μπανάνα σε ροδέλες και ρίξτε τη μισή μέσα στον χυλό.',
      'Σερβίρετε με την υπόλοιπη μπανάνα, τα καρύδια και κανέλα από πάνω.',
    ],
    steps_en: [
      'Put the oats and oat milk in a small pan over medium heat.',
      'Stir for 4–5 minutes until the porridge thickens.',
      'Slice the banana and stir half of it into the porridge.',
      'Serve topped with the remaining banana, the walnuts and a dusting of cinnamon.',
    ],
    portions: 1,
    prep_min: 10,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'oats', quantity: 50, unit: 'g' },
      { ingredient_slug: 'oat-milk', quantity: 250, unit: 'ml' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'walnuts', quantity: 15, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'greek-yoghurt-honey-walnuts-figs',
    title_el: 'Γιαούρτι με μέλι, καρύδια και σύκα',
    title_en: 'Greek yoghurt with honey, walnuts and figs',
    steps_el: [
      'Βάλτε το γιαούρτι σε ένα μπολ.',
      'Κόψτε τα σύκα στα τέσσερα και ακουμπήστε τα πάνω στο γιαούρτι.',
      'Σπάστε τα καρύδια με τα χέρια και σκορπίστε τα από πάνω.',
      'Περιχύστε με το μέλι και σερβίρετε αμέσως.',
    ],
    steps_en: [
      'Spoon the yoghurt into a bowl.',
      'Quarter the figs and arrange them on the yoghurt.',
      'Break the walnuts with your hands and scatter them over.',
      'Drizzle with the honey and serve straight away.',
    ],
    portions: 1,
    prep_min: 5,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'greek-yoghurt', quantity: 200, unit: 'g' },
      { ingredient_slug: 'honey', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'walnuts', quantity: 20, unit: 'g' },
      { ingredient_slug: 'fig', quantity: 2, unit: 'piece', note_el: 'φρέσκα', note_en: 'fresh' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'skyr-berry-oat-bowl',
    title_el: 'Σκυρ με μούρα, βρώμη και τσία',
    title_en: 'Skyr bowl with berries, oats and chia',
    steps_el: [
      'Βάλτε το σκυρ σε μπολ και ανακατέψτε μέσα τους σπόρους τσία.',
      'Πλύντε τις φράουλες και κόψτε τες στη μέση.',
      'Σκορπίστε από πάνω τη βρώμη, τις φράουλες και τα μύρτιλα.',
    ],
    steps_en: [
      'Spoon the skyr into a bowl and stir in the chia seeds.',
      'Rinse the strawberries and halve them.',
      'Scatter the oats, strawberries and blueberries over the top.',
    ],
    portions: 1,
    prep_min: 5,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'skyr', quantity: 200, unit: 'g' },
      { ingredient_slug: 'chia-seeds', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'strawberry', quantity: 80, unit: 'g' },
      { ingredient_slug: 'blueberry', quantity: 50, unit: 'g' },
      { ingredient_slug: 'oats', quantity: 20, unit: 'g' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'overnight-oats-apple-cinnamon',
    title_el: 'Βρώμη βραδιάς με μήλο και κανέλα',
    title_en: 'Overnight oats with apple and cinnamon',
    steps_el: [
      'Ανακατέψτε σε βάζο τη βρώμη, το γάλα αμυγδάλου, τους σπόρους τσία και την κανέλα.',
      'Κλείστε το βάζο και αφήστε το στο ψυγείο όλη τη νύχτα.',
      'Το πρωί τρίψτε το μισό μήλο και ανακατέψτε το μέσα.',
      'Σερβίρετε με τις σταφίδες από πάνω.',
    ],
    steps_en: [
      'Mix the oats, almond milk, chia seeds and cinnamon in a jar.',
      'Close the jar and leave it in the fridge overnight.',
      'In the morning, grate half an apple and stir it in.',
      'Serve with the raisins scattered on top.',
    ],
    portions: 1,
    prep_min: 10,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'oats', quantity: 50, unit: 'g' },
      { ingredient_slug: 'almond-milk', quantity: 200, unit: 'ml' },
      { ingredient_slug: 'chia-seeds', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'apple', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'raisins', quantity: 15, unit: 'g' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'strapatsada-tomato-scrambled-eggs',
    title_el: 'Στραπατσάδα (καγιανάς)',
    title_en: 'Strapatsada — Greek tomato scrambled eggs',
    steps_el: [
      'Τρίψτε τις ντομάτες στον τρίφτη και πετάξτε τη φλούδα.',
      'Ζεστάνετε το ελαιόλαδο σε αντικολλητικό τηγάνι και ρίξτε την τριμμένη ντομάτα με τη ρίγανη.',
      'Μαγειρέψτε 8–10 λεπτά σε μέτρια φωτιά μέχρι να φύγουν τα υγρά.',
      'Χτυπήστε ελαφρά τα αυγά, ρίξτε τα στο τηγάνι και ανακατεύετε μέχρι να δέσουν.',
      'Θρυμματίστε από πάνω τη φέτα και σερβίρετε με το ψωμί.',
    ],
    steps_en: [
      'Grate the tomatoes on a box grater and discard the skins.',
      'Heat the olive oil in a non-stick pan and add the grated tomato with the oregano.',
      'Cook for 8–10 minutes over medium heat until the liquid has evaporated.',
      'Lightly beat the eggs, pour them in and stir until just set.',
      'Crumble the feta over the top and serve with the bread.',
    ],
    portions: 2,
    prep_min: 20,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'tomato', quantity: 3, unit: 'piece', note_el: 'ώριμες', note_en: 'ripe' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'egg', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'feta', quantity: 60, unit: 'g' },
      { ingredient_slug: 'bread', quantity: 2, unit: 'slice' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'avocado-toast-whole-wheat',
    title_el: 'Τοστ ολικής με αβοκάντο',
    title_en: 'Whole wheat avocado toast',
    steps_el: [
      'Φρυγανίστε τις φέτες ψωμιού.',
      'Λιώστε το αβοκάντο με πιρούνι μαζί με τον χυμό λεμονιού και το πιπέρι.',
      'Απλώστε το αβοκάντο στο ψωμί.',
      'Κόψτε τα ντοματίνια στη μέση, βάλτε τα από πάνω και πασπαλίστε με νιφάδες τσίλι.',
    ],
    steps_en: [
      'Toast the bread.',
      'Mash the avocado with a fork together with the lemon juice and pepper.',
      'Spread the avocado over the toast.',
      'Halve the cherry tomatoes, put them on top and sprinkle with chilli flakes.',
    ],
    portions: 1,
    prep_min: 10,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'whole-wheat-bread', quantity: 2, unit: 'slice' },
      { ingredient_slug: 'avocado', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'lemon-juice', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'cherry-tomato', quantity: 50, unit: 'g' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.25, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'banana-oat-pancakes',
    title_el: 'Τηγανίτες βρώμης με μπανάνα',
    title_en: 'Banana oat pancakes',
    steps_el: [
      'Αλέστε τη βρώμη στο μπλέντερ μέχρι να γίνει αλεύρι.',
      'Προσθέστε τις μπανάνες, τα αυγά, το μπέικιν πάουντερ και την κανέλα και χτυπήστε μέχρι να ομογενοποιηθούν.',
      'Αλείψτε αντικολλητικό τηγάνι με λίγο ελαιόλαδο και ζεστάνετε σε μέτρια φωτιά.',
      'Ρίξτε μια κουταλιά σούπας ζύμη για κάθε τηγανίτα και ψήστε 2 λεπτά από κάθε πλευρά.',
      'Σερβίρετε με μια κουταλιά ελαφρύ γιαούρτι.',
    ],
    steps_en: [
      'Blitz the oats in a blender until they turn into flour.',
      'Add the bananas, eggs, baking powder and cinnamon and blend until smooth.',
      'Brush a non-stick pan with a little olive oil and heat over medium heat.',
      'Drop a tablespoon of batter per pancake and cook 2 minutes on each side.',
      'Serve with a spoonful of light yoghurt.',
    ],
    portions: 2,
    prep_min: 20,
    meal_types: ['breakfast'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'oats', quantity: 100, unit: 'g' },
      { ingredient_slug: 'banana', quantity: 2, unit: 'piece', note_el: 'ώριμες', note_en: 'ripe' },
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'baking-powder', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'greek-yoghurt-light', quantity: 100, unit: 'g' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'green-smoothie-spinach-banana',
    title_el: 'Πράσινο σμούθι με σπανάκι και μπανάνα',
    title_en: 'Green smoothie with spinach and banana',
    steps_el: [
      'Πλύντε το σπανάκι και κόψτε το μήλο σε κομμάτια, χωρίς τα κουκούτσια.',
      'Βάλτε στο μπλέντερ το σπανάκι, το μήλο, την μπανάνα, τον λιναρόσπορο και το γάλα βρώμης.',
      'Χτυπήστε 1 λεπτό μέχρι να γίνει λείο και σερβίρετε αμέσως.',
    ],
    steps_en: [
      'Rinse the spinach and cut the apple into chunks, discarding the core.',
      'Put the spinach, apple, banana, flaxseed and oat milk in a blender.',
      'Blend for a minute until smooth and serve at once.',
    ],
    portions: 1,
    prep_min: 5,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'spinach', quantity: 50, unit: 'g' },
      { ingredient_slug: 'apple', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'flaxseed', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'oat-milk', quantity: 250, unit: 'ml' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'tahini-petimezi-toast',
    title_el: 'Ψωμί με ταχίνι και πετιμέζι',
    title_en: 'Tahini and petimezi toast',
    steps_el: [
      'Φρυγανίστε τις φέτες ψωμιού.',
      'Απλώστε το ταχίνι σε κάθε φέτα.',
      'Περιχύστε με το πετιμέζι και πασπαλίστε με το σουσάμι.',
    ],
    steps_en: [
      'Toast the bread.',
      'Spread the tahini over each slice.',
      'Drizzle with the petimezi and sprinkle with the sesame seeds.',
    ],
    portions: 1,
    prep_min: 5,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'whole-wheat-bread', quantity: 2, unit: 'slice' },
      { ingredient_slug: 'tahini', quantity: 1.5, unit: 'tbsp' },
      { ingredient_slug: 'petimezi', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'sesame-seeds', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'mushroom-spinach-omelette',
    title_el: 'Ομελέτα με μανιτάρια και σπανάκι',
    title_en: 'Mushroom and spinach omelette',
    steps_el: [
      'Κόψτε τα μανιτάρια σε φέτες και σοτάρετέ τα στο μισό ελαιόλαδο μέχρι να ροδίσουν.',
      'Ρίξτε το σπανάκι και ανακατέψτε μέχρι να μαραθεί· βγάλτε τα σε πιάτο.',
      'Χτυπήστε τα αυγά με το πιπέρι και ρίξτε τα στο τηγάνι με το υπόλοιπο λάδι.',
      'Όταν πήξει η βάση, βάλτε τη γέμιση στη μία πλευρά και διπλώστε την ομελέτα.',
      'Σερβίρετε με ψιλοκομμένο μαϊντανό.',
    ],
    steps_en: [
      'Slice the mushrooms and sauté them in half the olive oil until golden.',
      'Add the spinach and stir until wilted; tip onto a plate.',
      'Beat the eggs with the pepper and pour into the pan with the remaining oil.',
      'When the base has set, spoon the filling onto one half and fold the omelette over.',
      'Serve with chopped parsley.',
    ],
    portions: 1,
    prep_min: 15,
    meal_types: ['breakfast', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'mushrooms', quantity: 100, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'spinach', quantity: 50, unit: 'g' },
      { ingredient_slug: 'egg', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'black-pepper', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'smoked-salmon-skyr-toast',
    title_el: 'Τοστ με σκυρ, καπνιστό σολομό και αγγούρι',
    title_en: 'Smoked salmon toast with skyr and cucumber',
    steps_el: [
      'Φρυγανίστε το ψωμί και απλώστε το σκυρ σε κάθε φέτα.',
      'Κόψτε το αγγούρι σε λεπτές ροδέλες και στρώστε τες πάνω στο σκυρ.',
      'Ακουμπήστε από πάνω τον σολομό, ψιλοκομμένο άνηθο και λίγες σταγόνες λεμόνι.',
    ],
    steps_en: [
      'Toast the bread and spread the skyr over each slice.',
      'Slice the cucumber thinly and lay it over the skyr.',
      'Top with the salmon, chopped dill and a squeeze of lemon.',
    ],
    portions: 1,
    prep_min: 10,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'whole-wheat-bread', quantity: 2, unit: 'slice' },
      { ingredient_slug: 'skyr', quantity: 50, unit: 'g' },
      { ingredient_slug: 'cucumber', quantity: 0.25, unit: 'piece' },
      { ingredient_slug: 'smoked-salmon', quantity: 60, unit: 'g' },
      { ingredient_slug: 'dill', quantity: 0.1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 0.25, unit: 'piece' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'tofu-scramble-turmeric-peppers',
    title_el: 'Σκράμπλ τόφου με κουρκουμά και πιπεριά',
    title_en: 'Turmeric tofu scramble with peppers',
    steps_el: [
      'Στραγγίστε το τόφου και θρυμματίστε το με πιρούνι.',
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και την πιπεριά ψιλοκομμένα για 5 λεπτά.',
      'Ρίξτε το τόφου, τον κουρκουμά και το πιπέρι και ανακατεύετε 5 λεπτά.',
      'Προσθέστε το σπανάκι και τη διατροφική μαγιά, ανακατέψτε μέχρι να μαραθεί και σερβίρετε.',
    ],
    steps_en: [
      'Drain the tofu and crumble it with a fork.',
      'Sauté the chopped onion and pepper in the olive oil for 5 minutes.',
      'Add the tofu, turmeric and black pepper and stir for 5 minutes.',
      'Add the spinach and nutritional yeast, stir until wilted and serve.',
    ],
    portions: 2,
    prep_min: 15,
    meal_types: ['breakfast', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'tofu', quantity: 300, unit: 'g', note_el: 'σφιχτό', note_en: 'firm' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'bell-pepper', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'turmeric', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'black-pepper', quantity: 0.25, unit: 'tsp' },
      { ingredient_slug: 'spinach', quantity: 100, unit: 'g' },
      { ingredient_slug: 'nutritional-yeast', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'seasonal-fruit-salad-walnuts',
    title_el: 'Φρουτοσαλάτα με καρύδια και κανέλα',
    title_en: 'Seasonal fruit salad with walnuts and cinnamon',
    steps_el: [
      'Καθαρίστε τα πορτοκάλια και κόψτε τα σε κύβους μαζί με το μήλο και την μπανάνα.',
      'Βγάλτε τους σπόρους από το μισό ρόδι.',
      'Ανακατέψτε όλα τα φρούτα σε μπολ με τα καρύδια και πασπαλίστε με κανέλα.',
    ],
    steps_en: [
      'Peel the oranges and dice them together with the apple and banana.',
      'Remove the seeds from half a pomegranate.',
      'Toss all the fruit in a bowl with the walnuts and dust with cinnamon.',
    ],
    portions: 2,
    prep_min: 10,
    meal_types: ['breakfast', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'orange', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'apple', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'banana', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'pomegranate', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'walnuts', quantity: 30, unit: 'g' },
      { ingredient_slug: 'cinnamon', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'trahana-soup-feta',
    title_el: 'Τραχανάς σούπα με φέτα',
    title_en: 'Trahana soup with feta',
    steps_el: [
      'Βράστε το νερό με το ελαιόλαδο και τον πελτέ.',
      'Ρίξτε τον τραχανά και ανακατεύετε συχνά για 10–12 λεπτά μέχρι να χυλώσει.',
      'Σερβίρετε ζεστό με θρυμματισμένη φέτα από πάνω.',
    ],
    steps_en: [
      'Bring the water to the boil with the olive oil and tomato paste.',
      'Add the trahana and stir often for 10–12 minutes until it thickens.',
      'Serve hot with crumbled feta on top.',
    ],
    portions: 2,
    prep_min: 15,
    meal_types: ['breakfast', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'water', quantity: 800, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'tomato-paste', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'trahana', quantity: 120, unit: 'g', note_el: 'ξινός', note_en: 'sour' },
      { ingredient_slug: 'feta', quantity: 60, unit: 'g' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },

  // --- Legume classics — όσπρια (7) ---------------------------------------------------------------
  {
    slug: 'fasolada-white-bean-soup',
    title_el: 'Φασολάδα',
    title_en: 'Fasolada — Greek white bean soup',
    steps_el: [
      'Μουλιάστε τα φασόλια από το προηγούμενο βράδυ, στραγγίστε και βράστε τα 5 λεπτά σε φρέσκο νερό· πετάξτε το νερό.',
      'Ψιλοκόψτε το κρεμμύδι, το καρότο και το σέλερι και σοτάρετέ τα στο μισό ελαιόλαδο.',
      'Προσθέστε τα φασόλια, τις ντομάτες, τον πελτέ, τη δάφνη και νερό να τα σκεπάζει κατά 3 δάχτυλα.',
      'Σιγοβράστε 60–90 λεπτά μέχρι να μαλακώσουν τα φασόλια και να δέσει η σούπα.',
      'Ρίξτε το υπόλοιπο ελαιόλαδο, τον μαϊντανό και το πιπέρι και σερβίρετε.',
    ],
    steps_en: [
      'Soak the beans overnight, drain, boil for 5 minutes in fresh water and discard that water.',
      'Finely chop the onion, carrot and celery and sauté them in half the olive oil.',
      'Add the beans, tomatoes, tomato paste, bay leaves and water to cover by about 5 cm.',
      'Simmer for 60–90 minutes until the beans are tender and the soup has thickened.',
      'Stir in the remaining olive oil, the parsley and the pepper and serve.',
    ],
    portions: 4,
    prep_min: 100,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'white-beans', quantity: 400, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'celery', quantity: 100, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'tomato-paste', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'fakes-lentil-soup',
    title_el: 'Φακές σούπα',
    title_en: 'Fakes — Greek lentil soup',
    steps_el: [
      'Πλύντε τις φακές και βράστε τες 5 λεπτά· στραγγίστε.',
      'Σοτάρετε στο μισό ελαιόλαδο το κρεμμύδι, το σκόρδο και το καρότο ψιλοκομμένα.',
      'Ρίξτε τις φακές, τις ντομάτες, τη δάφνη και νερό να τις σκεπάζει κατά 2 δάχτυλα.',
      'Σιγοβράστε 30–40 λεπτά μέχρι να μαλακώσουν.',
      'Τελειώστε με το υπόλοιπο ελαιόλαδο και το ξίδι και σερβίρετε.',
    ],
    steps_en: [
      'Rinse the lentils and boil them for 5 minutes; drain.',
      'Sauté the chopped onion, garlic and carrot in half the olive oil.',
      'Add the lentils, tomatoes, bay leaves and water to cover by about 3 cm.',
      'Simmer for 30–40 minutes until tender.',
      'Finish with the remaining olive oil and the vinegar and serve.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'lentils', quantity: 400, unit: 'g', note_el: 'ξερές', note_en: 'dry' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'canned-tomatoes', quantity: 200, unit: 'g' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'revithada-sifnos-baked-chickpeas',
    title_el: 'Ρεβιθάδα Σίφνου',
    title_en: 'Revithada — Sifnos slow-baked chickpeas',
    steps_el: [
      'Μουλιάστε τα ρεβίθια 12 ώρες και στραγγίστε.',
      'Βάλτε τα σε πήλινο ή γάστρα με το κρεμμύδι ψιλοκομμένο, το ελαιόλαδο, τη δάφνη και το δεντρολίβανο.',
      'Προσθέστε νερό να τα σκεπάζει κατά 2 δάχτυλα και σκεπάστε.',
      'Ψήστε στους 160 °C για 3 ώρες μέχρι να μαλακώσουν και να δέσει το ζουμί.',
      'Σερβίρετε με πιπέρι και λεμόνι.',
    ],
    steps_en: [
      'Soak the chickpeas for 12 hours and drain.',
      'Put them in a clay pot or casserole with the chopped onion, olive oil, bay leaves and rosemary.',
      'Add water to cover by about 3 cm and put the lid on.',
      'Bake at 160 °C for 3 hours until the chickpeas are soft and the liquid has thickened.',
      'Serve with pepper and lemon.',
    ],
    portions: 4,
    prep_min: 200,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chickpeas', quantity: 400, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'bay-leaf', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'rosemary', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml' },
      { ingredient_slug: 'black-pepper', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'gigantes-plaki-baked-giant-beans',
    title_el: 'Γίγαντες πλακί',
    title_en: 'Gigantes plaki — baked giant beans in tomato',
    steps_el: [
      'Μουλιάστε τους γίγαντες από το προηγούμενο βράδυ και βράστε τους 40 λεπτά μέχρι να μαλακώσουν ελαφρά.',
      'Σοτάρετε στο μισό ελαιόλαδο το κρεμμύδι, το σκόρδο, το καρότο και το σέλερι ψιλοκομμένα.',
      'Προσθέστε τις ντομάτες και σιγοβράστε 10 λεπτά.',
      'Απλώστε τα φασόλια σε ταψί, ρίξτε τη σάλτσα, το υπόλοιπο λάδι, τον μαϊντανό και τον άνηθο και λίγο νερό.',
      'Ψήστε στους 180 °C για 60 λεπτά μέχρι να ροδίσουν.',
    ],
    steps_en: [
      'Soak the beans overnight and boil them for 40 minutes until just tender.',
      'Sauté the chopped onion, garlic, carrot and celery in half the olive oil.',
      'Add the tomatoes and simmer for 10 minutes.',
      'Spread the beans in a baking dish, pour over the sauce, remaining oil, parsley, dill and a little water.',
      'Bake at 180 °C for 60 minutes until golden.',
    ],
    portions: 4,
    prep_min: 120,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'gigantes', quantity: 400, unit: 'g', note_el: 'ξεροί', note_en: 'dry' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'celery', quantity: 50, unit: 'g' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'fava-santorini-yellow-split-pea-puree',
    title_el: 'Φάβα Σαντορίνης',
    title_en: 'Fava — Santorini yellow split pea purée',
    steps_el: [
      'Πλύντε τη φάβα και βάλτε τη σε κατσαρόλα με το κρεμμύδι κομμένο στα τέσσερα και νερό να τη σκεπάζει.',
      'Σιγοβράστε 40–50 λεπτά ξαφρίζοντας, μέχρι να λιώσει.',
      'Πολτοποιήστε με το μισό ελαιόλαδο και τον χυμό του λεμονιού.',
      'Σερβίρετε με ψιλοκομμένο κόκκινο κρεμμύδι και το υπόλοιπο ελαιόλαδο από πάνω.',
    ],
    steps_en: [
      'Rinse the split peas and put them in a pan with the quartered onion and water to cover.',
      'Simmer for 40–50 minutes, skimming, until they fall apart.',
      'Blend with half the olive oil and the lemon juice.',
      'Serve topped with finely chopped red onion and the remaining olive oil.',
    ],
    portions: 4,
    prep_min: 55,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'fava', quantity: 250, unit: 'g' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'hummus-homemade',
    title_el: 'Χούμους σπιτικό',
    title_en: 'Homemade hummus',
    steps_el: [
      'Μουλιάστε τα ρεβίθια 12 ώρες και βράστε τα 60–80 λεπτά μέχρι να μαλακώσουν πολύ· κρατήστε λίγο ζουμί.',
      'Χτυπήστε στο μπλέντερ τα ρεβίθια με το ταχίνι, τον χυμό λεμονιού, το σκόρδο και το κύμινο.',
      'Προσθέστε ζουμί από το βράσιμο μέχρι να γίνει βελούδινο.',
      'Σερβίρετε με το ελαιόλαδο και την πάπρικα από πάνω.',
    ],
    steps_en: [
      'Soak the chickpeas for 12 hours and boil for 60–80 minutes until very soft; keep some cooking water.',
      'Blend the chickpeas with the tahini, lemon juice, garlic and cumin.',
      'Add cooking water until the hummus is silky.',
      'Serve with the olive oil and paprika on top.',
    ],
    portions: 4,
    prep_min: 90,
    meal_types: ['snack', 'lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chickpeas', quantity: 150, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'tahini', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'lemon-juice', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'garlic', quantity: 1, unit: 'clove' },
      { ingredient_slug: 'cumin', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'paprika', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'pumpkin-red-lentil-soup',
    title_el: 'Σούπα κολοκύθας με κόκκινες φακές',
    title_en: 'Pumpkin and red lentil soup',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι, το καρότο, το σκόρδο και το τζίντζερ ψιλοκομμένα για 5 λεπτά.',
      'Προσθέστε την κολοκύθα σε κύβους, τις φακές, το κύμινο και το νερό.',
      'Σιγοβράστε 25 λεπτά μέχρι να μαλακώσουν όλα.',
      'Πολτοποιήστε με ραβδομπλέντερ και σερβίρετε.',
    ],
    steps_en: [
      'Sauté the chopped onion, carrot, garlic and ginger in the olive oil for 5 minutes.',
      'Add the cubed pumpkin, the lentils, the cumin and the water.',
      'Simmer for 25 minutes until everything is soft.',
      'Blend with a stick blender and serve.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'ginger', quantity: 10, unit: 'g' },
      { ingredient_slug: 'pumpkin', quantity: 600, unit: 'g' },
      { ingredient_slug: 'red-lentils', quantity: 250, unit: 'g' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'water', quantity: 1000, unit: 'ml' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },

  // --- Ladera & stuffed vegetables — λαδερά (8) ---------------------------------------------------
  {
    slug: 'gemista-stuffed-tomatoes-peppers',
    title_el: 'Γεμιστά',
    title_en: 'Gemista — rice-stuffed tomatoes and peppers',
    steps_el: [
      'Κόψτε καπάκια από τις ντομάτες και τις πιπεριές και αδειάστε τες· κρατήστε τη σάρκα της ντομάτας.',
      'Σοτάρετε το κρεμμύδι στο μισό ελαιόλαδο, ρίξτε το ρύζι, τη σάρκα της ντομάτας, τα κουκουνάρια και τις σταφίδες και ανακατέψτε 5 λεπτά.',
      'Αποσύρετε και προσθέστε τον μαϊντανό και τον δυόσμο ψιλοκομμένους.',
      'Γεμίστε τα λαχανικά ως τα 3/4, κλείστε με τα καπάκια και βάλτε τις πατάτες κομμένες ανάμεσα.',
      'Περιχύστε με το υπόλοιπο λάδι και λίγο νερό και ψήστε στους 180 °C για 75 λεπτά.',
    ],
    steps_en: [
      'Cut lids off the tomatoes and peppers and hollow them out; keep the tomato flesh.',
      'Sauté the onion in half the olive oil, add the rice, tomato flesh, pine nuts and raisins and stir for 5 minutes.',
      'Take off the heat and add the chopped parsley and mint.',
      'Fill the vegetables three-quarters full, replace the lids and tuck the cut potatoes between them.',
      'Drizzle with the remaining oil and a little water and bake at 180 °C for 75 minutes.',
    ],
    portions: 4,
    prep_min: 110,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'tomato',
        quantity: 4,
        unit: 'piece',
        note_el: 'μεγάλες',
        note_en: 'large',
      },
      { ingredient_slug: 'bell-pepper', quantity: 4, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'rice', quantity: 200, unit: 'g' },
      { ingredient_slug: 'pine-nuts', quantity: 30, unit: 'g' },
      { ingredient_slug: 'raisins', quantity: 30, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 0.25, unit: 'bunch' },
      { ingredient_slug: 'potato', quantity: 2, unit: 'piece' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'briam-baked-summer-vegetables',
    title_el: 'Μπριάμ',
    title_en: 'Briam — Greek baked summer vegetables',
    steps_el: [
      'Κόψτε τις πατάτες, τα κολοκύθια, τη μελιτζάνα και τα κρεμμύδια σε φέτες μισού εκατοστού.',
      'Τρίψτε τις ντομάτες και ανακατέψτε τες με το σκόρδο λιωμένο, τον μαϊντανό, τη ρίγανη και το ελαιόλαδο.',
      'Απλώστε τα λαχανικά σε ταψί και περιχύστε με τη σάλτσα.',
      'Ψήστε στους 190 °C για 75–90 λεπτά μέχρι να μαλακώσουν και να καραμελώσουν στις άκρες.',
    ],
    steps_en: [
      'Slice the potatoes, courgettes, aubergine and onions about half a centimetre thick.',
      'Grate the tomatoes and mix them with the crushed garlic, parsley, oregano and olive oil.',
      'Spread the vegetables in a baking tray and pour over the sauce.',
      'Bake at 190 °C for 75–90 minutes until soft and caramelised at the edges.',
    ],
    portions: 4,
    prep_min: 100,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'zucchini', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'eggplant', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'tomato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'spanakorizo-spinach-rice',
    title_el: 'Σπανακόρυζο',
    title_en: 'Spanakorizo — spinach rice with dill and lemon',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και τα φρέσκα κρεμμυδάκια ψιλοκομμένα για 5 λεπτά.',
      'Ρίξτε το σπανάκι σε δόσεις και ανακατεύετε μέχρι να μαραθεί.',
      'Προσθέστε το ρύζι, τον άνηθο και 400 ml νερό και σιγοβράστε 20 λεπτά σκεπασμένο.',
      'Αποσύρετε, στύψτε το λεμόνι και αφήστε το 5 λεπτά πριν σερβίρετε.',
    ],
    steps_en: [
      'Sauté the chopped onion and spring onions in the olive oil for 5 minutes.',
      'Add the spinach in batches and stir until wilted.',
      'Add the rice, dill and 400 ml water and simmer, covered, for 20 minutes.',
      'Take off the heat, squeeze in the lemon and rest for 5 minutes before serving.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'spinach', quantity: 600, unit: 'g' },
      { ingredient_slug: 'rice', quantity: 200, unit: 'g' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'lahanorizo-cabbage-rice',
    title_el: 'Λαχανόρυζο',
    title_en: 'Lahanorizo — cabbage and rice',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και το καρότο ψιλοκομμένα για 5 λεπτά.',
      'Ρίξτε το λάχανο κομμένο σε λωρίδες και ανακατεύετε μέχρι να μαραθεί.',
      'Προσθέστε τον πελτέ, το ρύζι και 500 ml νερό και σιγοβράστε 20 λεπτά.',
      'Σερβίρετε με λεμόνι και ψιλοκομμένο μαϊντανό.',
    ],
    steps_en: [
      'Sauté the chopped onion and carrot in the olive oil for 5 minutes.',
      'Add the shredded cabbage and stir until it wilts.',
      'Add the tomato paste, the rice and 500 ml water and simmer for 20 minutes.',
      'Serve with lemon and chopped parsley.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'cabbage', quantity: 800, unit: 'g' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'rice', quantity: 200, unit: 'g' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'imam-bayildi-stuffed-eggplant',
    title_el: 'Ιμάμ μπαϊλντί',
    title_en: 'Imam bayildi — onion-stuffed baked aubergine',
    steps_el: [
      'Κόψτε τις μελιτζάνες στη μέση κατά μήκος, χαράξτε τη σάρκα και ψήστε τες 20 λεπτά στους 200 °C με το μισό ελαιόλαδο.',
      'Σοτάρετε στο υπόλοιπο λάδι τα κρεμμύδια σε φέτες και το σκόρδο μέχρι να μαλακώσουν.',
      'Προσθέστε τις ντομάτες ψιλοκομμένες και τον μαϊντανό και σιγοβράστε 10 λεπτά.',
      'Πιέστε τη σάρκα των μελιτζανών να ανοίξει, γεμίστε με το μείγμα και ψήστε άλλα 30 λεπτά.',
    ],
    steps_en: [
      'Halve the aubergines lengthways, score the flesh and roast for 20 minutes at 200 °C with half the olive oil.',
      'Sauté the sliced onions and garlic in the remaining oil until soft.',
      'Add the chopped tomatoes and parsley and simmer for 10 minutes.',
      'Press the aubergine flesh open, fill with the mixture and bake for another 30 minutes.',
    ],
    portions: 2,
    prep_min: 75,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'eggplant', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 4, unit: 'clove' },
      { ingredient_slug: 'tomato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'arakas-latheros-pea-stew',
    title_el: 'Αρακάς λαδερός',
    title_en: 'Arakas latheros — Greek pea stew',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι ψιλοκομμένο για 5 λεπτά.',
      'Προσθέστε τις πατάτες και τα καρότα σε κύβους και ανακατέψτε 3 λεπτά.',
      'Ρίξτε τον αρακά, τον πελτέ διαλυμένο σε 300 ml νερό και τον άνηθο.',
      'Σιγοβράστε 30 λεπτά σκεπασμένο μέχρι να μείνει μόνο το λάδι.',
    ],
    steps_en: [
      'Sauté the chopped onion in the olive oil for 5 minutes.',
      'Add the diced potatoes and carrots and stir for 3 minutes.',
      'Add the peas, the tomato paste dissolved in 300 ml water and the dill.',
      'Simmer, covered, for 30 minutes until only the oil remains.',
    ],
    portions: 4,
    prep_min: 45,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'potato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'peas', quantity: 600, unit: 'g' },
      { ingredient_slug: 'tomato-paste', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'dill', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'fasolakia-ladera-green-bean-stew',
    title_el: 'Φασολάκια λαδερά',
    title_en: 'Fasolakia — green beans braised in olive oil and tomato',
    steps_el: [
      'Καθαρίστε τα φασολάκια και κόψτε τα στη μέση.',
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και το σκόρδο ψιλοκομμένα για 5 λεπτά.',
      'Προσθέστε τα φασολάκια, τις πατάτες σε κομμάτια, τις ντομάτες και τον μαϊντανό.',
      'Σιγοβράστε 45 λεπτά σκεπασμένο μέχρι να μαλακώσουν και να δέσει η σάλτσα.',
    ],
    steps_en: [
      'Top and tail the green beans and halve them.',
      'Sauté the chopped onion and garlic in the olive oil for 5 minutes.',
      'Add the beans, the potatoes in chunks, the tomatoes and the parsley.',
      'Simmer, covered, for 45 minutes until tender and the sauce has thickened.',
    ],
    portions: 4,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'green-beans', quantity: 800, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 6, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'potato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'bamies-okra-tomato-stew',
    title_el: 'Μπάμιες λαδερές',
    title_en: 'Bamies — okra in tomato and olive oil',
    steps_el: [
      'Καθαρίστε τα κοτσάνια από τις μπάμιες, ραντίστε τες με το ξίδι και αφήστε τες 30 λεπτά στον ήλιο ή σε ζεστό μέρος.',
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι ψιλοκομμένο για 5 λεπτά.',
      'Προσθέστε τις ντομάτες και τον μαϊντανό και σιγοβράστε 10 λεπτά.',
      'Ρίξτε τις μπάμιες, κουνήστε την κατσαρόλα αντί να ανακατέψετε και σιγοβράστε 35 λεπτά.',
    ],
    steps_en: [
      'Trim the okra stems, sprinkle with the vinegar and leave for 30 minutes in the sun or a warm spot.',
      'Sauté the chopped onion in the olive oil for 5 minutes.',
      'Add the tomatoes and parsley and simmer for 10 minutes.',
      'Add the okra, shake the pan instead of stirring, and simmer for 35 minutes.',
    ],
    portions: 4,
    prep_min: 85,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'okra', quantity: 700, unit: 'g' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },

  // --- Salads, mezze & vegetarian plates — σαλάτες και μεζέδες (11) -------------------------------
  {
    slug: 'horiatiki-greek-village-salad',
    title_el: 'Χωριάτικη σαλάτα',
    title_en: 'Horiatiki — Greek village salad',
    steps_el: [
      'Κόψτε τις ντομάτες σε χοντρά κομμάτια και το αγγούρι σε ροδέλες.',
      'Κόψτε το κρεμμύδι και την πιπεριά σε λεπτές φέτες.',
      'Βάλτε όλα τα λαχανικά σε πιατέλα με τις ελιές.',
      'Ακουμπήστε τη φέτα από πάνω, πασπαλίστε με ρίγανη και περιχύστε με το ελαιόλαδο.',
    ],
    steps_en: [
      'Cut the tomatoes into chunky wedges and the cucumber into rounds.',
      'Slice the onion and the pepper thinly.',
      'Put all the vegetables on a platter with the olives.',
      'Lay the feta on top, sprinkle with oregano and pour over the olive oil.',
    ],
    portions: 2,
    prep_min: 10,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'tomato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'cucumber', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      {
        ingredient_slug: 'bell-pepper',
        quantity: 1,
        unit: 'piece',
        note_el: 'πράσινη',
        note_en: 'green',
      },
      { ingredient_slug: 'kalamata-olives', quantity: 10, unit: 'piece' },
      { ingredient_slug: 'feta', quantity: 150, unit: 'g' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'dakos-cretan-rusk-salad',
    title_el: 'Ντάκος Κρητικός',
    title_en: 'Dakos — Cretan barley rusk salad',
    steps_el: [
      'Βρέξτε ελαφρά τα παξιμάδια με νερό και βάλτε τα σε πιάτα.',
      'Τρίψτε τις ντομάτες και απλώστε τες πάνω στα παξιμάδια.',
      'Θρυμματίστε τη φέτα από πάνω και προσθέστε τις ελιές.',
      'Περιχύστε με το ελαιόλαδο και πασπαλίστε με ρίγανη.',
    ],
    steps_en: [
      'Moisten the rusks lightly with water and put them on plates.',
      'Grate the tomatoes and spread them over the rusks.',
      'Crumble the feta over the top and add the olives.',
      'Pour over the olive oil and sprinkle with oregano.',
    ],
    portions: 2,
    prep_min: 10,
    meal_types: ['lunch', 'snack'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'rusks',
        quantity: 2,
        unit: 'piece',
        note_el: 'κρίθινα',
        note_en: 'barley',
      },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'feta', quantity: 100, unit: 'g' },
      { ingredient_slug: 'kalamata-olives', quantity: 6, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'tzatziki',
    title_el: 'Τζατζίκι',
    title_en: 'Tzatziki',
    steps_el: [
      'Τρίψτε το αγγούρι, αλατίστε το ελαφρά και στύψτε το καλά σε τουλπάνι να φύγουν τα υγρά.',
      'Ανακατέψτε το γιαούρτι με το αγγούρι, το σκόρδο λιωμένο, το ξίδι και τον άνηθο.',
      'Προσθέστε το ελαιόλαδο, ανακατέψτε και αφήστε το 30 λεπτά στο ψυγείο πριν σερβίρετε.',
    ],
    steps_en: [
      'Grate the cucumber, salt it lightly and squeeze well in a cloth to remove the liquid.',
      'Mix the yoghurt with the cucumber, crushed garlic, vinegar and dill.',
      'Add the olive oil, stir and chill for 30 minutes before serving.',
    ],
    portions: 4,
    prep_min: 15,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'cucumber', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 0.25, unit: 'tsp' },
      {
        ingredient_slug: 'greek-yoghurt',
        quantity: 400,
        unit: 'g',
        note_el: 'στραγγιστό',
        note_en: 'strained',
      },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'dill', quantity: 0.25, unit: 'bunch' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'chickpea-salad-lemon-parsley',
    title_el: 'Ρεβιθοσαλάτα με λεμόνι και μαϊντανό',
    title_en: 'Chickpea salad with lemon and parsley',
    steps_el: [
      'Μουλιάστε τα ρεβίθια από το προηγούμενο βράδυ και βράστε τα 60 λεπτά μέχρι να μαλακώσουν· στραγγίστε και αφήστε να κρυώσουν.',
      'Κόψτε τα ντοματίνια στη μέση, το αγγούρι σε κύβους και το κρεμμύδι σε λεπτές φέτες.',
      'Ανακατέψτε τα ρεβίθια με τα λαχανικά και τον μαϊντανό ψιλοκομμένο.',
      'Περιχύστε με τον χυμό του λεμονιού, το ελαιόλαδο και το κύμινο και ανακατέψτε.',
    ],
    steps_en: [
      'Soak the chickpeas overnight and boil for 60 minutes until tender; drain and cool.',
      'Halve the cherry tomatoes, dice the cucumber and slice the onion thinly.',
      'Toss the chickpeas with the vegetables and the chopped parsley.',
      'Dress with the lemon juice, olive oil and cumin and toss again.',
    ],
    portions: 2,
    prep_min: 75,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chickpeas', quantity: 150, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'cherry-tomato', quantity: 150, unit: 'g' },
      { ingredient_slug: 'cucumber', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'cumin', quantity: 0.5, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'lentil-salad-roasted-beetroot-walnuts',
    title_el: 'Σαλάτα φακής με ψητό παντζάρι και καρύδια',
    title_en: 'Lentil salad with roasted beetroot and walnuts',
    steps_el: [
      'Τυλίξτε τα παντζάρια σε αλουμινόχαρτο και ψήστε τα 45 λεπτά στους 200 °C· καθαρίστε και κόψτε σε κύβους.',
      'Βράστε τις φακές 20 λεπτά να μείνουν σφιχτές και στραγγίστε.',
      'Ανακατέψτε τις φακές με τα παντζάρια, τη ρόκα και τα καρύδια.',
      'Περιχύστε με το βαλσάμικο και το ελαιόλαδο.',
    ],
    steps_en: [
      'Wrap the beetroot in foil and roast for 45 minutes at 200 °C; peel and dice.',
      'Boil the lentils for 20 minutes so they stay firm and drain.',
      'Toss the lentils with the beetroot, rocket and walnuts.',
      'Dress with the balsamic vinegar and olive oil.',
    ],
    portions: 2,
    prep_min: 60,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'beetroot', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'lentils', quantity: 150, unit: 'g', note_el: 'ξερές', note_en: 'dry' },
      { ingredient_slug: 'rocket', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'walnuts', quantity: 30, unit: 'g' },
      { ingredient_slug: 'balsamic-vinegar', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'quinoa-tabbouleh',
    title_el: 'Ταμπουλέ με κινόα',
    title_en: 'Quinoa tabbouleh',
    steps_el: [
      'Ξεπλύντε την κινόα και βράστε τη 15 λεπτά σε διπλάσιο νερό· στραγγίστε και αφήστε να κρυώσει.',
      'Ψιλοκόψτε τον μαϊντανό, τον δυόσμο, τις ντομάτες, το αγγούρι και τα φρέσκα κρεμμυδάκια.',
      'Ανακατέψτε τα όλα με την κινόα.',
      'Περιχύστε με τον χυμό του λεμονιού και το ελαιόλαδο.',
    ],
    steps_en: [
      'Rinse the quinoa and boil for 15 minutes in twice its volume of water; drain and cool.',
      'Finely chop the parsley, mint, tomatoes, cucumber and spring onions.',
      'Toss everything with the quinoa.',
      'Dress with the lemon juice and olive oil.',
    ],
    portions: 2,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'quinoa', quantity: 120, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'cucumber', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'kolokithokeftedes-zucchini-fritters',
    title_el: 'Κολοκυθοκεφτέδες',
    title_en: 'Kolokithokeftedes — zucchini and feta fritters',
    steps_el: [
      'Τρίψτε τα κολοκύθια, αλατίστε ελαφρά και στύψτε τα πολύ καλά να φύγουν τα υγρά.',
      'Ανακατέψτε με τη φέτα θρυμματισμένη, το αυγό, τα φρέσκα κρεμμυδάκια, τον άνηθο και τον δυόσμο ψιλοκομμένους.',
      'Προσθέστε το αλεύρι σταδιακά μέχρι να πλάθεται το μείγμα.',
      'Πλάστε μικρούς κεφτέδες και ψήστε τους στο ελαιόλαδο 3 λεπτά από κάθε πλευρά.',
    ],
    steps_en: [
      'Grate the courgettes, salt lightly and squeeze very well to remove the liquid.',
      'Mix with the crumbled feta, the egg and the chopped spring onions, dill and mint.',
      'Add the flour gradually until the mixture can be shaped.',
      'Shape into small patties and fry in the olive oil for 3 minutes on each side.',
    ],
    portions: 4,
    prep_min: 40,
    meal_types: ['lunch', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'zucchini', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'salt', quantity: 0.5, unit: 'tsp' },
      { ingredient_slug: 'feta', quantity: 150, unit: 'g' },
      { ingredient_slug: 'egg', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'spring-onion', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 0.25, unit: 'bunch' },
      { ingredient_slug: 'mint', quantity: 0.25, unit: 'bunch' },
      { ingredient_slug: 'flour', quantity: 60, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 4, unit: 'tbsp' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'spanakopita-spinach-feta-pie',
    title_el: 'Σπανακόπιτα',
    title_en: 'Spanakopita — spinach and feta pie',
    steps_el: [
      'Μαράντε το σπανάκι σε μεγάλο τηγάνι, στραγγίστε το πολύ καλά και ψιλοκόψτε το.',
      'Ανακατέψτε το με τα φρέσκα κρεμμυδάκια και τον άνηθο ψιλοκομμένους, τη φέτα θρυμματισμένη και τα αυγά.',
      'Λαδώστε ταψί και στρώστε τα μισά φύλλα, λαδώνοντας το καθένα.',
      'Απλώστε τη γέμιση και σκεπάστε με τα υπόλοιπα φύλλα, λαδώνοντας· χαράξτε σε κομμάτια.',
      'Ψήστε στους 180 °C για 45 λεπτά μέχρι να ροδίσει.',
    ],
    steps_en: [
      'Wilt the spinach in a large pan, squeeze it very dry and chop it.',
      'Mix it with the chopped spring onions and dill, the crumbled feta and the eggs.',
      'Oil a baking tin and lay in half the phyllo sheets, brushing each with oil.',
      'Spread the filling, cover with the remaining sheets, brushing with oil; score into pieces.',
      'Bake at 180 °C for 45 minutes until golden.',
    ],
    portions: 6,
    prep_min: 80,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'spinach', quantity: 800, unit: 'g' },
      { ingredient_slug: 'spring-onion', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'dill', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'feta', quantity: 300, unit: 'g' },
      { ingredient_slug: 'egg', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'phyllo', quantity: 250, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'halloumi-grilled-vegetable-salad',
    title_el: 'Σαλάτα με ψητό χαλούμι και λαχανικά',
    title_en: 'Grilled halloumi and vegetable salad',
    steps_el: [
      'Κόψτε το κολοκύθι και την πιπεριά σε φέτες και ψήστε τα σε γκριλ ή τηγάνι-σχάρα με λίγο ελαιόλαδο.',
      'Κόψτε το χαλούμι σε φέτες και ψήστε το 2 λεπτά από κάθε πλευρά μέχρι να ροδίσει.',
      'Απλώστε τη ρόκα και τα ντοματίνια κομμένα στη μέση σε πιατέλα.',
      'Βάλτε από πάνω τα λαχανικά και το χαλούμι, περιχύστε με το υπόλοιπο λάδι και το λεμόνι και σκορπίστε δυόσμο.',
    ],
    steps_en: [
      'Slice the courgette and pepper and grill them on a griddle with a little olive oil.',
      'Slice the halloumi and grill for 2 minutes per side until golden.',
      'Spread the rocket and halved cherry tomatoes on a platter.',
      'Top with the vegetables and halloumi, dress with the remaining oil and lemon and scatter mint.',
    ],
    portions: 2,
    prep_min: 25,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'bell-pepper', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'halloumi', quantity: 200, unit: 'g' },
      { ingredient_slug: 'rocket', quantity: 1, unit: 'bunch' },
      { ingredient_slug: 'cherry-tomato', quantity: 150, unit: 'g' },
      { ingredient_slug: 'lemon', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'mint', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['vegetarian', 'flexitarian', 'pescatarian', 'mediterranean'],
  },
  {
    slug: 'roasted-cauliflower-tahini-pomegranate',
    title_el: 'Ψητό κουνουπίδι με ταχίνι και ρόδι',
    title_en: 'Roasted cauliflower with tahini and pomegranate',
    steps_el: [
      'Κόψτε το κουνουπίδι σε μπουκέτα, ανακατέψτε με το ελαιόλαδο και το κύμινο και απλώστε σε ταψί.',
      'Ψήστε στους 220 °C για 25 λεπτά μέχρι να ροδίσει στις άκρες.',
      'Ανακατέψτε το ταχίνι με τον χυμό του λεμονιού, το σκόρδο λιωμένο και 3 κουταλιές νερό μέχρι να γίνει σάλτσα.',
      'Περιχύστε το κουνουπίδι με τη σάλτσα και σκορπίστε από πάνω το ρόδι και τον μαϊντανό.',
    ],
    steps_en: [
      'Cut the cauliflower into florets, toss with the olive oil and cumin and spread on a tray.',
      'Roast at 220 °C for 25 minutes until browned at the edges.',
      'Whisk the tahini with the lemon juice, crushed garlic and 3 tablespoons of water into a sauce.',
      'Spoon the sauce over the cauliflower and scatter with pomegranate seeds and parsley.',
    ],
    portions: 2,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'cauliflower', quantity: 600, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'tahini', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 1, unit: 'clove' },
      { ingredient_slug: 'pomegranate', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'tofu-souvlaki-skewers-pita',
    title_el: 'Σουβλάκι τόφου με πίτα',
    title_en: 'Tofu souvlaki skewers with pita',
    steps_el: [
      'Κόψτε το τόφου σε κύβους και μαρινάρετέ το 20 λεπτά με το ελαιόλαδο, τον χυμό του λεμονιού, τη ρίγανη και την πάπρικα.',
      'Κόψτε την πιπεριά, το κρεμμύδι και το κολοκύθι σε κομμάτια και περάστε τα σε σουβλάκια εναλλάξ με το τόφου.',
      'Ψήστε σε γκριλ ή τηγάνι-σχάρα 10–12 λεπτά γυρίζοντας.',
      'Ζεστάνετε τις πίτες και σερβίρετε με τα σουβλάκια.',
    ],
    steps_en: [
      'Cube the tofu and marinate for 20 minutes in the olive oil, lemon juice, oregano and paprika.',
      'Cut the pepper, onion and courgette into chunks and thread onto skewers alternating with the tofu.',
      'Grill or griddle for 10–12 minutes, turning.',
      'Warm the pitas and serve with the skewers.',
    ],
    portions: 2,
    prep_min: 40,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'tofu', quantity: 300, unit: 'g', note_el: 'σφιχτό', note_en: 'firm' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'bell-pepper', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'red-onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'zucchini', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'pita', quantity: 2, unit: 'piece' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },

  // --- Pasta — ζυμαρικά (2) -----------------------------------------------------------------------
  {
    slug: 'spaghetti-tomato-garlic-basil',
    title_el: 'Μακαρόνια ολικής με σάλτσα ντομάτας και βασιλικό',
    title_en: 'Whole wheat spaghetti with tomato, garlic and basil',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και το σκόρδο ψιλοκομμένα για 3 λεπτά.',
      'Ρίξτε τις ντομάτες και σιγοβράστε 20 λεπτά μέχρι να δέσει η σάλτσα.',
      'Βράστε τα μακαρόνια σύμφωνα με τη συσκευασία και στραγγίστε.',
      'Ανακατέψτε τα με τη σάλτσα, τον βασιλικό και το πιπέρι και σερβίρετε.',
    ],
    steps_en: [
      'Sauté the chopped onion and garlic in the olive oil for 3 minutes.',
      'Add the tomatoes and simmer for 20 minutes until the sauce thickens.',
      'Cook the spaghetti according to the packet and drain.',
      'Toss with the sauce, the basil and the pepper and serve.',
    ],
    portions: 2,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'whole-wheat-pasta', quantity: 160, unit: 'g' },
      { ingredient_slug: 'basil', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'black-pepper', quantity: 0.25, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'lentil-bolognese-whole-wheat-pasta',
    title_el: 'Μπολονέζ φακής με ζυμαρικά ολικής',
    title_en: 'Lentil bolognese with whole wheat pasta',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι, το καρότο, το σέλερι και το σκόρδο ψιλοκομμένα για 8 λεπτά.',
      'Προσθέστε τις φακές, τις ντομάτες, τη ρίγανη και 500 ml νερό.',
      'Σιγοβράστε 35 λεπτά μέχρι να μαλακώσουν οι φακές και να δέσει η σάλτσα.',
      'Βράστε τα ζυμαρικά, στραγγίστε και σερβίρετε με τη σάλτσα.',
    ],
    steps_en: [
      'Sauté the finely chopped onion, carrot, celery and garlic in the olive oil for 8 minutes.',
      'Add the lentils, tomatoes, oregano and 500 ml water.',
      'Simmer for 35 minutes until the lentils are tender and the sauce has thickened.',
      'Cook the pasta, drain and serve with the sauce.',
    ],
    portions: 4,
    prep_min: 50,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'carrot', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'celery', quantity: 50, unit: 'g' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'lentils', quantity: 300, unit: 'g', note_el: 'ξερές', note_en: 'dry' },
      { ingredient_slug: 'canned-tomatoes', quantity: 800, unit: 'g' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'whole-wheat-pasta', quantity: 320, unit: 'g' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },

  // --- Fish & seafood — ψάρια και θαλασσινά (9) ---------------------------------------------------
  {
    slug: 'grilled-sardines-lemon-oregano',
    title_el: 'Σαρδέλες στη σχάρα με λεμόνι και ρίγανη',
    title_en: 'Grilled sardines with lemon and oregano',
    steps_el: [
      'Καθαρίστε τις σαρδέλες, ξεπλύντε και στεγνώστε τες.',
      'Ανακατέψτε το ελαιόλαδο με τον χυμό του λεμονιού, τη ρίγανη και το σκόρδο λιωμένο.',
      'Ψήστε τις σαρδέλες σε δυνατή σχάρα 3 λεπτά από κάθε πλευρά.',
      'Περιχύστε με το λαδολέμονο και σκορπίστε μαϊντανό.',
    ],
    steps_en: [
      'Gut the sardines, rinse and pat dry.',
      'Mix the olive oil with the lemon juice, oregano and crushed garlic.',
      'Grill the sardines over high heat for 3 minutes per side.',
      'Pour over the lemon-oil dressing and scatter with parsley.',
    ],
    portions: 2,
    prep_min: 25,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      {
        ingredient_slug: 'sardines',
        quantity: 500,
        unit: 'g',
        note_el: 'φρέσκες',
        note_en: 'fresh',
      },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'garlic', quantity: 1, unit: 'clove' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'baked-sea-bream-lemon-potatoes',
    title_el: 'Τσιπούρα στον φούρνο με πατάτες λεμονάτες',
    title_en: 'Baked sea bream with lemon potatoes',
    steps_el: [
      'Κόψτε τις πατάτες σε κυδωνάτα κομμάτια και απλώστε τες σε ταψί με το μισό ελαιόλαδο, το σκόρδο, τη ρίγανη και τον χυμό μισού λεμονιού.',
      'Ψήστε στους 200 °C για 30 λεπτά.',
      'Χαράξτε τις τσιπούρες, βάλτε φέτες λεμονιού στην κοιλιά και ακουμπήστε τες πάνω στις πατάτες.',
      'Περιχύστε με το υπόλοιπο λάδι και ψήστε άλλα 25 λεπτά.',
      'Σερβίρετε με ψιλοκομμένο μαϊντανό.',
    ],
    steps_en: [
      'Cut the potatoes into wedges and spread in a tray with half the olive oil, the garlic, oregano and juice of half a lemon.',
      'Bake at 200 °C for 30 minutes.',
      'Score the sea bream, tuck lemon slices into the cavity and lay the fish on the potatoes.',
      'Drizzle with the remaining oil and bake for another 25 minutes.',
      'Serve with chopped parsley.',
    ],
    portions: 2,
    prep_min: 70,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      {
        ingredient_slug: 'sea-bream',
        quantity: 700,
        unit: 'g',
        note_el: 'δύο ολόκληρες',
        note_en: 'two whole fish',
      },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'psari-plaki-baked-cod-tomato-onion',
    title_el: 'Ψάρι πλακί',
    title_en: 'Psari plaki — cod baked with tomato and onion',
    steps_el: [
      'Σοτάρετε στο μισό ελαιόλαδο τα κρεμμύδια σε φέτες και το σκόρδο μέχρι να μαλακώσουν.',
      'Προσθέστε τις ντομάτες και τον μαϊντανό και σιγοβράστε 10 λεπτά.',
      'Στρώστε τις πατάτες σε λεπτές φέτες σε ταψί, ακουμπήστε από πάνω τα φιλέτα και σκεπάστε με τη σάλτσα.',
      'Περιχύστε με το υπόλοιπο λάδι και ψήστε στους 190 °C για 40 λεπτά.',
    ],
    steps_en: [
      'Sauté the sliced onions and garlic in half the olive oil until soft.',
      'Add the tomatoes and parsley and simmer for 10 minutes.',
      'Layer thinly sliced potatoes in a baking dish, lay the fillets on top and cover with the sauce.',
      'Drizzle with the remaining oil and bake at 190 °C for 40 minutes.',
    ],
    portions: 4,
    prep_min: 65,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 5, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 3, unit: 'clove' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'tomato', quantity: 2, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'potato', quantity: 3, unit: 'piece' },
      { ingredient_slug: 'cod', quantity: 600, unit: 'g', note_el: 'φιλέτο', note_en: 'fillets' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'shrimp-saganaki-feta-ouzo',
    title_el: 'Γαρίδες σαγανάκι',
    title_en: 'Shrimp saganaki with feta and ouzo',
    steps_el: [
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και το σκόρδο ψιλοκομμένα για 5 λεπτά.',
      'Προσθέστε τις ντομάτες και τις νιφάδες τσίλι και σιγοβράστε 15 λεπτά.',
      'Ρίξτε τις γαρίδες και το ούζο και μαγειρέψτε 4 λεπτά μέχρι να ροδίσουν.',
      'Θρυμματίστε τη φέτα από πάνω, σκεπάστε 2 λεπτά να μαλακώσει και σερβίρετε με μαϊντανό.',
    ],
    steps_en: [
      'Sauté the chopped onion and garlic in the olive oil for 5 minutes.',
      'Add the tomatoes and chilli flakes and simmer for 15 minutes.',
      'Add the shrimp and ouzo and cook for 4 minutes until pink.',
      'Crumble the feta over, cover for 2 minutes to soften and serve with parsley.',
    ],
    portions: 2,
    prep_min: 35,
    meal_types: ['dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'canned-tomatoes', quantity: 400, unit: 'g' },
      { ingredient_slug: 'chilli-flakes', quantity: 0.5, unit: 'tsp' },
      {
        ingredient_slug: 'shrimp',
        quantity: 400,
        unit: 'g',
        note_el: 'καθαρισμένες',
        note_en: 'peeled',
      },
      { ingredient_slug: 'ouzo', quantity: 30, unit: 'ml' },
      { ingredient_slug: 'feta', quantity: 100, unit: 'g' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'octopus-xydato-vinegar-oregano',
    title_el: 'Χταπόδι ξιδάτο',
    title_en: 'Octopus xydato — with vinegar, oregano and olive oil',
    steps_el: [
      'Βάλτε το χταπόδι σε κατσαρόλα χωρίς νερό, σκεπάστε και σιγοβράστε 45–60 λεπτά στα υγρά του μέχρι να μαλακώσει.',
      'Αφήστε το να κρυώσει και κόψτε το σε μπουκιές.',
      'Ανακατέψτε με το ξίδι, το ελαιόλαδο, τη ρίγανη και το κόκκινο κρεμμύδι σε λεπτές φέτες.',
      'Αφήστε 30 λεπτά να μαριναριστεί και σερβίρετε με μαϊντανό.',
    ],
    steps_en: [
      'Put the octopus in a pan with no water, cover and simmer in its own juices for 45–60 minutes until tender.',
      'Let it cool and cut into bite-sized pieces.',
      'Toss with the vinegar, olive oil, oregano and thinly sliced red onion.',
      'Marinate for 30 minutes and serve with parsley.',
    ],
    portions: 2,
    prep_min: 100,
    meal_types: ['lunch', 'dinner', 'snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'octopus', quantity: 600, unit: 'g' },
      { ingredient_slug: 'red-wine-vinegar', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'olive-oil', quantity: 3, unit: 'tbsp' },
      { ingredient_slug: 'oregano', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'mydopilafo-mussel-rice',
    title_el: 'Μυδοπίλαφο',
    title_en: 'Mydopilafo — mussel rice with dill and lemon',
    steps_el: [
      'Καθαρίστε τα μύδια και πετάξτε όσα μένουν ανοιχτά.',
      'Σοτάρετε στο ελαιόλαδο το κρεμμύδι και το σκόρδο ψιλοκομμένα για 5 λεπτά.',
      'Ρίξτε τα μύδια και το κρασί, σκεπάστε και μαγειρέψτε 4 λεπτά μέχρι να ανοίξουν· βγάλτε τα από τα κελύφη.',
      'Προσθέστε το ρύζι και 350 ml νερό στο ζουμί και σιγοβράστε 18 λεπτά.',
      'Ανακατέψτε με τα μύδια, τον άνηθο και τον χυμό του λεμονιού και σερβίρετε.',
    ],
    steps_en: [
      'Scrub the mussels and discard any that stay open.',
      'Sauté the chopped onion and garlic in the olive oil for 5 minutes.',
      'Add the mussels and wine, cover and cook for 4 minutes until they open; shell them.',
      'Add the rice and 350 ml water to the liquor and simmer for 18 minutes.',
      'Stir in the mussels, dill and lemon juice and serve.',
    ],
    portions: 2,
    prep_min: 45,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'mussels', quantity: 500, unit: 'g' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'onion', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 2, unit: 'clove' },
      { ingredient_slug: 'white-wine', quantity: 100, unit: 'ml' },
      { ingredient_slug: 'rice', quantity: 150, unit: 'g' },
      { ingredient_slug: 'dill', quantity: 0.5, unit: 'bunch' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'salmon-quinoa-broccoli-bowl',
    title_el: 'Μπολ με σολομό, κινόα και μπρόκολο',
    title_en: 'Salmon, quinoa and broccoli bowl',
    steps_el: [
      'Βράστε την κινόα 15 λεπτά σε διπλάσιο νερό και στραγγίστε.',
      'Αχνίστε το μπρόκολο 5 λεπτά.',
      'Ψήστε τον σολομό σε αντικολλητικό τηγάνι με το ελαιόλαδο 4 λεπτά από κάθε πλευρά.',
      'Μοιράστε την κινόα σε μπολ, βάλτε από πάνω το μπρόκολο, τον σολομό και το αβοκάντο σε φέτες και περιχύστε με λεμόνι και άνηθο.',
    ],
    steps_en: [
      'Boil the quinoa for 15 minutes in twice its volume of water and drain.',
      'Steam the broccoli for 5 minutes.',
      'Pan-fry the salmon in the olive oil for 4 minutes per side.',
      'Divide the quinoa between bowls, top with the broccoli, salmon and sliced avocado and finish with lemon and dill.',
    ],
    portions: 2,
    prep_min: 30,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'quinoa', quantity: 120, unit: 'g' },
      { ingredient_slug: 'broccoli', quantity: 200, unit: 'g' },
      { ingredient_slug: 'salmon', quantity: 300, unit: 'g', note_el: 'φιλέτο', note_en: 'fillet' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'avocado', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'lemon', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'dill', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'tuna-white-bean-salad',
    title_el: 'Σαλάτα με τόνο και φασόλια',
    title_en: 'Tuna and white bean salad',
    steps_el: [
      'Μουλιάστε τα φασόλια από το προηγούμενο βράδυ, βράστε τα 60 λεπτά μέχρι να μαλακώσουν και στραγγίστε.',
      'Στραγγίστε τον τόνο και ανακατέψτε τον με τα φασόλια, τα ντοματίνια κομμένα στη μέση και το κρεμμύδι σε λεπτές φέτες.',
      'Περιχύστε με τον χυμό του λεμονιού και το ελαιόλαδο και σκορπίστε τον μαϊντανό.',
    ],
    steps_en: [
      'Soak the beans overnight, boil for 60 minutes until tender and drain.',
      'Drain the tuna and toss it with the beans, halved cherry tomatoes and thinly sliced onion.',
      'Dress with the lemon juice and olive oil and scatter with parsley.',
    ],
    portions: 2,
    prep_min: 75,
    meal_types: ['lunch'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'white-beans', quantity: 120, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'canned-tuna', quantity: 160, unit: 'g' },
      { ingredient_slug: 'cherry-tomato', quantity: 100, unit: 'g' },
      { ingredient_slug: 'red-onion', quantity: 0.5, unit: 'piece' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'parsley', quantity: 0.25, unit: 'bunch' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean'],
  },
  {
    slug: 'grilled-mackerel-horta-lemon',
    title_el: 'Σκουμπρί στη σχάρα με χόρτα λαδολέμονο',
    title_en: 'Grilled mackerel with horta and lemon',
    steps_el: [
      'Καθαρίστε τα χόρτα και βράστε τα 10 λεπτά σε άφθονο νερό· στραγγίστε.',
      'Χαράξτε τα σκουμπριά και ψήστε τα σε δυνατή σχάρα 5 λεπτά από κάθε πλευρά.',
      'Ανακατέψτε το ελαιόλαδο με τον χυμό του λεμονιού και το σκόρδο λιωμένο.',
      'Σερβίρετε το ψάρι με τα χόρτα και περιχύστε όλα με το λαδολέμονο.',
    ],
    steps_en: [
      'Trim the greens and boil for 10 minutes in plenty of water; drain.',
      'Score the mackerel and grill over high heat for 5 minutes per side.',
      'Whisk the olive oil with the lemon juice and crushed garlic.',
      'Serve the fish with the greens and pour the lemon-oil dressing over everything.',
    ],
    portions: 2,
    prep_min: 35,
    meal_types: ['lunch', 'dinner'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'horta', quantity: 500, unit: 'g' },
      {
        ingredient_slug: 'mackerel',
        quantity: 400,
        unit: 'g',
        note_el: 'δύο ολόκληρα',
        note_en: 'two whole fish',
      },
      { ingredient_slug: 'olive-oil', quantity: 2, unit: 'tbsp' },
      { ingredient_slug: 'lemon', quantity: 1, unit: 'piece' },
      { ingredient_slug: 'garlic', quantity: 1, unit: 'clove' },
    ],
    diet_slugs: ['pescatarian', 'flexitarian', 'mediterranean', 'dash'],
  },

  // --- Snacks — σνακ (2) --------------------------------------------------------------------------
  {
    slug: 'roasted-chickpeas-paprika-cumin',
    title_el: 'Ψητά ρεβίθια με πάπρικα και κύμινο',
    title_en: 'Roasted chickpeas with paprika and cumin',
    steps_el: [
      'Μουλιάστε τα ρεβίθια 12 ώρες, βράστε τα 45 λεπτά να μείνουν σφιχτά και στεγνώστε τα καλά σε πετσέτα.',
      'Ανακατέψτε τα με το ελαιόλαδο, την πάπρικα και το κύμινο.',
      'Απλώστε σε ταψί και ψήστε στους 200 °C για 30 λεπτά ανακινώντας στα μισά, μέχρι να γίνουν τραγανά.',
    ],
    steps_en: [
      'Soak the chickpeas for 12 hours, boil for 45 minutes so they stay firm and dry them well on a towel.',
      'Toss with the olive oil, paprika and cumin.',
      'Spread on a tray and roast at 200 °C for 30 minutes, shaking halfway, until crunchy.',
    ],
    portions: 4,
    prep_min: 80,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'chickpeas', quantity: 200, unit: 'g', note_el: 'ξερά', note_en: 'dry' },
      { ingredient_slug: 'olive-oil', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredient_slug: 'cumin', quantity: 1, unit: 'tsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
  {
    slug: 'date-oat-energy-balls',
    title_el: 'Ενεργειακές μπάλες με χουρμάδες και βρώμη',
    title_en: 'Date and oat energy balls',
    steps_el: [
      'Αφαιρέστε τα κουκούτσια από τους χουρμάδες και χτυπήστε τους στο μπλέντερ με τα αμύγδαλα μέχρι να γίνουν πάστα.',
      'Προσθέστε τη βρώμη, το κακάο και το ταχίνι και χτυπήστε ξανά μέχρι να δέσει το μείγμα.',
      'Πλάστε 12 μπαλίτσες και βάλτε τες στο ψυγείο 30 λεπτά να σφίξουν.',
    ],
    steps_en: [
      'Pit the dates and blitz them with the almonds in a food processor until a paste forms.',
      'Add the oats, cocoa and tahini and blitz again until the mixture holds together.',
      'Roll into 12 balls and chill for 30 minutes to firm up.',
    ],
    portions: 6,
    prep_min: 45,
    meal_types: ['snack'],
    image_path: null,
    ingredients: [
      { ingredient_slug: 'dates', quantity: 15, unit: 'piece' },
      { ingredient_slug: 'almonds', quantity: 40, unit: 'g' },
      { ingredient_slug: 'oats', quantity: 80, unit: 'g' },
      { ingredient_slug: 'cocoa-powder', quantity: 1, unit: 'tbsp' },
      { ingredient_slug: 'tahini', quantity: 1, unit: 'tbsp' },
    ],
    diet_slugs: ['vegan', 'vegetarian', 'flexitarian', 'pescatarian', 'mediterranean', 'dash'],
  },
]
