-- GENERATED by scripts/gen-seed-sql.mjs (npm run seed:gen) — do not edit by hand; edit the
-- overlay module and regenerate. `npm run seed:check` fails on any drift.
-- Overlay: src/content/seed/overlays/0004-prices-nutrition.ts — Greek retail prices 2026-10 (142 ingredients shelf-checked at Sklavenitis and My market, 180 marked as estimates) and EU-sourced nutrition for 33 ingredients (CIQUAL 2020, EU labels)
-- Patches: ingredients 322. Additions: none.
-- Patches set editable content columns only (never id, slug, status or the review stamp), so an
-- approved row stays approved. Additions omit status (default pending): the lead approves them
-- live. Updates are idempotent and inserts are `on conflict do nothing`: re-applying is a no-op.

update hygieia.ingredients set
  kcal_100g = 348,
  protein_100g = 6.1,
  carbs_100g = 72.1,
  fat_100g = 8.7,
  source_note = 'USDA FoodData Central "Spices, allspice, ground" (171315) composition, energy recomputed with EU Reg. 1169/2011 factors (fibre 21.6 g at 2 kcal/g)',
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'allspice';

update hygieia.ingredients set
  price_eur_min = 29.3,
  price_eur_max = 39.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'almond-butter';

update hygieia.ingredients set
  price_eur_min = 24.6,
  price_eur_max = 30.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'almond-flour';

update hygieia.ingredients set
  price_eur_min = 2.07,
  price_eur_max = 2.94,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 18 products, 10th–90th percentile'
where slug = 'almond-milk';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'almonds';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'anchovies';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'anchovy-fillets';

update hygieia.ingredients set
  kcal_100g = 169,
  protein_100g = 12.2,
  carbs_100g = 3.4,
  fat_100g = 11.6,
  source_note = 'Mean of 4 EU nutrition labels (EU Reg. 1169/2011) of Greek fresh anthotyro cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 6.96,
  price_eur_max = 12,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 13 products, 10th–90th percentile'
where slug = 'anthotyro';

update hygieia.ingredients set
  price_eur_min = 1.29,
  price_eur_max = 2.49,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 15 products, 10th–90th percentile'
where slug = 'apple';

update hygieia.ingredients set
  price_eur_min = 3,
  price_eur_max = 6.35,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 14 products, 10th–90th percentile'
where slug = 'apple-cider-vinegar';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'apricot';

update hygieia.ingredients set
  price_eur_min = 1.56,
  price_eur_max = 5.44,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06, 12 products: Greek glacé round-grain risotto rice 1.56–4.36, imported arborio 5.44 (lowest–highest)'
where slug = 'arborio-rice';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per piece'
where slug = 'artichoke';

update hygieia.ingredients set
  price_eur_min = 19.8,
  price_eur_max = 19.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 1 product, lowest–highest'
where slug = 'asparagus';

update hygieia.ingredients set
  price_eur_min = 0.59,
  price_eur_max = 1.27,
  price_as_of = '2026-10-06'::date,
  price_note = 'per piece (~150 g), from per-kg prices — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'avocado';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'avocado-oil';

update hygieia.ingredients set
  price_eur_min = 8.19,
  price_eur_max = 27.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 15 products, 10th–90th percentile'
where slug = 'bacon';

update hygieia.ingredients set
  kcal_100g = 146,
  protein_100g = 2,
  carbs_100g = 35.1,
  fat_100g = 0.2,
  source_note = 'CIQUAL 2020 (ANSES), "Baking powder or raising agent" (11046); energy from the composition with EU Reg. 1169/2011 factors; carbs incl. fibre',
  price_eur_min = 7.47,
  price_eur_max = 8.76,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'baking-powder';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'baking-soda';

update hygieia.ingredients set
  price_eur_min = 4.6,
  price_eur_max = 9.32,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 11 products, 10th–90th percentile'
where slug = 'balsamic-vinegar';

update hygieia.ingredients set
  price_eur_min = 1.39,
  price_eur_max = 1.94,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'banana';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'barley';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per bunch'
where slug = 'basil';

update hygieia.ingredients set
  price_eur_min = 3.21,
  price_eur_max = 7.54,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 14 products, 10th–90th percentile'
where slug = 'basmati-rice';

update hygieia.ingredients set
  price_eur_min = 98.5,
  price_eur_max = 165,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'bay-leaf';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'beef-heart';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'beef-kidney';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'beef-liver';

update hygieia.ingredients set
  price_eur_min = 13.2,
  price_eur_max = 17.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'beef-mince';

update hygieia.ingredients set
  price_eur_min = 19.9,
  price_eur_max = 24,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'beef-steak';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'beef-stew';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'beer';

update hygieia.ingredients set
  price_eur_min = 1.57,
  price_eur_max = 1.59,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'beetroot';

update hygieia.ingredients set
  price_eur_min = 2.05,
  price_eur_max = 4.59,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 10 products, 10th–90th percentile'
where slug = 'bell-pepper';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'black-beans';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'black-eyed-peas';

update hygieia.ingredients set
  price_eur_min = 14.1,
  price_eur_max = 94.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'black-pepper';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'black-tea';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'blue-cheese';

update hygieia.ingredients set
  price_eur_min = 16,
  price_eur_max = 18.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'blueberry';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'bone-broth';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'bone-marrow';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'bread';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'breadcrumbs';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'breadsticks';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'broad-beans';

update hygieia.ingredients set
  price_eur_min = 2.9,
  price_eur_max = 3.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'broccoli';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'brown-rice';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'brown-sugar';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'brussels-sprouts';

update hygieia.ingredients set
  price_eur_min = 4.56,
  price_eur_max = 6.18,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'buckwheat';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'bulgur';

update hygieia.ingredients set
  price_eur_min = 8.56,
  price_eur_max = 21.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 14 products, 10th–90th percentile'
where slug = 'butter';

update hygieia.ingredients set
  price_eur_min = 0.65,
  price_eur_max = 0.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'cabbage';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'canned-chickpeas';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'canned-sardines';

update hygieia.ingredients set
  price_eur_min = 1.66,
  price_eur_max = 3.79,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 12 products, 10th–90th percentile'
where slug = 'canned-tomatoes';

update hygieia.ingredients set
  price_eur_min = 17.5,
  price_eur_max = 44.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 33 products, 10th–90th percentile'
where slug = 'canned-tuna';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'capers';

update hygieia.ingredients set
  price_eur_min = 0.95,
  price_eur_max = 1.98,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'carrot';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cashews';

update hygieia.ingredients set
  price_eur_min = 2.15,
  price_eur_max = 2.78,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'cauliflower';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'celeriac';

update hygieia.ingredients set
  price_eur_min = 1.98,
  price_eur_max = 1.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'celery';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'chamomile';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chard';

update hygieia.ingredients set
  price_eur_min = 12.2,
  price_eur_max = 21,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'cheddar';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cherry';

update hygieia.ingredients set
  price_eur_min = 5.19,
  price_eur_max = 9.64,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'cherry-tomato';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chestnuts';

update hygieia.ingredients set
  price_eur_min = 8.46,
  price_eur_max = 14.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'chia-seeds';

update hygieia.ingredients set
  price_eur_min = 9.23,
  price_eur_max = 16,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 11 products, 10th–90th percentile'
where slug = 'chicken-breast';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chicken-drumstick';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chicken-liver';

update hygieia.ingredients set
  price_eur_min = 5.19,
  price_eur_max = 18.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 13 products, 10th–90th percentile'
where slug = 'chicken-thigh';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chicken-wings';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'chickpea-flour';

update hygieia.ingredients set
  price_eur_min = 2.8,
  price_eur_max = 5.91,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 10 products, 10th–90th percentile'
where slug = 'chickpeas';

update hygieia.ingredients set
  kcal_100g = 376,
  protein_100g = 12,
  carbs_100g = 56.6,
  fat_100g = 17.3,
  source_note = 'CIQUAL 2020 (ANSES), "Cayenne pepper" (11088); carbs incl. fibre',
  price_eur_min = 15,
  price_eur_max = 38.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'chilli-flakes';

update hygieia.ingredients set
  price_eur_min = 11.8,
  price_eur_max = 36,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'cinnamon';

update hygieia.ingredients set
  kcal_100g = 335,
  protein_100g = 6,
  carbs_100g = 65.5,
  fat_100g = 13,
  source_note = 'CIQUAL 2020 (ANSES), "Cloves" (11052); carbs incl. fibre',
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cloves';

update hygieia.ingredients set
  kcal_100g = 387,
  protein_100g = 22.4,
  carbs_100g = 41.1,
  fat_100g = 20.6,
  source_note = 'CIQUAL 2020 (ANSES), "Cocoa powder, without sugar" (18100); carbs incl. fibre',
  price_eur_min = 15.8,
  price_eur_max = 28,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'cocoa-powder';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'coconut-flour';

update hygieia.ingredients set
  price_eur_min = 6,
  price_eur_max = 6.05,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'coconut-milk';

update hygieia.ingredients set
  price_eur_min = 13.9,
  price_eur_max = 13.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'coconut-oil';

update hygieia.ingredients set
  price_eur_min = 6.12,
  price_eur_max = 15.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 16 products, 10th–90th percentile'
where slug = 'cod';

update hygieia.ingredients set
  price_eur_min = 1.08,
  price_eur_max = 1.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l brewed, from ground filter coffee at 60 g per litre — Sklavenitis & My market online shelf prices, 2026-10-06; 30 products, 10th–90th percentile'
where slug = 'coffee';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'condensed-milk';

update hygieia.ingredients set
  price_eur_min = 0.75,
  price_eur_max = 0.75,
  price_as_of = '2026-10-06'::date,
  price_note = 'per bunch (~100 g) — Sklavenitis online shelf prices, 2026-10-06; 1 product, lowest–highest'
where slug = 'coriander';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'corn';

update hygieia.ingredients set
  price_eur_min = 2,
  price_eur_max = 2.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'cornmeal';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cornstarch';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cottage-cheese';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'couscous';

update hygieia.ingredients set
  price_eur_min = 7.99,
  price_eur_max = 16.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 12 products, 10th–90th percentile'
where slug = 'cream-cheese';

update hygieia.ingredients set
  price_eur_min = 0.32,
  price_eur_max = 0.53,
  price_as_of = '2026-10-06'::date,
  price_note = 'per piece (~300 g) — Sklavenitis & My market online shelf prices, 2026-10-06: 0.53 a piece at both chains; small cucumbers 1.08 €/kg (≈ 0.32 a 300 g piece)'
where slug = 'cucumber';

update hygieia.ingredients set
  price_eur_min = 21.6,
  price_eur_max = 60,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'cumin';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'curry-powder';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'cuttlefish';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'dark-chocolate';

update hygieia.ingredients set
  price_eur_min = 6.59,
  price_eur_max = 14.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'dates';

update hygieia.ingredients set
  price_eur_min = 7.2,
  price_eur_max = 9.69,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'desiccated-coconut';

update hygieia.ingredients set
  price_eur_min = 0.75,
  price_eur_max = 0.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per bunch (80–100 g) — Sklavenitis & My market online shelf prices, 2026-10-06, 3 products'
where slug = 'dill';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'dried-fig';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'dry-yeast';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'duck';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'edamame';

update hygieia.ingredients set
  price_eur_min = 0.24,
  price_eur_max = 0.58,
  price_as_of = '2026-10-06'::date,
  price_note = 'per egg, from pack prices — Sklavenitis & My market online shelf prices, 2026-10-06; 31 products, 10th–90th percentile'
where slug = 'egg';

update hygieia.ingredients set
  price_eur_min = 7.1,
  price_eur_max = 7.96,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'egg-white';

update hygieia.ingredients set
  price_eur_min = 1.45,
  price_eur_max = 2.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'eggplant';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'endive';

update hygieia.ingredients set
  kcal_100g = 0,
  source_note = 'Composition: USDA FoodData Central reference ranges; energy 0 kcal/g for erythritol per EU Reg. 1169/2011 Annex XIV',
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'erythritol';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'evaporated-milk';

update hygieia.ingredients set
  kcal_100g = 344,
  protein_100g = 22.8,
  carbs_100g = 67.8,
  fat_100g = 1.4,
  source_note = 'CIQUAL 2020 (ANSES), "Split pea, dried" (20515); energy from the composition with EU Reg. 1169/2011 factors; carbs incl. fibre',
  price_eur_min = 3,
  price_eur_max = 4.78,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'fava';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'fennel';

update hygieia.ingredients set
  kcal_100g = 285,
  protein_100g = 15.1,
  carbs_100g = 0.7,
  fat_100g = 24.3,
  source_note = 'CIQUAL 2020 (ANSES), "Feta cheese, PDO" (12066); carbs incl. fibre',
  price_eur_min = 12.4,
  price_eur_max = 17.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 23 products, 10th–90th percentile'
where slug = 'feta';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'fig';

update hygieia.ingredients set
  price_eur_min = 5.86,
  price_eur_max = 8.88,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'flaxseed';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'flour';

update hygieia.ingredients set
  price_eur_min = 8,
  price_eur_max = 14.4,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — derived from per-head prices (0.40–0.72 € a head, Sklavenitis & My market online shelf prices, 2026-10-06, 4 products) at ~50 g a head'
where slug = 'garlic';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'garlic-powder';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'gelatin';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'ghee';

update hygieia.ingredients set
  kcal_100g = 294,
  protein_100g = 20.4,
  carbs_100g = 60.3,
  fat_100g = 2.4,
  source_note = 'Mean of 4 EU nutrition labels (EU Reg. 1169/2011) of dried Greek gigantes beans on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 5.13,
  price_eur_max = 13.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 12 products, 10th–90th percentile'
where slug = 'gigantes';

update hygieia.ingredients set
  price_eur_min = 3.1,
  price_eur_max = 3.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'ginger';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'goat';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'goat-milk';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'gouda';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'granola';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'grapefruit';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'grapes';

update hygieia.ingredients set
  kcal_100g = 399,
  protein_100g = 25.5,
  carbs_100g = 2.1,
  fat_100g = 32.5,
  source_note = 'Mean of 4 EU nutrition labels (EU Reg. 1169/2011) of Greek graviera cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 12.5,
  price_eur_max = 19.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 33 products, 10th–90th percentile'
where slug = 'graviera';

update hygieia.ingredients set
  kcal_100g = 130,
  protein_100g = 6.1,
  carbs_100g = 3.6,
  fat_100g = 10,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek strained yoghurts, 10 % fat on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 2.65,
  price_eur_max = 4.24,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 7 products, 10th–90th percentile'
where slug = 'greek-yoghurt';

update hygieia.ingredients set
  kcal_100g = 71,
  protein_100g = 9.3,
  carbs_100g = 3.8,
  fat_100g = 2,
  source_note = 'Mean of 9 EU nutrition labels (EU Reg. 1169/2011) of Greek strained yoghurts, 2 % fat on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 3.1,
  price_eur_max = 6.63,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 31 products, 10th–90th percentile'
where slug = 'greek-yoghurt-light';

update hygieia.ingredients set
  price_eur_min = 3.1,
  price_eur_max = 3.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'green-beans';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'green-olives';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'grouper';

update hygieia.ingredients set
  price_eur_min = 16.3,
  price_eur_max = 16.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 1 product, lowest–highest'
where slug = 'halloumi';

update hygieia.ingredients set
  kcal_100g = 547,
  protein_100g = 12.3,
  carbs_100g = 53.2,
  fat_100g = 32.7,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek tahini halva, plain/vanilla on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 6.23,
  price_eur_max = 23.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 34 products, 10th–90th percentile'
where slug = 'halva';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'ham';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'hazelnuts';

update hygieia.ingredients set
  price_eur_min = 6.53,
  price_eur_max = 11.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'heavy-cream';

update hygieia.ingredients set
  kcal_100g = 354,
  protein_100g = 12,
  carbs_100g = 72.1,
  fat_100g = 1.5,
  source_note = 'Mean of 1 EU nutrition label (EU Reg. 1169/2011) of Greek hilopites egg pasta on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 2.76,
  price_eur_max = 4.23,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 10 products, 10th–90th percentile'
where slug = 'hilopites';

update hygieia.ingredients set
  kcal_100g = 334,
  protein_100g = 0.2,
  carbs_100g = 83.2,
  fat_100g = 0,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek honeys (thyme, pine, flower) on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 5.81,
  price_eur_max = 18.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 27 products, 10th–90th percentile'
where slug = 'honey';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'horn-pepper';

update hygieia.ingredients set
  kcal_100g = 49,
  protein_100g = 2.9,
  carbs_100g = 8.8,
  fat_100g = 0.9,
  source_note = 'CIQUAL 2020 (ANSES), "Dandelion, raw" (20038), the closest wild green; energy from the composition with EU Reg. 1169/2011 factors; carbs incl. fibre',
  price_eur_min = 1.68,
  price_eur_max = 1.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'horta';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'hot-pepper';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'hot-sauce';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'hummus';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'jam';

update hygieia.ingredients set
  kcal_100g = 236,
  protein_100g = 1.5,
  carbs_100g = 4.1,
  fat_100g = 23.9,
  source_note = 'Mean of 8 EU nutrition labels (EU Reg. 1169/2011) of Kalamata olives in brine, drained on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 6.97,
  price_eur_max = 20.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 17 products, 10th–90th percentile'
where slug = 'kalamata-olives';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'kale';

update hygieia.ingredients set
  kcal_100g = 344,
  protein_100g = 23.9,
  carbs_100g = 0.5,
  fat_100g = 27.3,
  source_note = 'Mean of 3 EU nutrition labels (EU Reg. 1169/2011) of Greek PDO kasseri cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 18,
  price_eur_max = 27.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'kasseri';

update hygieia.ingredients set
  kcal_100g = 363,
  protein_100g = 24.1,
  carbs_100g = 0.8,
  fat_100g = 30.5,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek kefalotyri cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 9.59,
  price_eur_max = 19,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 10 products, 10th–90th percentile'
where slug = 'kefalotyri';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'kefir';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'ketchup';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'kidney-beans';

update hygieia.ingredients set
  price_eur_min = 5.75,
  price_eur_max = 5.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'kiwi';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per piece'
where slug = 'koulouri';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'lamb-chops';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'lamb-leg';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'lard';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'leek';

update hygieia.ingredients set
  price_eur_min = 1.75,
  price_eur_max = 1.85,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'lemon';

update hygieia.ingredients set
  price_eur_min = 3.28,
  price_eur_max = 5.02,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'lemon-juice';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'lentil-pasta';

update hygieia.ingredients set
  price_eur_min = 2.24,
  price_eur_max = 5.19,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 18 products, 10th–90th percentile'
where slug = 'lentils';

update hygieia.ingredients set
  price_eur_min = 0.78,
  price_eur_max = 0.84,
  price_as_of = '2026-10-06'::date,
  price_note = 'per head — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'lettuce';

update hygieia.ingredients set
  price_eur_min = 0.25,
  price_eur_max = 0.29,
  price_as_of = '2026-10-06'::date,
  price_note = 'per piece (~65 g), from per-kg prices — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'lime';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'lupini';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'mackerel';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'mandarin';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'mango';

update hygieia.ingredients set
  kcal_100g = 451,
  protein_100g = 10,
  carbs_100g = 1.5,
  fat_100g = 45,
  source_note = 'Mean of 1 EU nutrition label (EU Reg. 1169/2011) of Greek PDO manouri cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 14.2,
  price_eur_max = 15.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'manouri';

update hygieia.ingredients set
  price_eur_min = 24.8,
  price_eur_max = 34.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'maple-syrup';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'margarine';

update hygieia.ingredients set
  price_eur_min = 4.97,
  price_eur_max = 10.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'ml-priced jars converted at 0.92 kg/l — Sklavenitis & My market online shelf prices, 2026-10-06; 29 products, 10th–90th percentile'
where slug = 'mayonnaise';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'melon';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'milk';

update hygieia.ingredients set
  price_eur_min = 0.85,
  price_eur_max = 1.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per bunch (25–50 g) — Sklavenitis online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'mint';

update hygieia.ingredients set
  kcal_100g = 269,
  protein_100g = 29.2,
  carbs_100g = 4.4,
  fat_100g = 15,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek dry mizithra cheeses on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 8.72,
  price_eur_max = 14.4,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 7 products, 10th–90th percentile'
where slug = 'mizithra';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'mountain-tea';

update hygieia.ingredients set
  price_eur_min = 8.36,
  price_eur_max = 17.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 9 products, 10th–90th percentile'
where slug = 'mozzarella';

update hygieia.ingredients set
  price_eur_min = 3.6,
  price_eur_max = 6.46,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'mushrooms';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'mussels';

update hygieia.ingredients set
  price_eur_min = 2.21,
  price_eur_max = 12.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 38 products, 10th–90th percentile'
where slug = 'mustard';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per sheet'
where slug = 'nori';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'nutmeg';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'nutritional-yeast';

update hygieia.ingredients set
  price_eur_min = 2.08,
  price_eur_max = 2.74,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 11 products, 10th–90th percentile'
where slug = 'oat-milk';

update hygieia.ingredients set
  price_eur_min = 2.24,
  price_eur_max = 5.89,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'oats';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'octopus';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'okra';

update hygieia.ingredients set
  kcal_100g = 900,
  protein_100g = 0,
  carbs_100g = 0,
  fat_100g = 99.9,
  source_note = 'CIQUAL 2020 (ANSES), "Olive oil, extra virgin" (17270); carbs incl. fibre',
  price_eur_min = 6.95,
  price_eur_max = 10.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 56 products, 10th–90th percentile'
where slug = 'olive-oil';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'olive-paste';

update hygieia.ingredients set
  price_eur_min = 0.72,
  price_eur_max = 0.79,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'onion';

update hygieia.ingredients set
  price_eur_min = 1,
  price_eur_max = 1.25,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'orange';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'orange-juice';

update hygieia.ingredients set
  price_eur_min = 16.8,
  price_eur_max = 67.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'oregano';

update hygieia.ingredients set
  kcal_100g = 359,
  protein_100g = 12,
  carbs_100g = 75.4,
  fat_100g = 1.7,
  source_note = 'Mean of 3 EU nutrition labels (EU Reg. 1169/2011) of Greek kritharaki (orzo) durum pasta on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 1.24,
  price_eur_max = 2.43,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 18 products, 10th–90th percentile'
where slug = 'orzo';

update hygieia.ingredients set
  price_eur_min = 11.8,
  price_eur_max = 20.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 35 products, 10th–90th percentile'
where slug = 'ouzo';

update hygieia.ingredients set
  price_eur_min = 15.4,
  price_eur_max = 85,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'paprika';

update hygieia.ingredients set
  price_eur_min = 22.3,
  price_eur_max = 41.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 26 products, 10th–90th percentile'
where slug = 'parmesan';

update hygieia.ingredients set
  price_eur_min = 0.75,
  price_eur_max = 0.79,
  price_as_of = '2026-10-06'::date,
  price_note = 'per bunch (~100 g) — Sklavenitis & My market online shelf prices, 2026-10-06, 2 products'
where slug = 'parsley';

update hygieia.ingredients set
  price_eur_min = 1.09,
  price_eur_max = 2.1,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 7 products, 10th–90th percentile'
where slug = 'passata';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pasta';

update hygieia.ingredients set
  kcal_100g = 187,
  protein_100g = 28.2,
  carbs_100g = 5.6,
  fat_100g = 4.8,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek/Armenian-style beef pastourma on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 37,
  price_eur_max = 65.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'pastourma';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pea-protein';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'peach';

update hygieia.ingredients set
  price_eur_min = 8.48,
  price_eur_max = 14,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 9 products, 10th–90th percentile'
where slug = 'peanut-butter';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'peanuts';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pear';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'peas';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pesto';

update hygieia.ingredients set
  price_eur_min = 13.1,
  price_eur_max = 13.1,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 1 product, lowest–highest'
where slug = 'petimezi';

update hygieia.ingredients set
  kcal_100g = 292,
  protein_100g = 8.7,
  carbs_100g = 61.8,
  fat_100g = 1,
  source_note = 'Mean of 4 EU nutrition labels (EU Reg. 1169/2011) of Greek phyllo (fyllo kroustas) on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 4.12,
  price_eur_max = 8.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 23 products, 10th–90th percentile'
where slug = 'phyllo';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pickles';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pine-nuts';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pineapple';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pistachios';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per piece'
where slug = 'pita';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'plum';

update hygieia.ingredients set
  price_eur_min = 2.59,
  price_eur_max = 2.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'pomegranate';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pork-belly';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pork-chop';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pork-mince';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pork-shoulder';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pork-tenderloin';

update hygieia.ingredients set
  price_eur_min = 0.68,
  price_eur_max = 1.67,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 9 products, 10th–90th percentile'
where slug = 'potato';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'prosciutto';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'prunes';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'psyllium-husk';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'pumpkin';

update hygieia.ingredients set
  price_eur_min = 7.38,
  price_eur_max = 16.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'pumpkin-seeds';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'quince';

update hygieia.ingredients set
  price_eur_min = 10.5,
  price_eur_max = 13.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'quinoa';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'rabbit';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per bunch'
where slug = 'radish';

update hygieia.ingredients set
  price_eur_min = 6.37,
  price_eur_max = 12.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'raisins';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'raspberry';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'red-cabbage';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'red-lentils';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'red-mullet';

update hygieia.ingredients set
  price_eur_min = 0.79,
  price_eur_max = 0.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'red-onion';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'red-wine';

update hygieia.ingredients set
  price_eur_min = 0.99,
  price_eur_max = 2.23,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'red-wine-vinegar';

update hygieia.ingredients set
  price_eur_min = 1.92,
  price_eur_max = 4.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 16 products, 10th–90th percentile'
where slug = 'rice';

update hygieia.ingredients set
  price_eur_min = 15,
  price_eur_max = 17,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'rice-cakes';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'rice-noodles';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'ricotta';

update hygieia.ingredients set
  kcal_100g = 23,
  protein_100g = 0.8,
  carbs_100g = 5.6,
  fat_100g = 0,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of roasted red (Florina-type) peppers in jars on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 6.53,
  price_eur_max = 8.86,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'roasted-red-peppers';

update hygieia.ingredients set
  price_eur_min = 10,
  price_eur_max = 12.9,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis online shelf prices, 2026-10-06; 2 products, lowest–highest'
where slug = 'rocket';

update hygieia.ingredients set
  price_eur_min = 58.4,
  price_eur_max = 79.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'rosemary';

update hygieia.ingredients set
  kcal_100g = 362,
  protein_100g = 13.9,
  carbs_100g = 77.4,
  fat_100g = 2.1,
  source_note = 'Mean of 4 EU nutrition labels (EU Reg. 1169/2011) of Cretan barley rusks (paximadia) on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 3.95,
  price_eur_max = 8.55,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 15 products, 10th–90th percentile'
where slug = 'rusks';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per 1 g sachet'
where slug = 'saffron';

update hygieia.ingredients set
  price_eur_min = 18,
  price_eur_max = 68.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'sage';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'salami';

update hygieia.ingredients set
  price_eur_min = 20.5,
  price_eur_max = 30.7,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis online shelf prices, 2026-10-06; 5 products, 10th–90th percentile'
where slug = 'salmon';

update hygieia.ingredients set
  price_eur_min = 0.79,
  price_eur_max = 3.52,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 20 products, 10th–90th percentile'
where slug = 'salt';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'salted-cod';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sardines';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sauerkraut';

update hygieia.ingredients set
  kcal_100g = 276,
  protein_100g = 14,
  carbs_100g = 1.7,
  fat_100g = 23.8,
  source_note = 'Mean of 3 EU nutrition labels (EU Reg. 1169/2011) of Greek village pork sausages (loukaniko) on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 8.14,
  price_eur_max = 16.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 21 products, 10th–90th percentile'
where slug = 'sausage';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sea-bass';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sea-bream';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'seitan';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'semi-skimmed-milk';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'semolina';

update hygieia.ingredients set
  price_eur_min = 11.3,
  price_eur_max = 31.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'sesame-oil';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sesame-seeds';

update hygieia.ingredients set
  kcal_100g = 100,
  protein_100g = 5.6,
  carbs_100g = 4.6,
  fat_100g = 6.6,
  source_note = 'Mean of 7 EU nutrition labels (EU Reg. 1169/2011) of Greek traditional sheep-milk yoghurts on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 5.64,
  price_eur_max = 7.08,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 13 products, 10th–90th percentile'
where slug = 'sheep-yoghurt';

update hygieia.ingredients set
  price_eur_min = 10.7,
  price_eur_max = 22.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 22 products, 10th–90th percentile'
where slug = 'shrimp';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'skyr';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'smoked-herring';

update hygieia.ingredients set
  price_eur_min = 40.6,
  price_eur_max = 69,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 11 products, 10th–90th percentile'
where slug = 'smoked-salmon';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sour-cream';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'soy-milk';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'soy-mince';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'soy-sauce';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'sparkling-water';

update hygieia.ingredients set
  price_eur_min = 2.6,
  price_eur_max = 5.87,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'spinach';

update hygieia.ingredients set
  price_eur_min = 0.28,
  price_eur_max = 1.34,
  price_as_of = '2026-10-06'::date,
  price_note = 'per bunch — Sklavenitis & My market online shelf prices, 2026-10-06: loose 2.75–2.99 €/kg (≈ 0.28–0.30 a 100 g bunch) to 1.34 for a packed 140 g bunch'
where slug = 'spring-onion';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'squid';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'stevia';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per cube'
where slug = 'stock-cube';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh (out of season: only a frozen pack on sale 2026-10-06) — typical Greek supermarket range, per kg'
where slug = 'strawberry';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sugar';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sun-dried-tomatoes';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'sunflower-oil';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'sunflower-seeds';

update hygieia.ingredients set
  price_eur_min = 1.75,
  price_eur_max = 2.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'sweet-potato';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'swordfish';

update hygieia.ingredients set
  kcal_100g = 621,
  protein_100g = 17.7,
  carbs_100g = 20.8,
  fat_100g = 53.4,
  source_note = 'CIQUAL 2020 (ANSES), "Tahini (sesame paste)" (15203); energy from the composition with EU Reg. 1169/2011 factors; carbs incl. fibre',
  price_eur_min = 6.26,
  price_eur_max = 16.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 19 products, 10th–90th percentile'
where slug = 'tahini';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'tallow';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'tempeh';

update hygieia.ingredients set
  price_eur_min = 17.5,
  price_eur_max = 79.6,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'thyme';

update hygieia.ingredients set
  price_eur_min = 8.25,
  price_eur_max = 12.3,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 4 products, lowest–highest'
where slug = 'tofu';

update hygieia.ingredients set
  price_eur_min = 1.78,
  price_eur_max = 2.62,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 6 products, 10th–90th percentile'
where slug = 'tomato';

update hygieia.ingredients set
  price_eur_min = 3.7,
  price_eur_max = 9.74,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 20 products, 10th–90th percentile'
where slug = 'tomato-paste';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per piece'
where slug = 'tortilla';

update hygieia.ingredients set
  kcal_100g = 370,
  protein_100g = 12.9,
  carbs_100g = 70.6,
  fat_100g = 3.3,
  source_note = 'Mean of 2 EU nutrition labels (EU Reg. 1169/2011) of Greek trahanas (sour and sweet) on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 4.1,
  price_eur_max = 5.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 8 products, 10th–90th percentile'
where slug = 'trahana';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'trout';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'tuna-steak';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'turkey-breast';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'turkey-mince';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'turkey-slices';

update hygieia.ingredients set
  price_eur_min = 51.5,
  price_eur_max = 51.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — My market online shelf prices, 2026-10-06; 1 product, lowest–highest'
where slug = 'turmeric';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'turnip';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per l'
where slug = 'vanilla-extract';

update hygieia.ingredients set
  kcal_100g = 52,
  protein_100g = 4,
  carbs_100g = 9.8,
  fat_100g = 0.3,
  source_note = 'Mean of 3 EU nutrition labels (EU Reg. 1169/2011) of vine leaves in brine on sale in Greece, 2026-10; carbs incl. fibre',
  price_eur_min = 18.3,
  price_eur_max = 26.5,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'vine-leaves';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'vlita';

update hygieia.ingredients set
  price_eur_min = 16,
  price_eur_max = 30.8,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'walnuts';

update hygieia.ingredients set
  price_eur_min = 0.18,
  price_eur_max = 0.23,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 18 products, 10th–90th percentile'
where slug = 'water';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'watermelon';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'whey-protein';

update hygieia.ingredients set
  price_eur_min = 2.58,
  price_eur_max = 7.56,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 16 products, 10th–90th percentile'
where slug = 'white-beans';

update hygieia.ingredients set
  price_eur_min = 5.09,
  price_eur_max = 22.2,
  price_as_of = '2026-10-06'::date,
  price_note = 'per l — Sklavenitis & My market online shelf prices, 2026-10-06; 52 products, 10th–90th percentile'
where slug = 'white-wine';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'whole-chicken';

update hygieia.ingredients set
  price_eur_min = 2.65,
  price_eur_max = 4.43,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 24 products, 10th–90th percentile'
where slug = 'whole-wheat-bread';

update hygieia.ingredients set
  price_note = 'Estimate, not checked against shelf prices in the 2026-10 refresh — typical Greek supermarket range, per kg'
where slug = 'whole-wheat-flour';

update hygieia.ingredients set
  price_eur_min = 1.5,
  price_eur_max = 2.44,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 31 products, 10th–90th percentile'
where slug = 'whole-wheat-pasta';

update hygieia.ingredients set
  price_eur_min = 1.3,
  price_eur_max = 1.99,
  price_as_of = '2026-10-06'::date,
  price_note = 'per kg — Sklavenitis & My market online shelf prices, 2026-10-06; 3 products, lowest–highest'
where slug = 'zucchini';

