-- GENERATED by scripts/gen-seed-sql.mjs (npm run seed:gen) — do not edit by hand; edit the
-- overlay module and regenerate. `npm run seed:check` fails on any drift.
-- Overlay: src/content/seed/overlays/0001-fix-typos.ts — two copy corrections: a pronoun (EN health tip) and a doubled «το το» (EL skincare tip)
-- Patches: health_tips 1, skincare_tips 1. Additions: none.
-- Patches set editable content columns only (never id, slug, status or the review stamp), so an
-- approved row stays approved. Additions omit status (default pending): the lead approves them
-- live. Updates are idempotent and inserts are `on conflict do nothing`: re-applying is a no-op.

update hygieia.health_tips set
  body_en = 'Two portions of fish a week, one of them oily — sardines, anchovies, mackerel, salmon — supply omega-3 fats and vitamin D. Small fish are cheap, local and lower in mercury than large ones. Grilled or baked with lemon and oregano, they make a ten-minute meal.'
where slug = 'nutrition-fish-twice-a-week';

update hygieia.skincare_tips set
  body_el = 'Έως και το 80 % της υπεριώδους ακτινοβολίας περνά μέσα από τα σύννεφα, και η UVA, που γερνά το δέρμα, περνά και από τα τζάμια του αυτοκινήτου και του γραφείου. Το αντηλιακό είναι το μόνο «αντιγηραντικό» με αδιαμφισβήτητα στοιχεία. Βάλ’ το ως τελευταίο βήμα της πρωινής ρουτίνας, όπως το βούρτσισμα των δοντιών.'
where slug = 'face-all-sunscreen-every-day-clouds-included';

