-- GENERATED by scripts/gen-seed-sql.mjs (npm run seed:gen) — do not edit by hand; edit the
-- overlay module and regenerate. `npm run seed:check` fails on any drift.
-- Overlay: src/content/seed/overlays/0005-recipe-photos.ts — photos for 182 recipes (image_path = recipes/<slug>)
-- Patches: recipes 182. Additions: none.
-- Patches set editable content columns only (never id, slug, status or the review stamp), so an
-- approved row stays approved. Additions omit status (default pending): the lead approves them
-- live. Updates are idempotent and inserts are `on conflict do nothing`: re-applying is a no-op.

update hygieia.recipes set
  image_path = 'recipes/aginares-a-la-polita-artichoke-stew'
where slug = 'aginares-a-la-polita-artichoke-stew';

update hygieia.recipes set
  image_path = 'recipes/almond-buckwheat-banana-bread'
where slug = 'almond-buckwheat-banana-bread';

update hygieia.recipes set
  image_path = 'recipes/almond-milk-rice-pudding'
where slug = 'almond-milk-rice-pudding';

update hygieia.recipes set
  image_path = 'recipes/apple-almond-butter-cinnamon'
where slug = 'apple-almond-butter-cinnamon';

update hygieia.recipes set
  image_path = 'recipes/arakas-latheros-pea-stew'
where slug = 'arakas-latheros-pea-stew';

update hygieia.recipes set
  image_path = 'recipes/avocado-toast-whole-wheat'
where slug = 'avocado-toast-whole-wheat';

update hygieia.recipes set
  image_path = 'recipes/bakaliaros-tiganitos-fried-salt-cod'
where slug = 'bakaliaros-tiganitos-fried-salt-cod';

update hygieia.recipes set
  image_path = 'recipes/baked-egg-casserole-zucchini-spinach'
where slug = 'baked-egg-casserole-zucchini-spinach';

update hygieia.recipes set
  image_path = 'recipes/baked-polenta-tomato-mozzarella'
where slug = 'baked-polenta-tomato-mozzarella';

update hygieia.recipes set
  image_path = 'recipes/baked-sea-bream-lemon-potatoes'
where slug = 'baked-sea-bream-lemon-potatoes';

update hygieia.recipes set
  image_path = 'recipes/bamies-okra-tomato-stew'
where slug = 'bamies-okra-tomato-stew';

update hygieia.recipes set
  image_path = 'recipes/banana-oat-pancakes'
where slug = 'banana-oat-pancakes';

update hygieia.recipes set
  image_path = 'recipes/beef-vegetable-chili-no-beans'
where slug = 'beef-vegetable-chili-no-beans';

update hygieia.recipes set
  image_path = 'recipes/beef-zucchini-ginger-stir-fry-rice'
where slug = 'beef-zucchini-ginger-stir-fry-rice';

update hygieia.recipes set
  image_path = 'recipes/break-the-fast-egg-avocado-feta-plate'
where slug = 'break-the-fast-egg-avocado-feta-plate';

update hygieia.recipes set
  image_path = 'recipes/briam-baked-summer-vegetables'
where slug = 'briam-baked-summer-vegetables';

update hygieia.recipes set
  image_path = 'recipes/buckwheat-banana-pancakes'
where slug = 'buckwheat-banana-pancakes';

update hygieia.recipes set
  image_path = 'recipes/buckwheat-beetroot-walnut-salad'
where slug = 'buckwheat-beetroot-walnut-salad';

update hygieia.recipes set
  image_path = 'recipes/buckwheat-chia-seeded-bread'
where slug = 'buckwheat-chia-seeded-bread';

update hygieia.recipes set
  image_path = 'recipes/carnivore-bacon-and-eggs'
where slug = 'carnivore-bacon-and-eggs';

update hygieia.recipes set
  image_path = 'recipes/carnivore-beef-and-bone-broth-soup'
where slug = 'carnivore-beef-and-bone-broth-soup';

update hygieia.recipes set
  image_path = 'recipes/carnivore-beef-liver-in-butter'
where slug = 'carnivore-beef-liver-in-butter';

update hygieia.recipes set
  image_path = 'recipes/carnivore-beef-mince-cheese-skillet'
where slug = 'carnivore-beef-mince-cheese-skillet';

update hygieia.recipes set
  image_path = 'recipes/carnivore-ghee-scrambled-eggs'
where slug = 'carnivore-ghee-scrambled-eggs';

update hygieia.recipes set
  image_path = 'recipes/carnivore-salmon-in-brown-butter'
where slug = 'carnivore-salmon-in-brown-butter';

update hygieia.recipes set
  image_path = 'recipes/carnivore-salt-crust-pork-belly'
where slug = 'carnivore-salt-crust-pork-belly';

update hygieia.recipes set
  image_path = 'recipes/carnivore-salt-roast-chicken-wings'
where slug = 'carnivore-salt-roast-chicken-wings';

update hygieia.recipes set
  image_path = 'recipes/carnivore-slow-roast-lamb-leg'
where slug = 'carnivore-slow-roast-lamb-leg';

update hygieia.recipes set
  image_path = 'recipes/carnivore-steak-and-eggs'
where slug = 'carnivore-steak-and-eggs';

update hygieia.recipes set
  image_path = 'recipes/carrot-ginger-rice-soup'
where slug = 'carrot-ginger-rice-soup';

update hygieia.recipes set
  image_path = 'recipes/chia-pudding-coconut-strawberry'
where slug = 'chia-pudding-coconut-strawberry';

update hygieia.recipes set
  image_path = 'recipes/chicken-avocado-orange-salad'
where slug = 'chicken-avocado-orange-salad';

update hygieia.recipes set
  image_path = 'recipes/chicken-coconut-curry-rice'
where slug = 'chicken-coconut-curry-rice';

update hygieia.recipes set
  image_path = 'recipes/chickpea-salad-lemon-parsley'
where slug = 'chickpea-salad-lemon-parsley';

update hygieia.recipes set
  image_path = 'recipes/dakos-cretan-rusk-salad'
where slug = 'dakos-cretan-rusk-salad';

update hygieia.recipes set
  image_path = 'recipes/date-oat-energy-balls'
where slug = 'date-oat-energy-balls';

update hygieia.recipes set
  image_path = 'recipes/date-walnut-cocoa-energy-balls'
where slug = 'date-walnut-cocoa-energy-balls';

update hygieia.recipes set
  image_path = 'recipes/dolmadakia-yalantzi-stuffed-vine-leaves'
where slug = 'dolmadakia-yalantzi-stuffed-vine-leaves';

update hygieia.recipes set
  image_path = 'recipes/domatokeftedes-santorini-tomato-fritters'
where slug = 'domatokeftedes-santorini-tomato-fritters';

update hygieia.recipes set
  image_path = 'recipes/fakes-lentil-soup'
where slug = 'fakes-lentil-soup';

update hygieia.recipes set
  image_path = 'recipes/fakorizo-lentils-with-rice'
where slug = 'fakorizo-lentils-with-rice';

update hygieia.recipes set
  image_path = 'recipes/fasolada-white-bean-soup'
where slug = 'fasolada-white-bean-soup';

update hygieia.recipes set
  image_path = 'recipes/fasolakia-ladera-green-bean-stew'
where slug = 'fasolakia-ladera-green-bean-stew';

update hygieia.recipes set
  image_path = 'recipes/fava-santorini-yellow-split-pea-puree'
where slug = 'fava-santorini-yellow-split-pea-puree';

update hygieia.recipes set
  image_path = 'recipes/fish-taco-bowls-cabbage-slaw'
where slug = 'fish-taco-bowls-cabbage-slaw';

update hygieia.recipes set
  image_path = 'recipes/fruit-salad-coconut-walnuts'
where slug = 'fruit-salad-coconut-walnuts';

update hygieia.recipes set
  image_path = 'recipes/gemista-stuffed-tomatoes-peppers'
where slug = 'gemista-stuffed-tomatoes-peppers';

update hygieia.recipes set
  image_path = 'recipes/gigantes-plaki-baked-giant-beans'
where slug = 'gigantes-plaki-baked-giant-beans';

update hygieia.recipes set
  image_path = 'recipes/giouvarlakia-avgolemono-meatball-soup'
where slug = 'giouvarlakia-avgolemono-meatball-soup';

update hygieia.recipes set
  image_path = 'recipes/giouvetsi-beef-orzo'
where slug = 'giouvetsi-beef-orzo';

update hygieia.recipes set
  image_path = 'recipes/greek-yoghurt-honey-walnuts-figs'
where slug = 'greek-yoghurt-honey-walnuts-figs';

update hygieia.recipes set
  image_path = 'recipes/green-smoothie-spinach-banana'
where slug = 'green-smoothie-spinach-banana';

update hygieia.recipes set
  image_path = 'recipes/grilled-mackerel-horta-lemon'
where slug = 'grilled-mackerel-horta-lemon';

update hygieia.recipes set
  image_path = 'recipes/grilled-sardines-lemon-oregano'
where slug = 'grilled-sardines-lemon-oregano';

update hygieia.recipes set
  image_path = 'recipes/halloumi-grilled-vegetable-salad'
where slug = 'halloumi-grilled-vegetable-salad';

update hygieia.recipes set
  image_path = 'recipes/halvas-simigdalenios-semolina-halva'
where slug = 'halvas-simigdalenios-semolina-halva';

update hygieia.recipes set
  image_path = 'recipes/high-protein-baked-cod-cherry-tomatoes-capers'
where slug = 'high-protein-baked-cod-cherry-tomatoes-capers';

update hygieia.recipes set
  image_path = 'recipes/high-protein-cottage-cheese-egg-scramble'
where slug = 'high-protein-cottage-cheese-egg-scramble';

update hygieia.recipes set
  image_path = 'recipes/high-protein-egg-white-turkey-omelette'
where slug = 'high-protein-egg-white-turkey-omelette';

update hygieia.recipes set
  image_path = 'recipes/high-protein-grilled-chicken-breast-broccoli'
where slug = 'high-protein-grilled-chicken-breast-broccoli';

update hygieia.recipes set
  image_path = 'recipes/high-protein-skyr-berry-walnut-bowl'
where slug = 'high-protein-skyr-berry-walnut-bowl';

update hygieia.recipes set
  image_path = 'recipes/high-protein-turkey-steak-green-beans'
where slug = 'high-protein-turkey-steak-green-beans';

update hygieia.recipes set
  image_path = 'recipes/high-protein-whey-coffee-shake'
where slug = 'high-protein-whey-coffee-shake';

update hygieia.recipes set
  image_path = 'recipes/horiatiki-greek-village-salad'
where slug = 'horiatiki-greek-village-salad';

update hygieia.recipes set
  image_path = 'recipes/horta-vrasta-boiled-greens'
where slug = 'horta-vrasta-boiled-greens';

update hygieia.recipes set
  image_path = 'recipes/hortopita-lenten-wild-greens-pie'
where slug = 'hortopita-lenten-wild-greens-pie';

update hygieia.recipes set
  image_path = 'recipes/htapodi-kritharaki-octopus-orzo'
where slug = 'htapodi-kritharaki-octopus-orzo';

update hygieia.recipes set
  image_path = 'recipes/hummus-homemade'
where slug = 'hummus-homemade';

update hygieia.recipes set
  image_path = 'recipes/imam-bayildi-stuffed-eggplant'
where slug = 'imam-bayildi-stuffed-eggplant';

update hygieia.recipes set
  image_path = 'recipes/kakavia-fishermans-soup'
where slug = 'kakavia-fishermans-soup';

update hygieia.recipes set
  image_path = 'recipes/kalamarakia-stifado-squid-pearl-onions'
where slug = 'kalamarakia-stifado-squid-pearl-onions';

update hygieia.recipes set
  image_path = 'recipes/keto-avocado-egg-feta-bowl'
where slug = 'keto-avocado-egg-feta-bowl';

update hygieia.recipes set
  image_path = 'recipes/keto-bacon-wrapped-stuffed-chicken-thighs'
where slug = 'keto-bacon-wrapped-stuffed-chicken-thighs';

update hygieia.recipes set
  image_path = 'recipes/keto-baked-cheese-crisps'
where slug = 'keto-baked-cheese-crisps';

update hygieia.recipes set
  image_path = 'recipes/keto-beef-taco-lettuce-wraps'
where slug = 'keto-beef-taco-lettuce-wraps';

update hygieia.recipes set
  image_path = 'recipes/keto-bulletproof-coffee'
where slug = 'keto-bulletproof-coffee';

update hygieia.recipes set
  image_path = 'recipes/keto-cauliflower-cheese-bake'
where slug = 'keto-cauliflower-cheese-bake';

update hygieia.recipes set
  image_path = 'recipes/keto-chicken-cauliflower-rice-bowl'
where slug = 'keto-chicken-cauliflower-rice-bowl';

update hygieia.recipes set
  image_path = 'recipes/keto-chicken-liver-mushrooms-thyme'
where slug = 'keto-chicken-liver-mushrooms-thyme';

update hygieia.recipes set
  image_path = 'recipes/keto-chocolate-almond-fat-bombs'
where slug = 'keto-chocolate-almond-fat-bombs';

update hygieia.recipes set
  image_path = 'recipes/keto-cobb-salad'
where slug = 'keto-cobb-salad';

update hygieia.recipes set
  image_path = 'recipes/keto-cream-cheese-pancakes'
where slug = 'keto-cream-cheese-pancakes';

update hygieia.recipes set
  image_path = 'recipes/keto-deviled-eggs'
where slug = 'keto-deviled-eggs';

update hygieia.recipes set
  image_path = 'recipes/keto-egg-salad-lettuce-wraps'
where slug = 'keto-egg-salad-lettuce-wraps';

update hygieia.recipes set
  image_path = 'recipes/keto-garlic-butter-shrimp-zoodles'
where slug = 'keto-garlic-butter-shrimp-zoodles';

update hygieia.recipes set
  image_path = 'recipes/keto-grilled-halloumi-rocket-walnut-salad'
where slug = 'keto-grilled-halloumi-rocket-walnut-salad';

update hygieia.recipes set
  image_path = 'recipes/keto-grilled-steak-herb-butter'
where slug = 'keto-grilled-steak-herb-butter';

update hygieia.recipes set
  image_path = 'recipes/keto-meatza-mince-crust-pizza'
where slug = 'keto-meatza-mince-crust-pizza';

update hygieia.recipes set
  image_path = 'recipes/keto-pork-chops-mustard-cream-sauce'
where slug = 'keto-pork-chops-mustard-cream-sauce';

update hygieia.recipes set
  image_path = 'recipes/keto-smoked-salmon-egg-avocado-plate'
where slug = 'keto-smoked-salmon-egg-avocado-plate';

update hygieia.recipes set
  image_path = 'recipes/keto-spinach-feta-omelette'
where slug = 'keto-spinach-feta-omelette';

update hygieia.recipes set
  image_path = 'recipes/keto-tuna-avocado-salad'
where slug = 'keto-tuna-avocado-salad';

update hygieia.recipes set
  image_path = 'recipes/keto-zucchini-noodle-bolognese'
where slug = 'keto-zucchini-noodle-bolognese';

update hygieia.recipes set
  image_path = 'recipes/kolokithokeftedes-zucchini-fritters'
where slug = 'kolokithokeftedes-zucchini-fritters';

update hygieia.recipes set
  image_path = 'recipes/kotosoupa-avgolemono'
where slug = 'kotosoupa-avgolemono';

update hygieia.recipes set
  image_path = 'recipes/lagana-clean-monday-flatbread'
where slug = 'lagana-clean-monday-flatbread';

update hygieia.recipes set
  image_path = 'recipes/lahanorizo-cabbage-rice'
where slug = 'lahanorizo-cabbage-rice';

update hygieia.recipes set
  image_path = 'recipes/lemon-chicken-rice-bowl'
where slug = 'lemon-chicken-rice-bowl';

update hygieia.recipes set
  image_path = 'recipes/lentil-bolognese-whole-wheat-pasta'
where slug = 'lentil-bolognese-whole-wheat-pasta';

update hygieia.recipes set
  image_path = 'recipes/lentil-pasta-tomato-spinach-feta'
where slug = 'lentil-pasta-tomato-spinach-feta';

update hygieia.recipes set
  image_path = 'recipes/lentil-salad-roasted-beetroot-walnuts'
where slug = 'lentil-salad-roasted-beetroot-walnuts';

update hygieia.recipes set
  image_path = 'recipes/low-carb-cauliflower-fried-rice-chicken-egg'
where slug = 'low-carb-cauliflower-fried-rice-chicken-egg';

update hygieia.recipes set
  image_path = 'recipes/low-carb-chicken-caesar-no-croutons'
where slug = 'low-carb-chicken-caesar-no-croutons';

update hygieia.recipes set
  image_path = 'recipes/low-carb-eggplant-mince-graviera-bake'
where slug = 'low-carb-eggplant-mince-graviera-bake';

update hygieia.recipes set
  image_path = 'recipes/low-carb-smoked-salmon-egg-muffins'
where slug = 'low-carb-smoked-salmon-egg-muffins';

update hygieia.recipes set
  image_path = 'recipes/low-carb-zucchini-feta-almond-fritters'
where slug = 'low-carb-zucchini-feta-almond-fritters';

update hygieia.recipes set
  image_path = 'recipes/mavromatika-black-eyed-pea-salad'
where slug = 'mavromatika-black-eyed-pea-salad';

update hygieia.recipes set
  image_path = 'recipes/melitzanosalata-smoky-aubergine-dip'
where slug = 'melitzanosalata-smoky-aubergine-dip';

update hygieia.recipes set
  image_path = 'recipes/moschari-stifado-beef-pearl-onions'
where slug = 'moschari-stifado-beef-pearl-onions';

update hygieia.recipes set
  image_path = 'recipes/moussakas-aubergine-mince-bechamel'
where slug = 'moussakas-aubergine-mince-bechamel';

update hygieia.recipes set
  image_path = 'recipes/mushroom-spinach-omelette'
where slug = 'mushroom-spinach-omelette';

update hygieia.recipes set
  image_path = 'recipes/mydia-achnista-steamed-mussels'
where slug = 'mydia-achnista-steamed-mussels';

update hygieia.recipes set
  image_path = 'recipes/mydopilafo-mussel-rice'
where slug = 'mydopilafo-mussel-rice';

update hygieia.recipes set
  image_path = 'recipes/oat-porridge-banana-walnuts'
where slug = 'oat-porridge-banana-walnuts';

update hygieia.recipes set
  image_path = 'recipes/octopus-xydato-vinegar-oregano'
where slug = 'octopus-xydato-vinegar-oregano';

update hygieia.recipes set
  image_path = 'recipes/overnight-oats-apple-cinnamon'
where slug = 'overnight-oats-apple-cinnamon';

update hygieia.recipes set
  image_path = 'recipes/overnight-oats-peanut-banana'
where slug = 'overnight-oats-peanut-banana';

update hygieia.recipes set
  image_path = 'recipes/paleo-almond-flaxseed-porridge'
where slug = 'paleo-almond-flaxseed-porridge';

update hygieia.recipes set
  image_path = 'recipes/paleo-banana-egg-pancakes'
where slug = 'paleo-banana-egg-pancakes';

update hygieia.recipes set
  image_path = 'recipes/paleo-beef-liver-and-onions'
where slug = 'paleo-beef-liver-and-onions';

update hygieia.recipes set
  image_path = 'recipes/paleo-berry-coconut-smoothie'
where slug = 'paleo-berry-coconut-smoothie';

update hygieia.recipes set
  image_path = 'recipes/paleo-chia-coconut-pudding'
where slug = 'paleo-chia-coconut-pudding';

update hygieia.recipes set
  image_path = 'recipes/paleo-chicken-vegetable-soup-no-rice'
where slug = 'paleo-chicken-vegetable-soup-no-rice';

update hygieia.recipes set
  image_path = 'recipes/paleo-egg-drop-bone-broth-soup'
where slug = 'paleo-egg-drop-bone-broth-soup';

update hygieia.recipes set
  image_path = 'recipes/paleo-keftedes-without-breadcrumbs'
where slug = 'paleo-keftedes-without-breadcrumbs';

update hygieia.recipes set
  image_path = 'recipes/paleo-lamb-chops-rosemary-garlic'
where slug = 'paleo-lamb-chops-rosemary-garlic';

update hygieia.recipes set
  image_path = 'recipes/paleo-lemon-garlic-roast-chicken-thighs'
where slug = 'paleo-lemon-garlic-roast-chicken-thighs';

update hygieia.recipes set
  image_path = 'recipes/paleo-lemon-oregano-roast-goat'
where slug = 'paleo-lemon-oregano-roast-goat';

update hygieia.recipes set
  image_path = 'recipes/paleo-mushroom-spinach-frittata'
where slug = 'paleo-mushroom-spinach-frittata';

update hygieia.recipes set
  image_path = 'recipes/paleo-pork-souvlaki-skewers-no-pita'
where slug = 'paleo-pork-souvlaki-skewers-no-pita';

update hygieia.recipes set
  image_path = 'recipes/paleo-salmon-with-asparagus'
where slug = 'paleo-salmon-with-asparagus';

update hygieia.recipes set
  image_path = 'recipes/paleo-stuffed-peppers-mince-cauliflower-rice'
where slug = 'paleo-stuffed-peppers-mince-cauliflower-rice';

update hygieia.recipes set
  image_path = 'recipes/paleo-sweet-potato-hash-with-eggs'
where slug = 'paleo-sweet-potato-hash-with-eggs';

update hygieia.recipes set
  image_path = 'recipes/paleo-tuna-steak-avocado-salsa'
where slug = 'paleo-tuna-steak-avocado-salsa';

update hygieia.recipes set
  image_path = 'recipes/pantzarosalata-beetroot-garlic-walnuts'
where slug = 'pantzarosalata-beetroot-garlic-walnuts';

update hygieia.recipes set
  image_path = 'recipes/pastitsio-baked-pasta-mince-bechamel'
where slug = 'pastitsio-baked-pasta-mince-bechamel';

update hygieia.recipes set
  image_path = 'recipes/patates-lemonates-lemon-oregano-potatoes'
where slug = 'patates-lemonates-lemon-oregano-potatoes';

update hygieia.recipes set
  image_path = 'recipes/polenta-mushroom-ragout'
where slug = 'polenta-mushroom-ragout';

update hygieia.recipes set
  image_path = 'recipes/pork-tenderloin-roasted-carrots-potatoes'
where slug = 'pork-tenderloin-roasted-carrots-potatoes';

update hygieia.recipes set
  image_path = 'recipes/prasorizo-leeks-with-rice'
where slug = 'prasorizo-leeks-with-rice';

update hygieia.recipes set
  image_path = 'recipes/psari-plaki-baked-cod-tomato-onion'
where slug = 'psari-plaki-baked-cod-tomato-onion';

update hygieia.recipes set
  image_path = 'recipes/pumpkin-red-lentil-soup'
where slug = 'pumpkin-red-lentil-soup';

update hygieia.recipes set
  image_path = 'recipes/pumpkin-sage-risotto'
where slug = 'pumpkin-sage-risotto';

update hygieia.recipes set
  image_path = 'recipes/quinoa-black-bean-sweet-potato-bowl'
where slug = 'quinoa-black-bean-sweet-potato-bowl';

update hygieia.recipes set
  image_path = 'recipes/quinoa-porridge-orange-walnuts'
where slug = 'quinoa-porridge-orange-walnuts';

update hygieia.recipes set
  image_path = 'recipes/quinoa-roasted-vegetable-feta-bowl'
where slug = 'quinoa-roasted-vegetable-feta-bowl';

update hygieia.recipes set
  image_path = 'recipes/quinoa-tabbouleh'
where slug = 'quinoa-tabbouleh';

update hygieia.recipes set
  image_path = 'recipes/revithada-sifnos-baked-chickpeas'
where slug = 'revithada-sifnos-baked-chickpeas';

update hygieia.recipes set
  image_path = 'recipes/revithokeftedes-chickpea-fritters'
where slug = 'revithokeftedes-chickpea-fritters';

update hygieia.recipes set
  image_path = 'recipes/rice-cakes-peanut-butter-banana'
where slug = 'rice-cakes-peanut-butter-banana';

update hygieia.recipes set
  image_path = 'recipes/rice-cakes-smoked-salmon-egg'
where slug = 'rice-cakes-smoked-salmon-egg';

update hygieia.recipes set
  image_path = 'recipes/rice-noodle-tofu-peanut-salad'
where slug = 'rice-noodle-tofu-peanut-salad';

update hygieia.recipes set
  image_path = 'recipes/roasted-cauliflower-tahini-pomegranate'
where slug = 'roasted-cauliflower-tahini-pomegranate';

update hygieia.recipes set
  image_path = 'recipes/roasted-chickpeas-paprika-cumin'
where slug = 'roasted-chickpeas-paprika-cumin';

update hygieia.recipes set
  image_path = 'recipes/salmon-quinoa-broccoli-bowl'
where slug = 'salmon-quinoa-broccoli-bowl';

update hygieia.recipes set
  image_path = 'recipes/seasonal-fruit-salad-walnuts'
where slug = 'seasonal-fruit-salad-walnuts';

update hygieia.recipes set
  image_path = 'recipes/sheet-pan-chicken-sweet-potato-broccoli'
where slug = 'sheet-pan-chicken-sweet-potato-broccoli';

update hygieia.recipes set
  image_path = 'recipes/sheet-pan-salmon-asparagus-potatoes'
where slug = 'sheet-pan-salmon-asparagus-potatoes';

update hygieia.recipes set
  image_path = 'recipes/shrimp-lemon-risotto'
where slug = 'shrimp-lemon-risotto';

update hygieia.recipes set
  image_path = 'recipes/shrimp-saganaki-feta-ouzo'
where slug = 'shrimp-saganaki-feta-ouzo';

update hygieia.recipes set
  image_path = 'recipes/skordalia-garlic-potato-dip'
where slug = 'skordalia-garlic-potato-dip';

update hygieia.recipes set
  image_path = 'recipes/skyr-berry-oat-bowl'
where slug = 'skyr-berry-oat-bowl';

update hygieia.recipes set
  image_path = 'recipes/skyr-bowl-kiwi-strawberry'
where slug = 'skyr-bowl-kiwi-strawberry';

update hygieia.recipes set
  image_path = 'recipes/smoked-salmon-skyr-toast'
where slug = 'smoked-salmon-skyr-toast';

update hygieia.recipes set
  image_path = 'recipes/socca-roasted-peppers-rocket'
where slug = 'socca-roasted-peppers-rocket';

update hygieia.recipes set
  image_path = 'recipes/soupies-me-spanaki-cuttlefish-spinach'
where slug = 'soupies-me-spanaki-cuttlefish-spinach';

update hygieia.recipes set
  image_path = 'recipes/soutzoukakia-smyrneika'
where slug = 'soutzoukakia-smyrneika';

update hygieia.recipes set
  image_path = 'recipes/spaghetti-tomato-garlic-basil'
where slug = 'spaghetti-tomato-garlic-basil';

update hygieia.recipes set
  image_path = 'recipes/spanakopita-spinach-feta-pie'
where slug = 'spanakopita-spinach-feta-pie';

update hygieia.recipes set
  image_path = 'recipes/spanakorizo-spinach-rice'
where slug = 'spanakorizo-spinach-rice';

update hygieia.recipes set
  image_path = 'recipes/strapatsada-tomato-scrambled-eggs'
where slug = 'strapatsada-tomato-scrambled-eggs';

update hygieia.recipes set
  image_path = 'recipes/sweet-potato-hash-eggs'
where slug = 'sweet-potato-hash-eggs';

update hygieia.recipes set
  image_path = 'recipes/tahini-petimezi-toast'
where slug = 'tahini-petimezi-toast';

update hygieia.recipes set
  image_path = 'recipes/tahinosoupa-lenten-tahini-soup'
where slug = 'tahinosoupa-lenten-tahini-soup';

update hygieia.recipes set
  image_path = 'recipes/taramosalata-fish-roe-dip'
where slug = 'taramosalata-fish-roe-dip';

update hygieia.recipes set
  image_path = 'recipes/tofu-scramble-turmeric-peppers'
where slug = 'tofu-scramble-turmeric-peppers';

update hygieia.recipes set
  image_path = 'recipes/tofu-souvlaki-skewers-pita'
where slug = 'tofu-souvlaki-skewers-pita';

update hygieia.recipes set
  image_path = 'recipes/trahana-soup-feta'
where slug = 'trahana-soup-feta';

update hygieia.recipes set
  image_path = 'recipes/tuna-potato-green-bean-salad'
where slug = 'tuna-potato-green-bean-salad';

update hygieia.recipes set
  image_path = 'recipes/tuna-white-bean-salad'
where slug = 'tuna-white-bean-salad';

update hygieia.recipes set
  image_path = 'recipes/turkey-spinach-breakfast-patties'
where slug = 'turkey-spinach-breakfast-patties';

update hygieia.recipes set
  image_path = 'recipes/tzatziki'
where slug = 'tzatziki';

