// SKINCARE SEED — ROUTINES (P7.1, PLAN.md §P7 `skincare_routines`). One routine per (area, audience,
// skin type, region style, time) cell the page offers: face routines for men / women × five skin
// types × AM / PM, each written in one regional STYLE — kr layering (toner → essence → serum →
// emulsion → sleeping mask), eu minimal / dermo-pharmacy (few steps, barrier first), us clinical
// actives (BHA, retinoids, benzoyl peroxide, mineral SPF), jp lightweight (watery gel textures,
// enzyme powders) — plus four nail routines (operator addition 2026-10-06), weekly or evening.
//
// Steps are an ORDERED array; `order` is 1-based and equals the index + 1 (the test and the
// generator check it). Every `product_type_slug` is a slug of ./product-types.ts — the seed test,
// the generator and the gate's jsonb scan all assert it resolves. `optional` marks the steps a
// beginner can skip without breaking the routine.
//
// Not medical advice: anything prescription-only says so in its note; persistent problems → "see a
// dermatologist". Plain data on purpose (node type stripping imports this from scripts/*.mjs).

import type { SkincareRoutineSeed } from '../../types.ts'

export const SKINCARE_ROUTINES: readonly SkincareRoutineSeed[] = [
  // --- men · face ---------------------------------------------------------------------------------
  {
    slug: 'face-men-normal-am-jp',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για άντρες, κανονική επιδερμίδα — ιαπωνικό στιλ',
    name_en: 'Men’s morning routine, normal skin — Japanese style',
    audience: 'men',
    skin_type: 'normal',
    region: 'jp',
    time: 'am',
    intro_el:
      'Τέσσερα ελαφριά βήματα που δεν «νιώθονται» πάνω στο δέρμα: καθαρισμός, ένα υδατικό στρώμα, γαλάκτωμα και το πιο υδαρές αντηλιακό της αγοράς. Πέντε λεπτά και είσαι έτοιμος.',
    intro_en:
      'Four light steps you will not feel on your skin: cleanse, one watery layer, an emulsion and the most water-like sunscreen on the market. Five minutes and you are done.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Χλιαρό νερό, 30 δευτερόλεπτα, χωρίς τρίψιμο.',
        note_en: 'Lukewarm water, 30 seconds, no scrubbing.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'toner-hydrating',
        note_el: 'Λίγες σταγόνες στις παλάμες και πίεσε στο νωπό δέρμα.',
        note_en: 'A few drops in your palms, pressed into damp skin.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Μια δόση όσο ένα φουντούκι, μέχρι τον λαιμό.',
        note_en: 'A hazelnut-sized amount, down to the neck.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-jp-gel-watery',
        note_el: 'Δύο δάχτυλα ποσότητα· άφησέ το ένα λεπτό πριν βγεις.',
        note_en: 'Two finger-lengths; give it a minute before heading out.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'lip-balm-spf',
        note_el: 'Τα χείλη καίγονται πρώτα στον ελληνικό ήλιο.',
        note_en: 'Lips burn first under the Greek sun.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-men-normal-pm-eu',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για άντρες, κανονική επιδερμίδα — ευρωπαϊκό μίνιμαλ',
    name_en: 'Men’s evening routine, normal skin — European minimal',
    audience: 'men',
    skin_type: 'normal',
    region: 'eu',
    time: 'pm',
    intro_el:
      'Η λογική του ευρωπαϊκού φαρμακείου: λίγα προϊόντα, χωρίς άρωμα, με έμφαση στον φραγμό. Καθάρισε, πρόσθεσε ένα ήπιο ενεργό αν θέλεις, σφράγισε με κρέμα.',
    intro_en:
      'The European pharmacy logic: few products, fragrance-free, barrier first. Cleanse, add one gentle active if you like, seal with a cream.',
    duration_min: 6,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-micellar-water',
        note_el: 'Μόνο αν φόρεσες αντηλιακό ή ίδρωσες πολύ· αλλιώς πήγαινε στο βήμα 2.',
        note_en: 'Only if you wore sunscreen or sweated a lot; otherwise go to step 2.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Ένα λεπτό μασάζ, ξέβγαλμα, ταμπονάρισμα με καθαρή πετσέτα.',
        note_en: 'A one-minute massage, rinse, pat dry with a clean towel.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'serum-niacinamide',
        note_el: 'Τρεις-τέσσερις σταγόνες· το πιο ανεκτό «ενεργό» για αρχή.',
        note_en: 'Three or four drops; the best-tolerated active to start with.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Πιο γενναιόδωρα τον χειμώνα με τη θέρμανση.',
        note_en: 'More generously in winter when the heating is on.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-dry-am-eu',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για άντρες, ξηρή επιδερμίδα — ευρωπαϊκό μίνιμαλ',
    name_en: 'Men’s morning routine, dry skin — European minimal',
    audience: 'men',
    skin_type: 'dry',
    region: 'eu',
    time: 'am',
    intro_el:
      'Η ξηρή επιδερμίδα δεν χρειάζεται δυνατό πρωινό καθάρισμα· χρειάζεται νερό, λιπίδια και αντηλιακό υψηλής προστασίας με τα σύγχρονα ευρωπαϊκά φίλτρα.',
    intro_en:
      'Dry skin does not need a strong morning wash; it needs water, lipids and a high-protection sunscreen with the modern European filters.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Ή μόνο χλιαρό νερό, αν το δέρμα το προτιμά.',
        note_en: 'Or lukewarm water alone, if your skin prefers it.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'serum-hyaluronic-acid',
        note_el: 'Σε νωπό δέρμα — αυτό είναι το μυστικό του.',
        note_en: 'On damp skin — that is the whole trick.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Περίμενε να απορροφηθεί πριν το αντηλιακό.',
        note_en: 'Let it absorb before the sunscreen.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-eu-modern-filters',
        note_el: 'SPF 50+ με τον κύκλο UVA στη συσκευασία.',
        note_en: 'SPF 50+ with the UVA circle on the pack.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-dry-pm-kr',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για άντρες, ξηρή επιδερμίδα — κορεατικές στρώσεις',
    name_en: 'Men’s evening routine, dry skin — Korean layering',
    audience: 'men',
    skin_type: 'dry',
    region: 'kr',
    time: 'pm',
    intro_el:
      'Η κορεατική προσέγγιση για ξηρή επιδερμίδα: πολλές λεπτές υδατικές στρώσεις αντί για μία παχιά κρέμα. Κάθε στρώση «πατάει» στην προηγούμενη όσο είναι ακόμη νωπή.',
    intro_en:
      'The Korean approach to dry skin: many thin watery layers instead of one thick cream. Each layer goes on while the previous one is still damp.',
    duration_min: 12,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Πρώτος καθαρισμός, μόνο αν φόρεσες αντηλιακό.',
        note_en: 'First cleanse, only if you wore sunscreen.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Δεύτερος καθαρισμός, ήπιος.',
        note_en: 'Second cleanse, gentle.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'toner-hydrating',
        note_el: 'Δύο στρώσεις, με τις παλάμες.',
        note_en: 'Two layers, with your palms.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'serum-snail-mucin',
        note_el: 'Κολλώδες στην αρχή — απορροφάται σε ένα λεπτό.',
        note_en: 'Tacky at first — it sinks in within a minute.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Σφράγισε όλες τις στρώσεις.',
        note_en: 'Seal every layer in.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'moisturizer-occlusive-balm',
        note_el: 'Λεπτή στρώση στα μάγουλα τις πολύ ξηρές νύχτες.',
        note_en: 'A thin layer on the cheeks on very dry nights.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-men-oily-am-us',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για άντρες, λιπαρή επιδερμίδα — αμερικανικά «ενεργά»',
    name_en: 'Men’s morning routine, oily skin — US actives',
    audience: 'men',
    skin_type: 'oily',
    region: 'us',
    time: 'am',
    intro_el:
      'Καθαρισμός, ένα συστατικό που ρυθμίζει το σμήγμα, ενυδάτωση χωρίς έλαια και ορυκτό αντηλιακό που δεν γυαλίζει. Αν ξυρίστηκες, το βάλσαμο μετά το ξύρισμα μπαίνει πριν την ενυδατική.',
    intro_en:
      'Cleanse, one sebum-regulating ingredient, oil-free hydration and a mineral sunscreen that does not shine. If you shaved, the aftershave balm goes on before the moisturiser.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Μετά το ντους ή το ξύρισμα.',
        note_en: 'After the shower or shave.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'shaving-aftershave-balm',
        note_el: 'Μόνο τις μέρες που ξυρίζεσαι.',
        note_en: 'Only on the days you shave.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'serum-niacinamide',
        note_el: 'Λιγότερη γυαλάδα μέσα στη μέρα μετά από λίγες εβδομάδες.',
        note_en: 'Less midday shine after a few weeks.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Ναι, και η λιπαρή επιδερμίδα ενυδατώνεται.',
        note_en: 'Yes, oily skin gets moisturised too.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'sunscreen-mineral-zinc',
        note_el: 'Ματ φινίρισμα· διάλεξε «tinted» αν σε ενοχλεί το λευκό ίχνος.',
        note_en: 'Matte finish; pick a tinted one if the white cast bothers you.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-oily-pm-kr',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για άντρες, λιπαρή επιδερμίδα — κορεατικό στιλ',
    name_en: 'Men’s evening routine, oily skin — Korean style',
    audience: 'men',
    skin_type: 'oily',
    region: 'kr',
    time: 'pm',
    intro_el:
      'Διπλός καθαρισμός για να φύγει το αντηλιακό της μέρας, ήπια απολέπιση 2–3 φορές την εβδομάδα και καταπραϋντικές στρώσεις αντί για «στέγνωμα». Η κορεατική λογική για τη λιπαρή επιδερμίδα είναι ισορροπία, όχι πόλεμος.',
    intro_en:
      'A double cleanse to remove the day’s sunscreen, gentle exfoliation two or three times a week and soothing layers instead of “drying out”. The Korean logic for oily skin is balance, not war.',
    duration_min: 12,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Ναι, λάδι σε λιπαρή επιδερμίδα: διαλύει σμήγμα και αντηλιακό.',
        note_en: 'Yes, oil on oily skin: it dissolves sebum and sunscreen.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Δεύτερος καθαρισμός.',
        note_en: 'Second cleanse.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'toner-exfoliating-bha',
        note_el: '2–3 βράδια την εβδομάδα, όχι κάθε μέρα.',
        note_en: 'Two or three evenings a week, not daily.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'toner-hydrating',
        note_el: 'Τα υπόλοιπα βράδια, ή μετά το BHA αφού στεγνώσει.',
        note_en: 'On the other evenings, or after the BHA once it has dried.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'serum-centella-cica',
        note_el: 'Ηρεμεί κοκκινίλες από σπυράκια και ξύρισμα.',
        note_en: 'Calms redness from spots and shaving.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Λεπτή στρώση.',
        note_en: 'A thin layer.',
        optional: false,
      },
      {
        order: 7,
        product_type_slug: 'treatment-hydrocolloid-patch',
        note_el: 'Πάνω σε σπυράκι με «κεφάλι», τελευταίο βήμα.',
        note_en: 'On a spot with a head, as the last step.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-men-combination-am-jp',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για άντρες, μικτή επιδερμίδα — ιαπωνικό στιλ',
    name_en: 'Men’s morning routine, combination skin — Japanese style',
    audience: 'men',
    skin_type: 'combination',
    region: 'jp',
    time: 'am',
    intro_el:
      'Λιπαρή ζώνη Τ και πιο ξηρά μάγουλα: η ιαπωνική απάντηση είναι υφές που ενυδατώνουν χωρίς βάρος και ένα αντηλιακό σαν νερό που δεν φράζει τους πόρους.',
    intro_en:
      'An oily T-zone and drier cheeks: the Japanese answer is textures that hydrate without weight and a water-like sunscreen that does not clog.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Επικεντρώσου στη ζώνη Τ, πέρνα απαλά από τα μάγουλα.',
        note_en: 'Focus on the T-zone, go lightly over the cheeks.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'toner-hydrating',
        note_el: 'Μία στρώση παντού.',
        note_en: 'One layer all over.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Λίγο περισσότερο στα μάγουλα.',
        note_en: 'A little more on the cheeks.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-jp-gel-watery',
        note_el: 'Ξαναβάλε το μεσημέρι αν είσαι έξω.',
        note_en: 'Reapply at midday if you are outdoors.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-combination-pm-us',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για άντρες, μικτή επιδερμίδα — αμερικανικά «ενεργά»',
    name_en: 'Men’s evening routine, combination skin — US actives',
    audience: 'men',
    skin_type: 'combination',
    region: 'us',
    time: 'pm',
    intro_el:
      'Ένα «ενεργό» κάθε βράδυ, ποτέ δύο μαζί: BHA τις μισές μέρες της εβδομάδας, ρετινόλη τις άλλες, και ενυδάτωση πάντα. Αυτή η εναλλαγή είναι ο πυρήνας της αμερικανικής ρουτίνας.',
    intro_en:
      'One active per evening, never two together: BHA half the week, retinol the other half, and moisturiser always. That alternation is the core of the US routine.',
    duration_min: 8,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Στέγνωσε καλά — η ρετινόλη μπαίνει σε στεγνό δέρμα.',
        note_en: 'Dry well — retinol goes on dry skin.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'exfoliant-bha-salicylic',
        note_el: 'Δευτέρα, Τετάρτη, Παρασκευή: μόνο στη ζώνη Τ.',
        note_en: 'Monday, Wednesday, Friday: T-zone only.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'serum-retinol',
        note_el: 'Τρίτη, Πέμπτη, Σάββατο· ένα μπιζέλι για όλο το πρόσωπο.',
        note_en: 'Tuesday, Thursday, Saturday; a pea-sized amount for the whole face.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'eye-cream-caffeine',
        note_el: 'Προαιρετικό· μια απλή ενυδατική κάνει σχεδόν το ίδιο.',
        note_en: 'Optional; a plain moisturiser does nearly the same.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Κυριακή: μόνο καθαρισμός και ενυδατική — ρεπό για το δέρμα.',
        note_en: 'Sunday: just cleanse and moisturise — a rest day for the skin.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-sensitive-am-eu',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για άντρες, ευαίσθητη επιδερμίδα — ξύρισμα χωρίς ερεθισμό',
    name_en: 'Men’s morning routine, sensitive skin — irritation-free shave',
    audience: 'men',
    skin_type: 'sensitive',
    region: 'eu',
    time: 'am',
    intro_el:
      'Για το ευαίσθητο δέρμα το πρόβλημα του πρωινού είναι συνήθως το ξύρισμα. Λάδι πριν, κρέμα με πινέλο, βάλσαμο μετά, κρέμα φραγμού και ορυκτό αντηλιακό χωρίς άρωμα.',
    intro_en:
      'For sensitive skin the morning problem is usually the shave. Oil before, brush-lathered cream, balm after, a barrier cream and a fragrance-free mineral sunscreen.',
    duration_min: 10,
    steps: [
      {
        order: 1,
        product_type_slug: 'shaving-pre-shave-oil',
        note_el: 'Μετά το ντους, σε νωπή τρίχα.',
        note_en: 'After the shower, on damp stubble.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'shaving-cream-brush',
        note_el: 'Ξύρισε με τη φορά της τρίχας, καθαρή λεπίδα.',
        note_en: 'Shave with the grain, fresh blade.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'shaving-aftershave-balm',
        note_el: 'Κρύο ξέβγαλμα, μετά το βάλσαμο· τίποτα με οινόπνευμα.',
        note_en: 'Cold rinse, then the balm; nothing with alcohol.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Τις μέρες χωρίς ξύρισμα: μόνο νερό, κρέμα, αντηλιακό.',
        note_en: 'On non-shave days: just water, cream, sunscreen.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'sunscreen-mineral-zinc',
        note_el: 'Τα ορυκτά φίλτρα τσούζουν λιγότερο σε φρεσκοξυρισμένο δέρμα.',
        note_en: 'Mineral filters sting less on freshly shaved skin.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-men-sensitive-pm-eu',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για άντρες, ευαίσθητη επιδερμίδα — επισκευή φραγμού',
    name_en: 'Men’s evening routine, sensitive skin — barrier repair',
    audience: 'men',
    skin_type: 'sensitive',
    region: 'eu',
    time: 'pm',
    intro_el:
      'Το βράδυ του ευαίσθητου δέρματος είναι για ξεκούραση: ήπιος καθαρισμός, ένα καταπραϋντικό και λιπίδια. Κανένα οξύ, καμία ρετινόλη μέχρι να ηρεμήσει η κοκκινίλα για δύο εβδομάδες.',
    intro_en:
      'Sensitive skin’s evening is for rest: a gentle cleanse, one soother and lipids. No acid, no retinol until the redness has been quiet for two weeks.',
    duration_min: 6,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Χωρίς άρωμα· ξέβγαλμα με χλιαρό, όχι ζεστό νερό.',
        note_en: 'Fragrance-free; rinse with lukewarm, not hot, water.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'serum-centella-cica',
        note_el: 'Ή αζελαϊκό 10 % αν έχεις και σπυράκια.',
        note_en: 'Or 10 % azelaic acid if you also get spots.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Γενναιόδωρα.',
        note_en: 'Generously.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-occlusive-balm',
        note_el: 'Στα σημεία που ξεφλουδίζουν, τις νύχτες με θέρμανση.',
        note_en: 'On the flaky patches, on nights with the heating on.',
        optional: true,
      },
    ],
  },

  // --- women · face --------------------------------------------------------------------------------
  {
    slug: 'face-women-normal-am-kr',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για γυναίκες, κανονική επιδερμίδα — κορεατικό στιλ',
    name_en: 'Women’s morning routine, normal skin — Korean style',
    audience: 'women',
    skin_type: 'normal',
    region: 'kr',
    time: 'am',
    intro_el:
      'Η πρωινή κορεατική ρουτίνα είναι πιο σύντομη από τη βραδινή: καθαρισμός, υδατικές στρώσεις, προαιρετικά βιταμίνη C, γαλάκτωμα και αντηλιακό PA++++. Όλα ελαφριά, για να κάθεται καλά και το μακιγιάζ.',
    intro_en:
      'The Korean morning routine is shorter than the evening one: cleanse, watery layers, optional vitamin C, emulsion and a PA++++ sunscreen. All light, so make-up sits well on top.',
    duration_min: 8,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Ή μόνο νερό αν το δέρμα είναι ήρεμο το πρωί.',
        note_en: 'Or water alone if your skin is calm in the morning.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'toner-hydrating',
        note_el: 'Δύο λεπτές στρώσεις.',
        note_en: 'Two thin layers.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'essence-hydrating',
        note_el: 'Πίεσε με τις παλάμες, μην τρίβεις.',
        note_en: 'Press in with your palms, do not rub.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'serum-vitamin-c',
        note_el: 'Το πρωινό αντιοξειδωτικό κάτω από το αντηλιακό.',
        note_en: 'The morning antioxidant under your sunscreen.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Περίμενε ένα λεπτό πριν το αντηλιακό.',
        note_en: 'Wait a minute before the sunscreen.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'sunscreen-kr-pa-plus',
        note_el: 'Δύο δάχτυλα ποσότητα· η ελαφριά υφή ξεγελά.',
        note_en: 'Two finger-lengths; the light texture is deceptive.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-women-normal-pm-jp',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για γυναίκες, κανονική επιδερμίδα — ιαπωνικό στιλ',
    name_en: 'Women’s evening routine, normal skin — Japanese style',
    audience: 'women',
    skin_type: 'normal',
    region: 'jp',
    time: 'pm',
    intro_el:
      'Διπλός καθαρισμός, μία φορά την εβδομάδα ενζυμική σκόνη, μια «πρώτη essence» με ζυμωμένα εκχυλίσματα και ελαφριές ενυδατικές στρώσεις. Η ιαπωνική ρουτίνα κυνηγά υφή και λάμψη, όχι πολλά βήματα.',
    intro_en:
      'A double cleanse, an enzyme powder once a week, a fermented “first essence” and light hydrating layers. The Japanese routine chases texture and glow, not step count.',
    duration_min: 12,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Σε στεγνό πρόσωπο, μετά γαλακτωματοποίησε με λίγο νερό.',
        note_en: 'On a dry face, then emulsify with a little water.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Δεύτερος καθαρισμός.',
        note_en: 'Second cleanse.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'exfoliant-enzyme-powder',
        note_el: 'Μία φορά την εβδομάδα στη θέση του δεύτερου καθαρισμού.',
        note_en: 'Once a week in place of the second cleanse.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'essence-first-treatment',
        note_el: 'Λίγες σταγόνες, ταμπονάρισμα με τις παλάμες.',
        note_en: 'A few drops, patted in with your palms.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'serum-hyaluronic-acid',
        note_el: 'Όσο το δέρμα είναι ακόμη νωπό.',
        note_en: 'While the skin is still damp.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Κρέμα από πάνω τον χειμώνα.',
        note_en: 'Add a cream on top in winter.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-women-dry-am-eu',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για γυναίκες, ξηρή επιδερμίδα — ευρωπαϊκό μίνιμαλ',
    name_en: 'Women’s morning routine, dry skin — European minimal',
    audience: 'women',
    skin_type: 'dry',
    region: 'eu',
    time: 'am',
    intro_el:
      'Νερό και λιπίδια πριν από οτιδήποτε άλλο, και αντηλιακό υψηλής προστασίας που ταυτόχρονα ενυδατώνει. Το μακιγιάζ κάθεται καλύτερα σε δέρμα που δεν «τραβάει».',
    intro_en:
      'Water and lipids before anything else, and a high-protection sunscreen that also moisturises. Make-up sits better on skin that is not tight.',
    duration_min: 6,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Ή μόνο χλιαρό νερό.',
        note_en: 'Or lukewarm water alone.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'serum-hyaluronic-acid',
        note_el: 'Σε νωπό δέρμα, πάντα με κρέμα από πάνω.',
        note_en: 'On damp skin, always with a cream on top.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Μέχρι τον λαιμό και το ντεκολτέ.',
        note_en: 'Down to the neck and chest.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-eu-modern-filters',
        note_el: 'Οι ενυδατικές εκδοχές «για ξηρή επιδερμίδα» λειτουργούν και ως βάση.',
        note_en: 'The moisturising “dry skin” versions double as a primer.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'lip-balm-spf',
        note_el: 'Πριν το κραγιόν.',
        note_en: 'Before lipstick.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-women-dry-pm-kr',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για γυναίκες, ξηρή επιδερμίδα — κορεατικές στρώσεις',
    name_en: 'Women’s evening routine, dry skin — Korean layering',
    audience: 'women',
    skin_type: 'dry',
    region: 'kr',
    time: 'pm',
    intro_el:
      'Η πλήρης κορεατική εμπειρία για ξηρή επιδερμίδα: διπλός καθαρισμός, τόνερ σε στρώσεις, essence, ορός σαλιγκαριού, κρέμα και, δύο-τρεις νύχτες την εβδομάδα, μάσκα ύπνου.',
    intro_en:
      'The full Korean experience for dry skin: double cleanse, layered toner, essence, snail serum, cream and, two or three nights a week, a sleeping mask.',
    duration_min: 15,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Διαλύει μακιγιάζ και αντηλιακό χωρίς τρίψιμο.',
        note_en: 'Dissolves make-up and sunscreen without rubbing.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Δεύτερος καθαρισμός.',
        note_en: 'Second cleanse.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'toner-hydrating',
        note_el: 'Τρεις στρώσεις — η «μέθοδος 7 στρώσεων» σε λογική εκδοχή.',
        note_en: 'Three layers — the “7-skin method”, within reason.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'essence-hydrating',
        note_el: 'Πίεσε, μην τρίβεις.',
        note_en: 'Press, do not rub.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'serum-snail-mucin',
        note_el: 'Ενυδάτωση και επούλωση μικροσημαδιών.',
        note_en: 'Hydration and healing of small marks.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Σφράγισμα.',
        note_en: 'Seal.',
        optional: false,
      },
      {
        order: 7,
        product_type_slug: 'mask-sleeping-overnight',
        note_el: '2–3 νύχτες την εβδομάδα στη θέση της κρέμας.',
        note_en: 'Two or three nights a week instead of the cream.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-women-oily-am-us',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για γυναίκες, λιπαρή επιδερμίδα — αμερικανικά «ενεργά»',
    name_en: 'Women’s morning routine, oily skin — US actives',
    audience: 'women',
    skin_type: 'oily',
    region: 'us',
    time: 'am',
    intro_el:
      'Καθαρισμός, βιταμίνη C ή νιασιναμίδη, ενυδάτωση χωρίς έλαια και ορυκτό αντηλιακό με ματ φινίρισμα — μια βάση που κρατά το μακιγιάζ στη θέση του ως το μεσημέρι.',
    intro_en:
      'Cleanse, vitamin C or niacinamide, oil-free hydration and a matte mineral sunscreen — a base that keeps make-up in place until midday.',
    duration_min: 6,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Χλιαρό νερό· το ζεστό αυξάνει το σμήγμα.',
        note_en: 'Lukewarm water; hot water drives sebum up.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'serum-vitamin-c',
        note_el: 'Εναλλακτικά νιασιναμίδη αν η C τσούζει.',
        note_en: 'Or niacinamide if vitamin C stings.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'serum-niacinamide',
        note_el: 'Ρυθμίζει τη γυαλάδα και τους πόρους.',
        note_en: 'Regulates shine and pores.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Λεπτή στρώση.',
        note_en: 'A thin layer.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'sunscreen-mineral-zinc',
        note_el: 'Με οξείδια σιδήρου (tinted) αν έχεις και κηλίδες.',
        note_en: 'With iron oxides (tinted) if you also have dark spots.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-women-oily-pm-us',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για γυναίκες, λιπαρή επιδερμίδα — αμερικανικά «ενεργά»',
    name_en: 'Women’s evening routine, oily skin — US actives',
    audience: 'women',
    skin_type: 'oily',
    region: 'us',
    time: 'pm',
    intro_el:
      'Το βράδυ της λιπαρής επιδερμίδας εναλλάσσει BHA και ρετινόλη, ποτέ την ίδια νύχτα. Ενυδάτωση κάθε φορά, και ένα υδροκολλοειδές επίθεμα για το σπυράκι που ήθελες να πειράξεις.',
    intro_en:
      'Oily skin’s evening alternates BHA and retinol, never on the same night. Moisturiser every time, and a hydrocolloid patch for the spot you were about to pick.',
    duration_min: 8,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Με μακιγιάζ: πρώτα βάλσαμο καθαρισμού ή μικυλλιακό.',
        note_en: 'With make-up on: a cleansing balm or micellar water first.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'exfoliant-bha-salicylic',
        note_el: 'Τρία βράδια την εβδομάδα.',
        note_en: 'Three evenings a week.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'serum-retinol',
        note_el: 'Τα άλλα τρία βράδια· ξεκίνα με χαμηλή συγκέντρωση.',
        note_en: 'The other three evenings; start with a low strength.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Ή κρέμα με κεραμίδια αν η ρετινόλη ξηραίνει.',
        note_en: 'Or a ceramide cream if retinol is drying you out.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'treatment-hydrocolloid-patch',
        note_el: 'Τελευταίο, σε καθαρό στεγνό δέρμα.',
        note_en: 'Last, on clean dry skin.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-women-combination-am-kr',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για γυναίκες, μικτή επιδερμίδα — κορεατικό στιλ',
    name_en: 'Women’s morning routine, combination skin — Korean style',
    audience: 'women',
    skin_type: 'combination',
    region: 'kr',
    time: 'am',
    intro_el:
      'Υδατικές στρώσεις που ενυδατώνουν τα μάγουλα χωρίς να βαραίνουν τη ζώνη Τ, νιασιναμίδη για τους πόρους και ένα ελαφρύ αντηλιακό PA++++ που κάθεται σαν ενυδατική.',
    intro_en:
      'Watery layers that hydrate the cheeks without weighing down the T-zone, niacinamide for pores and a light PA++++ sunscreen that wears like a moisturiser.',
    duration_min: 8,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Απαλά στα μάγουλα.',
        note_en: 'Gently over the cheeks.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'toner-hydrating',
        note_el: 'Δύο στρώσεις.',
        note_en: 'Two layers.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'essence-hydrating',
        note_el: 'Προαιρετικό όταν βιάζεσαι.',
        note_en: 'Optional when you are in a hurry.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'serum-niacinamide',
        note_el: 'Παντού, με έμφαση στη μύτη και το μέτωπο.',
        note_en: 'All over, with focus on the nose and forehead.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Λίγο περισσότερο στα μάγουλα.',
        note_en: 'A little more on the cheeks.',
        optional: false,
      },
      {
        order: 6,
        product_type_slug: 'sunscreen-kr-pa-plus',
        note_el: 'Δύο δάχτυλα ποσότητα.',
        note_en: 'Two finger-lengths.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-women-combination-pm-kr',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για γυναίκες, μικτή επιδερμίδα — κορεατικό στιλ',
    name_en: 'Women’s evening routine, combination skin — Korean style',
    audience: 'women',
    skin_type: 'combination',
    region: 'kr',
    time: 'pm',
    intro_el:
      'Οκτώ βήματα που δεν είναι όλα για κάθε βράδυ: διπλός καθαρισμός, ήπια απολέπιση PHA δύο φορές την εβδομάδα, στρώσεις ενυδάτωσης, καταπραϋντικός ορός και γαλάκτωμα — μάσκα ύπνου όταν το δέρμα το ζητά.',
    intro_en:
      'Eight steps that are not all for every night: double cleanse, gentle PHA twice a week, hydrating layers, a soothing serum and an emulsion — a sleeping mask when the skin asks for it.',
    duration_min: 15,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Πρώτος καθαρισμός.',
        note_en: 'First cleanse.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Δεύτερος καθαρισμός.',
        note_en: 'Second cleanse.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'exfoliant-pha-gentle',
        note_el: 'Δύο βράδια την εβδομάδα.',
        note_en: 'Two evenings a week.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'toner-hydrating',
        note_el: 'Δύο στρώσεις.',
        note_en: 'Two layers.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'essence-hydrating',
        note_el: 'Πίεσε με τις παλάμες.',
        note_en: 'Press in with your palms.',
        optional: true,
      },
      {
        order: 6,
        product_type_slug: 'serum-centella-cica',
        note_el: 'Ηρεμεί τη ζώνη Τ μετά την απολέπιση.',
        note_en: 'Calms the T-zone after exfoliation.',
        optional: false,
      },
      {
        order: 7,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Παντού.',
        note_en: 'All over.',
        optional: false,
      },
      {
        order: 8,
        product_type_slug: 'mask-sleeping-overnight',
        note_el: 'Μόνο στα μάγουλα, δύο νύχτες την εβδομάδα.',
        note_en: 'Cheeks only, two nights a week.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-women-sensitive-am-jp',
    area: 'face',
    name_el: 'Πρωινή ρουτίνα για γυναίκες, ευαίσθητη επιδερμίδα — ιαπωνικό στιλ',
    name_en: 'Women’s morning routine, sensitive skin — Japanese style',
    audience: 'women',
    skin_type: 'sensitive',
    region: 'jp',
    time: 'am',
    intro_el:
      'Λίγα, ήπια, χωρίς άρωμα: η ιαπωνική αγορά έχει ολόκληρες σειρές «για ευαίσθητη επιδερμίδα» με ελάχιστα συστατικά. Το αντηλιακό εδώ είναι ορυκτό — τα υδαρή gel με οινόπνευμα τσούζουν.',
    intro_en:
      'Few, gentle, fragrance-free: the Japanese market has entire “sensitive skin” lines with minimal ingredients. The sunscreen here is mineral — the alcohol-based watery gels sting.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Ή μόνο νερό το πρωί.',
        note_en: 'Or water alone in the morning.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'toner-hydrating',
        note_el: 'Χωρίς οινόπνευμα, χωρίς άρωμα.',
        note_en: 'Alcohol-free, fragrance-free.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Ή κρέμα με κεραμίδια αν έχεις ξεφλούδισμα.',
        note_en: 'Or a ceramide cream if you are flaking.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-mineral-zinc',
        note_el: 'Οξείδιο ψευδαργύρου: καταπραΰνει κιόλας.',
        note_en: 'Zinc oxide: it soothes as well.',
        optional: false,
      },
    ],
  },
  {
    slug: 'face-women-sensitive-pm-eu',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για γυναίκες, ευαίσθητη επιδερμίδα — ευρωπαϊκό δερμοκαλλυντικό',
    name_en: 'Women’s evening routine, sensitive skin — European dermo-cosmetic',
    audience: 'women',
    skin_type: 'sensitive',
    region: 'eu',
    time: 'pm',
    intro_el:
      'Αφαίρεση μακιγιάζ χωρίς τρίψιμο, ήπιος καθαρισμός, αζελαϊκό οξύ για κοκκινίλα και σπυράκια (ασφαλές και στην εγκυμοσύνη) και κρέμα φραγμού. Τέσσερα βήματα, όλα από το φαρμακείο.',
    intro_en:
      'Make-up removal without rubbing, a gentle cleanse, azelaic acid for redness and spots (safe in pregnancy too) and a barrier cream. Four steps, all from the pharmacy.',
    duration_min: 7,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-micellar-water',
        note_el: 'Με βαμβάκι, χωρίς πίεση· ξέβγαλε μετά.',
        note_en: 'On a cotton pad, no pressure; rinse afterwards.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Χλιαρό νερό.',
        note_en: 'Lukewarm water.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'serum-azelaic-acid',
        note_el: 'Ένα ελαφρύ τσούξιμο τις πρώτες μέρες είναι φυσιολογικό.',
        note_en: 'A light tingle in the first days is normal.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Χωρίς άρωμα, γενναιόδωρα.',
        note_en: 'Fragrance-free, generously.',
        optional: false,
      },
    ],
  },

  // --- everyone · face -----------------------------------------------------------------------------
  {
    slug: 'face-all-all-am-us-minimal',
    area: 'face',
    name_el: 'Το πρωινό τριών βημάτων για όλους — αμερικανικό μίνιμαλ',
    name_en: 'The three-step morning for everyone — US minimal',
    audience: 'all',
    skin_type: 'all',
    region: 'us',
    time: 'am',
    intro_el:
      'Αν δεν θέλεις καμία ρουτίνα, κράτα αυτή: καθάρισε, ενυδάτωσε, φόρεσε αντηλιακό. Το αντηλιακό είναι το μόνο βήμα που δεν διαπραγματεύεται κανένας δερματολόγος.',
    intro_en:
      'If you want no routine at all, keep this one: cleanse, moisturise, wear sunscreen. Sunscreen is the one step no dermatologist will negotiate on.',
    duration_min: 3,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Ή κρεμώδες αν η επιδερμίδα σου είναι ξηρή.',
        note_en: 'Or a cream cleanser if your skin is dry.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'serum-niacinamide',
        note_el: 'Το ένα «έξτρα» που αξίζει, όταν το θελήσεις.',
        note_en: 'The one extra worth adding, when you feel like it.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Κρέμα αντί για γαλάκτωμα τον χειμώνα.',
        note_en: 'A cream instead of an emulsion in winter.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'sunscreen-mineral-zinc',
        note_el: 'Κάθε μέρα, και με συννεφιά· τα UVA περνούν τα σύννεφα και τα τζάμια.',
        note_en: 'Every day, clouds included; UVA passes through clouds and glass.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'sunscreen-stick-reapply',
        note_el: 'Στην τσάντα για το μεσημέρι.',
        note_en: 'In your bag for midday.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-all-oily-pm-us-acne',
    area: 'face',
    name_el: 'Βραδινή ρουτίνα για ακμή — αμερικανική «κλινική» προσέγγιση',
    name_en: 'Evening acne routine — US clinical approach',
    audience: 'all',
    skin_type: 'oily',
    region: 'us',
    time: 'pm',
    intro_el:
      'Η ρουτίνα που προτείνουν οι αμερικανικοί οδηγοί για ήπια ως μέτρια ακμή: ήπιος καθαρισμός, υπεροξείδιο του βενζοϋλίου στα σπυράκια, αδαπαλένη παντού, ενυδάτωση. Στην Ελλάδα η αδαπαλένη και το υπεροξείδιο χρειάζονται φαρμακείο ή συνταγή — μίλα με δερματολόγο πριν ξεκινήσεις.',
    intro_en:
      'The routine US guidelines suggest for mild to moderate acne: gentle cleanse, benzoyl peroxide on spots, adapalene all over, moisturise. In Greece adapalene and benzoyl peroxide need a pharmacy or a prescription — talk to a dermatologist before starting.',
    duration_min: 8,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Όχι τρίψιμο, όχι «απολεπιστικά» σφουγγάρια.',
        note_en: 'No scrubbing, no “exfoliating” sponges.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'treatment-benzoyl-peroxide-spot',
        note_el: 'Μόνο στα φλεγμονώδη σπυράκια, 2,5 %· άσπρη πετσέτα.',
        note_en: 'Only on inflamed spots, 2.5 %; use a white towel.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'treatment-adapalene-otc',
        note_el: 'Ένα μπιζέλι για όλο το πρόσωπο, σε στεγνό δέρμα· 4–6 εβδομάδες για αποτέλεσμα.',
        note_en: 'A pea for the whole face, on dry skin; four to six weeks to see results.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-gel-oil-free',
        note_el: 'Κάθε βράδυ, χωρίς εξαίρεση — η ξηρότητα είναι η πρώτη αιτία παραίτησης.',
        note_en: 'Every night, no exception — dryness is the top reason people quit.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'treatment-hydrocolloid-patch',
        note_el: 'Αντί να το πειράξεις.',
        note_en: 'Instead of picking it.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-all-dry-pm-eu-winter',
    area: 'face',
    name_el: 'Χειμερινή επισκευή φραγμού — ευρωπαϊκό δερμοκαλλυντικό',
    name_en: 'Winter barrier repair — European dermo-cosmetic',
    audience: 'all',
    skin_type: 'dry',
    region: 'eu',
    time: 'pm',
    intro_el:
      'Για τις εβδομάδες με θέρμανση, κρύο αέρα και ξεφλούδισμα: καμία απολέπιση, καμία ρετινόλη, μόνο νερό, λιπίδια και ένα κλειστικό στρώμα για να μη χαθεί τίποτα μέσα στη νύχτα.',
    intro_en:
      'For the weeks of heating, cold air and flaking: no exfoliation, no retinol, just water, lipids and an occlusive layer so nothing is lost overnight.',
    duration_min: 7,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-cream-milk',
        note_el: 'Χλιαρό νερό· το ζεστό ντους ξηραίνει.',
        note_en: 'Lukewarm water; a hot shower dries you out.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'serum-hyaluronic-acid',
        note_el: 'Σε νωπό δέρμα.',
        note_en: 'On damp skin.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'moisturizer-cream-ceramide',
        note_el: 'Διπλή δόση.',
        note_en: 'A double dose.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'moisturizer-occlusive-balm',
        note_el: 'Λεπτή στρώση στα μάγουλα και γύρω από τη μύτη.',
        note_en: 'A thin layer on the cheeks and around the nose.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'lip-sleeping-mask',
        note_el: 'Ή απλή βαζελίνη στα χείλη.',
        note_en: 'Or plain petrolatum on the lips.',
        optional: true,
      },
    ],
  },
  {
    slug: 'face-all-all-pm-kr-ten-step',
    area: 'face',
    name_el: 'Η πλήρης κορεατική βραδινή ρουτίνα δέκα βημάτων',
    name_en: 'The full ten-step Korean evening routine',
    audience: 'all',
    skin_type: 'all',
    region: 'kr',
    time: 'pm',
    intro_el:
      'Η διάσημη ρουτίνα των δέκα βημάτων, όπως γίνεται στην πράξη: τα μισά βήματα είναι προαιρετικά και κανείς δεν τα κάνει όλα κάθε βράδυ. Είναι ένα μενού, όχι μια λίστα υποχρεώσεων.',
    intro_en:
      'The famous ten-step routine as it is actually done: half the steps are optional and nobody does all of them every night. It is a menu, not a checklist.',
    duration_min: 25,
    steps: [
      {
        order: 1,
        product_type_slug: 'cleanser-oil-balm',
        note_el: 'Πρώτος καθαρισμός, σε στεγνό πρόσωπο.',
        note_en: 'First cleanse, on a dry face.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'cleanser-gel-foaming',
        note_el: 'Δεύτερος καθαρισμός.',
        note_en: 'Second cleanse.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'exfoliant-pha-gentle',
        note_el: '1–2 φορές την εβδομάδα.',
        note_en: 'Once or twice a week.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'toner-hydrating',
        note_el: 'Δύο-τρεις στρώσεις.',
        note_en: 'Two or three layers.',
        optional: false,
      },
      {
        order: 5,
        product_type_slug: 'essence-first-treatment',
        note_el: 'Το «πολυτελές» βήμα· παράλειψέ το άφοβα.',
        note_en: 'The “luxury” step; skip it without guilt.',
        optional: true,
      },
      {
        order: 6,
        product_type_slug: 'essence-hydrating',
        note_el: 'Πίεσε με τις παλάμες.',
        note_en: 'Press in with your palms.',
        optional: true,
      },
      {
        order: 7,
        product_type_slug: 'serum-snail-mucin',
        note_el: 'Ή όποιος ορός ταιριάζει στο δικό σου ζήτημα.',
        note_en: 'Or whichever serum fits your own concern.',
        optional: false,
      },
      {
        order: 8,
        product_type_slug: 'mask-sheet',
        note_el: '15–20 λεπτά, 1–2 φορές την εβδομάδα.',
        note_en: '15–20 minutes, once or twice a week.',
        optional: true,
      },
      {
        order: 9,
        product_type_slug: 'moisturizer-emulsion-light',
        note_el: 'Κάθε βράδυ.',
        note_en: 'Every night.',
        optional: false,
      },
      {
        order: 10,
        product_type_slug: 'mask-sleeping-overnight',
        note_el: 'Στη θέση της κρέμας, 2–3 νύχτες την εβδομάδα.',
        note_en: 'Instead of a cream, two or three nights a week.',
        optional: true,
      },
    ],
  },

  // --- nails (operator addition 2026-10-06: "and nails") ---------------------------------------------
  {
    slug: 'nails-men-weekly-clean',
    area: 'nails',
    name_el: 'Εβδομαδιαία περιποίηση νυχιών για άντρες — κοντά και καθαρά',
    name_en: 'Men’s weekly nail care — short and clean',
    audience: 'men',
    skin_type: 'all',
    region: 'global',
    time: 'weekly',
    intro_el:
      'Δέκα λεπτά την Κυριακή: μαλάκωμα επωνυχίων, λιμάρισμα κοντά προς μία κατεύθυνση, προαιρετικό γυάλισμα και κρέμα χεριών. Χωρίς βερνίκι, χωρίς κόψιμο επωνυχίων, χωρίς ψαλίδι στα δάχτυλα.',
    intro_en:
      'Ten minutes on a Sunday: soften the cuticles, file short in one direction, optional buffing and hand cream. No polish, no cutting cuticles, no scissors on your fingers.',
    duration_min: 10,
    steps: [
      {
        order: 1,
        product_type_slug: 'cuticle-oil-jojoba',
        note_el: 'Μασάζ στη βάση κάθε νυχιού· σπρώξε απαλά τα επωνύχια με πετσέτα μετά το ντους.',
        note_en:
          'Massage into each nail base; gently push the cuticles back with a towel after the shower.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'nail-file-glass',
        note_el: 'Κοντά, ίσια με ελαφρά στρογγυλεμένες γωνίες, προς μία κατεύθυνση.',
        note_en: 'Short, straight across with slightly rounded corners, in one direction.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'nail-file-buffer-block',
        note_el: 'Μία φορά τον μήνα, ελαφρά, για φυσική γυαλάδα.',
        note_en: 'Once a month, lightly, for a natural shine.',
        optional: true,
      },
      {
        order: 4,
        product_type_slug: 'hand-cream-urea',
        note_el: 'Μέχρι τα επωνύχια· ξανά μετά από κάθε πλύσιμο πιάτων.',
        note_en: 'Right up to the cuticles; again after every round of dish-washing.',
        optional: false,
      },
    ],
  },
  {
    slug: 'nails-women-weekly-maintenance',
    area: 'nails',
    name_el: 'Εβδομαδιαία συντήρηση ανάμεσα σε μανικιούρ',
    name_en: 'Weekly upkeep between manicures',
    audience: 'women',
    skin_type: 'all',
    region: 'global',
    time: 'weekly',
    intro_el:
      'Για τις εβδομάδες χωρίς σαλόνι: αφαίρεση βερνικιού χωρίς ασετόν, σχήμα με γυάλινη λίμα, λάδι επωνυχίων, μια βάση που αφήνει το νύχι να «αναπνεύσει» και κρέμα χεριών.',
    intro_en:
      'For the weeks away from the salon: acetone-free removal, shaping with a glass file, cuticle oil, a base coat that lets the nail breathe and hand cream.',
    duration_min: 15,
    steps: [
      {
        order: 1,
        product_type_slug: 'nail-remover-acetone-free',
        note_el: 'Κράτα το βαμβάκι λίγα δευτερόλεπτα πάνω στο νύχι αντί να τρίβεις.',
        note_en: 'Hold the pad on the nail for a few seconds instead of rubbing.',
        optional: false,
      },
      {
        order: 2,
        product_type_slug: 'nail-file-glass',
        note_el: 'Σχήμα που ακολουθεί τη βάση του νυχιού· όχι μύτες σε αδύναμα νύχια.',
        note_en: 'A shape that follows the nail base; no points on weak nails.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'cuticle-oil-jojoba',
        note_el: 'Μασάζ, μετά σπρώξε απαλά — ποτέ κόψιμο.',
        note_en: 'Massage, then push back gently — never cut.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'base-coat-breathable',
        note_el: 'Μία στρώση, με ή χωρίς χρώμα από πάνω.',
        note_en: 'One coat, with or without colour on top.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'hand-cream-urea',
        note_el: 'Κάθε βράδυ πριν τον ύπνο.',
        note_en: 'Every night before bed.',
        optional: false,
      },
    ],
  },
  {
    slug: 'nails-all-brittle-strengthening',
    area: 'nails',
    name_el: 'Πρόγραμμα 4 εβδομάδων για εύθραυστα νύχια',
    name_en: 'Four-week programme for brittle nails',
    audience: 'all',
    skin_type: 'all',
    region: 'global',
    time: 'pm',
    intro_el:
      'Τα νύχια μεγαλώνουν περίπου 3 χιλιοστά τον μήνα, οπότε χρειάζονται εβδομάδες για να δεις αλλαγή. Κάθε βράδυ: λάδι, ενισχυτική θεραπεία δύο φορές την εβδομάδα, κρέμα· λιμάρισμα μία φορά την εβδομάδα. Αν τα νύχια αλλάζουν χρώμα ή σχήμα, δες γιατρό.',
    intro_en:
      'Nails grow about 3 mm a month, so it takes weeks to see a change. Every night: oil, a strengthener twice a week, cream; filing once a week. If nails change colour or shape, see a doctor.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'nail-file-glass',
        note_el: 'Μία φορά την εβδομάδα, κοντά, για να μη «σκαλώνουν».',
        note_en: 'Once a week, short, so they do not catch.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'cuticle-oil-jojoba',
        note_el: 'Κάθε βράδυ, σε νύχι και επωνύχια.',
        note_en: 'Every night, on nail and cuticles.',
        optional: false,
      },
      {
        order: 3,
        product_type_slug: 'nail-treatment-strengthener-keratin',
        note_el: 'Δύο βράδια την εβδομάδα, μία στρώση· αφαίρεση και ξανά κάθε εβδομάδα.',
        note_en: 'Two nights a week, one coat; remove and redo weekly.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'hand-cream-urea',
        note_el: 'Γάντια για τα πιάτα όλες τις 4 εβδομάδες.',
        note_en: 'Gloves for the dishes throughout the four weeks.',
        optional: false,
      },
    ],
  },
  {
    slug: 'nails-all-post-gel-recovery',
    area: 'nails',
    name_el: 'Ανάκαμψη μετά από gel ή ακρυλικό',
    name_en: 'Recovery after gel or acrylic',
    audience: 'all',
    skin_type: 'all',
    region: 'global',
    time: 'pm',
    intro_el:
      'Μετά την αφαίρεση gel ή ακρυλικού η πλάκα είναι λεπτή και αφυδατωμένη. Για δύο-τρεις εβδομάδες: τίποτα πάνω στο νύχι εκτός από λάδι και, προαιρετικά, μια ενισχυτική θεραπεία. Μη ξύνεις ποτέ υπολείμματα — μαλάκωσέ τα.',
    intro_en:
      'After gel or acrylic removal the plate is thin and dehydrated. For two or three weeks: nothing on the nail but oil and, optionally, a strengthener. Never scrape off residue — soften it.',
    duration_min: 5,
    steps: [
      {
        order: 1,
        product_type_slug: 'nail-remover-acetone-free',
        note_el: 'Μόνο για τα τελευταία ίχνη· το gel το ίδιο χρειάζεται ασετόν ή σαλόνι.',
        note_en: 'Only for the last traces; the gel itself needs acetone or the salon.',
        optional: true,
      },
      {
        order: 2,
        product_type_slug: 'nail-file-glass',
        note_el: 'Κόντυνε τα νύχια — το μακρύ αδύναμο νύχι σπάει βαθιά.',
        note_en: 'Shorten the nails — a long weak nail breaks deep.',
        optional: true,
      },
      {
        order: 3,
        product_type_slug: 'cuticle-oil-jojoba',
        note_el: 'Δύο φορές τη μέρα για τρεις εβδομάδες.',
        note_en: 'Twice a day for three weeks.',
        optional: false,
      },
      {
        order: 4,
        product_type_slug: 'nail-treatment-strengthener-keratin',
        note_el: 'Από τη δεύτερη εβδομάδα, αν ξεφλουδίζουν στις άκρες.',
        note_en: 'From the second week, if the tips are peeling.',
        optional: true,
      },
      {
        order: 5,
        product_type_slug: 'hand-cream-urea',
        note_el: 'Κάθε βράδυ, μέχρι τα επωνύχια.',
        note_en: 'Every night, up to the cuticles.',
        optional: false,
      },
    ],
  },
]
